Diag-Client-Lib: boost_support::socket::tcp::TcpServerConnection Class Reference
boost_support::socket::tcp::TcpServerConnection Class Reference final
Tcp Server connection class to create connection with client.
#include <tls_server_.h>
Public Types
enum class TcpErrorCode : std::uint8_t { kOpenFailed , kBindingFailed , kGenericError }
Tcp error code.
using TcpHandlerRead = std::function< void(message::tcp::TcpMessagePtr)>
Tcp function template used for reception.
using Tcp = boost::asio::ip::tcp
Type alias for tcp protocol.
using TcpSocket = Tcp::socket
Type alias for tcp socket.
using TlsStream = boost::asio::ssl::stream< TcpSocket >
Type alias for tls stream wrapping tcp socket.
Public Member Functions
TcpServerConnection (TlsStream tls_socket, TcpHandlerRead tcp_handler_read)
Constructs an instance of TcpServerConnection.
~TcpServerConnection ()=default
Destruct an instance of TcpServerConnection.
TcpServerConnection (TcpServerConnection &&) noexcept=default
Default move ctor and assignment operator.
TcpServerConnection & operator= (TcpServerConnection &&) noexcept=default
TcpServerConnection (TcpServerConnection const &)=delete
Deleted copy ctor and assignment operator.
TcpServerConnection & operator= (TcpServerConnection const &)=delete
core_type::Result< void, TcpErrorCode > Transmit (message::tcp::TcpMessageConstPtr tcp_message)
Function to trigger transmission.
bool TryReceivingMessage ()
Function to initiate reception of tcp message.
core_type::Result< void, TcpErrorCode > Shutdown ()
Function to shutdown the socket.
Private Member Functions
TlsStream::lowest_layer_type & GetNativeTcpSocket ()
Function to get the native tcp socket under tls socket.
Private Attributes
TlsStream tls_socket_
Store ssl socket.
TcpHandlerRead tcp_handler_read_
Store the handler.
Detailed Description
Tcp Server connection class to create connection with client.
Definition at line 28 of file tls_server_.h.
Member Typedef Documentation
Tcp
using boost_support::socket::tcp::TcpServerConnection::Tcp = boost::asio::ip::tcp
Type alias for tcp protocol.
Definition at line 43 of file tls_server_.h.
TcpHandlerRead
using boost_support::socket::tcp::TcpServerConnection::TcpHandlerRead = std::function<void(message::tcp::TcpMessagePtr)>
Tcp function template used for reception.
Definition at line 38 of file tls_server_.h.
TcpSocket
using boost_support::socket::tcp::TcpServerConnection::TcpSocket = Tcp::socket
Type alias for tcp socket.
Definition at line 48 of file tls_server_.h.
TlsStream
using boost_support::socket::tcp::TcpServerConnection::TlsStream = boost::asio::ssl::stream<TcpSocket>
Type alias for tls stream wrapping tcp socket.
Definition at line 53 of file tls_server_.h.
Member Enumeration Documentation
TcpErrorCode
enum boost_support::socket::tcp::TcpServerConnection::TcpErrorCode : std::uint8_t strong
Tcp error code.
Enumerator
kOpenFailed
kBindingFailed
kGenericError
Definition at line 33 of file tls_server_.h.
 : std::uint8_t { kOpenFailed, kBindingFailed, kGenericError };
Constructor & Destructor Documentation
TcpServerConnection() [1/3]
boost_support::socket::tcp::TcpServerConnection::TcpServerConnection (TlsStream tls_socket, TcpHandlerRead tcp_handler_read)
Constructs an instance of TcpServerConnection.
Parameters
[in] io_context The local ip address
[in] tcp_handler_read The handler to send received data to user
Definition at line 65 of file tls_server_.cpp.
     : tls_socket_{std::move(tls_socket)},
       tcp_handler_read_{std::move(tcp_handler_read)} {}
~TcpServerConnection()
boost_support::socket::tcp::TcpServerConnection::~TcpServerConnection () default
Destruct an instance of TcpServerConnection.
TcpServerConnection() [2/3]
boost_support::socket::tcp::TcpServerConnection::TcpServerConnection (TcpServerConnection &&) default noexcept
Default move ctor and assignment operator.
TcpServerConnection() [3/3]
boost_support::socket::tcp::TcpServerConnection::TcpServerConnection (TcpServerConnection const &) delete
Deleted copy ctor and assignment operator.
Member Function Documentation
GetNativeTcpSocket()
TcpServerConnection::TlsStream::lowest_layer_type & boost_support::socket::tcp::TcpServerConnection::GetNativeTcpSocket () private
Function to get the native tcp socket under tls socket.
Definition at line 69 of file tls_server_.cpp.
{
   return tls_socket_.lowest_layer();
 }
References tls_socket_.
Referenced by Shutdown(), Transmit(), and TryReceivingMessage().
operator=() [1/2]
TcpServerConnection& boost_support::socket::tcp::TcpServerConnection::operator= (TcpServerConnection &&) default noexcept
operator=() [2/2]
TcpServerConnection& boost_support::socket::tcp::TcpServerConnection::operator= (TcpServerConnection const &) delete
Shutdown()
core_type::Result< void, TcpServerConnection::TcpErrorCode > boost_support::socket::tcp::TcpServerConnection::Shutdown ()
Function to shutdown the socket.
Returns
Empty result on success otherwise error code
Definition at line 163 of file tls_server_.cpp.
{
   core_type::Result<void, TcpErrorCode> result{TcpErrorCode::kGenericError};
   TcpErrorCodeType ec{};
   // Graceful shutdown
   if (GetNativeTcpSocket().is_open()) {
     // Shutdown TLS connection
     tls_socket_.shutdown(ec);
     // Shutdown of TCP connection
     GetNativeTcpSocket().shutdown(TcpSocket::shutdown_both, ec);
     if (ec.value() == boost::system::errc::success) {
       // Socket shutdown success
       result.EmplaceValue();
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
             msg << "Tcp Socket Disconnection failed with error: " << ec.message();
           });
     }
     GetNativeTcpSocket().close();
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), kGenericError, and tls_socket_.
Transmit()
core_type::Result< void, TcpServerConnection::TcpErrorCode > boost_support::socket::tcp::TcpServerConnection::Transmit (message::tcp::TcpMessageConstPtr tcp_message)
Function to trigger transmission.
Parameters
[in] tcp_message The tcp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 73 of file tls_server_.cpp.
{
   TcpErrorCodeType ec{};
   core_type::Result<void, TcpErrorCode> result{TcpErrorCode::kGenericError};
   boost::asio::write(tls_socket_,
                      boost::asio::buffer(tcp_tx_message->GetPayload().data(),
                                          std::size_t(tcp_tx_message->GetPayload().size())),
                      ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     Tcp::endpoint endpoint_{GetNativeTcpSocket().remote_endpoint()};
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [endpoint_](std::stringstream &msg) {
           msg << "Tcp message sent to "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp message sending failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), kGenericError, and tls_socket_.
TryReceivingMessage()
bool boost_support::socket::tcp::TcpServerConnection::TryReceivingMessage ()
Function to initiate reception of tcp message.
Definition at line 100 of file tls_server_.cpp.
{
   TcpErrorCodeType ec{};
   bool connection_closed{false};
   // Perform TLS handshake
   tls_socket_.handshake(boost::asio::ssl::stream_base::server, ec);
   if (ec.value() == boost::system::errc::success) {
     // Create and reserve the buffer
     message::tcp::TcpMessage::BufferType rx_buffer{};
     rx_buffer.resize(message::tcp::kDoipheadrSize);
     // Start blocking read to read Header first
     boost::asio::read(tls_socket_, boost::asio::buffer(&rx_buffer[0], message::tcp::kDoipheadrSize),
                       ec);
     // Check for error
     if (ec.value() == boost::system::errc::success) {
       // Read the next bytes to read
       std::uint32_t const read_next_bytes = [&rx_buffer]() noexcept -> std::uint32_t {
         return static_cast<std::uint32_t>(
             (static_cast<std::uint32_t>(rx_buffer[4u] << 24u) & 0xFF000000) |
             (static_cast<std::uint32_t>(rx_buffer[5u] << 16u) & 0x00FF0000) |
             (static_cast<std::uint32_t>(rx_buffer[6u] << 8u) & 0x0000FF00) |
             (static_cast<std::uint32_t>(rx_buffer[7u] & 0x000000FF)));
       }();
       // reserve the buffer
       rx_buffer.resize(message::tcp::kDoipheadrSize + std::size_t(read_next_bytes));
       boost::asio::read(
           tls_socket_,
           boost::asio::buffer(&rx_buffer[message::tcp::kDoipheadrSize], read_next_bytes), ec);
       // all message received, transfer to upper layer
       Tcp::endpoint endpoint_{GetNativeTcpSocket().remote_endpoint()};
       message::tcp::TcpMessagePtr tcp_rx_message{std::make_unique<message::tcp::TcpMessage>(
           endpoint_.address().to_string(), endpoint_.port(), std::move(rx_buffer))};
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__, [endpoint_](std::stringstream &msg) {
             msg << "Tcp Message received from "
                 << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
           });
       // send data to upper layer
       tcp_handler_read_(std::move(tcp_rx_message));
     } else if (ec.value() == boost::asio::error::eof) {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [ec](std::stringstream &msg) { msg << "Remote Disconnected with: " << ec.message(); });
       connection_closed = true;
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
             msg << "Remote Disconnected with undefined error: " << ec.message();
           });
       connection_closed = true;
     }
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tls server handshake with host failed with error: " << ec.message();
         });
     connection_closed = true;
   }
   return connection_closed;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), boost_support::message::tcp::kDoipheadrSize, tcp_handler_read_, and tls_socket_.
Member Data Documentation
tcp_handler_read_
TcpHandlerRead boost_support::socket::tcp::TcpServerConnection::tcp_handler_read_ private
Store the handler.
Definition at line 110 of file tls_server_.h.
Referenced by TryReceivingMessage().
tls_socket_
TlsStream boost_support::socket::tcp::TcpServerConnection::tls_socket_ private
Store ssl socket.
Definition at line 105 of file tls_server_.h.
Referenced by GetNativeTcpSocket(), Shutdown(), Transmit(), and TryReceivingMessage().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tcp/tls_server_.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tcp/tls_server_.cpp