Diag-Client-Lib: doip_client::sockets::TcpSocketHandler Class Reference
doip_client::sockets::TcpSocketHandler Class Reference final
Class used to create a tcp socket for handling transmission and reception of tcp message from driver.
#include <tcp_socket_handler.h>
Public Types
enum class SocketHandlerState : std::uint8_t { kSocketOffline = 0U , kSocketOnline = 1U , kSocketConnected = 2U , kSocketDisconnected = 4U }
Definitions of different socket state.
using TcpMessage = boost_support::socket::tcp::TcpMessage
Type alias for Tcp message.
using TcpMessagePtr = boost_support::socket::tcp::TcpMessagePtr
Type alias for Tcp message pointer.
using TcpMessageConstPtr = boost_support::socket::tcp::TcpMessageConstPtr
Type alias for Tcp message const pointer.
using TcpChannel = channel::tcp_channel::DoipTcpChannel
Type alias for Tcp message.
Public Member Functions
TcpSocketHandler (std::string_view local_ip_address, TcpChannel &channel)
Constructs an instance of TcpSocketHandler.
~TcpSocketHandler ()=default
Destruct an instance of TcpSocketHandler.
void Start ()
Function to start the socket handler.
void Stop ()
Function to stop the socket handler.
core_type::Result< void > ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num)
Function to connect to remote ip address and port number.
core_type::Result< void > DisconnectFromHost ()
Function to disconnect from remote host if already connected.
core_type::Result< void > Transmit (TcpMessageConstPtr tcp_message)
Function to transmit the provided tcp message.
SocketHandlerState GetSocketHandlerState () const
Function to get the current state of socket handler.
Private Types
using TcpSocket = boost_support::socket::tcp::TcpClientSocket
Type alias for tcp client socket.
Private Attributes
std::string local_ip_address_
Store the local ip address.
std::uint16_t local_port_num_
Store the local port number.
std::optional< TcpSocket > tcp_socket_
Store the socket object.
TcpChannel & channel_
Store the reference to tcp channel.
std::atomic< SocketHandlerState > state_
Store the state of handler.
Detailed Description
Class used to create a tcp socket for handling transmission and reception of tcp message from driver.
Definition at line 32 of file tcp_socket_handler.h.
Member Typedef Documentation
TcpChannel
using doip_client::sockets::TcpSocketHandler::TcpChannel = channel::tcp_channel::DoipTcpChannel
Type alias for Tcp message.
Definition at line 62 of file tcp_socket_handler.h.
TcpMessage
using doip_client::sockets::TcpSocketHandler::TcpMessage = boost_support::socket::tcp::TcpMessage
Type alias for Tcp message.
Definition at line 47 of file tcp_socket_handler.h.
TcpMessageConstPtr
using doip_client::sockets::TcpSocketHandler::TcpMessageConstPtr = boost_support::socket::tcp::TcpMessageConstPtr
Type alias for Tcp message const pointer.
Definition at line 57 of file tcp_socket_handler.h.
TcpMessagePtr
using doip_client::sockets::TcpSocketHandler::TcpMessagePtr = boost_support::socket::tcp::TcpMessagePtr
Type alias for Tcp message pointer.
Definition at line 52 of file tcp_socket_handler.h.
TcpSocket
using doip_client::sockets::TcpSocketHandler::TcpSocket = boost_support::socket::tcp::TcpClientSocket private
Type alias for tcp client socket.
Definition at line 122 of file tcp_socket_handler.h.
Member Enumeration Documentation
SocketHandlerState
enum doip_client::sockets::TcpSocketHandler::SocketHandlerState : std::uint8_t strong
Definitions of different socket state.
Enumerator
kSocketOffline
Socket offline state
kSocketOnline
Socket online state
kSocketConnected
Socket connected to remote server
kSocketDisconnected
Socket disconnected from remote server
Definition at line 37 of file tcp_socket_handler.h.
                                 : std::uint8_t {
     kSocketOffline = 0U,
     kSocketOnline = 1U,
     kSocketConnected = 2U,
     kSocketDisconnected = 4U
   };
Constructor & Destructor Documentation
TcpSocketHandler()
doip_client::sockets::TcpSocketHandler::TcpSocketHandler (std::string_view local_ip_address, TcpChannel & channel)
Constructs an instance of TcpSocketHandler.
Parameters
[in] local_ip_address The local ip address
[in] channel The reference to tcp transport handler
Definition at line 19 of file tcp_socket_handler.cpp.
     : local_ip_address_{local_ip_address},
       local_port_num_{0U},  // port number with "0" will create socket with random port number at client side
       tcp_socket_{},
       channel_{channel},
       state_{SocketHandlerState::kSocketOffline} {}
~TcpSocketHandler()
doip_client::sockets::TcpSocketHandler::~TcpSocketHandler () default
Destruct an instance of TcpSocketHandler.
Member Function Documentation
ConnectToHost()
core_type::Result< void > doip_client::sockets::TcpSocketHandler::ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num)
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
The
Definition at line 37 of file tcp_socket_handler.cpp.
{
   core_type::Result<void> result{error_domain::MakeErrorCode(error_domain::DoipErrorErrc::kGenericError)};
   if (state_.load() != SocketHandlerState::kSocketConnected) {
     tcp_socket_->Open()
         .AndThen([this]() noexcept { state_.store(SocketHandlerState::kSocketOnline); })
         .AndThen([this, &result, host_ip_address, host_port_num]() {
           return tcp_socket_->ConnectToHost(host_ip_address, host_port_num).AndThen([this, &result]() {
             state_.store(SocketHandlerState::kSocketConnected);
             result.EmplaceValue();
           });
         });
   } else {
     // already connected
     result.EmplaceValue();
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogVerbose(
         __FILE__, __LINE__, __func__, [](std::stringstream &msg) { msg << "Tcp socket socket already connected"; });
   }
   return result;
 }
References doip_client::logger::DoipClientLogger::GetDiagClientLogger(), doip_client::error_domain::kGenericError, kSocketConnected, kSocketOnline, doip_client::error_domain::MakeErrorCode(), state_, and tcp_socket_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::ConnectToHost().
DisconnectFromHost()
core_type::Result< void > doip_client::sockets::TcpSocketHandler::DisconnectFromHost ()
Function to disconnect from remote host if already connected.
Returns
The
Definition at line 57 of file tcp_socket_handler.cpp.
{
   core_type::Result<void> result{error_domain::MakeErrorCode(error_domain::DoipErrorErrc::kGenericError)};
   if (state_.load() == SocketHandlerState::kSocketConnected) {
     tcp_socket_->DisconnectFromHost()
         .AndThen([this]() noexcept { state_.store(SocketHandlerState::kSocketDisconnected); })
         .AndThen([this, &result]() noexcept {
           return tcp_socket_->Destroy().AndThen([this, &result]() {
             state_.store(SocketHandlerState::kSocketOffline);
             result.EmplaceValue();
           });
         });
   } else {
     // not connected
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogDebug(
         __FILE__, __LINE__, __func__,
         [](std::stringstream &msg) { msg << "Tcp socket already in not connected state"; });
   }
   return result;
 }
References doip_client::logger::DoipClientLogger::GetDiagClientLogger(), doip_client::error_domain::kGenericError, kSocketConnected, kSocketDisconnected, kSocketOffline, doip_client::error_domain::MakeErrorCode(), state_, and tcp_socket_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::DisconnectFromHost(), and Stop().
GetSocketHandlerState()
TcpSocketHandler::SocketHandlerState doip_client::sockets::TcpSocketHandler::GetSocketHandlerState () const
Function to get the current state of socket handler.
Returns
The socket handler state
Definition at line 90 of file tcp_socket_handler.cpp.
 { return state_.load(); }
References state_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::IsConnectToHost().
Start()
void doip_client::sockets::TcpSocketHandler::Start ()
Function to start the socket handler.
Definition at line 26 of file tcp_socket_handler.cpp.
{
   tcp_socket_.emplace(local_ip_address_, local_port_num_, [this](TcpMessagePtr tcp_message) {
     channel_.ProcessReceivedTcpMessage(std::move(tcp_message));
   });
 }
References channel_, local_ip_address_, local_port_num_, doip_client::channel::tcp_channel::DoipTcpChannel::ProcessReceivedTcpMessage(), and tcp_socket_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Start().
Stop()
void doip_client::sockets::TcpSocketHandler::Stop ()
Function to stop the socket handler.
Definition at line 32 of file tcp_socket_handler.cpp.
{
   if (state_.load() != SocketHandlerState::kSocketOffline) { DisconnectFromHost(); }
   tcp_socket_.reset();
 }
References DisconnectFromHost(), kSocketOffline, state_, and tcp_socket_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Stop().
Transmit()
core_type::Result< void > doip_client::sockets::TcpSocketHandler::Transmit (TcpMessageConstPtr tcp_message)
Function to transmit the provided tcp message.
Parameters
[in] tcp_message The tcp message
Returns
The
Definition at line 77 of file tcp_socket_handler.cpp.
{
   core_type::Result<void> result{error_domain::MakeErrorCode(error_domain::DoipErrorErrc::kGenericError)};
   if (state_.load() == SocketHandlerState::kSocketConnected) {
     if (tcp_socket_->Transmit(std::move(tcp_message)).HasValue()) { result.EmplaceValue(); }
   } else {
     // not connected
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
         __FILE__, __LINE__, __func__,
         [](std::stringstream &msg) { msg << "Tcp socket Offline, please connect to server first"; });
   }
   return result;
 }
References doip_client::logger::DoipClientLogger::GetDiagClientLogger(), doip_client::error_domain::kGenericError, kSocketConnected, doip_client::error_domain::MakeErrorCode(), state_, and tcp_socket_.
Member Data Documentation
channel_
TcpChannel& doip_client::sockets::TcpSocketHandler::channel_ private
Store the reference to tcp channel.
Definition at line 142 of file tcp_socket_handler.h.
Referenced by Start().
local_ip_address_
std::string doip_client::sockets::TcpSocketHandler::local_ip_address_ private
Store the local ip address.
Definition at line 127 of file tcp_socket_handler.h.
Referenced by Start().
local_port_num_
std::uint16_t doip_client::sockets::TcpSocketHandler::local_port_num_ private
Store the local port number.
Definition at line 132 of file tcp_socket_handler.h.
Referenced by Start().
state_
std::atomic<SocketHandlerState> doip_client::sockets::TcpSocketHandler::state_ private
Store the state of handler.
Definition at line 147 of file tcp_socket_handler.h.
Referenced by ConnectToHost(), DisconnectFromHost(), GetSocketHandlerState(), Stop(), and Transmit().
tcp_socket_
std::optional<TcpSocket> doip_client::sockets::TcpSocketHandler::tcp_socket_ private
Store the socket object.
Definition at line 137 of file tcp_socket_handler.h.
Referenced by ConnectToHost(), DisconnectFromHost(), Start(), Stop(), and Transmit().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/sockets/tcp_socket_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/sockets/tcp_socket_handler.cpp