Diag-Client-Lib: boost_support::client::tcp::TcpClient::TcpClientImpl Class Reference
boost_support::client::tcp::TcpClient::TcpClientImpl Class Reference final
Class to provide implementation of tcp client.
Public Member Functions
TcpClientImpl (std::string_view client_name, std::string_view local_ip_address, std::uint16_t local_port_num) noexcept
Constructs an instance of TcpClientImpl.
TcpClientImpl (const TcpClientImpl &other) noexcept=delete
Deleted copy assignment and copy constructor.
TcpClientImpl & operator= (const TcpClientImpl &other) noexcept=delete
TcpClientImpl (TcpClientImpl &&other) noexcept=delete
Deleted move assignment and move constructor.
TcpClientImpl & operator= (TcpClientImpl &&other) noexcept=delete
~TcpClientImpl () noexcept=default
Destruct an instance of TcpClientImpl.
void Initialize () noexcept
Initialize the client.
void DeInitialize () noexcept
De-initialize the client.
void SetReadHandler (HandlerRead read_handler) noexcept
Function to set the read handler that is invoked when message is received.
core_type::Result< void > ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num)
Function to connect to remote ip address and port number.
core_type::Result< void > DisconnectFromHost ()
Function to disconnect from remote host if already connected.
auto IsConnectedToHost () const noexcept -> bool
Function to get the connection status.
core_type::Result< void > Transmit (MessageConstPtr tcp_message)
Function to transmit the provided tcp message.
Private Types
enum class State : std::uint8_t { kConnected = 0U , kDisconnected = 1U }
Definitions of different connection state.
using TcpConnection = connection::tcp::TcpConnection< connection::tcp::ConnectionType::kClient, socket::tcp::TcpSocket >
Type alias for unsecured tcp connection.
using IoContext = boost_support::socket::IoContext
Type alias for boost context.
Private Attributes
IoContext io_context_
Stores the io context.
std::atomic< State > connection_state_
Store the state of tcp connection.
std::string client_name_
The client name.
TcpConnection tcp_connection_
Store the tcp connection.
Detailed Description
Class to provide implementation of tcp client.
Definition at line 42 of file tcp_client.cpp.
Member Typedef Documentation
IoContext
using boost_support::client::tcp::TcpClient::TcpClientImpl::IoContext = boost_support::socket::IoContext private
Type alias for boost context.
Definition at line 61 of file tcp_client.cpp.
TcpConnection
using boost_support::client::tcp::TcpClient::TcpClientImpl::TcpConnection = connection::tcp::TcpConnection<connection::tcp::ConnectionType::kClient, socket::tcp::TcpSocket> private
Type alias for unsecured tcp connection.
Definition at line 47 of file tcp_client.cpp.
Member Enumeration Documentation
State
enum boost_support::client::tcp::TcpClient::TcpClientImpl::State : std::uint8_t strong private
Definitions of different connection state.
Enumerator
kConnected
Connected to remote server
kDisconnected
Disconnected from remote server
Definition at line 53 of file tcp_client.cpp.
                    : std::uint8_t {
     kConnected = 0U,
     kDisconnected = 1U
   };
Constructor & Destructor Documentation
TcpClientImpl() [1/3]
boost_support::client::tcp::TcpClient::TcpClientImpl::TcpClientImpl (std::string_view client_name, std::string_view local_ip_address, std::uint16_t local_port_num) inline noexcept
Constructs an instance of TcpClientImpl.
Parameters
[in] local_ip_address The local ip address of client
[in] local_port_num The local port number of client
Definition at line 71 of file tcp_client.cpp.
       : io_context_{},
         connection_state_{State::kDisconnected},
         client_name_{AppendIpAddressAndPort(client_name, local_ip_address, local_port_num)},
         tcp_connection_{client_name,
                         socket::tcp::TcpSocket{local_ip_address, local_port_num, io_context_}} {}
TcpClientImpl() [2/3]
boost_support::client::tcp::TcpClient::TcpClientImpl::TcpClientImpl (const TcpClientImpl & other) delete noexcept
Deleted copy assignment and copy constructor.
TcpClientImpl() [3/3]
boost_support::client::tcp::TcpClient::TcpClientImpl::TcpClientImpl (TcpClientImpl && other) delete noexcept
Deleted move assignment and move constructor.
~TcpClientImpl()
boost_support::client::tcp::TcpClient::TcpClientImpl::~TcpClientImpl () default noexcept
Destruct an instance of TcpClientImpl.
Member Function Documentation
ConnectToHost()
core_type::Result<void> boost_support::client::tcp::TcpClient::TcpClientImpl::ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num) inline
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
Empty void on success, otherwise error is returned
Definition at line 124 of file tcp_client.cpp.
{
     core_type::Result<void> result{
         error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kSocketError)};
     if (connection_state_.load(std::memory_order_seq_cst) != State::kConnected) {
       if (tcp_connection_.ConnectToHost(host_ip_address, host_port_num)) {
         connection_state_.store(State::kConnected, std::memory_order_seq_cst);
         result.EmplaceValue();
       }  // else, connect failed
     } else {
       // already connected
       result.EmplaceValue();
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogVerbose(
           FILE_NAME, __LINE__, __func__,
           [](std::stringstream &msg) { msg << "Tcp client is already connected"; });
     }
     return result;
   }
References connection_state_, FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), kConnected, boost_support::error_domain::kSocketError, boost_support::error_domain::MakeErrorCode(), and tcp_connection_.
DeInitialize()
void boost_support::client::tcp::TcpClient::TcpClientImpl::DeInitialize () inline noexcept
De-initialize the client.
Definition at line 104 of file tcp_client.cpp.
 { tcp_connection_.DeInitialize(); }
References tcp_connection_.
DisconnectFromHost()
core_type::Result<void> boost_support::client::tcp::TcpClient::TcpClientImpl::DisconnectFromHost () inline
Function to disconnect from remote host if already connected.
Returns
Empty void on success, otherwise error is returned
Definition at line 147 of file tcp_client.cpp.
{
     core_type::Result<void> result{
         error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kSocketError)};
     if (connection_state_.load(std::memory_order_seq_cst) == State::kConnected) {
       tcp_connection_.DisconnectFromHost();
       connection_state_.store(State::kDisconnected, std::memory_order_seq_cst);
       result.EmplaceValue();
     } else {
       // Not connected
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [](std::stringstream &msg) { msg << "Tcp client is in disconnected state"; });
     }
     return result;
   }
References connection_state_, FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), kConnected, kDisconnected, boost_support::error_domain::kSocketError, boost_support::error_domain::MakeErrorCode(), and tcp_connection_.
Initialize()
void boost_support::client::tcp::TcpClient::TcpClientImpl::Initialize () inline noexcept
Initialize the client.
Definition at line 99 of file tcp_client.cpp.
 { tcp_connection_.Initialize(); }
References tcp_connection_.
IsConnectedToHost()
auto boost_support::client::tcp::TcpClient::TcpClientImpl::IsConnectedToHost () const -> bool inline noexcept
Function to get the connection status.
Returns
True if connected, False otherwise
Definition at line 167 of file tcp_client.cpp.
{
     return (connection_state_.load(std::memory_order_seq_cst) == State::kConnected);
   }
References connection_state_, and kConnected.
operator=() [1/2]
TcpClientImpl& boost_support::client::tcp::TcpClient::TcpClientImpl::operator= (const TcpClientImpl & other) delete noexcept
operator=() [2/2]
TcpClientImpl& boost_support::client::tcp::TcpClient::TcpClientImpl::operator= (TcpClientImpl && other) delete noexcept
SetReadHandler()
void boost_support::client::tcp::TcpClient::TcpClientImpl::SetReadHandler (HandlerRead read_handler) inline noexcept
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 112 of file tcp_client.cpp.
{
     tcp_connection_.SetReadHandler(std::move(read_handler));
   }
References tcp_connection_.
Transmit()
core_type::Result<void> boost_support::client::tcp::TcpClient::TcpClientImpl::Transmit (MessageConstPtr tcp_message) inline
Function to transmit the provided tcp message.
Parameters
[in] tcp_message The tcp message
Returns
Empty void on success, otherwise error is returned
Definition at line 177 of file tcp_client.cpp.
{
     core_type::Result<void> result{
         error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kGenericError)};
     if (connection_state_.load(std::memory_order_seq_cst) == State::kConnected) {
       if (tcp_connection_.Transmit(std::move(tcp_message))) { result.EmplaceValue(); }
     } else {
       // not connected
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [](std::stringstream &msg) {
             msg << "Tcp client is Offline, please connect to server first";
           });
     }
     return result;
   }
References connection_state_, FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), kConnected, boost_support::error_domain::kGenericError, boost_support::error_domain::MakeErrorCode(), and tcp_connection_.
Member Data Documentation
client_name_
std::string boost_support::client::tcp::TcpClient::TcpClientImpl::client_name_ private
The client name.
Definition at line 206 of file tcp_client.cpp.
connection_state_
std::atomic<State> boost_support::client::tcp::TcpClient::TcpClientImpl::connection_state_ private
Store the state of tcp connection.
Definition at line 201 of file tcp_client.cpp.
Referenced by ConnectToHost(), DisconnectFromHost(), IsConnectedToHost(), and Transmit().
io_context_
IoContext boost_support::client::tcp::TcpClient::TcpClientImpl::io_context_ private
Stores the io context.
Definition at line 196 of file tcp_client.cpp.
tcp_connection_
TcpConnection boost_support::client::tcp::TcpClient::TcpClientImpl::tcp_connection_ private
Store the tcp connection.
Definition at line 211 of file tcp_client.cpp.
Referenced by ConnectToHost(), DeInitialize(), DisconnectFromHost(), Initialize(), SetReadHandler(), and Transmit().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/client/tcp/tcp_client.cpp