Diag-Client-Lib: doip_client::channel::tcp_channel::DoipTcpChannel Class Reference
doip_client::channel::tcp_channel::DoipTcpChannel Class Reference final
Class to manage a tcp channel as per DoIP protocol.
#include <doip_tcp_channel.h>
Public Types
using TcpSocketHandler = sockets::TcpSocketHandler
Type alias for Tcp socket handler.
using TcpMessagePtr = sockets::TcpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
Public Member Functions
DoipTcpChannel (TcpSocketHandler tcp_socket_handler, uds_transport::Connection &connection)
Constructs an instance of TcpChannel.
~DoipTcpChannel ()=default
Destruct an instance of TcpChannel.
void Start ()
Function to start the channel.
void Stop ()
Function to stop the channel.
bool IsConnectedToHost ()
Function to check if connected to host remote server.
uds_transport::UdsTransportProtocolMgr::ConnectionResult ConnectToHost (uds_transport::UdsMessageConstPtr message)
Function to establish connection to remote host server.
uds_transport::UdsTransportProtocolMgr::DisconnectionResult DisconnectFromHost ()
Function to disconnect from remote host server.
std::pair< uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr > IndicateMessage (uds_transport::UdsMessage::Address source_addr, uds_transport::UdsMessage::Address target_addr, uds_transport::UdsMessage::TargetAddressType type, uds_transport::ChannelID channel_id, std::size_t size, uds_transport::Priority priority, uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info)
Function to indicate a start of reception of message.
uds_transport::UdsTransportProtocolMgr::TransmissionResult Transmit (uds_transport::UdsMessageConstPtr message)
Function to transmit a valid Uds message.
void HandleMessage (uds_transport::UdsMessagePtr message)
Function to Hands over a valid received Uds message to upper layer.
void ProcessReceivedTcpMessage (TcpMessagePtr tcp_rx_message)
Function to process the received Tcp message from socket layer.
Private Attributes
TcpSocketHandler tcp_socket_handler_
Store the tcp socket handler.
DoipTcpChannelHandler tcp_channel_handler_
Store the doip channel handler.
uds_transport::Connection & connection_
Store the reference to doip connection.
Detailed Description
Class to manage a tcp channel as per DoIP protocol.
Definition at line 26 of file doip_tcp_channel.h.
Member Typedef Documentation
TcpMessagePtr
using doip_client::channel::tcp_channel::DoipTcpChannel::TcpMessagePtr = sockets::TcpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
Definition at line 36 of file doip_tcp_channel.h.
TcpSocketHandler
using doip_client::channel::tcp_channel::DoipTcpChannel::TcpSocketHandler = sockets::TcpSocketHandler
Type alias for Tcp socket handler.
Definition at line 31 of file doip_tcp_channel.h.
Constructor & Destructor Documentation
DoipTcpChannel()
doip_client::channel::tcp_channel::DoipTcpChannel::DoipTcpChannel (TcpSocketHandler tcp_socket_handler, uds_transport::Connection & connection)
Constructs an instance of TcpChannel.
Parameters
[in] tcp_socket_handler The tcp socket handler
[in] connection The reference to tcp transport handler
Definition at line 19 of file doip_tcp_channel.cpp.
     : tcp_socket_handler_{std::move(tcp_socket_handler)},
       tcp_channel_handler_{tcp_socket_handler_, *this},
       connection_{connection} {}
~DoipTcpChannel()
doip_client::channel::tcp_channel::DoipTcpChannel::~DoipTcpChannel () default
Destruct an instance of TcpChannel.
Member Function Documentation
ConnectToHost()
uds_transport::UdsTransportProtocolMgr::ConnectionResult doip_client::channel::tcp_channel::DoipTcpChannel::ConnectToHost (uds_transport::UdsMessageConstPtr message)
Function to establish connection to remote host server.
Parameters
[in] message The connection message
Returns
Connection result
Definition at line 41 of file doip_tcp_channel.cpp.
{
   uds_transport::UdsTransportProtocolMgr::ConnectionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::ConnectionResult::kConnectionFailed};
   uds_transport::UdsMessage::IpAddress const kHostIpAddress{message->GetHostIpAddress()};
   uds_transport::UdsMessage::PortNumber const kHostPortNumber{message->GetHostPortNumber()};
   // Initiate connecting to server
   if (tcp_socket_handler_.ConnectToHost(kHostIpAddress, kHostPortNumber)) {
     // Once connected, Send routing activation req and get response
     ret_val = tcp_channel_handler_.SendRoutingActivationRequest(std::move(message));
   } else {  // failure
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [&kHostIpAddress, &kHostPortNumber](std::stringstream &msg) {
           msg << "Doip Tcp socket connect failed for remote endpoints : "
               << "<Ip: " << kHostIpAddress << ", Port: " << kHostPortNumber << ">";
         });
   }
   return ret_val;
 }
References doip_client::sockets::SocketHandler< ClientType >::ConnectToHost(), FILE_NAME, doip_client::logger::DoipClientLogger::GetDiagClientLogger(), uds_transport::UdsTransportProtocolMgr::kConnectionFailed, doip_client::channel::tcp_channel::DoipTcpChannelHandler::SendRoutingActivationRequest(), tcp_channel_handler_, and tcp_socket_handler_.
Referenced by doip_client::connection::DoipTcpConnection::ConnectToHost().
DisconnectFromHost()
uds_transport::UdsTransportProtocolMgr::DisconnectionResult doip_client::channel::tcp_channel::DoipTcpChannel::DisconnectFromHost ()
Function to disconnect from remote host server.
Returns
Disconnection result
Definition at line 62 of file doip_tcp_channel.cpp.
{
   uds_transport::UdsTransportProtocolMgr::DisconnectionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::DisconnectionResult::kDisconnectionFailed};
   if (tcp_socket_handler_.DisconnectFromHost()) {
     if (tcp_channel_handler_.IsRoutingActivated()) {
       // Reset the handler
       tcp_channel_handler_.Reset();
     }
     ret_val = uds_transport::UdsTransportProtocolMgr::DisconnectionResult::kDisconnectionOk;
   }
   return ret_val;
 }
References doip_client::sockets::SocketHandler< ClientType >::DisconnectFromHost(), doip_client::channel::tcp_channel::DoipTcpChannelHandler::IsRoutingActivated(), uds_transport::UdsTransportProtocolMgr::kDisconnectionFailed, uds_transport::UdsTransportProtocolMgr::kDisconnectionOk, doip_client::channel::tcp_channel::DoipTcpChannelHandler::Reset(), tcp_channel_handler_, and tcp_socket_handler_.
Referenced by doip_client::connection::DoipTcpConnection::DisconnectFromHost().
HandleMessage()
void doip_client::channel::tcp_channel::DoipTcpChannel::HandleMessage (uds_transport::UdsMessagePtr message)
Function to Hands over a valid received Uds message to upper layer.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Definition at line 107 of file doip_tcp_channel.cpp.
{
   connection_.HandleMessage(std::move(message));
 }
References connection_, and uds_transport::Connection::HandleMessage().
IndicateMessage()
std::pair< uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr > doip_client::channel::tcp_channel::DoipTcpChannel::IndicateMessage (uds_transport::UdsMessage::Address source_addr, uds_transport::UdsMessage::Address target_addr, uds_transport::UdsMessage::TargetAddressType type, uds_transport::ChannelID channel_id, std::size_t size, uds_transport::Priority priority, uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info)
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The view onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Definition at line 96 of file doip_tcp_channel.cpp.
{
   return connection_.IndicateMessage(source_addr, target_addr, type, channel_id, size, priority,
                                      protocol_kind, payload_info);
 }
References connection_, and uds_transport::Connection::IndicateMessage().
IsConnectedToHost()
bool doip_client::channel::tcp_channel::DoipTcpChannel::IsConnectedToHost ()
Function to check if connected to host remote server.
Returns
True if connection, False otherwise
Definition at line 39 of file doip_tcp_channel.cpp.
 { return tcp_socket_handler_.IsConnectedToHost(); }
References doip_client::sockets::SocketHandler< ClientType >::IsConnectedToHost(), and tcp_socket_handler_.
Referenced by doip_client::connection::DoipTcpConnection::IsConnectToHost().
ProcessReceivedTcpMessage()
void doip_client::channel::tcp_channel::DoipTcpChannel::ProcessReceivedTcpMessage (TcpMessagePtr tcp_rx_message)
Function to process the received Tcp message from socket layer.
Parameters
[in] tcp_rx_message The Tcp message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the channel here
Definition at line 75 of file doip_tcp_channel.cpp.
{
   tcp_channel_handler_.HandleMessage(std::move(tcp_rx_message));
 }
References doip_client::channel::tcp_channel::DoipTcpChannelHandler::HandleMessage(), and tcp_channel_handler_.
Referenced by Start().
Start()
void doip_client::channel::tcp_channel::DoipTcpChannel::Start ()
Function to start the channel.
Definition at line 25 of file doip_tcp_channel.cpp.
{
   // Set the handler to receive data from socket handler
   tcp_socket_handler_.SetReadHandler(
       [this](TcpMessagePtr tcp_message) { ProcessReceivedTcpMessage(std::move(tcp_message)); });
   // Start the socket and channel handler
   tcp_socket_handler_.Initialize();
   tcp_channel_handler_.Start();
 }
References doip_client::sockets::SocketHandler< ClientType >::Initialize(), ProcessReceivedTcpMessage(), doip_client::sockets::SocketHandler< ClientType >::SetReadHandler(), doip_client::channel::tcp_channel::DoipTcpChannelHandler::Start(), tcp_channel_handler_, and tcp_socket_handler_.
Referenced by doip_client::connection::DoipTcpConnection::Start().
Stop()
void doip_client::channel::tcp_channel::DoipTcpChannel::Stop ()
Function to stop the channel.
Definition at line 34 of file doip_tcp_channel.cpp.
{
   tcp_socket_handler_.DeInitialize();
   tcp_channel_handler_.Stop();
 }
References doip_client::sockets::SocketHandler< ClientType >::DeInitialize(), doip_client::channel::tcp_channel::DoipTcpChannelHandler::Stop(), tcp_channel_handler_, and tcp_socket_handler_.
Referenced by doip_client::connection::DoipTcpConnection::Stop().
Transmit()
uds_transport::UdsTransportProtocolMgr::TransmissionResult doip_client::channel::tcp_channel::DoipTcpChannel::Transmit (uds_transport::UdsMessageConstPtr message)
Function to transmit a valid Uds message.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request.
Definition at line 79 of file doip_tcp_channel.cpp.
{
   uds_transport::UdsTransportProtocolMgr::TransmissionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed};
   // Routing activation should be active before sending diag request
   if (tcp_channel_handler_.IsRoutingActivated()) {
     ret_val = tcp_channel_handler_.SendDiagnosticRequest(std::move(message));
   } else {
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [](std::stringstream &msg) {
           msg << "Routing Activation required, please connect to server first";
         });
   }
   return ret_val;
 }
References FILE_NAME, doip_client::logger::DoipClientLogger::GetDiagClientLogger(), doip_client::channel::tcp_channel::DoipTcpChannelHandler::IsRoutingActivated(), uds_transport::UdsTransportProtocolMgr::kTransmitFailed, doip_client::channel::tcp_channel::DoipTcpChannelHandler::SendDiagnosticRequest(), and tcp_channel_handler_.
Referenced by doip_client::connection::DoipTcpConnection::Transmit().
Member Data Documentation
connection_
uds_transport::Connection& doip_client::channel::tcp_channel::DoipTcpChannel::connection_ private
Store the reference to doip connection.
Definition at line 154 of file doip_tcp_channel.h.
Referenced by HandleMessage(), and IndicateMessage().
tcp_channel_handler_
DoipTcpChannelHandler doip_client::channel::tcp_channel::DoipTcpChannel::tcp_channel_handler_ private
Store the doip channel handler.
Definition at line 149 of file doip_tcp_channel.h.
Referenced by ConnectToHost(), DisconnectFromHost(), ProcessReceivedTcpMessage(), Start(), Stop(), and Transmit().
tcp_socket_handler_
TcpSocketHandler doip_client::channel::tcp_channel::DoipTcpChannel::tcp_socket_handler_ private
Store the tcp socket handler.
Definition at line 144 of file doip_tcp_channel.h.
Referenced by ConnectToHost(), DisconnectFromHost(), IsConnectedToHost(), Start(), and Stop().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_tcp_channel.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_tcp_channel.cpp