Diag-Client-Lib: core_type::Result< T, E > Class Template Reference
core_type::Result< T, E > Class Template Reference final
Class type to contains a value (of type ValueType), or an error (of type ErrorType)
#include <result.h>
Public Types
using value_type = T
Type alias for the type T of values.
using error_type = E
Type alias for the type E of errors.
Public Member Functions
constexpr Result (const T &t) noexcept
Construct a new Result from the specified value (given as lvalue)
constexpr Result (T &&t) noexcept
Construct a new Result from the specified value (given as rvalue)
constexpr Result (const E &e) noexcept
Construct a new Result from the specified error (given as lvalue)
constexpr Result (E &&e) noexcept
Construct a new Result from the specified error (given as rvalue)
Result (const Result &other)=default
Copy-construct a new Result from another instance.
Result & operator= (const Result &other)=default
Copy-assign another Result to this instance.
Result (Result &&other) noexcept(std::is_nothrow_move_constructible< T >::value &&std::is_nothrow_move_constructible< E >::value)=default
Move-construct a new Result from another instance.
Result & operator= (Result &&other) noexcept(std::is_nothrow_move_constructible< T >::value &&std::is_nothrow_move_assignable< T >::value &&std::is_nothrow_move_constructible< E >::value &&std::is_nothrow_move_assignable< E >::value)=default
Move-assign another Result to this instance.
~Result () noexcept=default
Destruct an instance of Result.
template<typename... Args>
void EmplaceValue (Args &&...args) noexcept
Put a new value into this instance, constructed in-place from the given arguments.
template<typename... Args>
void EmplaceError (Args &&...args) noexcept
Put a new error into this instance, constructed in-place from the given arguments.
bool HasValue () const noexcept
Check whether *this contains a value.
operator bool () const noexcept
Check whether *this contains a value.
const T & operator* () const &noexcept
Access the contained value.
T && operator* () &&noexcept
Access the contained value.
const T * operator-> () const noexcept
Access the contained value.
const T & Value () const &noexcept
Access the contained value.
T && Value () &&noexcept
Access the contained value.
const E & Error () const &noexcept
Access the contained error.
E && Error () &&noexcept
Access the contained error.
std::optional< T > Ok () const &noexcept
Return the contained value as an Optional.
std::optional< T > Ok () &&noexcept
Return the contained value as an Optional.
std::optional< E > Err () const &noexcept
Return the contained error as an Optional.
std::optional< E > Err () &&noexcept
Return the contained error as an Optional.
template<typename F , typename T2 = typename std::invoke_result_t<F, T>>
Result< T2, E > AndThen (F &&fn) &&noexcept
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
template<typename F , typename E2 = std::invoke_result_t<F, E>>
Result< T, E2 > MapError (F &&fn)
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
template<typename F >
Result OrElse (F &&fn) &&noexcept
Returns the result itself if it contains a value; otherwise, returns the result of the given function on the error value.
template<typename U >
T ValueOr (U &&defaultValue) const &noexcept
Return the contained value or the given default value.
template<typename U >
T ValueOr (U &&defaultValue) &&noexcept
Return the contained value or the given default value.
template<typename G >
E ErrorOr (G &&defaultError) const &noexcept
Return the contained error or the given default error.
template<typename G >
E ErrorOr (G &&defaultError) &&noexcept
Return the contained error or the given default error.
template<typename F >
T Resolve (F &&f) const
Return the contained value or return the result of a function call.
Static Public Member Functions
static Result FromValue (T &t) noexcept
Build a new Result from the specified value (given as lvalue)
static Result FromValue (T &&t) noexcept
Build a new Result from the specified value (given as rvalue)
template<typename... Args>
static Result FromValue (Args &&...args) noexcept
Build a new Result from a value that is constructed in-place from the given arguments.
static Result FromError (const E &e) noexcept
Build a new Result from the specified error (given as lvalue)
static Result FromError (E &&e) noexcept
Build a new Result from the specified error (given as rvalue)
template<typename... Args>
static Result FromError (Args &&...args) noexcept
Build a new Result from an error that is constructed in-place from the given arguments.
Private Attributes
std::variant< T, E > storage_
Storage to contain value of type T or error of type E.
Detailed Description
template<typename T, typename E = ErrorCode>
class core_type::Result< T, E >
Class type to contains a value (of type ValueType), or an error (of type ErrorType)
This class is implemented based on API specification of ara::core::Result from Adaptive Platform Core AUTOSAR AP R21-11
Template Parameters
T The type of value
E The type of error
Definition at line 29 of file result.h.
Member Typedef Documentation
error_type
template<typename T , typename E = ErrorCode> using core_type::Result< T, E >::error_type = E
Type alias for the type E of errors.
Definition at line 39 of file result.h.
value_type
template<typename T , typename E = ErrorCode> using core_type::Result< T, E >::value_type = T
Type alias for the type T of values.
Definition at line 34 of file result.h.
Constructor & Destructor Documentation
Result() [1/6]
template<typename T , typename E = ErrorCode> constexpr core_type::Result< T, E >::Result (const T & t) inline explicit constexpr noexcept
Construct a new Result from the specified value (given as lvalue)
Parameters
[in] t The value to put into the Result
Definition at line 116 of file result.h.
 : storage_{t} {}
Result() [2/6]
template<typename T , typename E = ErrorCode> constexpr core_type::Result< T, E >::Result (T && t) inline explicit constexpr noexcept
Construct a new Result from the specified value (given as rvalue)
Parameters
[in] t The value to put into the Result
Definition at line 123 of file result.h.
 : storage_{std::move(t)} {}
Result() [3/6]
template<typename T , typename E = ErrorCode> constexpr core_type::Result< T, E >::Result (const E & e) inline explicit constexpr noexcept
Construct a new Result from the specified error (given as lvalue)
Parameters
[in] e The error to put into the Result
Definition at line 130 of file result.h.
 : storage_{e} {}
Result() [4/6]
template<typename T , typename E = ErrorCode> constexpr core_type::Result< T, E >::Result (E && e) inline explicit constexpr noexcept
Construct a new Result from the specified error (given as rvalue)
Parameters
[in] e The error to put into the Result
Definition at line 137 of file result.h.
 : storage_{std::move(e)} {}
Result() [5/6]
template<typename T , typename E = ErrorCode> core_type::Result< T, E >::Result (const Result< T, E > & other) default
Copy-construct a new Result from another instance.
Parameters
[in] other The other instance
Result() [6/6]
template<typename T , typename E = ErrorCode> core_type::Result< T, E >::Result (Result< T, E > && other) const && default noexcept
Move-construct a new Result from another instance.
Parameters
[in] other The other instance
~Result()
template<typename T , typename E = ErrorCode> core_type::Result< T, E >::~Result () default noexcept
Destruct an instance of Result.
Member Function Documentation
AndThen()
template<typename T , typename E = ErrorCode> template<typename F , typename T2 = typename std::invoke_result_t<F, T>> Result<T2, E> core_type::Result< T, E >::AndThen (F && fn) && inline noexcept
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
Template Parameters
F Functor type
Parameters
[in] fn Callable function
Returns
Result An Result
Definition at line 328 of file result.h.
{
     return HasValue() ? Result<T2, E>{fn(std::move(*this).Value())} : Result<T2, E>{*this};
   }
References core_type::Result< T, E >::HasValue().
EmplaceError()
template<typename T , typename E = ErrorCode> template<typename... Args> void core_type::Result< T, E >::EmplaceError (Args &&... args) inline noexcept
Put a new error into this instance, constructed in-place from the given arguments.
Template Parameters
Args The types of arguments given to this function
Parameters
[in] args The arguments used for constructing the error
Definition at line 199 of file result.h.
{
     storage_.template emplace<error_type>(std::forward<Args>(args)...);
   }
References core_type::Result< T, E >::storage_.
EmplaceValue()
template<typename T , typename E = ErrorCode> template<typename... Args> void core_type::Result< T, E >::EmplaceValue (Args &&... args) inline noexcept
Put a new value into this instance, constructed in-place from the given arguments.
Template Parameters
Args The types of arguments given to this function
Parameters
[in] args The arguments used for constructing the value
Definition at line 187 of file result.h.
{
     storage_.template emplace<value_type>(std::forward<Args>(args)...);
   }
References core_type::Result< T, E >::storage_.
Referenced by boost_support::socket::udp::UdpClientSocket::Destroy(), and boost_support::parser::Read().
Err() [1/2]
template<typename T , typename E = ErrorCode> std::optional<E> core_type::Result< T, E >::Err () && inline noexcept
Return the contained error as an Optional.
Returns
std::optional<E> An Optional with the error, if present
Definition at line 311 of file result.h.
{
     std::optional<E> opt_err{};
     if (!HasValue()) { opt_err.emplace(std::move(Error())); }
     return opt_err;
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
Err() [2/2]
template<typename T , typename E = ErrorCode> std::optional<E> core_type::Result< T, E >::Err () const & inline noexcept
Return the contained error as an Optional.
Returns
std::optional<E> An Optional with the error, if present
Definition at line 300 of file result.h.
{
     std::optional<E> opt_err{};
     if (!HasValue()) { opt_err.emplace(Error()); }
     return opt_err;
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
Error() [1/2]
template<typename T , typename E = ErrorCode> E&& core_type::Result< T, E >::Error () && inline noexcept
Access the contained error.
This functions behavior is undefined if *this does not contain an error
Returns
E && An rvalue reference to the contained error
Definition at line 271 of file result.h.
 { return std::move(std::get<error_type>(storage_)); }
References core_type::Result< T, E >::storage_.
Error() [2/2]
template<typename T , typename E = ErrorCode> const E& core_type::Result< T, E >::Error () const & inline noexcept
Access the contained error.
This functions behavior is undefined if *this does not contain an error
Returns
const E & A const reference to the contained error
Definition at line 263 of file result.h.
 { return std::get<error_type>(storage_); }
References core_type::Result< T, E >::storage_.
Referenced by core_type::Result< void, E >::CheckError(), core_type::Result< T, E >::Err(), core_type::Result< void, E >::Err(), core_type::Result< void, E >::MapError(), core_type::Result< void, E >::OrElse(), core_type::Result< T, E >::Resolve(), and core_type::Result< void, E >::Resolve().
ErrorOr() [1/2]
template<typename T , typename E = ErrorCode> template<typename G > E core_type::Result< T, E >::ErrorOr (G && defaultError) && inline noexcept
Return the contained error or the given default error.
If *this contains an error, it is returned. Otherwise, the specified default error is returned, static_castd to E
Template Parameters
G The type of defaultError
Parameters
[in] defaultError The error to use if *this does not contain an error
Returns
E The error
Definition at line 418 of file result.h.
{
     return !HasValue() ? Result{std::move(*this)} : static_cast<E>(defaultError);
   }
References core_type::Result< T, E >::HasValue().
ErrorOr() [2/2]
template<typename T , typename E = ErrorCode> template<typename G > E core_type::Result< T, E >::ErrorOr (G && defaultError) const & inline noexcept
Return the contained error or the given default error.
If *this contains an error, it is returned. Otherwise, the specified default error is returned, static_castd to E
Template Parameters
G The type of defaultError
Parameters
[in] defaultError The error to use if *this does not contain an error
Returns
E The error
Definition at line 403 of file result.h.
{
     return !HasValue() ? Result{*this} : static_cast<E>(defaultError);
   }
References core_type::Result< T, E >::HasValue().
FromError() [1/3]
template<typename T , typename E = ErrorCode> template<typename... Args> static Result core_type::Result< T, E >::FromError (Args &&... args) inline static noexcept
Build a new Result from an error that is constructed in-place from the given arguments.
This function shall not participate in overload resolution unless: std::is_const Args&&...>::value is true, and the first type of the expanded parameter pack first type of the expanded parameter pack is not a specialization of Result
Template Parameters
Args The types of arguments given to this function
Parameters
[in] args The arguments used for constructing the error
Returns
Result A Result that contains an error
Definition at line 107 of file result.h.
{
     return Result{std::forward<Args>(args)...};
   }
FromError() [2/3]
template<typename T , typename E = ErrorCode> static Result core_type::Result< T, E >::FromError (const E & e) inline static noexcept
Build a new Result from the specified error (given as lvalue)
Parameters
[in] e The error to put into the Result
Returns
Result A Result that contains the error e
Definition at line 83 of file result.h.
 { return Result{e}; }
Referenced by diag::client::conversation::DmConversation::SendDiagnosticRequest(), and diag::client::conversation::Conversation::SendDiagnosticRequest().
FromError() [3/3]
template<typename T , typename E = ErrorCode> static Result core_type::Result< T, E >::FromError (E && e) inline static noexcept
Build a new Result from the specified error (given as rvalue)
Parameters
[in] e The error to put into the Result
Returns
Result A Result that contains the error e
Definition at line 92 of file result.h.
 { return Result{std::move(e)}; }
FromValue() [1/3]
template<typename T , typename E = ErrorCode> template<typename... Args> static Result core_type::Result< T, E >::FromValue (Args &&... args) inline static noexcept
Build a new Result from a value that is constructed in-place from the given arguments.
This function shall not participate in overload resolution unless: std::is_constructible<T, Args&&...>::value is true, and the first type of the expanded parameter pack is not T, and the first type of the expanded parameter pack is not a specialization of Result
Template Parameters
Args The types of arguments given to this function
Parameters
[in] args The arguments used for constructing the value
Returns
Result A Result that contains a value
Definition at line 72 of file result.h.
{
     return Result{std::forward<Args>(args)...};
   }
FromValue() [2/3]
template<typename T , typename E = ErrorCode> static Result core_type::Result< T, E >::FromValue (T && t) inline static noexcept
Build a new Result from the specified value (given as rvalue)
Parameters
[in] t The value to put into the Result
Returns
Result A Result that contains the value t
Definition at line 57 of file result.h.
 { return Result{std::move(t)}; }
FromValue() [3/3]
template<typename T , typename E = ErrorCode> static Result core_type::Result< T, E >::FromValue (T & t) inline static noexcept
Build a new Result from the specified value (given as lvalue)
Parameters
[in] t The value to put into the Result
Returns
Result A Result that contains the value t
Definition at line 48 of file result.h.
 { return Result{t}; }
HasValue()
template<typename T , typename E = ErrorCode> bool core_type::Result< T, E >::HasValue () const inline noexcept
Check whether *this contains a value.
Returns
bool True if *this contains a value, false otherwise
Definition at line 208 of file result.h.
 { return std::holds_alternative<value_type>(storage_); }
References core_type::Result< T, E >::storage_.
Referenced by core_type::Result< T, E >::AndThen(), core_type::Result< void, E >::AndThen(), core_type::Result< void, E >::CheckError(), core_type::Result< T, E >::Err(), core_type::Result< void, E >::Err(), core_type::Result< T, E >::ErrorOr(), core_type::Result< void, E >::ErrorOr(), core_type::Result< T, E >::MapError(), core_type::Result< void, E >::MapError(), core_type::Result< T, E >::Ok(), core_type::Result< T, E >::operator bool(), core_type::Result< void, E >::operator bool(), core_type::Result< T, E >::OrElse(), core_type::Result< void, E >::OrElse(), core_type::Result< T, E >::Resolve(), and core_type::Result< T, E >::ValueOr().
MapError()
template<typename T , typename E = ErrorCode> template<typename F , typename E2 = std::invoke_result_t<F, E>> Result<T, E2> core_type::Result< T, E >::MapError (F && fn) inline
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
Template Parameters
F Functor type
Parameters
[in] fn Callable function
Returns
Result An Result
Definition at line 343 of file result.h.
{
     return HasValue() ? Result<T, E2>{std::move(*this).Value()} : Result<T, E2>{fn(std::move(*this).Error())};
   }
References core_type::Result< T, E >::HasValue(), and core_type::Result< T, E >::Value().
Ok() [1/2]
template<typename T , typename E = ErrorCode> std::optional<T> core_type::Result< T, E >::Ok () && inline noexcept
Return the contained value as an Optional.
Returns
std::optional<T> An Optional with the value, if present
Definition at line 289 of file result.h.
{
     std::optional<T> opt_val{};
     if (HasValue()) { opt_val.emplace(std::move(Value())); }
     return opt_val;
   }
References core_type::Result< T, E >::HasValue(), and core_type::Result< T, E >::Value().
Ok() [2/2]
template<typename T , typename E = ErrorCode> std::optional<T> core_type::Result< T, E >::Ok () const & inline noexcept
Return the contained value as an Optional.
Returns
std::optional<T> An Optional with the value, if present
Definition at line 278 of file result.h.
{
     std::optional<T> opt_val{};
     if (HasValue()) { opt_val.emplace(Value()); }
     return opt_val;
   }
References core_type::Result< T, E >::HasValue(), and core_type::Result< T, E >::Value().
operator bool()
template<typename T , typename E = ErrorCode> core_type::Result< T, E >::operator bool () const inline explicit noexcept
Check whether *this contains a value.
Returns
bool True if *this contains a value, false otherwise
Definition at line 215 of file result.h.
 { return HasValue(); }
References core_type::Result< T, E >::HasValue().
operator*() [1/2]
template<typename T , typename E = ErrorCode> T&& core_type::Result< T, E >::operator* () && inline noexcept
Access the contained value.
This functions behavior is undefined if *this does not contain a value
Returns
T && An rvalue reference to the contained value
Definition at line 231 of file result.h.
 { return std::move(std::get<value_type>(storage_)); }
References core_type::Result< T, E >::storage_.
operator*() [2/2]
template<typename T , typename E = ErrorCode> const T& core_type::Result< T, E >::operator* () const & inline noexcept
Access the contained value.
This functions behavior is undefined if *this does not contain a value
Returns
const T & A const_reference to the contained value
Definition at line 223 of file result.h.
 { return std::get<value_type>(storage_); }
References core_type::Result< T, E >::storage_.
operator->()
template<typename T , typename E = ErrorCode> const T* core_type::Result< T, E >::operator-> () const inline noexcept
Access the contained value.
This functions behavior is undefined if *this does not contain a value
Returns
const T * A pointer to the contained value
Definition at line 239 of file result.h.
 { return std::get_if<value_type>(storage_); }
References core_type::Result< T, E >::storage_.
operator=() [1/2]
template<typename T , typename E = ErrorCode> Result& core_type::Result< T, E >::operator= (const Result< T, E > & other) default
Copy-assign another Result to this instance.
Parameters
[in] other The other instance
Returns
Result & *this, containing the contents of other
operator=() [2/2]
template<typename T , typename E = ErrorCode> Result& core_type::Result< T, E >::operator= (Result< T, E > && other) const && default noexcept
Move-assign another Result to this instance.
Parameters
[in] other The other instance
Returns
Result & *this, containing the contents of other
OrElse()
template<typename T , typename E = ErrorCode> template<typename F > Result core_type::Result< T, E >::OrElse (F && fn) && inline noexcept
Returns the result itself if it contains a value; otherwise, returns the result of the given function on the error value.
Template Parameters
F Functor type
Parameters
[in] fn Callable function
Returns
Result An Result
Definition at line 358 of file result.h.
{
     return HasValue() ? Result{std::move(*this)} : Result{fn(std::move(*this).Error())};
   }
References core_type::Result< T, E >::HasValue().
Resolve()
template<typename T , typename E = ErrorCode> template<typename F > T core_type::Result< T, E >::Resolve (F && f) const inline
Return the contained value or return the result of a function call.
If *this contains a value, it is returned. Otherwise, the specified callable is invoked and its return value which is to be compatible to type T is returned from this function. The Callable is expected to be compatible to this interface: T f(const E&)
Template Parameters
F The type of the Callable f
Parameters
[in] f The Callable
Returns
T The value
Definition at line 435 of file result.h.
{
     return HasValue() ? Result{*this} : f(Error());
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
Value() [1/2]
template<typename T , typename E = ErrorCode> T&& core_type::Result< T, E >::Value () && inline noexcept
Access the contained value.
This functions behavior is undefined if *this does not contain a value
Returns
T && An rvalue reference to the contained value
Definition at line 255 of file result.h.
 { return std::move(std::get<value_type>(storage_)); }
References core_type::Result< T, E >::storage_.
Value() [2/2]
template<typename T , typename E = ErrorCode> const T& core_type::Result< T, E >::Value () const & inline noexcept
Access the contained value.
This functions behavior is undefined if *this does not contain a value
Returns
const T & A const reference to the contained value
Definition at line 247 of file result.h.
 { return std::get<value_type>(storage_); }
References core_type::Result< T, E >::storage_.
Referenced by core_type::Result< T, E >::MapError(), and core_type::Result< T, E >::Ok().
ValueOr() [1/2]
template<typename T , typename E = ErrorCode> template<typename U > T core_type::Result< T, E >::ValueOr (U && defaultValue) && inline noexcept
Return the contained value or the given default value.
If *this contains a value, it is returned. Otherwise, the specified default value is returned, static_castd to T
Template Parameters
U The type of defaultValue
Parameters
[in] defaultValue The value to use if *this does not contain a value
Returns
T The value
Definition at line 388 of file result.h.
{
     return HasValue() ? Result{std::move(*this)} : static_cast<T>(defaultValue);
   }
References core_type::Result< T, E >::HasValue().
ValueOr() [2/2]
template<typename T , typename E = ErrorCode> template<typename U > T core_type::Result< T, E >::ValueOr (U && defaultValue) const & inline noexcept
Return the contained value or the given default value.
If *this contains a value, it is returned. Otherwise, the specified default value is returned, static_castd to T
Template Parameters
U The type of defaultValue
Parameters
[in] defaultValue The value to use if *this does not contain a value
Returns
T The value
Definition at line 373 of file result.h.
{
     return HasValue() ? Result{*this} : static_cast<T>(defaultValue);
   }
References core_type::Result< T, E >::HasValue().
Member Data Documentation
storage_
template<typename T , typename E = ErrorCode> std::variant<T, E> core_type::Result< T, E >::storage_ private
Storage to contain value of type T or error of type E.
Definition at line 443 of file result.h.
Referenced by core_type::Result< T, E >::EmplaceError(), core_type::Result< void, E >::EmplaceError(), core_type::Result< void, E >::EmplaceValue(), core_type::Result< T, E >::EmplaceValue(), core_type::Result< T, E >::Error(), core_type::Result< void, E >::Error(), core_type::Result< T, E >::HasValue(), core_type::Result< void, E >::HasValue(), core_type::Result< T, E >::operator*(), core_type::Result< T, E >::operator->(), and core_type::Result< T, E >::Value().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/platform-core/core/include/result.h