Diag-Client-Lib: boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket > Class Template Reference
boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket > Class Template Reference final
Server connection class used to handle transmission and reception of tcp message from socket.
#include <tcp_connection.h>
Public Types
using TcpMessage = typename Socket::TcpMessage
Type alias for Tcp message.
using TcpMessagePtr = typename Socket::TcpMessagePtr
Type alias for Tcp message pointer.
using TcpMessageConstPtr = typename Socket::TcpMessageConstPtr
Type alias for Tcp message const pointer.
using HandlerRead = std::function< void(TcpMessagePtr)>
Tcp function template used for reception.
Public Member Functions
TcpConnection (std::string_view connection_name, Socket socket) noexcept
Constructs an instance of TcpConnection.
TcpConnection (const TcpConnection &other) noexcept=delete
Deleted copy assignment and copy constructor.
TcpConnection & operator= (const TcpConnection &other) &noexcept=delete
TcpConnection (TcpConnection &&other) noexcept
Move assignment.
TcpConnection & operator= (TcpConnection &&other) &noexcept
Move constructor.
~TcpConnection () noexcept=default
Destruct an instance of TcpConnection.
void SetReadHandler (HandlerRead read_handler)
Function to set the read handler that is invoked when message is received.
void Initialize () noexcept
Initialize the Server.
void DeInitialize () noexcept
De-initialize the server.
core_type::Result< void > Transmit (TcpMessageConstPtr message) noexcept
Function to trigger transmission.
Private Member Functions
auto ReadMessage () noexcept -> bool
Function to send the received message to stored handler.
Private Attributes
Socket socket_
Store socket used for reading and writing tcp message.
HandlerRead handler_read_
Store the handler.
std::atomic_bool exit_request_
Flag to terminate the thread.
std::atomic_bool running_
Flag to start the thread.
std::condition_variable cond_var_
Conditional variable to block the thread.
std::string connection_name_
Store the connection name.
utility::thread::Thread thread_
Store the thread.
std::mutex mutex_
mutex to lock critical section
Detailed Description
template<typename Socket>
class boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >
Server connection class used to handle transmission and reception of tcp message from socket.
Template Parameters
Socket The type of socket to read and write from/to
Definition at line 259 of file tcp_connection.h.
Member Typedef Documentation
HandlerRead
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::HandlerRead = std::function<void(TcpMessagePtr)>
Tcp function template used for reception.
Definition at line 279 of file tcp_connection.h.
TcpMessage
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::TcpMessage = typename Socket::TcpMessage
Type alias for Tcp message.
Definition at line 264 of file tcp_connection.h.
TcpMessageConstPtr
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::TcpMessageConstPtr = typename Socket::TcpMessageConstPtr
Type alias for Tcp message const pointer.
Definition at line 274 of file tcp_connection.h.
TcpMessagePtr
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::TcpMessagePtr = typename Socket::TcpMessagePtr
Type alias for Tcp message pointer.
Definition at line 269 of file tcp_connection.h.
Constructor & Destructor Documentation
TcpConnection() [1/3]
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::TcpConnection (std::string_view connection_name, Socket socket) inline explicit noexcept
Constructs an instance of TcpConnection.
Parameters
[in] socket The socket used for read and writing messages
Definition at line 287 of file tcp_connection.h.
       : socket_{std::move(socket)},
         handler_read_{},
         exit_request_{false},
         running_{false},
         cond_var_{},
         connection_name_{connection_name},
         thread_{},
         mutex_{} {}
TcpConnection() [2/3]
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::TcpConnection (const TcpConnection< ConnectionType::kServer, Socket > & other) delete noexcept
Deleted copy assignment and copy constructor.
TcpConnection() [3/3]
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::TcpConnection (TcpConnection< ConnectionType::kServer, Socket > && other) inline noexcept
Move assignment.
Definition at line 306 of file tcp_connection.h.
       : socket_{std::move(other.socket_)},
         handler_read_{std::move(other.handler_read_)},
         exit_request_{other.exit_request_.load()},
         running_{other.running_.load()},
         thread_{std::move(other.thread_)} {}
~TcpConnection()
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::~TcpConnection () default noexcept
Destruct an instance of TcpConnection.
Member Function Documentation
DeInitialize()
template<typename Socket > void boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::DeInitialize () inline noexcept
De-initialize the server.
Definition at line 366 of file tcp_connection.h.
{
     socket_.Close();
     {
       std::unique_lock<std::mutex> lck(mutex_);
       exit_request_ = true;
       running_ = false;
     }
     cond_var_.notify_all();
     thread_.Join();
   }
Initialize()
template<typename Socket > void boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::Initialize () inline noexcept
Initialize the Server.
Definition at line 341 of file tcp_connection.h.
{
     // Start thread to receive messages
     thread_ = utility::thread::Thread(connection_name_, [this]() {
       std::unique_lock<std::mutex> lck(mutex_);
       while (!exit_request_) {
         if (!running_) {
           cond_var_.wait(lck, [this]() { return exit_request_ || running_; });
         }
         if (!exit_request_ && running_) {
           lck.unlock();
           running_ = ReadMessage();
           lck.lock();
         }
       }
     });
     {  // start reading
       std::lock_guard<std::mutex> lock{mutex_};
       running_ = true;
       cond_var_.notify_all();
     }
   }
operator=() [1/2]
template<typename Socket > TcpConnection& boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::operator= (const TcpConnection< ConnectionType::kServer, Socket > & other) & delete noexcept
operator=() [2/2]
template<typename Socket > TcpConnection& boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::operator= (TcpConnection< ConnectionType::kServer, Socket > && other) & inline noexcept
Move constructor.
Definition at line 316 of file tcp_connection.h.
{
     socket_ = std::move(other.socket_);
     handler_read_ = std::move(other.handler_read_);
     exit_request_.store(other.exit_request_.load());
     running_.store(other.running_.load());
     thread_ = std::move(other.thread_);
     return *this;
   }
ReadMessage()
template<typename Socket > auto boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::ReadMessage () -> bool inline private noexcept
Function to send the received message to stored handler.
Returns
True if message is read successfully, otherwise False
Definition at line 437 of file tcp_connection.h.
{
     // Try reading from socket
     return socket_.Read()
         .AndThen([this](TcpMessagePtr tcp_message) {
           if (handler_read_) { handler_read_(std::move(tcp_message)); }
           return core_type::Result<void, typename Socket::SocketError>::FromValue();
         })
         .HasValue();
   }
References core_type::Result< T, E >::FromValue().
SetReadHandler()
template<typename Socket > void boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::SetReadHandler (HandlerRead read_handler) inline
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 336 of file tcp_connection.h.
 { handler_read_ = std::move(read_handler); }
Transmit()
template<typename Socket > core_type::Result<void> boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::Transmit (TcpMessageConstPtr message) inline noexcept
Function to trigger transmission.
Parameters
[in] message The tcp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 383 of file tcp_connection.h.
{
     return socket_.Transmit(std::move(message))
         .AndThen([]() { return core_type::Result<void>::FromValue(); })
         .MapError([](typename Socket::SocketError const &) {
           return error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kSocketError);
         });
   }
References core_type::Result< T, E >::FromValue(), boost_support::error_domain::kSocketError, and boost_support::error_domain::MakeErrorCode().
Member Data Documentation
cond_var_
template<typename Socket > std::condition_variable boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::cond_var_ private
Conditional variable to block the thread.
Definition at line 415 of file tcp_connection.h.
connection_name_
template<typename Socket > std::string boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::connection_name_ private
Store the connection name.
Definition at line 420 of file tcp_connection.h.
exit_request_
template<typename Socket > std::atomic_bool boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::exit_request_ private
Flag to terminate the thread.
Definition at line 405 of file tcp_connection.h.
handler_read_
template<typename Socket > HandlerRead boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::handler_read_ private
Store the handler.
Definition at line 400 of file tcp_connection.h.
mutex_
template<typename Socket > std::mutex boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::mutex_ private
mutex to lock critical section
Definition at line 430 of file tcp_connection.h.
running_
template<typename Socket > std::atomic_bool boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::running_ private
Flag to start the thread.
Definition at line 410 of file tcp_connection.h.
socket_
template<typename Socket > Socket boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::socket_ private
Store socket used for reading and writing tcp message.
Definition at line 395 of file tcp_connection.h.
thread_
template<typename Socket > utility::thread::Thread boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::thread_ private
Store the thread.
Definition at line 425 of file tcp_connection.h.
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/connection/tcp/tcp_connection.h