Diag-Client-Lib: boost_support::connection::udp::UdpConnection< Socket > Class Template Reference
boost_support::connection::udp::UdpConnection< Socket > Class Template Reference final
Client connection class used to handle transmission and reception of udp message from socket.
#include <udp_connection.h>
Public Types
using UdpMessage = typename Socket::UdpMessage
Type alias for Udp message.
using UdpMessagePtr = typename Socket::UdpMessagePtr
Type alias for Udp message pointer.
using UdpMessageConstPtr = typename Socket::UdpMessageConstPtr
Type alias for Udp message const pointer.
using HandlerRead = std::function< void(UdpMessagePtr)>
Tcp function template used for reception.
Public Member Functions
UdpConnection (Socket socket) noexcept
Constructs an instance of UdpConnection.
UdpConnection (const UdpConnection &other) noexcept=delete
Deleted copy assignment and copy constructor.
UdpConnection & operator= (const UdpConnection &other) &noexcept=delete
UdpConnection (UdpConnection &&other) noexcept=default
Move assignment and move constructor.
UdpConnection & operator= (UdpConnection &&other) &noexcept=default
~UdpConnection () noexcept=default
Destruct an instance of UdpConnection.
void SetReadHandler (HandlerRead read_handler)
Function to set the read handler that is invoked when message is received.
void Initialize () noexcept
Initialize the client.
void DeInitialize () noexcept
De-initialize the client.
core_type::Result< void > Transmit (UdpMessageConstPtr message) noexcept
Function to trigger transmission.
Private Attributes
Socket socket_
Store socket used for reading and writing tcp message.
Detailed Description
template<typename Socket>
class boost_support::connection::udp::UdpConnection< Socket >
Client connection class used to handle transmission and reception of udp message from socket.
Template Parameters
Socket The type of socket to read and write from/to
Definition at line 26 of file udp_connection.h.
Member Typedef Documentation
HandlerRead
template<typename Socket > using boost_support::connection::udp::UdpConnection< Socket >::HandlerRead = std::function<void(UdpMessagePtr)>
Tcp function template used for reception.
Definition at line 46 of file udp_connection.h.
UdpMessage
template<typename Socket > using boost_support::connection::udp::UdpConnection< Socket >::UdpMessage = typename Socket::UdpMessage
Type alias for Udp message.
Definition at line 31 of file udp_connection.h.
UdpMessageConstPtr
template<typename Socket > using boost_support::connection::udp::UdpConnection< Socket >::UdpMessageConstPtr = typename Socket::UdpMessageConstPtr
Type alias for Udp message const pointer.
Definition at line 41 of file udp_connection.h.
UdpMessagePtr
template<typename Socket > using boost_support::connection::udp::UdpConnection< Socket >::UdpMessagePtr = typename Socket::UdpMessagePtr
Type alias for Udp message pointer.
Definition at line 36 of file udp_connection.h.
Constructor & Destructor Documentation
UdpConnection() [1/3]
template<typename Socket > boost_support::connection::udp::UdpConnection< Socket >::UdpConnection (Socket socket) inline explicit noexcept
Constructs an instance of UdpConnection.
Parameters
[in] socket The socket used for read and writing messages
Definition at line 54 of file udp_connection.h.
 : socket_{std::move(socket)} {}
UdpConnection() [2/3]
template<typename Socket > boost_support::connection::udp::UdpConnection< Socket >::UdpConnection (const UdpConnection< Socket > & other) delete noexcept
Deleted copy assignment and copy constructor.
UdpConnection() [3/3]
template<typename Socket > boost_support::connection::udp::UdpConnection< Socket >::UdpConnection (UdpConnection< Socket > && other) default noexcept
Move assignment and move constructor.
~UdpConnection()
template<typename Socket > boost_support::connection::udp::UdpConnection< Socket >::~UdpConnection () default noexcept
Destruct an instance of UdpConnection.
Member Function Documentation
DeInitialize()
template<typename Socket > void boost_support::connection::udp::UdpConnection< Socket >::DeInitialize () inline noexcept
De-initialize the client.
Definition at line 92 of file udp_connection.h.
 { socket_.Close(); }
References boost_support::connection::udp::UdpConnection< Socket >::socket_.
Referenced by boost_support::client::udp::UdpClient::UdpClientImpl::DeInitialize().
Initialize()
template<typename Socket > void boost_support::connection::udp::UdpConnection< Socket >::Initialize () inline noexcept
Initialize the client.
Definition at line 84 of file udp_connection.h.
{
     // Open socket
     socket_.Open();
   }
References boost_support::connection::udp::UdpConnection< Socket >::socket_.
Referenced by boost_support::client::udp::UdpClient::UdpClientImpl::Initialize().
operator=() [1/2]
template<typename Socket > UdpConnection& boost_support::connection::udp::UdpConnection< Socket >::operator= (const UdpConnection< Socket > & other) & delete noexcept
operator=() [2/2]
template<typename Socket > UdpConnection& boost_support::connection::udp::UdpConnection< Socket >::operator= (UdpConnection< Socket > && other) & default noexcept
SetReadHandler()
template<typename Socket > void boost_support::connection::udp::UdpConnection< Socket >::SetReadHandler (HandlerRead read_handler) inline
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 79 of file udp_connection.h.
 { socket_.SetReadHandler(std::move(read_handler)); }
References boost_support::connection::udp::UdpConnection< Socket >::socket_.
Referenced by boost_support::client::udp::UdpClient::UdpClientImpl::SetReadHandler().
Transmit()
template<typename Socket > core_type::Result<void> boost_support::connection::udp::UdpConnection< Socket >::Transmit (UdpMessageConstPtr message) inline noexcept
Function to trigger transmission.
Parameters
[in] message The udp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 100 of file udp_connection.h.
{
     return socket_.Transmit(std::move(message))
         .AndThen([]() { return core_type::Result<void>::FromValue(); })
         .MapError([](typename Socket::SocketError const &) {
           return error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kSocketError);
         });
   }
References core_type::Result< T, E >::FromValue(), boost_support::error_domain::kSocketError, boost_support::error_domain::MakeErrorCode(), and boost_support::connection::udp::UdpConnection< Socket >::socket_.
Referenced by boost_support::client::udp::UdpClient::UdpClientImpl::Transmit().
Member Data Documentation
socket_
template<typename Socket > Socket boost_support::connection::udp::UdpConnection< Socket >::socket_ private
Store socket used for reading and writing tcp message.
Definition at line 112 of file udp_connection.h.
Referenced by boost_support::connection::udp::UdpConnection< Socket >::DeInitialize(), boost_support::connection::udp::UdpConnection< Socket >::Initialize(), boost_support::connection::udp::UdpConnection< Socket >::SetReadHandler(), and boost_support::connection::udp::UdpConnection< Socket >::Transmit().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/connection/udp/udp_connection.h