Diag-Client-Lib: doip_client::channel::tcp_channel::DoipTcpChannelHandler Class Reference
doip_client::channel::tcp_channel::DoipTcpChannelHandler Class Reference final
Class to handle tcp received messages from lower layer.
#include <doip_tcp_channel_handler.h>
Public Types
using TcpMessagePtr = sockets::TcpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
Public Member Functions
DoipTcpChannelHandler (sockets::TcpSocketHandler &tcp_socket_handler, DoipTcpChannel &channel)
Constructs an instance of DoipTcpChannelHandler.
void Start ()
Function to start the handler.
void Stop ()
Function to stop the handler.
void Reset ()
Function to reset the handler.
auto SendRoutingActivationRequest (uds_transport::UdsMessageConstPtr routing_activation_request) noexcept -> uds_transport::UdsTransportProtocolMgr::ConnectionResult
Function to send routing activation request.
auto SendDiagnosticRequest (uds_transport::UdsMessageConstPtr diagnostic_request) noexcept -> uds_transport::UdsTransportProtocolMgr::TransmissionResult
Function to send diagnostic request.
void HandleMessage (TcpMessagePtr tcp_rx_message) noexcept
Function to process the received message.
auto IsRoutingActivated () noexcept -> bool
Check if routing activation is active for this handler.
Private Member Functions
auto ProcessDoIPHeader (DoipMessage &doip_rx_message, std::uint8_t &nack_code) noexcept -> bool
Function to process doip header in received response.
auto ProcessDoIPPayloadLength (std::uint32_t payload_len, std::uint16_t payload_type) noexcept -> bool
Function to verify payload length of various payload type.
void ProcessDoIPPayload (DoipMessage &doip_payload) noexcept
Function to process the doip payload.
Private Attributes
RoutingActivationHandler routing_activation_handler_
Handler to process routing activation req/ resp.
DiagnosticMessageHandler diagnostic_message_handler_
Handler to process diagnostic message req/ resp.
std::mutex channel_handler_lock
Mutex to protect critical section.
Detailed Description
Class to handle tcp received messages from lower layer.
Definition at line 30 of file doip_tcp_channel_handler.h.
Member Typedef Documentation
TcpMessagePtr
using doip_client::channel::tcp_channel::DoipTcpChannelHandler::TcpMessagePtr = sockets::TcpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
Definition at line 35 of file doip_tcp_channel_handler.h.
Constructor & Destructor Documentation
DoipTcpChannelHandler()
doip_client::channel::tcp_channel::DoipTcpChannelHandler::DoipTcpChannelHandler (sockets::TcpSocketHandler & tcp_socket_handler, DoipTcpChannel & channel)
Constructs an instance of DoipTcpChannelHandler.
Parameters
[in] tcp_socket_handler The reference to socket handler
[in] channel The reference to tcp transport handler
Definition at line 66 of file doip_tcp_channel_handler.cpp.
     : routing_activation_handler_{tcp_socket_handler},
       diagnostic_message_handler_{tcp_socket_handler, channel} {}
Member Function Documentation
HandleMessage()
auto doip_client::channel::tcp_channel::DoipTcpChannelHandler::HandleMessage (TcpMessagePtr tcp_rx_message) noexcept
Function to process the received message.
Parameters
[in] tcp_rx_message The message received
Definition at line 99 of file doip_tcp_channel_handler.cpp.
{
   std::uint8_t nack_code{};
   DoipMessage doip_rx_message{DoipMessage::MessageType::kTcp, tcp_rx_message->GetHostIpAddress(),
                               tcp_rx_message->GetHostPortNumber(), tcp_rx_message->GetPayload()};
   // Process the Doip Generic header check
   if (ProcessDoIPHeader(doip_rx_message, nack_code)) {
     ProcessDoIPPayload(doip_rx_message);
   } else {
     // send NACK or ignore
     (void) nack_code;
   }
 }
References doip_client::DoipMessage::kTcp.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::ProcessReceivedTcpMessage().
IsRoutingActivated()
auto doip_client::channel::tcp_channel::DoipTcpChannelHandler::IsRoutingActivated () -> bool noexcept
Check if routing activation is active for this handler.
Returns
True if activated, otherwise False
Definition at line 112 of file doip_tcp_channel_handler.cpp.
{
   return routing_activation_handler_.IsRoutingActivated();
 }
References doip_client::channel::tcp_channel::RoutingActivationHandler::IsRoutingActivated(), and routing_activation_handler_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::DisconnectFromHost(), and doip_client::channel::tcp_channel::DoipTcpChannel::Transmit().
ProcessDoIPHeader()
auto doip_client::channel::tcp_channel::DoipTcpChannelHandler::ProcessDoIPHeader (DoipMessage & doip_rx_message, std::uint8_t & nack_code) -> bool private noexcept
Function to process doip header in received response.
Parameters
[in] doip_rx_message The received doip rx message
[in] nack_code The negative ack code
Definition at line 116 of file doip_tcp_channel_handler.cpp.
{
   bool ret_val = false;
   /* Check the header synchronisation pattern */
   if (((doip_rx_message.GetProtocolVersion() == kDoip_ProtocolVersion) &&
        (doip_rx_message.GetInverseProtocolVersion() ==
         static_cast<std::uint8_t>(~kDoip_ProtocolVersion))) ||
       ((doip_rx_message.GetProtocolVersion() == kDoip_ProtocolVersion_Def) &&
        (doip_rx_message.GetInverseProtocolVersion() ==
         static_cast<std::uint8_t>(~kDoip_ProtocolVersion_Def)))) {
     /* Check the supported payload type */
     if ((doip_rx_message.GetPayloadType() == kDoip_RoutingActivation_ResType) ||
         (doip_rx_message.GetPayloadType() == kDoipDiagMessagePosAck) ||
         (doip_rx_message.GetPayloadType() == kDoipDiagMessageNegAck) ||
         (doip_rx_message.GetPayloadType() == kDoipDiagMessage) ||
         (doip_rx_message.GetPayloadType() == kDoip_AliveCheck_ReqType)) {
       /* Req-[AUTOSAR_SWS_DiagnosticOverIP][SWS_DoIP_00017] */
       if (doip_rx_message.GetPayloadLength() <= kDoip_Protocol_MaxPayload) {
         /* Req-[AUTOSAR_SWS_DiagnosticOverIP][SWS_DoIP_00018] */
         if (doip_rx_message.GetPayloadLength() <= kTcpChannelLength) {
           /* Req-[AUTOSAR_SWS_DiagnosticOverIP][SWS_DoIP_00019] */
           if (ProcessDoIPPayloadLength(doip_rx_message.GetPayloadLength(),
                                        doip_rx_message.GetPayloadType())) {
             ret_val = true;
           } else {
             // Send NACK code 0x04, close the socket
             nack_code = kDoip_GenericHeader_InvalidPayloadLen;
             // socket closure ??
           }
         } else {
           // Send NACK code 0x03, discard message
           nack_code = kDoip_GenericHeader_OutOfMemory;
         }
       } else {
         // Send NACK code 0x02, discard message
         nack_code = kDoip_GenericHeader_MessageTooLarge;
       }
     } else {  // Send NACK code 0x01, discard message
       nack_code = kDoip_GenericHeader_UnknownPayload;
     }
   } else {  // Send NACK code 0x00, close the socket
     nack_code = kDoip_GenericHeader_IncorrectPattern;
     // socket closure
   }
   return ret_val;
 }
References doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_AliveCheck_ReqType, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_GenericHeader_IncorrectPattern, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_GenericHeader_InvalidPayloadLen, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_GenericHeader_MessageTooLarge, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_GenericHeader_OutOfMemory, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_GenericHeader_UnknownPayload, doip_client::kDoip_Protocol_MaxPayload, doip_client::kDoip_ProtocolVersion, doip_client::kDoip_ProtocolVersion_Def, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_RoutingActivation_ResType, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessage, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessageNegAck, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessagePosAck, and doip_client::kTcpChannelLength.
ProcessDoIPPayload()
void doip_client::channel::tcp_channel::DoipTcpChannelHandler::ProcessDoIPPayload (DoipMessage & doip_payload) private noexcept
Function to process the doip payload.
Parameters
[in] doip_payload The reference to received payload
Definition at line 192 of file doip_tcp_channel_handler.cpp.
{
   std::lock_guard<std::mutex> const lck(channel_handler_lock);
   switch (doip_payload.GetPayloadType()) {
     case kDoip_RoutingActivation_ResType:
       // Process RoutingActivation response
       routing_activation_handler_.ProcessDoIPRoutingActivationResponse(doip_payload);
       break;
     case kDoipDiagMessage:
       // Process Diagnostic Message Response
       diagnostic_message_handler_.ProcessDoIPDiagnosticMessageResponse(doip_payload);
       break;
     case kDoipDiagMessagePosAck:
     case kDoipDiagMessageNegAck:
       // Process positive or negative diag ack message
       diagnostic_message_handler_.ProcessDoIPDiagnosticAckMessageResponse(doip_payload);
       break;
     default:
       /* do nothing */
       break;
   }
 }
References doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_RoutingActivation_ResType, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessage, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessageNegAck, and doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessagePosAck.
ProcessDoIPPayloadLength()
auto doip_client::channel::tcp_channel::DoipTcpChannelHandler::ProcessDoIPPayloadLength (std::uint32_t payload_len, std::uint16_t payload_type) -> bool private noexcept
Function to verify payload length of various payload type.
Parameters
[in] payload_len The length of payload received
[in] payload_type The type of payload
Definition at line 163 of file doip_tcp_channel_handler.cpp.
{
   bool ret_val{false};
   switch (payload_type) {
     case kDoip_RoutingActivation_ResType: {
       if (payload_length <= kDoipRoutingActivationResMaxLen) ret_val = true;
       break;
     }
     case kDoipDiagMessagePosAck:
     case kDoipDiagMessageNegAck: {
       if (payload_length >= kDoipDiagMessageAckResMinLen) ret_val = true;
       break;
     }
     case kDoipDiagMessage: {
       // Atleast 1 byte of data must be present
       if (payload_length >= (kDoipDiagMessageReqResMinLen + 1u)) ret_val = true;
       break;
     }
     case kDoip_AliveCheck_ReqType: {
       if (payload_length <= kDoipRoutingActivationResMaxLen) ret_val = true;
       break;
     }
     default:
       // do nothing
       break;
   }
   return ret_val;
 }
References doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_AliveCheck_ReqType, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoip_RoutingActivation_ResType, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessage, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessageAckResMinLen, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessageNegAck, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessagePosAck, doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipDiagMessageReqResMinLen, and doip_client::channel::tcp_channel::anonymous_namespace{doip_tcp_channel_handler.cpp}::kDoipRoutingActivationResMaxLen.
Reset()
void doip_client::channel::tcp_channel::DoipTcpChannelHandler::Reset ()
Function to reset the handler.
This will reset all the internal handler back to default state
Definition at line 81 of file doip_tcp_channel_handler.cpp.
{
   routing_activation_handler_.Reset();
   diagnostic_message_handler_.Reset();
 }
References diagnostic_message_handler_, doip_client::channel::tcp_channel::DiagnosticMessageHandler::Reset(), doip_client::channel::tcp_channel::RoutingActivationHandler::Reset(), and routing_activation_handler_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::DisconnectFromHost().
SendDiagnosticRequest()
auto doip_client::channel::tcp_channel::DoipTcpChannelHandler::SendDiagnosticRequest (uds_transport::UdsMessageConstPtr diagnostic_request) -> uds_transport::UdsTransportProtocolMgr::TransmissionResult noexcept
Function to send diagnostic request.
Parameters
[in] diagnostic_request The diagnostic request
Returns
TransmissionResult The transmission result
Definition at line 93 of file doip_tcp_channel_handler.cpp.
{
   return diagnostic_message_handler_.HandleDiagnosticRequest(std::move(diagnostic_request));
 }
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Transmit().
SendRoutingActivationRequest()
auto doip_client::channel::tcp_channel::DoipTcpChannelHandler::SendRoutingActivationRequest (uds_transport::UdsMessageConstPtr routing_activation_request) -> uds_transport::UdsTransportProtocolMgr::ConnectionResult noexcept
Function to send routing activation request.
Parameters
[in] routing_activation_request The routing activation request
Returns
ConnectionResult The connection result
Definition at line 86 of file doip_tcp_channel_handler.cpp.
{
   return routing_activation_handler_.HandleRoutingActivationRequest(
       std::move(routing_activation_request));
 }
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::ConnectToHost().
Start()
void doip_client::channel::tcp_channel::DoipTcpChannelHandler::Start ()
Function to start the handler.
Definition at line 71 of file doip_tcp_channel_handler.cpp.
{
   routing_activation_handler_.Start();
   diagnostic_message_handler_.Start();
 }
References diagnostic_message_handler_, routing_activation_handler_, doip_client::channel::tcp_channel::DiagnosticMessageHandler::Start(), and doip_client::channel::tcp_channel::RoutingActivationHandler::Start().
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Start().
Stop()
void doip_client::channel::tcp_channel::DoipTcpChannelHandler::Stop ()
Function to stop the handler.
This will reset all the internal handler back to default state
Definition at line 76 of file doip_tcp_channel_handler.cpp.
{
   routing_activation_handler_.Stop();
   diagnostic_message_handler_.Stop();
 }
References diagnostic_message_handler_, routing_activation_handler_, doip_client::channel::tcp_channel::DiagnosticMessageHandler::Stop(), and doip_client::channel::tcp_channel::RoutingActivationHandler::Stop().
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Stop().
Member Data Documentation
channel_handler_lock
std::mutex doip_client::channel::tcp_channel::DoipTcpChannelHandler::channel_handler_lock private
Mutex to protect critical section.
Definition at line 137 of file doip_tcp_channel_handler.h.
diagnostic_message_handler_
DiagnosticMessageHandler doip_client::channel::tcp_channel::DoipTcpChannelHandler::diagnostic_message_handler_ private
Handler to process diagnostic message req/ resp.
Definition at line 132 of file doip_tcp_channel_handler.h.
Referenced by Reset(), Start(), and Stop().
routing_activation_handler_
RoutingActivationHandler doip_client::channel::tcp_channel::DoipTcpChannelHandler::routing_activation_handler_ private
Handler to process routing activation req/ resp.
Definition at line 127 of file doip_tcp_channel_handler.h.
Referenced by IsRoutingActivated(), Reset(), Start(), and Stop().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_tcp_channel_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_tcp_channel_handler.cpp