Diag-Client-Lib: diag::client::conversation::DiagClientConversation::DiagClientConversationImpl Class Reference
diag::client::conversation::DiagClientConversation::DiagClientConversationImpl Class Reference final
Public Member Functions
DiagClientConversationImpl (std::string_view conversation_name) noexcept
Constructor an instance of DiagClientConversationImpl.
~DiagClientConversationImpl () noexcept=default
Destructor an instance of DiagClientConversationImpl.
void Startup () noexcept
Function to startup the Diagnostic Client Conversation.
void Shutdown () noexcept
Function to shutdown the Diagnostic Client Conversation.
ConnectResult ConnectToDiagServer (std::uint16_t target_address, IpAddress host_ip_addr) noexcept
Function to connect to Diagnostic Server.
DisconnectResult DisconnectFromDiagServer () noexcept
Function to disconnect from Diagnostic Server.
Result< uds_message::UdsResponseMessagePtr, DiagClientConversation::DiagError > SendDiagnosticRequest (uds_message::UdsRequestMessageConstPtr message) noexcept
Function to send Diagnostic Request and get Diagnostic Response.
Private Attributes
Conversation & internal_conversation_
Reference to valid conversation created.
Detailed Description
Definition at line 19 of file diagnostic_client_conversation.cpp.
Constructor & Destructor Documentation
DiagClientConversationImpl()
diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::DiagClientConversationImpl (std::string_view conversation_name) inline explicit noexcept
Constructor an instance of DiagClientConversationImpl.
Parameters
[in] conversation_name The name of conversation configured as json parameter under "ConversationName"
Definition at line 26 of file diagnostic_client_conversation.cpp.
       : internal_conversation_{
             dcm::GetConversationManager().GetDiagnosticClientConversation(conversation_name)} {}
References diag::client::dcm::GetConversationManager().
~DiagClientConversationImpl()
diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::~DiagClientConversationImpl () default noexcept
Destructor an instance of DiagClientConversationImpl.
Member Function Documentation
ConnectToDiagServer()
ConnectResult diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::ConnectToDiagServer (std::uint16_t target_address, IpAddress host_ip_addr) inline noexcept
Function to connect to Diagnostic Server.
Parameters
[in] target_address Logical address of the Remote server
[in] host_ip_addr IP address of the Remote server
Returns
ConnectResult Connection result returned
Definition at line 57 of file diagnostic_client_conversation.cpp.
{
     return internal_conversation_.ConnectToDiagServer(target_address, host_ip_addr);
   }
References diag::client::conversation::Conversation::ConnectToDiagServer(), and internal_conversation_.
DisconnectFromDiagServer()
DisconnectResult diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::DisconnectFromDiagServer () inline noexcept
Function to disconnect from Diagnostic Server.
Returns
DisconnectResult Disconnection result returned
Definition at line 66 of file diagnostic_client_conversation.cpp.
{
     return internal_conversation_.DisconnectFromDiagServer();
   }
References diag::client::conversation::Conversation::DisconnectFromDiagServer(), and internal_conversation_.
SendDiagnosticRequest()
Result<uds_message::UdsResponseMessagePtr, DiagClientConversation::DiagError> diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::SendDiagnosticRequest (uds_message::UdsRequestMessageConstPtr message) inline noexcept
Function to send Diagnostic Request and get Diagnostic Response.
Parameters
[in] message The diagnostic request message wrapped in a unique pointer
Returns
DiagResult The result returned
uds_message::UdsResponseMessagePtr Diagnostic Response message received, null_ptr in case of error
Definition at line 80 of file diagnostic_client_conversation.cpp.
{
     return internal_conversation_.SendDiagnosticRequest(std::move(message));
   }
References internal_conversation_, and diag::client::conversation::Conversation::SendDiagnosticRequest().
Shutdown()
void diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::Shutdown () inline noexcept
Function to shutdown the Diagnostic Client Conversation.
Must be called during shutdown phase, no further processing of any function will be allowed after this call
Definition at line 46 of file diagnostic_client_conversation.cpp.
 { internal_conversation_.Shutdown(); }
References internal_conversation_, and diag::client::conversation::Conversation::Shutdown().
Startup()
void diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::Startup () inline noexcept
Function to startup the Diagnostic Client Conversation.
Must be called once and before using any other functions of DiagClientConversation
Definition at line 39 of file diagnostic_client_conversation.cpp.
 { internal_conversation_.Startup(); }
References internal_conversation_, and diag::client::conversation::Conversation::Startup().
Member Data Documentation
internal_conversation_
Conversation& diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::internal_conversation_ private
Reference to valid conversation created.
Definition at line 88 of file diagnostic_client_conversation.cpp.
Referenced by ConnectToDiagServer(), DisconnectFromDiagServer(), SendDiagnosticRequest(), Shutdown(), and Startup().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/diagnostic_client_conversation.cpp