Diag-Client-Lib: utility::state::StateContext< EnumState > Class Template Reference
utility::state::StateContext< EnumState > Class Template Reference
#include <state.h>
Public Member Functions
StateContext ()
~StateContext ()=default
void AddState (EnumState state, std::unique_ptr< State< EnumState >> state_ptr)
auto GetActiveState () noexcept -> State< EnumState > &
void TransitionTo (EnumState state)
auto GetContext () noexcept -> StateContext *
Private Member Functions
void Start ()
void Stop ()
void Update (EnumState state)
Private Attributes
std::mutex state_lock
State< EnumState > * current_state_
std::map< EnumState, std::unique_ptr< State< EnumState > > > state_map_
Detailed Description
template<typename EnumState>
class utility::state::StateContext< EnumState >
Definition at line 49 of file state.h.
Constructor & Destructor Documentation
StateContext()
template<typename EnumState > utility::state::StateContext< EnumState >::StateContext () inline
Definition at line 52 of file state.h.
 : current_state_{nullptr}, state_map_{} {}
~StateContext()
template<typename EnumState > utility::state::StateContext< EnumState >::~StateContext () default
Member Function Documentation
AddState()
template<typename EnumState > void utility::state::StateContext< EnumState >::AddState (EnumState state, std::unique_ptr< State< EnumState >> state_ptr) inline
Definition at line 58 of file state.h.
{
     state_map_.insert(
         std::pair<EnumState, std::unique_ptr<State<EnumState>>>(state, std::move(state_ptr)));
   }
References utility::state::StateContext< EnumState >::state_map_.
Referenced by doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::DiagnosticMessageHandlerImpl(), doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::RoutingActivationHandlerImpl(), doip_client::channel::udp_channel::VehicleDiscoveryHandler::VehicleDiscoveryHandlerImpl::VehicleDiscoveryHandlerImpl(), and doip_client::channel::udp_channel::VehicleIdentificationHandler::VehicleIdentificationHandlerImpl::VehicleIdentificationHandlerImpl().
GetActiveState()
template<typename EnumState > auto utility::state::StateContext< EnumState >::GetActiveState () -> State<EnumState> & inline noexcept
Definition at line 64 of file state.h.
{
     std::lock_guard<std::mutex> const lck{state_lock};
     return *current_state_;
   }
References utility::state::StateContext< EnumState >::current_state_, and utility::state::StateContext< EnumState >::state_lock.
GetContext()
template<typename EnumState > auto utility::state::StateContext< EnumState >::GetContext () -> StateContext * inline noexcept
Definition at line 80 of file state.h.
 { return this; }
Start()
template<typename EnumState > void utility::state::StateContext< EnumState >::Start () inline private
Definition at line 84 of file state.h.
                {
     if (this->current_state_ != nullptr) { this->current_state_->Start(); }
   }
References utility::state::StateContext< EnumState >::current_state_.
Referenced by utility::state::StateContext< EnumState >::TransitionTo().
Stop()
template<typename EnumState > void utility::state::StateContext< EnumState >::Stop () inline private
Definition at line 89 of file state.h.
               {
     if (this->current_state_ != nullptr) { this->current_state_->Stop(); }
   }
References utility::state::StateContext< EnumState >::current_state_.
Referenced by utility::state::StateContext< EnumState >::TransitionTo().
TransitionTo()
template<typename EnumState > void utility::state::StateContext< EnumState >::TransitionTo (EnumState state) inline
Definition at line 70 of file state.h.
{
     // stop the current state
     Stop();
     // Update to new state
     Update(state);
     // Start new state
     Start();
   }
References utility::state::StateContext< EnumState >::Start(), utility::state::StateContext< EnumState >::Stop(), and utility::state::StateContext< EnumState >::Update().
Referenced by doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::DiagnosticMessageHandlerImpl(), doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::RoutingActivationHandlerImpl(), doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::Stop(), doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::Stop(), doip_client::channel::udp_channel::VehicleDiscoveryHandler::VehicleDiscoveryHandlerImpl::VehicleDiscoveryHandlerImpl(), and doip_client::channel::udp_channel::VehicleIdentificationHandler::VehicleIdentificationHandlerImpl::VehicleIdentificationHandlerImpl().
Update()
template<typename EnumState > void utility::state::StateContext< EnumState >::Update (EnumState state) inline private
Definition at line 94 of file state.h.
{
     std::lock_guard<std::mutex> const lck{state_lock};
     auto it = state_map_.find(state);
     if (it != state_map_.end()) {
       this->current_state_ = it->second.get();
     } else {
       // failure condition
     }
   }
References utility::state::StateContext< EnumState >::current_state_, utility::state::StateContext< EnumState >::state_lock, and utility::state::StateContext< EnumState >::state_map_.
Referenced by utility::state::StateContext< EnumState >::TransitionTo().
Member Data Documentation
current_state_
template<typename EnumState > State<EnumState>* utility::state::StateContext< EnumState >::current_state_ private
Definition at line 108 of file state.h.
Referenced by utility::state::StateContext< EnumState >::GetActiveState(), utility::state::StateContext< EnumState >::Start(), utility::state::StateContext< EnumState >::Stop(), and utility::state::StateContext< EnumState >::Update().
state_lock
template<typename EnumState > std::mutex utility::state::StateContext< EnumState >::state_lock private
Definition at line 105 of file state.h.
Referenced by utility::state::StateContext< EnumState >::GetActiveState(), and utility::state::StateContext< EnumState >::Update().
state_map_
template<typename EnumState > std::map<EnumState, std::unique_ptr<State<EnumState> > > utility::state::StateContext< EnumState >::state_map_ private
Definition at line 110 of file state.h.
Referenced by utility::state::StateContext< EnumState >::AddState(), and utility::state::StateContext< EnumState >::Update().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/utility-support/utility/state.h