Diag-Client-Lib: diag::client::dcm::DCMClient Class Reference
diag::client::dcm::DCMClient Class Reference final
Class to create Diagnostic Manager Client functionality.
#include <dcm_client.h>
Public Member Functions
DCMClient (config_parser::DcmClientConfig dcm_client_config)
Constructs an instance of DCMClient.
DCMClient (const DCMClient &other) noexcept=delete
Deleted copy assignment and copy constructor.
DCMClient & operator= (const DCMClient &other) noexcept=delete
DCMClient (DCMClient &&other) noexcept=delete
Deleted move assignment and move constructor.
DCMClient & operator= (DCMClient &&other) noexcept=delete
~DCMClient () noexcept override
Destructs an instance of DCMClient.
void Initialize () noexcept override
Function to initialize the DCMClient.
void Run () noexcept override
Function to run DCMClient.
void Shutdown () noexcept override
Function to shutdown the DCMClient.
conversation::DiagClientConversation GetDiagnosticClientConversation (std::string_view conversation_name) noexcept override
Function to get required diag client conversation object based on conversation name.
core_type::Result< diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > SendVehicleIdentificationRequest (diag::client::vehicle_info::VehicleInfoListRequestType vehicle_info_request) noexcept override
Function to send vehicle identification request and get the Diagnostic Server list.
Public Member Functions inherited from diag::client::common::DiagnosticManager
DiagnosticManager () noexcept
Constructs an instance of DiagnosticManager.
DiagnosticManager (const DiagnosticManager &other) noexcept=delete
Deleted copy assignment and copy constructor.
DiagnosticManager & operator= (const DiagnosticManager &other) noexcept=delete
DiagnosticManager (DiagnosticManager &&other) noexcept=delete
Deleted move assignment and move constructor.
DiagnosticManager & operator= (DiagnosticManager &&other) noexcept=delete
virtual ~DiagnosticManager () noexcept
Destructs an instance of DiagnosticManager.
virtual void Main () noexcept
Function to manage the whole lifecycle of DiagnosticManager.
virtual Result< void > SignalShutdown () noexcept
Function to initiate shutdown of DiagnosticManager.
Private Attributes
std::unique_ptr< uds_transport::UdsTransportProtocolManager > uds_transport_protocol_mgr_
Stores the uds transport protocol manager.
conversation_manager::ConversationManager conversation_mgr_
Stores the conversation manager instance.
conversation::Conversation & vehicle_discovery_conversation_
Store the conversation for vehicle discovery.
Detailed Description
Class to create Diagnostic Manager Client functionality.
Definition at line 26 of file dcm_client.h.
Constructor & Destructor Documentation
DCMClient() [1/3]
diag::client::dcm::DCMClient::DCMClient (config_parser::DcmClientConfig dcm_client_config) explicit
Constructs an instance of DCMClient.
Parameters
[in] dcm_client_config The configuration of dcm client
Definition at line 32 of file dcm_client.cpp.
     : DiagnosticManager{},
       uds_transport_protocol_mgr_{std::make_unique<uds_transport::UdsTransportProtocolManager>()},
       conversation_mgr_{std::move(dcm_client_config), *uds_transport_protocol_mgr_},
       vehicle_discovery_conversation_{
           conversation_mgr_.GetDiagnosticClientConversation(VehicleDiscoveryConversation)} {
   // make the conversation manager reference available externally
   conversation_manager_ref.emplace(conversation_mgr_);
 }
References diag::client::dcm::anonymous_namespace{dcm_client.cpp}::conversation_manager_ref, and conversation_mgr_.
DCMClient() [2/3]
diag::client::dcm::DCMClient::DCMClient (const DCMClient & other) delete noexcept
Deleted copy assignment and copy constructor.
DCMClient() [3/3]
diag::client::dcm::DCMClient::DCMClient (DCMClient && other) delete noexcept
Deleted move assignment and move constructor.
~DCMClient()
diag::client::dcm::DCMClient::~DCMClient () override default noexcept
Destructs an instance of DCMClient.
Member Function Documentation
GetDiagnosticClientConversation()
conversation::DiagClientConversation diag::client::dcm::DCMClient::GetDiagnosticClientConversation (std::string_view conversation_name) override virtual noexcept
Function to get required diag client conversation object based on conversation name.
Parameters
[in] conversation_name Name of conversation configured as json parameter "ConversationName"
Returns
Diag client conversation object as per passed conversation name
Implements diag::client::common::DiagnosticManager.
Definition at line 78 of file dcm_client.cpp.
{
   return conversation::DiagClientConversation{conversation_name};
 }
Initialize()
void diag::client::dcm::DCMClient::Initialize () override virtual noexcept
Function to initialize the DCMClient.
Implements diag::client::common::DiagnosticManager.
Definition at line 44 of file dcm_client.cpp.
{
   // start Conversation Manager
   conversation_mgr_.Startup();
   // start all the udsTransportProtocol Layer
   uds_transport_protocol_mgr_->Startup();
   // start Vehicle Discovery
   vehicle_discovery_conversation_.Startup();
   logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
       FILE_NAME, __LINE__, __func__,
       [](std::stringstream &msg) { msg << "Dcm Client Initialized"; });
 }
References FILE_NAME, and diag::client::logger::DiagClientLogger::GetDiagClientLogger().
operator=() [1/2]
DCMClient& diag::client::dcm::DCMClient::operator= (const DCMClient & other) delete noexcept
operator=() [2/2]
DCMClient& diag::client::dcm::DCMClient::operator= (DCMClient && other) delete noexcept
Run()
void diag::client::dcm::DCMClient::Run () override virtual noexcept
Function to run DCMClient.
Implements diag::client::common::DiagnosticManager.
Definition at line 57 of file dcm_client.cpp.
{
   // run udsTransportProtocol layer
   uds_transport_protocol_mgr_->Run();
   logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
       FILE_NAME, __LINE__, __func__,
       [](std::stringstream &msg) { msg << "Dcm Client is ready to serve"; });
 }
References FILE_NAME, diag::client::logger::DiagClientLogger::GetDiagClientLogger(), and uds_transport_protocol_mgr_.
SendVehicleIdentificationRequest()
core_type::Result< diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > diag::client::dcm::DCMClient::SendVehicleIdentificationRequest (diag::client::vehicle_info::VehicleInfoListRequestType vehicle_info_request) override virtual noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
Parameters
[in] vehicle_info_request Vehicle information sent along with request
Returns
Result containing available vehicle information response on success, VehicleResponseErrorCode on error
Implements diag::client::common::DiagnosticManager.
Definition at line 85 of file dcm_client.cpp.
{
   return vehicle_discovery_conversation_.SendVehicleIdentificationRequest(vehicle_info_request);
 }
Shutdown()
void diag::client::dcm::DCMClient::Shutdown () override virtual noexcept
Function to shutdown the DCMClient.
Implements diag::client::common::DiagnosticManager.
Definition at line 65 of file dcm_client.cpp.
{
   // shutdown Vehicle Discovery
   vehicle_discovery_conversation_.Shutdown();
   // shutdown udsTransportProtocol layer
   uds_transport_protocol_mgr_->Shutdown();
   // shutdown Conversation Manager
   conversation_mgr_.Shutdown();
   logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
       FILE_NAME, __LINE__, __func__,
       [](std::stringstream &msg) { msg << "Dcm Client Shutdown completed"; });
 }
References conversation_mgr_, FILE_NAME, diag::client::logger::DiagClientLogger::GetDiagClientLogger(), diag::client::conversation_manager::ConversationManager::Shutdown(), diag::client::conversation::Conversation::Shutdown(), uds_transport_protocol_mgr_, and vehicle_discovery_conversation_.
Member Data Documentation
conversation_mgr_
conversation_manager::ConversationManager diag::client::dcm::DCMClient::conversation_mgr_ private
Stores the conversation manager instance.
Definition at line 96 of file dcm_client.h.
Referenced by DCMClient(), and Shutdown().
uds_transport_protocol_mgr_
std::unique_ptr<uds_transport::UdsTransportProtocolManager> diag::client::dcm::DCMClient::uds_transport_protocol_mgr_ private
Stores the uds transport protocol manager.
Definition at line 91 of file dcm_client.h.
Referenced by Run(), and Shutdown().
vehicle_discovery_conversation_
conversation::Conversation& diag::client::dcm::DCMClient::vehicle_discovery_conversation_ private
Store the conversation for vehicle discovery.
Definition at line 101 of file dcm_client.h.
Referenced by Shutdown().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/dcm/dcm_client.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/dcm/dcm_client.cpp