Diag-Client-Lib: doip_client::channel::tcp_channel::DiagnosticMessageHandler Class Reference
doip_client::channel::tcp_channel::DiagnosticMessageHandler Class Reference final
Class used as a handler to process routing activation messages.
#include <doip_diagnostic_message_handler.h>
Classes
class DiagnosticMessageHandlerImpl
Class implements routing activation handler.
Public Types
using TcpMessagePtr = sockets::TcpSocketHandler::TcpMessagePtr
Type alias for Tcp message pointer.
using TcpMessage = sockets::TcpSocketHandler::TcpMessage
Type alias for Tcp message.
Public Member Functions
DiagnosticMessageHandler (sockets::TcpSocketHandler &tcp_socket_handler, DoipTcpChannel &channel)
Constructs an instance of DiagnosticMessageHandler.
~DiagnosticMessageHandler ()
Destruct an instance of DiagnosticMessageHandler.
void Start ()
Function to start the handler.
void Stop ()
Function to stop the handler.
void Reset ()
Function to reset the handler.
void ProcessDoIPDiagnosticAckMessageResponse (DoipMessage &doip_payload) noexcept
Function to process received diagnostic acknowledgement from server.
void ProcessDoIPDiagnosticMessageResponse (DoipMessage &doip_payload) noexcept
Function to process received diagnostic positive/negative response from server.
auto HandleDiagnosticRequest (uds_transport::UdsMessageConstPtr diagnostic_request) noexcept -> uds_transport::UdsTransportProtocolMgr::TransmissionResult
Function to handle sending of diagnostic request.
Private Member Functions
auto SendDiagnosticRequest (uds_transport::UdsMessageConstPtr diagnostic_request) noexcept -> uds_transport::UdsTransportProtocolMgr::TransmissionResult
Function to send diagnostic request.
Static Private Member Functions
static void CreateDoipGenericHeader (std::vector< std::uint8_t > &doip_header, std::uint16_t payload_type, std::uint32_t payload_len)
Function to create doip generic header.
Private Attributes
std::unique_ptr< DiagnosticMessageHandlerImpl > handler_impl_
Stores the Handler implementation.
Detailed Description
Class used as a handler to process routing activation messages.
Definition at line 29 of file doip_diagnostic_message_handler.h.
Member Typedef Documentation
TcpMessage
using doip_client::channel::tcp_channel::DiagnosticMessageHandler::TcpMessage = sockets::TcpSocketHandler::TcpMessage
Type alias for Tcp message.
Definition at line 39 of file doip_diagnostic_message_handler.h.
TcpMessagePtr
using doip_client::channel::tcp_channel::DiagnosticMessageHandler::TcpMessagePtr = sockets::TcpSocketHandler::TcpMessagePtr
Type alias for Tcp message pointer.
Definition at line 34 of file doip_diagnostic_message_handler.h.
Constructor & Destructor Documentation
DiagnosticMessageHandler()
doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandler (sockets::TcpSocketHandler & tcp_socket_handler, DoipTcpChannel & channel)
Constructs an instance of DiagnosticMessageHandler.
Parameters
[in] tcp_socket_handler The reference to socket handler
[in] channel The reference to doip channel
Definition at line 377 of file doip_diagnostic_message_handler.cpp.
     : handler_impl_{std::make_unique<DiagnosticMessageHandlerImpl>(tcp_socket_handler, channel)} {}
~DiagnosticMessageHandler()
doip_client::channel::tcp_channel::DiagnosticMessageHandler::~DiagnosticMessageHandler () default
Destruct an instance of DiagnosticMessageHandler.
Member Function Documentation
CreateDoipGenericHeader()
void doip_client::channel::tcp_channel::DiagnosticMessageHandler::CreateDoipGenericHeader (std::vector< std::uint8_t > & doip_header, std::uint16_t payload_type, std::uint32_t payload_len) static private
Function to create doip generic header.
Parameters
[in,out] doip_header The doip header
[in] payload_type The type of payload
[in] payload_len The length of payload
Definition at line 540 of file doip_diagnostic_message_handler.cpp.
{
   doip_header_buffer.emplace_back(kDoip_ProtocolVersion);
   doip_header_buffer.emplace_back(~(static_cast<std::uint8_t>(kDoip_ProtocolVersion)));
   doip_header_buffer.emplace_back(static_cast<std::uint8_t>((payload_type & 0xFF00) >> 8));
   doip_header_buffer.emplace_back(static_cast<std::uint8_t>(payload_type & 0x00FF));
   doip_header_buffer.emplace_back(static_cast<std::uint8_t>((payload_len & 0xFF000000) >> 24));
   doip_header_buffer.emplace_back(static_cast<std::uint8_t>((payload_len & 0x00FF0000) >> 16));
   doip_header_buffer.emplace_back(static_cast<std::uint8_t>((payload_len & 0x0000FF00) >> 8));
   doip_header_buffer.emplace_back(static_cast<std::uint8_t>(payload_len & 0x000000FF));
 }
References doip_client::kDoip_ProtocolVersion.
HandleDiagnosticRequest()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::HandleDiagnosticRequest (uds_transport::UdsMessageConstPtr diagnostic_request) -> uds_transport::UdsTransportProtocolMgr::TransmissionResult noexcept
Function to handle sending of diagnostic request.
Parameters
[in] diagnostic_request The diagnostic request
Returns
The Transmission result
Definition at line 455 of file doip_diagnostic_message_handler.cpp.
{
   uds_transport::UdsTransportProtocolMgr::TransmissionResult result{
       uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed};
   if (handler_impl_->GetStateContext().GetActiveState().GetState() == DiagnosticMessageState::kIdle) {
     if (SendDiagnosticRequest(std::move(diagnostic_request)) ==
         uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk) {
       handler_impl_->GetStateContext().TransitionTo(DiagnosticMessageState::kWaitForDiagnosticAck);
       handler_impl_->GetSyncTimer().WaitForTimeout(
           [this, &result]() {
             result = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kNoTransmitAckReceived;
             handler_impl_->GetStateContext().TransitionTo(DiagnosticMessageState::kIdle);
             logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
                 __FILE__, __LINE__, "", [](std::stringstream &msg) {
                   msg << "Diagnostic Message Ack Request timed out, no response received in: "
                       << kDoIPDiagnosticAckTimeout << "seconds";
                 });
           },
           [this, &result]() {
             if (handler_impl_->GetStateContext().GetActiveState().GetState() ==
                 DiagnosticMessageState::kDiagnosticPositiveAckRecvd) {
               handler_impl_->GetStateContext().TransitionTo(DiagnosticMessageState::kWaitForDiagnosticResponse);
               // success
               result = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk;
               logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
                   __FILE__, __LINE__, "",
                   [](std::stringstream &msg) { msg << "Diagnostic Message Positive Ack received"; });
             } else {
               // failed with neg acknowledgement from server
               result = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kNegTransmitAckReceived;
               handler_impl_->GetStateContext().TransitionTo(DiagnosticMessageState::kIdle);
               logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
                   __FILE__, __LINE__, "",
                   [](std::stringstream &msg) { msg << "Diagnostic Message Transmission Failed Neg Ack Received"; });
             }
           },
           std::chrono::milliseconds{kDoIPDiagnosticAckTimeout});
     } else {
       // Failed, do nothing
       handler_impl_->GetStateContext().TransitionTo(DiagnosticMessageState::kIdle);
       logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
           __FILE__, __LINE__, "",
           [](std::stringstream &msg) { msg << "Diagnostic Request Message Transmission Failed"; });
     }
   } else {
     // channel not in idle state
     result = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kBusyProcessing;
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogVerbose(
         __FILE__, __LINE__, "",
         [](std::stringstream &msg) { msg << "Diagnostic Message Transmission already in progress"; });
   }
   return result;
 }
References doip_client::logger::DoipClientLogger::GetDiagClientLogger(), uds_transport::UdsTransportProtocolMgr::kBusyProcessing, doip_client::channel::tcp_channel::anonymous_namespace{doip_diagnostic_message_handler.cpp}::kDoIPDiagnosticAckTimeout, uds_transport::UdsTransportProtocolMgr::kNegTransmitAckReceived, uds_transport::UdsTransportProtocolMgr::kNoTransmitAckReceived, uds_transport::UdsTransportProtocolMgr::kTransmitFailed, and uds_transport::UdsTransportProtocolMgr::kTransmitOk.
ProcessDoIPDiagnosticAckMessageResponse()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::ProcessDoIPDiagnosticAckMessageResponse (DoipMessage & doip_payload) noexcept
Function to process received diagnostic acknowledgement from server.
Parameters
[in] doip_payload The doip message received
Definition at line 389 of file doip_diagnostic_message_handler.cpp.
{
   DiagnosticMessageState final_state{DiagnosticMessageState::kDiagnosticNegativeAckRecvd};
   if (handler_impl_->GetStateContext().GetActiveState().GetState() == DiagnosticMessageState::kWaitForDiagnosticAck) {
     // get the ack code
     DiagAckType const diag_ack_type{doip_payload.GetPayload()[0u]};
     if (doip_payload.GetPayloadType() == kDoip_DiagMessagePosAck_Type) {
       if (diag_ack_type.ack_type_ == kDoip_DiagnosticMessage_PosAckCode_Confirm) {
         final_state = DiagnosticMessageState::kDiagnosticPositiveAckRecvd;
         logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
             __FILE__, __LINE__, __func__, [&doip_payload](std::stringstream &msg) {
               msg << "Diagnostic message positively acknowledged from remote server "
                   << " (0x" << std::hex << doip_payload.GetServerAddress() << ")";
             });
       } else {
         // do nothing
       }
     } else if (doip_payload.GetPayloadType() == kDoip_DiagMessageNegAck_Type) {
       logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogWarn(
           __FILE__, __LINE__, __func__,
           [&diag_ack_type](std::stringstream &msg) { msg << "Diagnostic request denied due to " << diag_ack_type; });
     } else {
       // do nothing
     }
     handler_impl_->GetStateContext().TransitionTo(final_state);
     handler_impl_->GetSyncTimer().CancelWait();
   } else {
     /* ignore */
   }
 }
References doip_client::logger::DoipClientLogger::GetDiagClientLogger(), doip_client::channel::tcp_channel::anonymous_namespace{doip_diagnostic_message_handler.cpp}::kDoip_DiagMessageNegAck_Type, doip_client::channel::tcp_channel::anonymous_namespace{doip_diagnostic_message_handler.cpp}::kDoip_DiagMessagePosAck_Type, and doip_client::channel::tcp_channel::anonymous_namespace{doip_diagnostic_message_handler.cpp}::kDoip_DiagnosticMessage_PosAckCode_Confirm.
ProcessDoIPDiagnosticMessageResponse()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::ProcessDoIPDiagnosticMessageResponse (DoipMessage & doip_payload) noexcept
Function to process received diagnostic positive/negative response from server.
Parameters
[in] doip_payload The doip message received
Definition at line 419 of file doip_diagnostic_message_handler.cpp.
{
   if (handler_impl_->GetStateContext().GetActiveState().GetState() ==
       DiagnosticMessageState::kWaitForDiagnosticResponse) {
     // Indicate upper layer about incoming data
     std::pair<uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr> ret_val{
         handler_impl_->GetDoipChannel().IndicateMessage(
             doip_payload.GetServerAddress(), doip_payload.GetClientAddress(),
             uds_transport::UdsMessage::TargetAddressType::kPhysical, 0U, doip_payload.GetPayload().size(), 0u,
             "DoIPTcp", doip_payload.GetPayload())};
     if (ret_val.first == uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationPending) {
       // keep channel alive since pending request received, do not change channel state
     } else {
       // Check result and udsMessagePtr
       if ((ret_val.first == uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationOk) &&
           (ret_val.second != nullptr)) {
         // copy to application buffer
         (void) std::copy(doip_payload.GetPayload().begin(), doip_payload.GetPayload().end(),
                          ret_val.second->GetPayload().begin());
         handler_impl_->GetDoipChannel().HandleMessage(std::move(ret_val.second));
       } else {
         logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogVerbose(
             __FILE__, __LINE__, __func__,
             [](std::stringstream &msg) { msg << "Diagnostic message response ignored due to unknown error"; });
       }
       handler_impl_->GetStateContext().TransitionTo(DiagnosticMessageState::kIdle);
     }
   } else {
     // ignore
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogVerbose(
         __FILE__, __LINE__, __func__, [this](std::stringstream &msg) {
           msg << "Diagnostic message response ignored due to channel in state: "
               << static_cast<int>(handler_impl_->GetStateContext().GetActiveState().GetState());
         });
   }
 }
References doip_client::logger::DoipClientLogger::GetDiagClientLogger(), uds_transport::UdsTransportProtocolMgr::kIndicationOk, uds_transport::UdsTransportProtocolMgr::kIndicationPending, and uds_transport::UdsMessage::kPhysical.
Reset()
void doip_client::channel::tcp_channel::DiagnosticMessageHandler::Reset ()
Function to reset the handler.
This will reset all the internal handler back to default state
Definition at line 387 of file doip_diagnostic_message_handler.cpp.
 { handler_impl_->Reset(); }
References handler_impl_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannelHandler::Reset().
SendDiagnosticRequest()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::SendDiagnosticRequest (uds_transport::UdsMessageConstPtr diagnostic_request) -> uds_transport::UdsTransportProtocolMgr::TransmissionResult private noexcept
Function to send diagnostic request.
Parameters
[in] diagnostic_request The routing activation request
Returns
The Transmission result
Definition at line 509 of file doip_diagnostic_message_handler.cpp.
{
   uds_transport::UdsTransportProtocolMgr::TransmissionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed};
   constexpr std::uint8_t kDoipheadrSize{8u};
   constexpr std::uint8_t kSourceAddressSize{4u};
   TcpMessagePtr doip_diag_req = std::make_unique<TcpMessage>();
   // reserve bytes in vector
   doip_diag_req->GetTxBuffer().reserve(kDoipheadrSize + kDoip_DiagMessage_ReqResMinLen +
                                        diagnostic_request->GetPayload().size());
   // create header
   CreateDoipGenericHeader(
       doip_diag_req->GetTxBuffer(), kDoip_DiagMessage_Type,
       kDoip_DiagMessage_ReqResMinLen + static_cast<std::uint32_t>(diagnostic_request->GetPayload().size()));
   // Add source address
   doip_diag_req->GetTxBuffer().emplace_back(static_cast<std::uint8_t>((diagnostic_request->GetSa() & 0xFF00) >> 8u));
   doip_diag_req->GetTxBuffer().emplace_back(static_cast<std::uint8_t>(diagnostic_request->GetSa() & 0x00FF));
   // Add target address
   doip_diag_req->GetTxBuffer().emplace_back(static_cast<std::uint8_t>((diagnostic_request->GetSa() & 0xFF00) >> 8u));
   doip_diag_req->GetTxBuffer().emplace_back(static_cast<std::uint8_t>(diagnostic_request->GetSa() & 0x00FF));
   // Copy data bytes
   doip_diag_req->GetTxBuffer().insert(doip_diag_req->GetTxBuffer().begin() + kDoipheadrSize + kSourceAddressSize,
                                       diagnostic_request->GetPayload().begin(), diagnostic_request->GetPayload().end());
   // Initiate transmission
   if (handler_impl_->GetSocketHandler().Transmit(std::move(doip_diag_req))) {
     ret_val = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk;
   }
   return ret_val;
 }
References doip_client::channel::udp_channel::anonymous_namespace{doip_vehicle_identification_handler.cpp}::CreateDoipGenericHeader(), doip_client::channel::tcp_channel::anonymous_namespace{doip_diagnostic_message_handler.cpp}::kDoip_DiagMessage_ReqResMinLen, doip_client::channel::tcp_channel::anonymous_namespace{doip_diagnostic_message_handler.cpp}::kDoip_DiagMessage_Type, doip_client::kDoipheadrSize, uds_transport::UdsTransportProtocolMgr::kTransmitFailed, and uds_transport::UdsTransportProtocolMgr::kTransmitOk.
Start()
void doip_client::channel::tcp_channel::DiagnosticMessageHandler::Start ()
Function to start the handler.
Definition at line 383 of file doip_diagnostic_message_handler.cpp.
 { handler_impl_->Start(); }
References handler_impl_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannelHandler::Start().
Stop()
void doip_client::channel::tcp_channel::DiagnosticMessageHandler::Stop ()
Function to stop the handler.
This will reset all the internal handler back to default state
Definition at line 385 of file doip_diagnostic_message_handler.cpp.
 { handler_impl_->Stop(); }
References handler_impl_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannelHandler::Stop().
Member Data Documentation
handler_impl_
std::unique_ptr<DiagnosticMessageHandlerImpl> doip_client::channel::tcp_channel::DiagnosticMessageHandler::handler_impl_ private
Stores the Handler implementation.
Definition at line 127 of file doip_diagnostic_message_handler.h.
Referenced by Reset(), Start(), and Stop().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_diagnostic_message_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_diagnostic_message_handler.cpp