Diag-Client-Lib: doip_client::channel::udp_channel::DoipUdpChannelHandler Class Reference
doip_client::channel::udp_channel::DoipUdpChannelHandler Class Reference final
Class to handle udp received messages from lower layer.
#include <doip_udp_channel_handler.h>
Public Types
using UdpMessagePtr = sockets::UdpSocketHandler::UdpMessagePtr
Type alias for Tcp message pointer.
Public Member Functions
DoipUdpChannelHandler (sockets::UdpSocketHandler &udp_socket_handler_broadcast, sockets::UdpSocketHandler &udp_socket_handler_unicast, DoipUdpChannel &channel)
Constructs an instance of DoipUdpChannelHandler.
auto SendVehicleIdentificationRequest (uds_transport::UdsMessageConstPtr vehicle_identification_request) noexcept -> uds_transport::UdsTransportProtocolMgr::TransmissionResult
Function to vehicle identification request to the connected network.
void HandleMessageUnicast (UdpMessagePtr udp_rx_message) noexcept
Function to process the received unicast udp message.
void HandleMessageBroadcast (UdpMessagePtr udp_rx_message) noexcept
Function to process the received broadcast udp message.
Private Member Functions
auto ProcessDoIPHeader (DoipMessage &doip_rx_message, std::uint8_t &nack_code) noexcept -> bool
Function to process doip header in received response.
void ProcessDoIPPayload (DoipMessage &doip_payload, DoipMessage::RxSocketType socket_type=DoipMessage::RxSocketType::kUnicast)
Function to process the doip payload.
Static Private Member Functions
static auto ProcessDoIPPayloadLength (std::uint32_t payload_len, std::uint16_t payload_type) noexcept -> bool
Function to verify payload length of various payload type.
Private Attributes
VehicleDiscoveryHandler vehicle_discovery_handler_
Handler to process vehicle discovery messages.
VehicleIdentificationHandler vehicle_identification_handler_
Handler to process vehicle identification req/res messages.
std::mutex channel_handler_lock
Mutex to protect critical section.
Detailed Description
Class to handle udp received messages from lower layer.
Definition at line 28 of file doip_udp_channel_handler.h.
Member Typedef Documentation
UdpMessagePtr
using doip_client::channel::udp_channel::DoipUdpChannelHandler::UdpMessagePtr = sockets::UdpSocketHandler::UdpMessagePtr
Type alias for Tcp message pointer.
Definition at line 33 of file doip_udp_channel_handler.h.
Constructor & Destructor Documentation
DoipUdpChannelHandler()
doip_client::channel::udp_channel::DoipUdpChannelHandler::DoipUdpChannelHandler (sockets::UdpSocketHandler & udp_socket_handler_broadcast, sockets::UdpSocketHandler & udp_socket_handler_unicast, DoipUdpChannel & channel)
Constructs an instance of DoipUdpChannelHandler.
Parameters
[in] udp_socket_handler_broadcast The reference to socket handler with broadcast mechanism
[in] udp_socket_handler_unicast The reference to socket handler with unicast mechanism
[in] channel The reference to tcp transport handler
Definition at line 30 of file doip_udp_channel_handler.cpp.
     : vehicle_discovery_handler_{udp_socket_handler_broadcast, channel},
       vehicle_identification_handler_{udp_socket_handler_unicast, channel} {}
Member Function Documentation
HandleMessageBroadcast()
auto doip_client::channel::udp_channel::DoipUdpChannelHandler::HandleMessageBroadcast (UdpMessagePtr udp_rx_message) noexcept
Function to process the received broadcast udp message.
Parameters
[in] udp_rx_message The message received
Definition at line 71 of file doip_udp_channel_handler.cpp.
{
   uint8_t nack_code;
   DoipMessage doip_rx_message{DoipMessage::MessageType::kUdp, udp_rx_message->GetHostIpAddress(),
                               udp_rx_message->GetHostPortNumber(),
                               core_type::Span<std::uint8_t>{udp_rx_message->GetRxBuffer()}};
   // Process the Doip Generic header check
   if (ProcessDoIPHeader(doip_rx_message, nack_code)) {
     vehicle_discovery_handler_.ProcessVehicleAnnouncementResponse(doip_rx_message);
   } else {
     // send NACK or ignore
     (void) nack_code;
   }
 }
References doip_client::DoipMessage::kUdp.
Referenced by doip_client::channel::udp_channel::DoipUdpChannel::ProcessReceivedUdpBroadcast().
HandleMessageUnicast()
auto doip_client::channel::udp_channel::DoipUdpChannelHandler::HandleMessageUnicast (UdpMessagePtr udp_rx_message) noexcept
Function to process the received unicast udp message.
Parameters
[in] udp_rx_message The message received
Definition at line 57 of file doip_udp_channel_handler.cpp.
{
   std::uint8_t nack_code{};
   DoipMessage doip_rx_message{DoipMessage::MessageType::kUdp, udp_rx_message->GetHostIpAddress(),
                               udp_rx_message->GetHostPortNumber(),
                               core_type::Span<std::uint8_t>{udp_rx_message->GetRxBuffer()}};
   // Process the Doip Generic header check
   if (ProcessDoIPHeader(doip_rx_message, nack_code)) {
     ProcessDoIPPayload(doip_rx_message);
   } else {
     // send NACK or ignore
     (void) nack_code;
   }
 }
References doip_client::DoipMessage::kUdp.
Referenced by doip_client::channel::udp_channel::DoipUdpChannel::ProcessReceivedUdpUnicast().
ProcessDoIPHeader()
auto doip_client::channel::udp_channel::DoipUdpChannelHandler::ProcessDoIPHeader (DoipMessage & doip_rx_message, std::uint8_t & nack_code) -> bool private noexcept
Function to process doip header in received response.
Parameters
[in] doip_rx_message The received doip rx message
[in] nack_code The negative ack code
Definition at line 85 of file doip_udp_channel_handler.cpp.
{
   bool ret_val{false};
   /* Check the header synchronisation pattern */
   if (((doip_rx_message.GetProtocolVersion() == kDoip_ProtocolVersion) &&
        (doip_rx_message.GetInverseProtocolVersion() == static_cast<std::uint8_t>(~kDoip_ProtocolVersion))) ||
       ((doip_rx_message.GetProtocolVersion() == kDoip_ProtocolVersion_Def) &&
        (doip_rx_message.GetInverseProtocolVersion() == static_cast<std::uint8_t>(~kDoip_ProtocolVersion_Def)))) {
     /* Check the supported payload type */
     if (doip_rx_message.GetPayloadType() == kDoip_VehicleAnnouncement_ResType) {
       /* Req-[AUTOSAR_SWS_DiagnosticOverIP][SWS_DoIP_00017] */
       if (doip_rx_message.GetPayloadLength() <= kDoip_Protocol_MaxPayload) {
         /* Req-[AUTOSAR_SWS_DiagnosticOverIP][SWS_DoIP_00018] */
         if (doip_rx_message.GetPayloadLength() <= kUdpChannelLength) {
           /* Req-[AUTOSAR_SWS_DiagnosticOverIP][SWS_DoIP_00019] */
           if (ProcessDoIPPayloadLength(doip_rx_message.GetPayloadLength(), doip_rx_message.GetPayloadType())) {
             ret_val = true;
           } else {
             // Send NACK code 0x04, close the socket
             nack_code = kDoip_GenericHeader_InvalidPayloadLen;
             // socket closure ??
           }
         } else {
           // Send NACK code 0x03, discard message
           nack_code = kDoip_GenericHeader_OutOfMemory;
         }
       } else {
         // Send NACK code 0x02, discard message
         nack_code = kDoip_GenericHeader_MessageTooLarge;
       }
     } else {  // Send NACK code 0x01, discard message
       nack_code = kDoip_GenericHeader_UnknownPayload;
     }
   } else {  // Send NACK code 0x00, close the socket
     nack_code = kDoip_GenericHeader_IncorrectPattern;
     // socket closure
   }
   return ret_val;
 }
References doip_client::channel::udp_channel::kDoip_GenericHeader_IncorrectPattern, doip_client::channel::udp_channel::kDoip_GenericHeader_InvalidPayloadLen, doip_client::channel::udp_channel::kDoip_GenericHeader_MessageTooLarge, doip_client::channel::udp_channel::kDoip_GenericHeader_OutOfMemory, doip_client::channel::udp_channel::kDoip_GenericHeader_UnknownPayload, doip_client::kDoip_Protocol_MaxPayload, doip_client::kDoip_ProtocolVersion, doip_client::kDoip_ProtocolVersion_Def, doip_client::kDoip_VehicleAnnouncement_ResType, and doip_client::kUdpChannelLength.
ProcessDoIPPayload()
void doip_client::channel::udp_channel::DoipUdpChannelHandler::ProcessDoIPPayload (DoipMessage & doip_payload, DoipMessage::RxSocketType socket_type = DoipMessage::RxSocketType::kUnicast) private
Function to process the doip payload.
Parameters
[in] doip_payload The reference to received payload
Definition at line 139 of file doip_udp_channel_handler.cpp.
{
   std::lock_guard<std::mutex> const lck(channel_handler_lock);
   switch (doip_payload.GetPayloadType()) {
     case kDoip_VehicleAnnouncement_ResType: {
       vehicle_identification_handler_.ProcessVehicleIdentificationResponse(doip_payload);
       break;
     }
     default:
       /* do nothing */
       break;
   }
 }
References channel_handler_lock, doip_client::DoipMessage::GetPayloadType(), doip_client::kDoip_VehicleAnnouncement_ResType, doip_client::channel::udp_channel::VehicleIdentificationHandler::ProcessVehicleIdentificationResponse(), and vehicle_identification_handler_.
ProcessDoIPPayloadLength()
auto doip_client::channel::udp_channel::DoipUdpChannelHandler::ProcessDoIPPayloadLength (std::uint32_t payload_len, std::uint16_t payload_type) -> bool static private noexcept
Function to verify payload length of various payload type.
Parameters
[in] payload_len The length of payload received
[in] payload_type The type of payload
Definition at line 124 of file doip_udp_channel_handler.cpp.
             {
   bool ret_val{false};
   switch (payload_type) {
     case kDoip_VehicleAnnouncement_ResType: {
       if (payload_len <= kDoip_VehicleAnnouncement_ResMaxLen) ret_val = true;
       break;
     }
     default:
       // do nothing
       break;
   }
   return ret_val;
 }
References doip_client::kDoip_VehicleAnnouncement_ResMaxLen, and doip_client::kDoip_VehicleAnnouncement_ResType.
SendVehicleIdentificationRequest()
auto doip_client::channel::udp_channel::DoipUdpChannelHandler::SendVehicleIdentificationRequest (uds_transport::UdsMessageConstPtr vehicle_identification_request) -> uds_transport::UdsTransportProtocolMgr::TransmissionResult noexcept
Function to vehicle identification request to the connected network.
Parameters
[in] vehicle_identification_request The vehicle identification request
Returns
TransmissionResult The transmission result
Definition at line 36 of file doip_udp_channel_handler.cpp.
{
   uds_transport::UdsTransportProtocolMgr::TransmissionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed};
   // Get the udp handler type from payload
   std::uint8_t const handler_type{vehicle_identification_request->GetPayload()[BYTE_POS_ZERO]};
   // deserialize and send to proper handler
   switch (handler_type) {
     case 0U:
       // 0U -> Vehicle Identification Req
       ret_val =
           vehicle_identification_handler_.HandleVehicleIdentificationRequest(std::move(vehicle_identification_request));
       break;
     case 1U:
       // 1U -> Power Mode Req
       break;
   }
   return ret_val;
 }
References BYTE_POS_ZERO, and uds_transport::UdsTransportProtocolMgr::kTransmitFailed.
Referenced by doip_client::channel::udp_channel::DoipUdpChannel::Transmit().
Member Data Documentation
channel_handler_lock
std::mutex doip_client::channel::udp_channel::DoipUdpChannelHandler::channel_handler_lock private
Mutex to protect critical section.
Definition at line 111 of file doip_udp_channel_handler.h.
Referenced by ProcessDoIPPayload().
vehicle_discovery_handler_
VehicleDiscoveryHandler doip_client::channel::udp_channel::DoipUdpChannelHandler::vehicle_discovery_handler_ private
Handler to process vehicle discovery messages.
Definition at line 101 of file doip_udp_channel_handler.h.
vehicle_identification_handler_
VehicleIdentificationHandler doip_client::channel::udp_channel::DoipUdpChannelHandler::vehicle_identification_handler_ private
Handler to process vehicle identification req/res messages.
Definition at line 106 of file doip_udp_channel_handler.h.
Referenced by ProcessDoIPPayload().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/udp_channel/doip_udp_channel_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/udp_channel/doip_udp_channel_handler.cpp