Diag-Client-Lib: doip_client::channel::udp_channel::DoipUdpChannel Class Reference
doip_client::channel::udp_channel::DoipUdpChannel Class Reference final
Class to manage a udp channel as per DoIP protocol.
#include <doip_udp_channel.h>
Public Types
using UdpMessagePtr = sockets::UdpSocketHandler::UdpMessagePtr
Type alias for Udp message pointer.
Public Member Functions
DoipUdpChannel (std::string_view udp_ip_address, std::uint16_t port_num, uds_transport::Connection &connection)
Constructs an instance of UdpChannel.
~DoipUdpChannel ()=default
Destruct an instance of UdpChannel.
void Start ()
Function to start the channel.
void Stop ()
Function to stop the channel.
std::pair< uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr > IndicateMessage (uds_transport::UdsMessage::Address source_addr, uds_transport::UdsMessage::Address target_addr, uds_transport::UdsMessage::TargetAddressType type, uds_transport::ChannelID channel_id, std::size_t size, uds_transport::Priority priority, uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t > payload_info)
Function to indicate a start of reception of message.
void HandleMessage (uds_transport::UdsMessagePtr message)
Function to Hands over a valid received Uds message to upper layer.
void ProcessReceivedUdpBroadcast (UdpMessagePtr udp_rx_message)
Function to process the received Udp broadcast message from socket layer.
void ProcessReceivedUdpUnicast (UdpMessagePtr udp_rx_message)
Function to process the received Udp unicast message from socket layer.
uds_transport::UdsTransportProtocolMgr::TransmissionResult Transmit (uds_transport::UdsMessageConstPtr message)
Function to transmit a Vehicle Identification request.
Private Types
using UdpSocketHandler = sockets::UdpSocketHandler
Type alias for Udp socket handler.
Private Attributes
UdpSocketHandler udp_socket_handler_broadcast_
Store the udp socket handler for broadcast messages.
UdpSocketHandler udp_socket_handler_unicast_
Store the udp socket handler for unicast messages.
DoipUdpChannelHandler udp_channel_handler_
Store the doip channel handler.
uds_transport::Connection & connection_
Store the reference to doip connection.
Detailed Description
Class to manage a udp channel as per DoIP protocol.
Definition at line 26 of file doip_udp_channel.h.
Member Typedef Documentation
UdpMessagePtr
using doip_client::channel::udp_channel::DoipUdpChannel::UdpMessagePtr = sockets::UdpSocketHandler::UdpMessagePtr
Type alias for Udp message pointer.
Definition at line 31 of file doip_udp_channel.h.
UdpSocketHandler
using doip_client::channel::udp_channel::DoipUdpChannel::UdpSocketHandler = sockets::UdpSocketHandler private
Type alias for Udp socket handler.
Definition at line 125 of file doip_udp_channel.h.
Constructor & Destructor Documentation
DoipUdpChannel()
doip_client::channel::udp_channel::DoipUdpChannel::DoipUdpChannel (std::string_view udp_ip_address, std::uint16_t port_num, uds_transport::Connection & connection)
Constructs an instance of UdpChannel.
Parameters
[in] udp_ip_address The local ip address
[in] port_num The reference to tcp transport handler
[in] connection The reference to tcp transport handler
Definition at line 15 of file doip_udp_channel.cpp.
     : udp_socket_handler_broadcast_{udp_ip_address, port_num, UdpSocketHandler::PortType::kUdp_Broadcast, *this},
       udp_socket_handler_unicast_{udp_ip_address, port_num, UdpSocketHandler::PortType::kUdp_Unicast, *this},
       udp_channel_handler_{udp_socket_handler_broadcast_, udp_socket_handler_unicast_, *this},
       connection_{connection} {}
~DoipUdpChannel()
doip_client::channel::udp_channel::DoipUdpChannel::~DoipUdpChannel () default
Destruct an instance of UdpChannel.
Member Function Documentation
HandleMessage()
void doip_client::channel::udp_channel::DoipUdpChannel::HandleMessage (uds_transport::UdsMessagePtr message)
Function to Hands over a valid received Uds message to upper layer.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Definition at line 55 of file doip_udp_channel.cpp.
{
   connection_.HandleMessage(std::move(message));
 }
References connection_, and uds_transport::Connection::HandleMessage().
IndicateMessage()
std::pair< uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr > doip_client::channel::udp_channel::DoipUdpChannel::IndicateMessage (uds_transport::UdsMessage::Address source_addr, uds_transport::UdsMessage::Address target_addr, uds_transport::UdsMessage::TargetAddressType type, uds_transport::ChannelID channel_id, std::size_t size, uds_transport::Priority priority, uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t > payload_info)
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The view onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Definition at line 46 of file doip_udp_channel.cpp.
{
   return connection_.IndicateMessage(source_addr, target_addr, type, channel_id, size, priority, protocol_kind,
                                      payload_info);
 }
References connection_, and uds_transport::Connection::IndicateMessage().
ProcessReceivedUdpBroadcast()
void doip_client::channel::udp_channel::DoipUdpChannel::ProcessReceivedUdpBroadcast (DoipUdpChannel::UdpMessagePtr udp_rx_message)
Function to process the received Udp broadcast message from socket layer.
Parameters
[in] udp_rx_message The Udp message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the channel here
Definition at line 32 of file doip_udp_channel.cpp.
{
   udp_channel_handler_.HandleMessageBroadcast(std::move(udp_rx_message));
 }
References doip_client::channel::udp_channel::DoipUdpChannelHandler::HandleMessageBroadcast(), and udp_channel_handler_.
Referenced by doip_client::sockets::UdpSocketHandler::UdpSocketHandler().
ProcessReceivedUdpUnicast()
void doip_client::channel::udp_channel::DoipUdpChannel::ProcessReceivedUdpUnicast (DoipUdpChannel::UdpMessagePtr udp_rx_message)
Function to process the received Udp unicast message from socket layer.
Parameters
[in] udp_rx_message The Udp message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the channel here
Definition at line 36 of file doip_udp_channel.cpp.
{
   udp_channel_handler_.HandleMessageUnicast(std::move(udp_rx_message));
 }
References doip_client::channel::udp_channel::DoipUdpChannelHandler::HandleMessageUnicast(), and udp_channel_handler_.
Referenced by doip_client::sockets::UdpSocketHandler::UdpSocketHandler().
Start()
void doip_client::channel::udp_channel::DoipUdpChannel::Start ()
Function to start the channel.
Definition at line 22 of file doip_udp_channel.cpp.
{
   udp_socket_handler_broadcast_.Start();
   udp_socket_handler_unicast_.Start();
 }
References doip_client::sockets::UdpSocketHandler::Start(), udp_socket_handler_broadcast_, and udp_socket_handler_unicast_.
Referenced by doip_client::connection::DoipUdpConnection::Start().
Stop()
void doip_client::channel::udp_channel::DoipUdpChannel::Stop ()
Function to stop the channel.
Definition at line 27 of file doip_udp_channel.cpp.
{
   udp_socket_handler_broadcast_.Stop();
   udp_socket_handler_unicast_.Stop();
 }
References doip_client::sockets::UdpSocketHandler::Stop(), udp_socket_handler_broadcast_, and udp_socket_handler_unicast_.
Referenced by doip_client::connection::DoipUdpConnection::Stop().
Transmit()
uds_transport::UdsTransportProtocolMgr::TransmissionResult doip_client::channel::udp_channel::DoipUdpChannel::Transmit (uds_transport::UdsMessageConstPtr message)
Function to transmit a Vehicle Identification request.
Parameters
[in] message The vehicle identification message
Definition at line 40 of file doip_udp_channel.cpp.
{
   return udp_channel_handler_.SendVehicleIdentificationRequest(std::move(message));
 }
References doip_client::channel::udp_channel::DoipUdpChannelHandler::SendVehicleIdentificationRequest(), and udp_channel_handler_.
Referenced by doip_client::connection::DoipUdpConnection::Transmit().
Member Data Documentation
connection_
uds_transport::Connection& doip_client::channel::udp_channel::DoipUdpChannel::connection_ private
Store the reference to doip connection.
Definition at line 145 of file doip_udp_channel.h.
Referenced by HandleMessage(), and IndicateMessage().
udp_channel_handler_
DoipUdpChannelHandler doip_client::channel::udp_channel::DoipUdpChannel::udp_channel_handler_ private
Store the doip channel handler.
Definition at line 140 of file doip_udp_channel.h.
Referenced by ProcessReceivedUdpBroadcast(), ProcessReceivedUdpUnicast(), and Transmit().
udp_socket_handler_broadcast_
UdpSocketHandler doip_client::channel::udp_channel::DoipUdpChannel::udp_socket_handler_broadcast_ private
Store the udp socket handler for broadcast messages.
Definition at line 130 of file doip_udp_channel.h.
Referenced by Start(), and Stop().
udp_socket_handler_unicast_
UdpSocketHandler doip_client::channel::udp_channel::DoipUdpChannel::udp_socket_handler_unicast_ private
Store the udp socket handler for unicast messages.
Definition at line 135 of file doip_udp_channel.h.
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/udp_channel/doip_udp_channel.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/udp_channel/doip_udp_channel.cpp