Diag-Client-Lib: doip_client::transport_protocol_handler::DoipTransportProtocolHandler Class Reference
doip_client::transport_protocol_handler::DoipTransportProtocolHandler Class Reference final
Protocol handler class to manage the whole Doip protocol communication.
#include <doip_transport_protocol_handler.h>
Public Types
using UdsTransportProtocolHandlerId = uds_transport::UdsTransportProtocolHandler::UdsTransportProtocolHandlerId
Type alias for handler id.
using InitializationResult = uds_transport::UdsTransportProtocolHandler::InitializationResult
Type alias for Initialization result.
Public Types inherited from uds_transport::UdsTransportProtocolHandler
enum class InitializationResult : std::uint8_t { kInitializeOk = 0 , kInitializeFailed = 1 }
Definitions of different initialization result.
using UdsTransportProtocolHandlerId = std::uint8_t
Type alias for handler id.
Public Member Functions
DoipTransportProtocolHandler (UdsTransportProtocolHandlerId handler_id, uds_transport::UdsTransportProtocolMgr const &transport_protocol_mgr)
Constructs an instance of DoipTransportProtocolHandler.
~DoipTransportProtocolHandler () final
Destruct an instance of DoipTransportProtocolHandler.
InitializationResult Initialize () override
Function to initialize the handler.
void Start () override
Function to start the protocol handler.
void Stop () override
Function to stop the protocol handler.
std::unique_ptr< uds_transport::Connection > CreateTcpConnection (uds_transport::ConversionHandler &conversation, std::string_view tcp_ip_address, std::uint16_t port_num) override
Function to create a new Tcp connection.
std::unique_ptr< uds_transport::Connection > CreateUdpConnection (uds_transport::ConversionHandler &conversion_handler, std::string_view udp_ip_address, std::uint16_t port_num) override
Function to create a new Udp connection.
Public Member Functions inherited from uds_transport::UdsTransportProtocolHandler
UdsTransportProtocolHandler (UdsTransportProtocolHandlerId const handler_id, UdsTransportProtocolMgr const &)
Constructs an instance of UdsTransportProtocolHandler.
virtual ~UdsTransportProtocolHandler ()=default
Destruct an instance of UdsTransportProtocolHandler.
virtual UdsTransportProtocolHandlerId GetHandlerID () const
Function to get the handler id.
virtual std::unique_ptr< Connection > CreateTcpConnection (ConversionHandler &conversion_handler, std::string_view tcpIpaddress, uint16_t portNum)=0
Function to create a new Tcp connection.
virtual std::unique_ptr< Connection > CreateUdpConnection (ConversionHandler &conversion_handler, std::string_view udpIpaddress, uint16_t portNum)=0
Function to create a new Udp connection.
Private Attributes
connection::DoipConnectionManager doip_connection_mgr_
Store Doip Connection manager.
Additional Inherited Members
Protected Attributes inherited from uds_transport::UdsTransportProtocolHandler
UdsTransportProtocolHandlerId handler_id_
Store the handler id.
Detailed Description
Protocol handler class to manage the whole Doip protocol communication.
This class must be instantiated by user for using the DoIP functionalities. This will inherit uds transport protocol handler
Definition at line 25 of file doip_transport_protocol_handler.h.
Member Typedef Documentation
InitializationResult
using doip_client::transport_protocol_handler::DoipTransportProtocolHandler::InitializationResult = uds_transport::UdsTransportProtocolHandler::InitializationResult
Type alias for Initialization result.
Definition at line 35 of file doip_transport_protocol_handler.h.
UdsTransportProtocolHandlerId
using doip_client::transport_protocol_handler::DoipTransportProtocolHandler::UdsTransportProtocolHandlerId = uds_transport::UdsTransportProtocolHandler::UdsTransportProtocolHandlerId
Type alias for handler id.
Definition at line 30 of file doip_transport_protocol_handler.h.
Constructor & Destructor Documentation
DoipTransportProtocolHandler()
doip_client::transport_protocol_handler::DoipTransportProtocolHandler::DoipTransportProtocolHandler (UdsTransportProtocolHandlerId handler_id, uds_transport::UdsTransportProtocolMgr const & transport_protocol_mgr)
Constructs an instance of DoipTransportProtocolHandler.
Parameters
[in] handler_id The id of this transport protocol handler
[in] transport_protocol_mgr The reference to transport protocol manager
Definition at line 16 of file doip_transport_protocol_handler.cpp.
     : uds_transport::UdsTransportProtocolHandler(handler_id, transport_protocol_mgr),
       doip_connection_mgr_{} {}
~DoipTransportProtocolHandler()
doip_client::transport_protocol_handler::DoipTransportProtocolHandler::~DoipTransportProtocolHandler () final default
Destruct an instance of DoipTransportProtocolHandler.
Member Function Documentation
CreateTcpConnection()
std::unique_ptr< uds_transport::Connection > doip_client::transport_protocol_handler::DoipTransportProtocolHandler::CreateTcpConnection (uds_transport::ConversionHandler & conversation, std::string_view tcp_ip_address, std::uint16_t port_num) override
Function to create a new Tcp connection.
Parameters
[in] conversation The conversation handler used by tcp connection to communicate
[in] tcp_ip_address The local tcp ip address
[in] port_num The local port number
Returns
The unique pointer to Connection created
Definition at line 32 of file doip_transport_protocol_handler.cpp.
{
   logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
       __FILE__, __LINE__, __func__, [tcp_ip_address](std::stringstream &msg) {
         msg << "Doip Tcp protocol requested with local endpoint : "
             << "<Tcp: " << tcp_ip_address << ">";
       });
   return doip_connection_mgr_.FindOrCreateTcpConnection(conversation, tcp_ip_address, port_num);
 }
References doip_connection_mgr_, doip_client::connection::DoipConnectionManager::FindOrCreateTcpConnection(), and doip_client::logger::DoipClientLogger::GetDiagClientLogger().
CreateUdpConnection()
std::unique_ptr< uds_transport::Connection > doip_client::transport_protocol_handler::DoipTransportProtocolHandler::CreateUdpConnection (uds_transport::ConversionHandler & conversion_handler, std::string_view udp_ip_address, std::uint16_t port_num) override
Function to create a new Udp connection.
Parameters
[in] conversation The conversation handler used by tcp connection to communicate
[in] udp_ip_address The local udp ip address
[in] port_num The local port number
Returns
The unique pointer to Connection created
Definition at line 42 of file doip_transport_protocol_handler.cpp.
{
   logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
       __FILE__, __LINE__, __func__, [udp_ip_address](std::stringstream &msg) {
         msg << "Doip Udp protocol requested with local endpoint : "
             << "<Udp: " << udp_ip_address << ">";
       });
   return doip_connection_mgr_.FindOrCreateUdpConnection(conversation, udp_ip_address, port_num);
 }
References doip_connection_mgr_, doip_client::connection::DoipConnectionManager::FindOrCreateUdpConnection(), and doip_client::logger::DoipClientLogger::GetDiagClientLogger().
Initialize()
DoipTransportProtocolHandler::InitializationResult doip_client::transport_protocol_handler::DoipTransportProtocolHandler::Initialize () override virtual
Function to initialize the handler.
Returns
The initialization result
Implements uds_transport::UdsTransportProtocolHandler.
Definition at line 24 of file doip_transport_protocol_handler.cpp.
{
   return (InitializationResult::kInitializeOk);
 }
References uds_transport::UdsTransportProtocolHandler::kInitializeOk.
Start()
void doip_client::transport_protocol_handler::DoipTransportProtocolHandler::Start () override virtual
Function to start the protocol handler.
Implements uds_transport::UdsTransportProtocolHandler.
Definition at line 28 of file doip_transport_protocol_handler.cpp.
 {}
Stop()
void doip_client::transport_protocol_handler::DoipTransportProtocolHandler::Stop () override virtual
Function to stop the protocol handler.
Implements uds_transport::UdsTransportProtocolHandler.
Definition at line 30 of file doip_transport_protocol_handler.cpp.
 {}
Member Data Documentation
doip_connection_mgr_
connection::DoipConnectionManager doip_client::transport_protocol_handler::DoipTransportProtocolHandler::doip_connection_mgr_ private
Store Doip Connection manager.
Definition at line 100 of file doip_transport_protocol_handler.h.
Referenced by CreateTcpConnection(), and CreateUdpConnection().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/doip_transport_protocol_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/doip_transport_protocol_handler.cpp