Diag-Client-Lib: diag::client::conversation::Conversation Class Reference
diag::client::conversation::Conversation Class Reference abstract
Interface for diag client conversation.
#include <conversation.h>
Public Types
enum class ActivityStatusType : uint8_t { kActive = 0x00 , kInactive = 0x01 }
Definitions of current activity status.
using IpAddress = DiagClientConversation::IpAddress
Type alias for Ip address.
using ConnectResult = DiagClientConversation::ConnectResult
Type alias for Connection results.
using DisconnectResult = DiagClientConversation::DisconnectResult
Type alias for Disconnection results.
using DiagError = DiagClientConversation::DiagError
Type alias for Diagnostic results.
Public Member Functions
Conversation () noexcept=default
Constructs an instance of Conversation.
Conversation (const Conversation &other) noexcept=delete
Deleted copy assignment and copy constructor.
Conversation & operator= (const Conversation &other) noexcept=delete
Conversation (Conversation &&other) noexcept=delete
Deleted move assignment and move constructor.
Conversation & operator= (Conversation &&other) noexcept=delete
virtual ~Conversation () noexcept=default
Destructs an instance of Conversation.
virtual void Startup () noexcept=0
Function to start the Conversation.
virtual void Shutdown () noexcept=0
Function to shutdown the Conversation.
virtual void RegisterConnection (std::unique_ptr<::uds_transport::Connection > connection) noexcept=0
Function to register the conversation to underlying transport protocol handler.
virtual ::uds_transport::ConversionHandler & GetConversationHandler () noexcept=0
Function to get the conversation handler from conversation object.
virtual ConnectResult ConnectToDiagServer (std::uint16_t, IpAddress) noexcept
Function to connect to Diagnostic Server.
virtual DisconnectResult DisconnectFromDiagServer () noexcept
Function to disconnect from Diagnostic Server.
virtual std::pair<::uds_transport::UdsTransportProtocolMgr::IndicationResult, ::uds_transport::UdsMessagePtr > IndicateMessage (::uds_transport::UdsMessage::Address source_addr, ::uds_transport::UdsMessage::Address target_addr, ::uds_transport::UdsMessage::TargetAddressType type, ::uds_transport::ChannelID channel_id, std::size_t size, ::uds_transport::Priority priority, ::uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) noexcept=0
Function to indicate a start of reception of message.
virtual void HandleMessage (::uds_transport::UdsMessagePtr message) noexcept=0
Function to Hands over a valid received Uds message.
virtual Result< uds_message::UdsResponseMessagePtr, DiagError > SendDiagnosticRequest (uds_message::UdsRequestMessageConstPtr) noexcept
Function to send Diagnostic Request and get Diagnostic Response.
virtual core_type::Result< diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > SendVehicleIdentificationRequest (vehicle_info::VehicleInfoListRequestType) noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
auto GetActivityStatus () const noexcept -> ActivityStatusType
Get the current activity status of this conversation.
Protected Attributes
ActivityStatusType activity_status_ {ActivityStatusType::kInactive}
Store the conversation activity status.
Detailed Description
Interface for diag client conversation.
Definition at line 24 of file conversation.h.
Member Typedef Documentation
ConnectResult
using diag::client::conversation::Conversation::ConnectResult = DiagClientConversation::ConnectResult
Type alias for Connection results.
Definition at line 34 of file conversation.h.
DiagError
using diag::client::conversation::Conversation::DiagError = DiagClientConversation::DiagError
Type alias for Diagnostic results.
Definition at line 44 of file conversation.h.
DisconnectResult
using diag::client::conversation::Conversation::DisconnectResult = DiagClientConversation::DisconnectResult
Type alias for Disconnection results.
Definition at line 39 of file conversation.h.
IpAddress
using diag::client::conversation::Conversation::IpAddress = DiagClientConversation::IpAddress
Type alias for Ip address.
Definition at line 29 of file conversation.h.
Member Enumeration Documentation
ActivityStatusType
enum diag::client::conversation::Conversation::ActivityStatusType : uint8_t strong
Definitions of current activity status.
Enumerator
kActive
kInactive
Definition at line 49 of file conversation.h.
 : uint8_t { kActive = 0x00, kInactive = 0x01 };
Constructor & Destructor Documentation
Conversation() [1/3]
diag::client::conversation::Conversation::Conversation () default noexcept
Constructs an instance of Conversation.
Conversation() [2/3]
diag::client::conversation::Conversation::Conversation (const Conversation & other) delete noexcept
Deleted copy assignment and copy constructor.
Conversation() [3/3]
diag::client::conversation::Conversation::Conversation (Conversation && other) delete noexcept
Deleted move assignment and move constructor.
~Conversation()
virtual diag::client::conversation::Conversation::~Conversation () virtual default noexcept
Destructs an instance of Conversation.
Member Function Documentation
ConnectToDiagServer()
virtual ConnectResult diag::client::conversation::Conversation::ConnectToDiagServer (std::uint16_t , IpAddress) inline virtual noexcept
Function to connect to Diagnostic Server.
Parameters
[in] target_address Logical address of the Remote server
[in] host_ip_addr IP address of the Remote server
Returns
ConnectResult Connection result returned
Reimplemented in diag::client::conversation::DmConversation.
Definition at line 108 of file conversation.h.
{
     return ConnectResult::kConnectFailed;
   }
References diag::client::conversation::DiagClientConversation::kConnectFailed.
Referenced by diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::ConnectToDiagServer().
DisconnectFromDiagServer()
virtual DisconnectResult diag::client::conversation::Conversation::DisconnectFromDiagServer () inline virtual noexcept
Function to disconnect from Diagnostic Server.
Returns
DisconnectResult Disconnection result returned
Reimplemented in diag::client::conversation::DmConversation.
Definition at line 117 of file conversation.h.
{
     return DisconnectResult::kDisconnectFailed;
   }
References diag::client::conversation::DiagClientConversation::kDisconnectFailed.
Referenced by diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::DisconnectFromDiagServer().
GetActivityStatus()
auto diag::client::conversation::Conversation::GetActivityStatus () const -> ActivityStatusType inline noexcept
Get the current activity status of this conversation.
Returns
The activity status
Definition at line 196 of file conversation.h.
 { return activity_status_; }
References activity_status_.
Referenced by diag::client::conversation::DmConversation::Shutdown(), and diag::client::conversation::VdConversation::Shutdown().
GetConversationHandler()
virtual ::uds_transport::ConversionHandler& diag::client::conversation::Conversation::GetConversationHandler () pure virtual noexcept
Function to get the conversation handler from conversation object.
Returns
ConversionHandler & The reference to conversation handler
Implemented in diag::client::conversation::VdConversation, and diag::client::conversation::DmConversation.
HandleMessage()
virtual void diag::client::conversation::Conversation::HandleMessage (::uds_transport::UdsMessagePtr message) pure virtual noexcept
Function to Hands over a valid received Uds message.
Parameters
[in] message The The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Implemented in diag::client::conversation::VdConversation, and diag::client::conversation::DmConversation.
IndicateMessage()
virtual std::pair<::uds_transport::UdsTransportProtocolMgr::IndicationResult, ::uds_transport::UdsMessagePtr> diag::client::conversation::Conversation::IndicateMessage (::uds_transport::UdsMessage::Address source_addr, ::uds_transport::UdsMessage::Address target_addr, ::uds_transport::UdsMessage::TargetAddressType type, ::uds_transport::ChannelID channel_id, std::size_t size, ::uds_transport::Priority priority, ::uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) pure virtual noexcept
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The View onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Implemented in diag::client::conversation::VdConversation, and diag::client::conversation::DmConversation.
operator=() [1/2]
Conversation& diag::client::conversation::Conversation::operator= (const Conversation & other) delete noexcept
operator=() [2/2]
Conversation& diag::client::conversation::Conversation::operator= (Conversation && other) delete noexcept
RegisterConnection()
virtual void diag::client::conversation::Conversation::RegisterConnection (std::unique_ptr<::uds_transport::Connection > connection) pure virtual noexcept
Function to register the conversation to underlying transport protocol handler.
Parameters
[in] connection The conversation connection object
Implemented in diag::client::conversation::VdConversation, and diag::client::conversation::DmConversation.
SendDiagnosticRequest()
virtual Result<uds_message::UdsResponseMessagePtr, DiagError> diag::client::conversation::Conversation::SendDiagnosticRequest (uds_message::UdsRequestMessageConstPtr) inline virtual noexcept
Function to send Diagnostic Request and get Diagnostic Response.
Parameters
[in] message The diagnostic request message wrapped in a unique pointer
Returns
DiagResult The Result returned
uds_message::UdsResponseMessagePtr Diagnostic Response message received, null_ptr in case of error
Reimplemented in diag::client::conversation::DmConversation.
Definition at line 172 of file conversation.h.
{
     return Result<uds_message::UdsResponseMessagePtr, DiagError>::FromError(
         DiagError::kDiagRequestSendFailed);
   }
References core_type::Result< T, E >::FromError(), and diag::client::conversation::DiagClientConversation::kDiagRequestSendFailed.
Referenced by diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::SendDiagnosticRequest().
SendVehicleIdentificationRequest()
virtual core_type::Result<diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError> diag::client::conversation::Conversation::SendVehicleIdentificationRequest (vehicle_info::VehicleInfoListRequestType) inline virtual noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
Parameters
[in] vehicle_info_request Vehicle information sent along with request
Returns
Result containing available vehicle information response on success, VehicleResponseErrorCode on error
Reimplemented in diag::client::conversation::VdConversation.
Definition at line 186 of file conversation.h.
{
     return core_type::Result<diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr,
                              DiagClient::VehicleInfoResponseError>::
         FromError(DiagClient::VehicleInfoResponseError::kTransmitFailed);
   }
References diag::client::DiagClient::kTransmitFailed.
Shutdown()
virtual void diag::client::conversation::Conversation::Shutdown () pure virtual noexcept
Function to shutdown the Conversation.
Implemented in diag::client::conversation::VdConversation, and diag::client::conversation::DmConversation.
Referenced by diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::Shutdown(), and diag::client::dcm::DCMClient::Shutdown().
Startup()
virtual void diag::client::conversation::Conversation::Startup () pure virtual noexcept
Function to start the Conversation.
Implemented in diag::client::conversation::VdConversation, and diag::client::conversation::DmConversation.
Referenced by diag::client::conversation::DiagClientConversation::DiagClientConversationImpl::Startup().
Member Data Documentation
activity_status_
ActivityStatusType diag::client::conversation::Conversation::activity_status_ {ActivityStatusType::kInactive} protected
Store the conversation activity status.
Definition at line 202 of file conversation.h.
Referenced by GetActivityStatus(), diag::client::conversation::DmConversation::Shutdown(), diag::client::conversation::VdConversation::Shutdown(), diag::client::conversation::DmConversation::Startup(), and diag::client::conversation::VdConversation::Startup().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/dcm/conversation/conversation.h