Diag-Client-Lib: boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl Class Reference
boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl Class Reference final
Class to provide implementation of tls client.
Public Member Functions
TlsClientImpl (std::string_view client_name, std::string_view local_ip_address, std::uint16_t local_port_num, std::string_view ca_certification_path, TlsVersion tls_version) noexcept
Constructs an instance of TcpClient.
TlsClientImpl (const TlsClientImpl &other) noexcept=delete
Deleted copy assignment and copy constructor.
TlsClientImpl & operator= (const TlsClientImpl &other) noexcept=delete
TlsClientImpl (TlsClientImpl &&other) noexcept=delete
Deleted move assignment and move constructor.
TlsClientImpl & operator= (TlsClientImpl &&other) noexcept=delete
~TlsClientImpl () noexcept=default
Destruct an instance of TcpClientImpl.
void Initialize () noexcept
Initialize the client.
void DeInitialize () noexcept
De-initialize the client.
void SetReadHandler (HandlerRead read_handler) noexcept
Function to set the read handler that is invoked when message is received.
core_type::Result< void > ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num)
Function to connect to remote ip address and port number.
core_type::Result< void > DisconnectFromHost ()
Function to disconnect from remote host if already connected.
auto IsConnectedToHost () const noexcept -> bool
Function to get the connection status.
core_type::Result< void > Transmit (MessageConstPtr tcp_message)
Function to transmit the provided tcp message.
Private Types
using TlsSocket = socket::tls::TlsSocket
Type alias for secured socket.
using TcpConnectionSecured = connection::tcp::TcpConnection< connection::tcp::ConnectionType::kClient, TlsSocket >
Type alias for secured tcp connection.
using IoContext = boost_support::socket::IoContext
Type alias for boost context.
using TlsContext = boost_support::socket::tls::TlsContext
Type alias for tls context.
Private Attributes
IoContext io_context_
Stores the io context.
TlsContext tls_context_
Stores the tls context.
std::atomic< State > connection_state_
Store the state of tcp connection.
std::string client_name_
The client name.
TcpConnectionSecured tcp_connection_
Store the tcp connection.
Detailed Description
template<typename TlsVersion>
class boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl
Class to provide implementation of tls client.
Definition at line 40 of file tls_client.cpp.
Member Typedef Documentation
IoContext
template<typename TlsVersion > using boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::IoContext = boost_support::socket::IoContext private
Type alias for boost context.
Definition at line 64 of file tls_client.cpp.
TcpConnectionSecured
template<typename TlsVersion > using boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::TcpConnectionSecured = connection::tcp::TcpConnection<connection::tcp::ConnectionType::kClient, TlsSocket> private
Type alias for secured tcp connection.
Definition at line 50 of file tls_client.cpp.
TlsContext
template<typename TlsVersion > using boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::TlsContext = boost_support::socket::tls::TlsContext private
Type alias for tls context.
Definition at line 69 of file tls_client.cpp.
TlsSocket
template<typename TlsVersion > using boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::TlsSocket = socket::tls::TlsSocket private
Type alias for secured socket.
Definition at line 45 of file tls_client.cpp.
Constructor & Destructor Documentation
TlsClientImpl() [1/3]
template<typename TlsVersion > boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::TlsClientImpl (std::string_view client_name, std::string_view local_ip_address, std::uint16_t local_port_num, std::string_view ca_certification_path, TlsVersion tls_version) inline noexcept
Constructs an instance of TcpClient.
Parameters
[in] local_ip_address The local ip address of client
[in] local_port_num The local port number of client
Definition at line 79 of file tls_client.cpp.
       : io_context_{},
         tls_context_{tls_version, ca_certification_path},
         connection_state_{State::kDisconnected},
         client_name_{AppendIpAddressAndPort(client_name, local_ip_address, local_port_num)},
         tcp_connection_{client_name,
                         TlsSocket{local_ip_address, local_port_num, tls_context_, io_context_}} {}
TlsClientImpl() [2/3]
template<typename TlsVersion > boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::TlsClientImpl (const TlsClientImpl & other) delete noexcept
Deleted copy assignment and copy constructor.
TlsClientImpl() [3/3]
template<typename TlsVersion > boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::TlsClientImpl (TlsClientImpl && other) delete noexcept
Deleted move assignment and move constructor.
~TlsClientImpl()
template<typename TlsVersion > boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::~TlsClientImpl () default noexcept
Destruct an instance of TcpClientImpl.
Member Function Documentation
ConnectToHost()
template<typename TlsVersion > core_type::Result<void> boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num) inline
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
Empty void on success, otherwise error is returned
Definition at line 134 of file tls_client.cpp.
{
     core_type::Result<void> result{
         error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kSocketError)};
     if (connection_state_.load(std::memory_order_seq_cst) != State::kConnected) {
       if (tcp_connection_.ConnectToHost(host_ip_address, host_port_num)) {
         connection_state_.store(State::kConnected, std::memory_order_seq_cst);
         result.EmplaceValue();
       }  // else, connect failed
     } else {
       // already connected
       result.EmplaceValue();
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogVerbose(
           FILE_NAME, __LINE__, __func__,
           [](std::stringstream &msg) { msg << "Tcp client is already connected"; });
     }
     return result;
   }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), boost_support::error_domain::kSocketError, and boost_support::error_domain::MakeErrorCode().
DeInitialize()
template<typename TlsVersion > void boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::DeInitialize () inline noexcept
De-initialize the client.
Definition at line 114 of file tls_client.cpp.
 { tcp_connection_.DeInitialize(); }
DisconnectFromHost()
template<typename TlsVersion > core_type::Result<void> boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::DisconnectFromHost () inline
Function to disconnect from remote host if already connected.
Returns
Empty void on success, otherwise error is returned
Definition at line 157 of file tls_client.cpp.
{
     core_type::Result<void> result{
         error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kSocketError)};
     if (connection_state_.load(std::memory_order_seq_cst) == State::kConnected) {
       tcp_connection_.DisconnectFromHost();
       connection_state_.store(State::kDisconnected, std::memory_order_seq_cst);
       result.EmplaceValue();
     } else {
       // Not connected
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [](std::stringstream &msg) { msg << "Tcp client is in disconnected state"; });
     }
     return result;
   }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), boost_support::error_domain::kSocketError, and boost_support::error_domain::MakeErrorCode().
Initialize()
template<typename TlsVersion > void boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::Initialize () inline noexcept
Initialize the client.
Definition at line 109 of file tls_client.cpp.
 { tcp_connection_.Initialize(); }
IsConnectedToHost()
template<typename TlsVersion > auto boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::IsConnectedToHost () const -> bool inline noexcept
Function to get the connection status.
Returns
True if connected, False otherwise
Definition at line 177 of file tls_client.cpp.
{
     return (connection_state_.load(std::memory_order_seq_cst) == State::kConnected);
   }
operator=() [1/2]
template<typename TlsVersion > TlsClientImpl& boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::operator= (const TlsClientImpl & other) delete noexcept
operator=() [2/2]
template<typename TlsVersion > TlsClientImpl& boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::operator= (TlsClientImpl && other) delete noexcept
SetReadHandler()
template<typename TlsVersion > void boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::SetReadHandler (HandlerRead read_handler) inline noexcept
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 122 of file tls_client.cpp.
{
     tcp_connection_.SetReadHandler(std::move(read_handler));
   }
References boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::SetReadHandler().
Referenced by boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::SetReadHandler().
Transmit()
template<typename TlsVersion > core_type::Result<void> boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::Transmit (MessageConstPtr tcp_message) inline
Function to transmit the provided tcp message.
Parameters
[in] tcp_message The tcp message
Returns
Empty void on success, otherwise error is returned
Definition at line 187 of file tls_client.cpp.
{
     core_type::Result<void> result{
         error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kGenericError)};
     if (connection_state_.load(std::memory_order_seq_cst) == State::kConnected) {
       if (tcp_connection_.Transmit(std::move(tcp_message))) { result.EmplaceValue(); }
     } else {
       // not connected
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [](std::stringstream &msg) {
             msg << "Tcp client is Offline, please connect to server first";
           });
     }
     return result;
   }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), boost_support::error_domain::kGenericError, and boost_support::error_domain::MakeErrorCode().
Member Data Documentation
client_name_
template<typename TlsVersion > std::string boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::client_name_ private
The client name.
Definition at line 221 of file tls_client.cpp.
connection_state_
template<typename TlsVersion > std::atomic<State> boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::connection_state_ private
Store the state of tcp connection.
Definition at line 216 of file tls_client.cpp.
io_context_
template<typename TlsVersion > IoContext boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::io_context_ private
Stores the io context.
Definition at line 206 of file tls_client.cpp.
tcp_connection_
template<typename TlsVersion > TcpConnectionSecured boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::tcp_connection_ private
Store the tcp connection.
Definition at line 226 of file tls_client.cpp.
tls_context_
template<typename TlsVersion > TlsContext boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::tls_context_ private
Stores the tls context.
Definition at line 211 of file tls_client.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/client/tls/tls_client.cpp