Diag-Client-Lib: doip_client::connection::DoipTcpConnection Class Reference
doip_client::connection::DoipTcpConnection Class Reference final
Doip Tcp Connection handle connection between two layers.
Public Types
using InitializationResult = uds_transport::Connection::InitializationResult
Type alias for Initialization result.
using TcpClient = sockets::TcpSocketHandler::Client
Type alias for Tcp client used by socket handler.
Public Types inherited from uds_transport::Connection
using ConnectionId = std::uint8_t
Type alias for connection id.
using InitializationResult = uds_transport::UdsTransportProtocolHandler::InitializationResult
Type alias for Initialization result.
Public Member Functions
DoipTcpConnection (uds_transport::ConversionHandler const &conversation_handler, std::string_view tcp_ip_address, std::uint16_t port_num)
Constructor to create a new tcp connection.
~DoipTcpConnection () final=default
Destruct an instance of DoipTcpConnection.
InitializationResult Initialize () override
Function to initialize the connection.
void Start () override
Function to start the connection.
void Stop () override
Function to stop the connection.
bool IsConnectToHost () override
Function to check if connected to host remote server.
uds_transport::UdsTransportProtocolMgr::ConnectionResult ConnectToHost (uds_transport::UdsMessageConstPtr message) override
Function to establish connection to remote host server.
uds_transport::UdsTransportProtocolMgr::DisconnectionResult DisconnectFromHost () override
Function to disconnect from remote host server.
std::pair< uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr > IndicateMessage (uds_transport::UdsMessage::Address source_addr, uds_transport::UdsMessage::Address target_addr, uds_transport::UdsMessage::TargetAddressType type, uds_transport::ChannelID channel_id, std::size_t size, uds_transport::Priority priority, uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) override
Function to indicate a start of reception of message.
uds_transport::UdsTransportProtocolMgr::TransmissionResult Transmit (uds_transport::UdsMessageConstPtr message) override
Function to transmit a valid Uds message.
void HandleMessage (uds_transport::UdsMessagePtr message) override
Function to Hands over a valid received Uds message.
Public Member Functions inherited from uds_transport::Connection
Connection (std::string_view connection_name, ConnectionId connection_id, uds_transport::ConversionHandler const &conversation_handler) noexcept
Constructor to create a new connection.
virtual ~Connection ()=default
Destruct an instance of Connection.
ConnectionId GetConnectionId () const noexcept
Function to get the connection id.
std::string_view GetConnectionName () const noexcept
Function to get the connection name.
Private Attributes
channel::tcp_channel::DoipTcpChannel doip_tcp_channel_
Store the doip tcp channel.
Additional Inherited Members
Protected Attributes inherited from uds_transport::Connection
uds_transport::ConversionHandler const & conversation_handler_
Store the conversation handler.
Detailed Description
Doip Tcp Connection handle connection between two layers.
Definition at line 38 of file connection_manager.cpp.
Member Typedef Documentation
InitializationResult
using doip_client::connection::DoipTcpConnection::InitializationResult = uds_transport::Connection::InitializationResult
Type alias for Initialization result.
Definition at line 43 of file connection_manager.cpp.
TcpClient
using doip_client::connection::DoipTcpConnection::TcpClient = sockets::TcpSocketHandler::Client
Type alias for Tcp client used by socket handler.
Definition at line 48 of file connection_manager.cpp.
Constructor & Destructor Documentation
DoipTcpConnection()
doip_client::connection::DoipTcpConnection::DoipTcpConnection (uds_transport::ConversionHandler const & conversation_handler, std::string_view tcp_ip_address, std::uint16_t port_num) inline
Constructor to create a new tcp connection.
Parameters
[in] conversation_handler The reference to conversation handler
[in] tcp_ip_address The local tcp ip address
[in] port_num The local port number
[in] io_context The reference to io context
Definition at line 61 of file connection_manager.cpp.
       : uds_transport::Connection{kDoipTcpConnectionName, 1u, conversation_handler},
         doip_tcp_channel_{
             sockets::TcpSocketHandler{TcpClient{GetConnectionName(), tcp_ip_address, port_num}},
             *this} {}
~DoipTcpConnection()
doip_client::connection::DoipTcpConnection::~DoipTcpConnection () final default
Destruct an instance of DoipTcpConnection.
Member Function Documentation
ConnectToHost()
uds_transport::UdsTransportProtocolMgr::ConnectionResult doip_client::connection::DoipTcpConnection::ConnectToHost (uds_transport::UdsMessageConstPtr message) inline override virtual
Function to establish connection to remote host server.
Parameters
[in] message The connection message
Returns
Connection result
Implements uds_transport::Connection.
Definition at line 101 of file connection_manager.cpp.
{
     return (doip_tcp_channel_.ConnectToHost(std::move(message)));
   }
References doip_client::channel::tcp_channel::DoipTcpChannel::ConnectToHost(), and doip_tcp_channel_.
DisconnectFromHost()
uds_transport::UdsTransportProtocolMgr::DisconnectionResult doip_client::connection::DoipTcpConnection::DisconnectFromHost () inline override virtual
Function to disconnect from remote host server.
Returns
Disconnection result
Implements uds_transport::Connection.
Definition at line 110 of file connection_manager.cpp.
{
     return (doip_tcp_channel_.DisconnectFromHost());
   }
References doip_client::channel::tcp_channel::DoipTcpChannel::DisconnectFromHost(), and doip_tcp_channel_.
HandleMessage()
void doip_client::connection::DoipTcpConnection::HandleMessage (uds_transport::UdsMessagePtr message) inline override virtual
Function to Hands over a valid received Uds message.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Implements uds_transport::Connection.
Definition at line 166 of file connection_manager.cpp.
{
     conversation_handler_.HandleMessage(std::move(message));
   }
References uds_transport::Connection::conversation_handler_, and uds_transport::ConversionHandler::HandleMessage().
IndicateMessage()
std::pair<uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr> doip_client::connection::DoipTcpConnection::IndicateMessage (uds_transport::UdsMessage::Address source_addr, uds_transport::UdsMessage::Address target_addr, uds_transport::UdsMessage::TargetAddressType type, uds_transport::ChannelID channel_id, std::size_t size, uds_transport::Priority priority, uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) inline override virtual
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The view onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Implements uds_transport::Connection.
Definition at line 140 of file connection_manager.cpp.
{
     return (conversation_handler_.IndicateMessage(source_addr, target_addr, type, channel_id, size,
                                                   priority, protocol_kind, payload_info));
   }
References uds_transport::Connection::conversation_handler_, and uds_transport::ConversionHandler::IndicateMessage().
Initialize()
InitializationResult doip_client::connection::DoipTcpConnection::Initialize () inline override virtual
Function to initialize the connection.
Returns
The initialization result
Implements uds_transport::Connection.
Definition at line 77 of file connection_manager.cpp.
 { return InitializationResult::kInitializeOk; }
References uds_transport::UdsTransportProtocolHandler::kInitializeOk.
IsConnectToHost()
bool doip_client::connection::DoipTcpConnection::IsConnectToHost () inline override virtual
Function to check if connected to host remote server.
Returns
True if connected, False otherwise
Implements uds_transport::Connection.
Definition at line 93 of file connection_manager.cpp.
 { return (doip_tcp_channel_.IsConnectedToHost()); }
References doip_tcp_channel_, and doip_client::channel::tcp_channel::DoipTcpChannel::IsConnectedToHost().
Start()
void doip_client::connection::DoipTcpConnection::Start () inline override virtual
Function to start the connection.
Implements uds_transport::Connection.
Definition at line 82 of file connection_manager.cpp.
 { doip_tcp_channel_.Start(); }
References doip_tcp_channel_, and doip_client::channel::tcp_channel::DoipTcpChannel::Start().
Stop()
void doip_client::connection::DoipTcpConnection::Stop () inline override virtual
Function to stop the connection.
Implements uds_transport::Connection.
Definition at line 87 of file connection_manager.cpp.
 { doip_tcp_channel_.Stop(); }
References doip_tcp_channel_, and doip_client::channel::tcp_channel::DoipTcpChannel::Stop().
Transmit()
uds_transport::UdsTransportProtocolMgr::TransmissionResult doip_client::connection::DoipTcpConnection::Transmit (uds_transport::UdsMessageConstPtr message) inline override virtual
Function to transmit a valid Uds message.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request.
Implements uds_transport::Connection.
Definition at line 155 of file connection_manager.cpp.
{
     return doip_tcp_channel_.Transmit(std::move(message));
   }
References doip_tcp_channel_, and doip_client::channel::tcp_channel::DoipTcpChannel::Transmit().
Member Data Documentation
doip_tcp_channel_
channel::tcp_channel::DoipTcpChannel doip_client::connection::DoipTcpConnection::doip_tcp_channel_ private
Store the doip tcp channel.
Definition at line 174 of file connection_manager.cpp.
Referenced by ConnectToHost(), DisconnectFromHost(), IsConnectToHost(), Start(), Stop(), and Transmit().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/connection/connection_manager.cpp