Diag-Client-Lib: uds_transport::Connection Class Reference
uds_transport::Connection Class Reference abstract
Interface class to handle connection between two layers.
#include <connection.h>
Public Types
using ConnectionId = std::uint8_t
Type alias for connection id.
using InitializationResult = uds_transport::UdsTransportProtocolHandler::InitializationResult
Type alias for Initialization result.
Public Member Functions
Connection (ConnectionId connection_id, uds_transport::ConversionHandler const &conversation_handler) noexcept
Constructor to create a new connection.
virtual ~Connection ()=default
Destruct an instance of Connection.
virtual InitializationResult Initialize ()=0
Function to initialize the connection.
ConnectionId GetConnectionId () noexcept
Function to get the connection id.
virtual void Start ()=0
Function to start the connection.
virtual void Stop ()=0
Function to stop the connection.
virtual bool IsConnectToHost ()=0
Function to check if connected to host remote server.
virtual UdsTransportProtocolMgr::ConnectionResult ConnectToHost (UdsMessageConstPtr message)=0
Function to establish connection to remote host server.
virtual UdsTransportProtocolMgr::DisconnectionResult DisconnectFromHost ()=0
Function to disconnect from remote host server.
virtual std::pair< UdsTransportProtocolMgr::IndicationResult, UdsMessagePtr > IndicateMessage (UdsMessage::Address source_addr, UdsMessage::Address target_addr, UdsMessage::TargetAddressType type, ChannelID channel_id, std::size_t size, Priority priority, ProtocolKind protocol_kind, core_type::Span< std::uint8_t > payload_info)=0
Function to indicate a start of reception of message.
virtual UdsTransportProtocolMgr::TransmissionResult Transmit (UdsMessageConstPtr message)=0
Function to transmit a valid Uds message.
virtual void HandleMessage (UdsMessagePtr message)=0
Function to Hands over a valid received Uds message.
ConnectionId GetConnectionId () const
Function to get the connection id.
Protected Attributes
uds_transport::ConversionHandler const & conversation_handler_
Store the conversation handler.
Private Attributes
ConnectionId connection_id_
Store the connection id.
Detailed Description
Interface class to handle connection between two layers.
Definition at line 23 of file connection.h.
Member Typedef Documentation
ConnectionId
using uds_transport::Connection::ConnectionId = std::uint8_t
Type alias for connection id.
Definition at line 28 of file connection.h.
InitializationResult
using uds_transport::Connection::InitializationResult = uds_transport::UdsTransportProtocolHandler::InitializationResult
Type alias for Initialization result.
Definition at line 33 of file connection.h.
Constructor & Destructor Documentation
Connection()
uds_transport::Connection::Connection (ConnectionId connection_id, uds_transport::ConversionHandler const & conversation_handler) inline noexcept
Constructor to create a new connection.
Parameters
[in] connection_id The connection identification
[in] conversation_handler The reference to conversation handler
Definition at line 42 of file connection.h.
       : conversation_handler_{conversation_handler},
         connection_id_{connection_id} {}
~Connection()
virtual uds_transport::Connection::~Connection () virtual default
Destruct an instance of Connection.
Member Function Documentation
ConnectToHost()
virtual UdsTransportProtocolMgr::ConnectionResult uds_transport::Connection::ConnectToHost (UdsMessageConstPtr message) pure virtual
Function to establish connection to remote host server.
Parameters
[in] message The connection message
Returns
Connection result
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
DisconnectFromHost()
virtual UdsTransportProtocolMgr::DisconnectionResult uds_transport::Connection::DisconnectFromHost () pure virtual
Function to disconnect from remote host server.
Returns
Disconnection result
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
GetConnectionId() [1/2]
ConnectionId uds_transport::Connection::GetConnectionId () const inline
Function to get the connection id.
Returns
The connection id
Definition at line 142 of file connection.h.
 { return connection_id_; }
References connection_id_.
GetConnectionId() [2/2]
ConnectionId uds_transport::Connection::GetConnectionId () inline noexcept
Function to get the connection id.
Returns
The connection id
Definition at line 61 of file connection.h.
 { return connection_id_; }
References connection_id_.
HandleMessage()
virtual void uds_transport::Connection::HandleMessage (UdsMessagePtr message) pure virtual
Function to Hands over a valid received Uds message.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::HandleMessage(), and doip_client::channel::udp_channel::DoipUdpChannel::HandleMessage().
IndicateMessage()
virtual std::pair<UdsTransportProtocolMgr::IndicationResult, UdsMessagePtr> uds_transport::Connection::IndicateMessage (UdsMessage::Address source_addr, UdsMessage::Address target_addr, UdsMessage::TargetAddressType type, ChannelID channel_id, std::size_t size, Priority priority, ProtocolKind protocol_kind, core_type::Span< std::uint8_t > payload_info) pure virtual
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The view onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::IndicateMessage(), and doip_client::channel::udp_channel::DoipUdpChannel::IndicateMessage().
Initialize()
virtual InitializationResult uds_transport::Connection::Initialize () pure virtual
Function to initialize the connection.
Returns
The initialization result
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
IsConnectToHost()
virtual bool uds_transport::Connection::IsConnectToHost () pure virtual
Function to check if connected to host remote server.
Returns
True if connection, False otherwise
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
Start()
virtual void uds_transport::Connection::Start () pure virtual
Function to start the connection.
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
Stop()
virtual void uds_transport::Connection::Stop () pure virtual
Function to stop the connection.
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
Transmit()
virtual UdsTransportProtocolMgr::TransmissionResult uds_transport::Connection::Transmit (UdsMessageConstPtr message) pure virtual
Function to transmit a valid Uds message.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request.
Implemented in doip_client::connection::DoipUdpConnection, and doip_client::connection::DoipTcpConnection.
Member Data Documentation
connection_id_
ConnectionId uds_transport::Connection::connection_id_ private
Store the connection id.
Definition at line 154 of file connection.h.
Referenced by GetConnectionId().
conversation_handler_
uds_transport::ConversionHandler const& uds_transport::Connection::conversation_handler_ protected
Store the conversation handler.
Definition at line 148 of file connection.h.
Referenced by doip_client::connection::DoipTcpConnection::HandleMessage(), doip_client::connection::DoipUdpConnection::HandleMessage(), doip_client::connection::DoipTcpConnection::IndicateMessage(), and doip_client::connection::DoipUdpConnection::IndicateMessage().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/uds-transport-layer-api/uds_transport/connection.h