Diag-Client-Lib: doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl Class Reference
doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl Class Reference final
Class implements routing activation handler.
Public Types
using RoutingActivationStateContext = utility::state::StateContext< RoutingActivationState >
Type alias for state context.
using SyncTimer = utility::sync_timer::SyncTimer< std::chrono::steady_clock >
Type alias for Sync timer.
Public Member Functions
RoutingActivationHandlerImpl (sockets::TcpSocketHandler &tcp_socket_handler)
Constructs an instance of RoutingActivationHandlerImpl.
void Start ()
Function to start the handler.
void Stop ()
Function to stop the handler.
void Reset ()
Function to reset the handler.
auto GetStateContext () noexcept -> RoutingActivationStateContext &
Function to get the Routing Activation State context.
auto GetSocketHandler () noexcept -> sockets::TcpSocketHandler &
Function to get the socket handler.
auto GetSyncTimer () noexcept -> SyncTimer &
Function to get the sync timer.
Private Attributes
sockets::TcpSocketHandler & tcp_socket_handler_
The reference to socket handler.
RoutingActivationStateContext state_context_
Stores the routing activation states.
SyncTimer sync_timer_
Store the synchronous timer.
Detailed Description
Class implements routing activation handler.
Definition at line 238 of file doip_routing_activation_handler.cpp.
Member Typedef Documentation
RoutingActivationStateContext
using doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::RoutingActivationStateContext = utility::state::StateContext<RoutingActivationState>
Type alias for state context.
Definition at line 243 of file doip_routing_activation_handler.cpp.
SyncTimer
using doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::SyncTimer = utility::sync_timer::SyncTimer<std::chrono::steady_clock>
Type alias for Sync timer.
Definition at line 248 of file doip_routing_activation_handler.cpp.
Constructor & Destructor Documentation
RoutingActivationHandlerImpl()
doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::RoutingActivationHandlerImpl (sockets::TcpSocketHandler & tcp_socket_handler) inline explicit
Constructs an instance of RoutingActivationHandlerImpl.
Parameters
[in] tcp_socket_handler The reference to socket handler
Definition at line 255 of file doip_routing_activation_handler.cpp.
       : tcp_socket_handler_{tcp_socket_handler},
         state_context_{},
         sync_timer_{} {
     // create and add state for routing activation
     // kIdle
     state_context_.AddState(RoutingActivationState::kIdle,
                             std::make_unique<kIdle>(RoutingActivationState::kIdle));
     // kWaitForRoutingActivationRes
     state_context_.AddState(RoutingActivationState::kWaitForRoutingActivationRes,
                             std::make_unique<kWaitForRoutingActivationRes>(
                                 RoutingActivationState::kWaitForRoutingActivationRes));
     // kRoutingActivationSuccessful
     state_context_.AddState(RoutingActivationState::kRoutingActivationSuccessful,
                             std::make_unique<kRoutingActivationSuccessful>(
                                 RoutingActivationState::kRoutingActivationSuccessful));
     // kRoutingActivationFailed
     state_context_.AddState(RoutingActivationState::kRoutingActivationFailed,
                             std::make_unique<kRoutingActivationFailed>(
                                 RoutingActivationState::kRoutingActivationFailed));
     // Transit to idle state
     state_context_.TransitionTo(RoutingActivationState::kIdle);
   }
References utility::state::StateContext< EnumState >::AddState(), state_context_, and utility::state::StateContext< EnumState >::TransitionTo().
Member Function Documentation
GetSocketHandler()
auto doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::GetSocketHandler () -> sockets::TcpSocketHandler & inline noexcept
Function to get the socket handler.
Returns
The reference to socket handler
Definition at line 309 of file doip_routing_activation_handler.cpp.
 { return tcp_socket_handler_; }
References tcp_socket_handler_.
GetStateContext()
auto doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::GetStateContext () -> RoutingActivationStateContext & inline noexcept
Function to get the Routing Activation State context.
Returns
The reference to state context
Definition at line 303 of file doip_routing_activation_handler.cpp.
 { return state_context_; }
References state_context_.
GetSyncTimer()
auto doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::GetSyncTimer () -> SyncTimer & inline noexcept
Function to get the sync timer.
Returns
The reference to sync timer
Definition at line 315 of file doip_routing_activation_handler.cpp.
 { return sync_timer_; }
References sync_timer_.
Reset()
void doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::Reset () inline
Function to reset the handler.
This will reset all the internal handler back to default state
Definition at line 297 of file doip_routing_activation_handler.cpp.
 { Stop(); }
References Stop().
Start()
void doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::Start () inline
Function to start the handler.
Definition at line 282 of file doip_routing_activation_handler.cpp.
 {}
Stop()
void doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::Stop () inline
Function to stop the handler.
This will reset all the internal handler back to default state
Definition at line 288 of file doip_routing_activation_handler.cpp.
               {
     if (sync_timer_.IsTimerActive()) { sync_timer_.CancelWait(); }
     state_context_.TransitionTo(RoutingActivationState::kIdle);
   }
References utility::sync_timer::SyncTimer< ClockType >::CancelWait(), utility::sync_timer::SyncTimer< ClockType >::IsTimerActive(), state_context_, sync_timer_, and utility::state::StateContext< EnumState >::TransitionTo().
Referenced by Reset().
Member Data Documentation
state_context_
RoutingActivationStateContext doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::state_context_ private
Stores the routing activation states.
Definition at line 326 of file doip_routing_activation_handler.cpp.
Referenced by GetStateContext(), RoutingActivationHandlerImpl(), and Stop().
sync_timer_
SyncTimer doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::sync_timer_ private
Store the synchronous timer.
Definition at line 331 of file doip_routing_activation_handler.cpp.
Referenced by GetSyncTimer(), and Stop().
tcp_socket_handler_
sockets::TcpSocketHandler& doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::tcp_socket_handler_ private
The reference to socket handler.
Definition at line 321 of file doip_routing_activation_handler.cpp.
Referenced by GetSocketHandler().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_routing_activation_handler.cpp