Diag-Client-Lib: utility::sync_timer::SyncTimer< ClockType > Class Template Reference
utility::sync_timer::SyncTimer< ClockType > Class Template Reference final
Timer class for timeout monitoring.
#include <sync_timer.h>
Public Types
enum class TimerState : std::uint8_t { kIdle = 0 , kCancelRequested , kTimeout }
Definition of different timer state during timeout monitoring.
using Clock = ClockType
Type alias for the clock type.
using TimePoint = std::chrono::time_point< Clock >
Type alias for the clock time point.
Public Member Functions
SyncTimer ()
Construct an instance of SyncTimer.
~SyncTimer ()
Destruct an instance of SyncTimer.
template<typename TimeoutCallback , typename CancelCallback >
void WaitForTimeout (TimeoutCallback &&timeout_func, CancelCallback &&cancellation_func, std::chrono::milliseconds const timeout)
Helper function to wait for response with timeout monitoring.
auto IsTimerActive ()
Function to query if timer is running.
void CancelWait ()
Function to cancel the synchronous wait.
Private Member Functions
auto Start (std::chrono::milliseconds const timeout) noexcept -> TimerState
Function to start the timeout monitoring.
void Stop () noexcept
Function to stop the current timeout monitoring.
Private Attributes
std::condition_variable cond_var_
The conditional variable needed for synchronizing between start and stop of running timer.
std::mutex mutex_lock_
The mutex for the conditional variable.
bool exit_request_
The flag to terminate the wait.
bool start_running_
The flag to stop the current running timer.
Detailed Description
template<typename ClockType>
class utility::sync_timer::SyncTimer< ClockType >
Timer class for timeout monitoring.
Template Parameters
ClockType The type of clock to be used for time monitoring
Definition at line 25 of file sync_timer.h.
Member Typedef Documentation
Clock
template<typename ClockType > using utility::sync_timer::SyncTimer< ClockType >::Clock = ClockType
Type alias for the clock type.
Definition at line 30 of file sync_timer.h.
TimePoint
template<typename ClockType > using utility::sync_timer::SyncTimer< ClockType >::TimePoint = std::chrono::time_point<Clock>
Type alias for the clock time point.
Definition at line 35 of file sync_timer.h.
Member Enumeration Documentation
TimerState
template<typename ClockType > enum utility::sync_timer::SyncTimer::TimerState : std::uint8_t strong
Definition of different timer state during timeout monitoring.
Enumerator
kIdle
kCancelRequested
kTimeout
Definition at line 40 of file sync_timer.h.
 : std::uint8_t { kIdle = 0, kCancelRequested, kTimeout };
Constructor & Destructor Documentation
SyncTimer()
template<typename ClockType > utility::sync_timer::SyncTimer< ClockType >::SyncTimer () inline
Construct an instance of SyncTimer.
Definition at line 45 of file sync_timer.h.
 : cond_var_{}, mutex_lock_{}, exit_request_{false}, start_running_{false} {}
~SyncTimer()
template<typename ClockType > utility::sync_timer::SyncTimer< ClockType >::~SyncTimer () inline
Destruct an instance of SyncTimer.
Definition at line 50 of file sync_timer.h.
                {
     std::lock_guard<std::mutex> const lck(mutex_lock_);
     exit_request_ = false;
     start_running_ = false;
     cond_var_.notify_all();
   }
References utility::sync_timer::SyncTimer< ClockType >::cond_var_, utility::sync_timer::SyncTimer< ClockType >::exit_request_, utility::sync_timer::SyncTimer< ClockType >::mutex_lock_, and utility::sync_timer::SyncTimer< ClockType >::start_running_.
Member Function Documentation
CancelWait()
template<typename ClockType > void utility::sync_timer::SyncTimer< ClockType >::CancelWait () inline
Function to cancel the synchronous wait.
Definition at line 91 of file sync_timer.h.
 { Stop(); }
References utility::sync_timer::SyncTimer< ClockType >::Stop().
Referenced by doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::Stop(), and doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::Stop().
IsTimerActive()
template<typename ClockType > auto utility::sync_timer::SyncTimer< ClockType >::IsTimerActive () inline
Function to query if timer is running.
Definition at line 83 of file sync_timer.h.
{
     std::lock_guard<std::mutex> const lck(mutex_lock_);
     return start_running_;
   }
References utility::sync_timer::SyncTimer< ClockType >::mutex_lock_, and utility::sync_timer::SyncTimer< ClockType >::start_running_.
Referenced by doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::Stop(), and doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandlerImpl::Stop().
Start()
template<typename ClockType > auto utility::sync_timer::SyncTimer< ClockType >::Start (std::chrono::milliseconds const timeout) -> TimerState inline private noexcept
Function to start the timeout monitoring.
Parameters
[in] timeout The timeout value in milliseconds after which timeout happens
Returns
TimerState "kTimeout" in case of timeout or "kCancelRequested" when timeout monitoring was cancelled
Definition at line 101 of file sync_timer.h.
{
     TimerState timer_state{TimerState::kIdle};
     std::unique_lock<std::mutex> lck(mutex_lock_);
     start_running_ = true;
     TimePoint const expiry_time_point{Clock::now() + timeout};
     if (cond_var_.wait_until(lck, expiry_time_point, [this, &expiry_time_point, &timer_state]() {
           bool do_exit_wait{false};
           // check if exit was requested
           if (!exit_request_) {
             TimePoint const current_time{Clock::now()};
             // check for expiry
             if (current_time >= expiry_time_point) {
               // timeout
               timer_state = TimerState::kTimeout;
               do_exit_wait = true;
             } else {
               // check for cancellation request
               if (!start_running_) {
                 timer_state = TimerState::kCancelRequested;
                 do_exit_wait = true;
               }  // else - spurious wake-up, do nothing
             }
           } else {
             do_exit_wait = true;
           }
           return do_exit_wait;
         })) {}
     return timer_state;
   }
References utility::sync_timer::SyncTimer< ClockType >::cond_var_, utility::sync_timer::SyncTimer< ClockType >::exit_request_, utility::sync_timer::SyncTimer< ClockType >::kCancelRequested, utility::sync_timer::SyncTimer< ClockType >::kIdle, utility::sync_timer::SyncTimer< ClockType >::kTimeout, utility::sync_timer::SyncTimer< ClockType >::mutex_lock_, and utility::sync_timer::SyncTimer< ClockType >::start_running_.
Referenced by utility::sync_timer::SyncTimer< ClockType >::WaitForTimeout().
Stop()
template<typename ClockType > void utility::sync_timer::SyncTimer< ClockType >::Stop () inline private noexcept
Function to stop the current timeout monitoring.
Definition at line 134 of file sync_timer.h.
{
     std::lock_guard<std::mutex> const lck(mutex_lock_);
     start_running_ = false;
     cond_var_.notify_all();
   }
Referenced by utility::sync_timer::SyncTimer< ClockType >::CancelWait().
WaitForTimeout()
template<typename ClockType > template<typename TimeoutCallback , typename CancelCallback > void utility::sync_timer::SyncTimer< ClockType >::WaitForTimeout (TimeoutCallback && timeout_func, CancelCallback && cancellation_func, std::chrono::milliseconds const timeout) inline
Helper function to wait for response with timeout monitoring.
Template Parameters
TimeoutCallback The callback functor type for timeout notification
CancelCallback The callback functor type for cancellation notification
Parameters
[in] timeout_func The functor to be called when timeout occurs
[in] cancel_func The functor to be called when expected event occurs within timeout
[in] timeout The timeout in milliseconds
Definition at line 71 of file sync_timer.h.
{
     if (Start(timeout) == TimerState::kTimeout) {
       timeout_func();
     } else {
       cancellation_func();
     }
   }
References utility::sync_timer::SyncTimer< ClockType >::kTimeout, and utility::sync_timer::SyncTimer< ClockType >::Start().
Member Data Documentation
cond_var_
template<typename ClockType > std::condition_variable utility::sync_timer::SyncTimer< ClockType >::cond_var_ private
The conditional variable needed for synchronizing between start and stop of running timer.
Definition at line 144 of file sync_timer.h.
Referenced by utility::sync_timer::SyncTimer< ClockType >::Start(), and utility::sync_timer::SyncTimer< ClockType >::~SyncTimer().
exit_request_
template<typename ClockType > bool utility::sync_timer::SyncTimer< ClockType >::exit_request_ private
The flag to terminate the wait.
Definition at line 154 of file sync_timer.h.
Referenced by utility::sync_timer::SyncTimer< ClockType >::Start(), and utility::sync_timer::SyncTimer< ClockType >::~SyncTimer().
mutex_lock_
template<typename ClockType > std::mutex utility::sync_timer::SyncTimer< ClockType >::mutex_lock_ private
The mutex for the conditional variable.
Definition at line 149 of file sync_timer.h.
Referenced by utility::sync_timer::SyncTimer< ClockType >::IsTimerActive(), utility::sync_timer::SyncTimer< ClockType >::Start(), and utility::sync_timer::SyncTimer< ClockType >::~SyncTimer().
start_running_
template<typename ClockType > bool utility::sync_timer::SyncTimer< ClockType >::start_running_ private
The flag to stop the current running timer.
Definition at line 159 of file sync_timer.h.
Referenced by utility::sync_timer::SyncTimer< ClockType >::IsTimerActive(), utility::sync_timer::SyncTimer< ClockType >::Start(), and utility::sync_timer::SyncTimer< ClockType >::~SyncTimer().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/utility-support/utility/sync_timer.h