Diag-Client-Lib: doip_client::channel::tcp_channel::RoutingActivationHandler Class Reference
doip_client::channel::tcp_channel::RoutingActivationHandler Class Reference final
Class used as a handler to process routing activation messages.
#include <doip_routing_activation_handler.h>
Classes
class RoutingActivationHandlerImpl
Class implements routing activation handler.
Public Types
using TcpMessagePtr = sockets::TcpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
using TcpMessage = sockets::TcpSocketHandler::Message
Type alias for Tcp message.
Public Member Functions
RoutingActivationHandler (sockets::TcpSocketHandler &tcp_socket_handler)
Constructs an instance of RoutingActivationHandler.
~RoutingActivationHandler ()
Destruct an instance of RoutingActivationHandler.
void Start ()
Function to start the handler.
void Stop ()
Function to stop the handler.
void Reset ()
Function to reset the handler.
void ProcessDoIPRoutingActivationResponse (DoipMessage &doip_payload) noexcept
Function to process received routing activation response.
auto HandleRoutingActivationRequest (uds_transport::UdsMessageConstPtr routing_activation_request) noexcept -> uds_transport::UdsTransportProtocolMgr::ConnectionResult
Function to handle sending of routing activation request.
auto IsRoutingActivated () noexcept -> bool
Check if routing activation is active for this handler.
Private Member Functions
auto SendRoutingActivationRequest (uds_transport::UdsMessageConstPtr routing_activation_request) noexcept -> uds_transport::UdsTransportProtocolMgr::TransmissionResult
Function to send routing activation request.
Private Attributes
std::unique_ptr< RoutingActivationHandlerImpl > handler_impl_
Stores the Handler implementation.
Detailed Description
Class used as a handler to process routing activation messages.
Definition at line 29 of file doip_routing_activation_handler.h.
Member Typedef Documentation
TcpMessage
using doip_client::channel::tcp_channel::RoutingActivationHandler::TcpMessage = sockets::TcpSocketHandler::Message
Type alias for Tcp message.
Definition at line 39 of file doip_routing_activation_handler.h.
TcpMessagePtr
using doip_client::channel::tcp_channel::RoutingActivationHandler::TcpMessagePtr = sockets::TcpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
Definition at line 34 of file doip_routing_activation_handler.h.
Constructor & Destructor Documentation
RoutingActivationHandler()
doip_client::channel::tcp_channel::RoutingActivationHandler::RoutingActivationHandler (sockets::TcpSocketHandler & tcp_socket_handler) explicit
Constructs an instance of RoutingActivationHandler.
Parameters
[in] tcp_socket_handler The reference to socket handler
Definition at line 334 of file doip_routing_activation_handler.cpp.
     : handler_impl_{std::make_unique<RoutingActivationHandlerImpl>(tcp_socket_handler)} {}
~RoutingActivationHandler()
doip_client::channel::tcp_channel::RoutingActivationHandler::~RoutingActivationHandler () default
Destruct an instance of RoutingActivationHandler.
Member Function Documentation
HandleRoutingActivationRequest()
auto doip_client::channel::tcp_channel::RoutingActivationHandler::HandleRoutingActivationRequest (uds_transport::UdsMessageConstPtr routing_activation_request) -> uds_transport::UdsTransportProtocolMgr::ConnectionResult noexcept
Function to handle sending of routing activation request.
Parameters
[in] routing_activation_request The routing activation request
Returns
Transmission result
Definition at line 387 of file doip_routing_activation_handler.cpp.
{
   uds_transport::UdsTransportProtocolMgr::ConnectionResult result{
       uds_transport::UdsTransportProtocolMgr::ConnectionResult::kConnectionFailed};
   if (handler_impl_->GetStateContext().GetActiveState().GetState() ==
       RoutingActivationState::kIdle) {
     if (SendRoutingActivationRequest(std::move(routing_activation_request)) ==
         uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk) {
       // Wait for routing activation response
       handler_impl_->GetStateContext().TransitionTo(
           RoutingActivationState::kWaitForRoutingActivationRes);
       handler_impl_->GetSyncTimer().WaitForTimeout(
           [this, &result]() {
             result = uds_transport::UdsTransportProtocolMgr::ConnectionResult::kConnectionTimeout;
             handler_impl_->GetStateContext().TransitionTo(RoutingActivationState::kIdle);
             logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
                 FILE_NAME, __LINE__, "", [](std::stringstream &msg) {
                   msg << "RoutingActivation response timeout, no response "
                          "received in: "
                       << kDoIPRoutingActivationTimeout << " milliseconds";
                 });
           },
           [this, &result]() {
             if (handler_impl_->GetStateContext().GetActiveState().GetState() ==
                 RoutingActivationState::kRoutingActivationSuccessful) {
               // success
               result = uds_transport::UdsTransportProtocolMgr::ConnectionResult::kConnectionOk;
               logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
                   FILE_NAME, __LINE__, "", [](std::stringstream &msg) {
                     msg << "RoutingActivation successful with remote server";
                   });
             } else {  // failed
               handler_impl_->GetStateContext().TransitionTo(RoutingActivationState::kIdle);
               logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
                   FILE_NAME, __LINE__, "", [](std::stringstream &msg) {
                     msg << "RoutingActivation failed with remote server";
                   });
             }
           },
           std::chrono::milliseconds{kDoIPRoutingActivationTimeout});
     } else {
       // failed, do nothing
       handler_impl_->GetStateContext().TransitionTo(RoutingActivationState::kIdle);
       logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, "", [](std::stringstream &msg) {
             msg << "RoutingActivation Request send failed with remote server";
           });
     }
   } else {
     // channel not free
     logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogVerbose(
         FILE_NAME, __LINE__, "",
         [](std::stringstream &msg) { msg << "RoutingActivation channel not free"; });
   }
   return result;
 }
References FILE_NAME, doip_client::logger::DoipClientLogger::GetDiagClientLogger(), uds_transport::UdsTransportProtocolMgr::kConnectionFailed, uds_transport::UdsTransportProtocolMgr::kConnectionOk, uds_transport::UdsTransportProtocolMgr::kConnectionTimeout, doip_client::channel::tcp_channel::anonymous_namespace{doip_routing_activation_handler.cpp}::kDoIPRoutingActivationTimeout, and uds_transport::UdsTransportProtocolMgr::kTransmitOk.
IsRoutingActivated()
auto doip_client::channel::tcp_channel::RoutingActivationHandler::IsRoutingActivated () -> bool noexcept
Check if routing activation is active for this handler.
Returns
True if activated, otherwise False
Definition at line 445 of file doip_routing_activation_handler.cpp.
{
   return (handler_impl_->GetStateContext().GetActiveState().GetState() ==
           RoutingActivationState::kRoutingActivationSuccessful);
 }
References handler_impl_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannelHandler::IsRoutingActivated().
ProcessDoIPRoutingActivationResponse()
auto doip_client::channel::tcp_channel::RoutingActivationHandler::ProcessDoIPRoutingActivationResponse (DoipMessage & doip_payload) noexcept
Function to process received routing activation response.
Parameters
[in] doip_payload The doip message received
Definition at line 345 of file doip_routing_activation_handler.cpp.
{
   RoutingActivationState final_state{RoutingActivationState::kRoutingActivationFailed};
   if (handler_impl_->GetStateContext().GetActiveState().GetState() ==
       RoutingActivationState::kWaitForRoutingActivationRes) {
     // get the ack code
     RoutingActivationAckType const rout_act_type{doip_payload.GetPayload()[0u]};
     switch (rout_act_type.act_type_) {
       case kDoipRoutingActivationResCodeRoutingSuccessful: {
         // routing successful
         final_state = RoutingActivationState::kRoutingActivationSuccessful;
         logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
             FILE_NAME, __LINE__, __func__, [&doip_payload](std::stringstream &msg) {
               msg << "RoutingActivation successfully activated in remote "
                      "server with logical Address"
                   << " (0x" << std::hex << doip_payload.GetServerAddress() << ")";
             });
       } break;
       case kDoipRoutingActivationResCodeConfirmtnRequired: {
         // trigger routing activation after sometime, not implemented yet
         logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
             FILE_NAME, __LINE__, __func__, [&doip_payload](std::stringstream &msg) {
               msg << "RoutingActivation is activated, confirmation required in "
                      "remote server with logical Address"
                   << " (0x" << std::hex << doip_payload.GetServerAddress() << ")";
             });
       } break;
       default:
         // failure, do nothing
         logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogWarn(
             FILE_NAME, __LINE__, __func__, [&rout_act_type](std::stringstream &msg) {
               msg << "Routing activation denied due to " << rout_act_type;
             });
         break;
     }
     handler_impl_->GetStateContext().TransitionTo(final_state);
     handler_impl_->GetSyncTimer().CancelWait();
   } else {
     /* ignore */
   }
 }
References FILE_NAME, doip_client::logger::DoipClientLogger::GetDiagClientLogger(), doip_client::channel::tcp_channel::anonymous_namespace{doip_routing_activation_handler.cpp}::kDoipRoutingActivationResCodeConfirmtnRequired, and doip_client::channel::tcp_channel::anonymous_namespace{doip_routing_activation_handler.cpp}::kDoipRoutingActivationResCodeRoutingSuccessful.
Reset()
void doip_client::channel::tcp_channel::RoutingActivationHandler::Reset ()
Function to reset the handler.
This will reset all the internal handler back to default state
Definition at line 343 of file doip_routing_activation_handler.cpp.
 { handler_impl_->Reset(); }
References handler_impl_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannelHandler::Reset().
SendRoutingActivationRequest()
auto doip_client::channel::tcp_channel::RoutingActivationHandler::SendRoutingActivationRequest (uds_transport::UdsMessageConstPtr routing_activation_request) -> uds_transport::UdsTransportProtocolMgr::TransmissionResult private noexcept
Function to send routing activation request.
Parameters
[in] routing_activation_request The routing activation request
Returns
Transmission result
Definition at line 450 of file doip_routing_activation_handler.cpp.
{
   uds_transport::UdsTransportProtocolMgr::TransmissionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed};
   // Create header
   TcpMessage::BufferType compose_routing_activation_req{
       CreateDoipGenericHeader(kDoip_RoutingActivation_ReqType, kDoipRoutingActivationReqMinLen)};
   compose_routing_activation_req.reserve(kDoipheadrSize + kDoipRoutingActivationReqMinLen);
   // Add source address
   compose_routing_activation_req.emplace_back(
       static_cast<std::uint8_t>((message->GetSa() & 0xFF00) >> 8u));
   compose_routing_activation_req.emplace_back(static_cast<std::uint8_t>(message->GetSa() & 0x00FF));
   // Add activation type
   compose_routing_activation_req.emplace_back(kDoip_RoutingActivation_ReqActType_Default);
   // Add reservation byte , default zeroes
   compose_routing_activation_req.emplace_back(0x00);
   compose_routing_activation_req.emplace_back(0x00);
   compose_routing_activation_req.emplace_back(0x00);
   compose_routing_activation_req.emplace_back(0x00);
   TcpMessagePtr doip_routing_act_req{
       std::make_unique<TcpMessage>(message->GetHostIpAddress(), message->GetHostPortNumber(),
                                    std::move(compose_routing_activation_req))};
   // Initiate transmission
   if (handler_impl_->GetSocketHandler().Transmit(std::move(doip_routing_act_req))) {
     ret_val = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk;
   }
   return ret_val;
 }
References doip_client::channel::tcp_channel::anonymous_namespace{doip_routing_activation_handler.cpp}::CreateDoipGenericHeader(), doip_client::channel::tcp_channel::anonymous_namespace{doip_routing_activation_handler.cpp}::kDoip_RoutingActivation_ReqActType_Default, doip_client::channel::tcp_channel::anonymous_namespace{doip_routing_activation_handler.cpp}::kDoip_RoutingActivation_ReqType, doip_client::kDoipheadrSize, doip_client::channel::tcp_channel::anonymous_namespace{doip_routing_activation_handler.cpp}::kDoipRoutingActivationReqMinLen, uds_transport::UdsTransportProtocolMgr::kTransmitFailed, and uds_transport::UdsTransportProtocolMgr::kTransmitOk.
Start()
void doip_client::channel::tcp_channel::RoutingActivationHandler::Start ()
Function to start the handler.
Definition at line 339 of file doip_routing_activation_handler.cpp.
 { handler_impl_->Start(); }
References handler_impl_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannelHandler::Start().
Stop()
void doip_client::channel::tcp_channel::RoutingActivationHandler::Stop ()
Function to stop the handler.
This will reset all the internal handler back to default state
Definition at line 341 of file doip_routing_activation_handler.cpp.
 { handler_impl_->Stop(); }
References handler_impl_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannelHandler::Stop().
Member Data Documentation
handler_impl_
std::unique_ptr<RoutingActivationHandlerImpl> doip_client::channel::tcp_channel::RoutingActivationHandler::handler_impl_ private
Stores the Handler implementation.
Definition at line 114 of file doip_routing_activation_handler.h.
Referenced by IsRoutingActivated(), Reset(), Start(), and Stop().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_routing_activation_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_routing_activation_handler.cpp