Diag-Client-Lib: boost_support::socket::tls::TlsSocket Class Reference
boost_support::socket::tls::TlsSocket Class Reference final
Class used to create a tcp socket for handling transmission and reception of tcp message from driver.
#include <tls_socket.h>
Public Types
enum class SocketError : std::uint8_t {
kOpenFailed , kBindingFailed , kRemoteDisconnected , kTlsHandshakeFailed ,
kGenericError
}
Socket error code.
using TcpMessage = boost_support::message::tcp::TcpMessage
Type alias for Tcp message.
using TcpMessagePtr = boost_support::message::tcp::TcpMessagePtr
Type alias for Tcp message pointer.
using TcpMessageConstPtr = boost_support::message::tcp::TcpMessageConstPtr
Type alias for Tcp message const pointer.
using Tcp = boost::asio::ip::tcp
Type alias for tcp protocol.
using TcpSocket = Tcp::socket
Type alias for tcp socket.
Public Member Functions
TlsSocket (std::string_view local_ip_address, std::uint16_t local_port_num, TlsContext &tls_context, IoContext &io_context) noexcept
Constructs an instance of TcpSocket.
TlsSocket (TcpSocket tcp_socket, TlsContext &tls_context) noexcept
Constructs an instance of TcpSocket.
TlsSocket (const TlsSocket &other) noexcept=delete
Deleted copy assignment and copy constructor.
TlsSocket & operator= (const TlsSocket &other) noexcept=delete
TlsSocket & operator= (TlsSocket &&other) noexcept
Move assignment.
TlsSocket (TlsSocket &&other) noexcept
Move constructor.
~TlsSocket () noexcept
Destruct an instance of TcpSocket.
core_type::Result< void, SocketError > Open () noexcept
Function to open and bind the socket to provided ip address & port.
core_type::Result< void, SocketError > Connect (std::string_view host_ip_address, std::uint16_t host_port_num) noexcept
Function to connect to remote ip address and port number.
core_type::Result< void, SocketError > Disconnect () noexcept
Function to Disconnect from host.
core_type::Result< void, SocketError > Transmit (TcpMessageConstPtr tcp_message) noexcept
Function to trigger transmission.
core_type::Result< TcpMessagePtr, SocketError > Read () noexcept
Function to read message from socket.
core_type::Result< void, SocketError > Close () noexcept
Function to destroy the socket.
Private Types
using TcpIpAddress = boost::asio::ip::address
Type alias for tcp ip address.
using TcpErrorCodeType = boost::system::error_code
Type alias for tcp error codes.
using SslStream = boost::asio::ssl::stream< Tcp::socket >
Type alias for tcp socket.
Private Member Functions
SslStream::lowest_layer_type & GetNativeTcpSocket ()
Function to get the native tcp socket under tls socket.
Private Attributes
SslStream ssl_stream_
Store the underlying tcp socket.
Tcp::endpoint local_endpoint_
Store the local endpoints.
Detailed Description
Class used to create a tcp socket for handling transmission and reception of tcp message from driver.
Definition at line 25 of file tls_socket.h.
Member Typedef Documentation
SslStream
using boost_support::socket::tls::TlsSocket::SslStream = boost::asio::ssl::stream<Tcp::socket> private
Type alias for tcp socket.
Definition at line 161 of file tls_socket.h.
Tcp
using boost_support::socket::tls::TlsSocket::Tcp = boost::asio::ip::tcp
Type alias for tcp protocol.
Definition at line 56 of file tls_socket.h.
TcpErrorCodeType
using boost_support::socket::tls::TlsSocket::TcpErrorCodeType = boost::system::error_code private
Type alias for tcp error codes.
Definition at line 156 of file tls_socket.h.
TcpIpAddress
using boost_support::socket::tls::TlsSocket::TcpIpAddress = boost::asio::ip::address private
Type alias for tcp ip address.
Definition at line 151 of file tls_socket.h.
TcpMessage
using boost_support::socket::tls::TlsSocket::TcpMessage = boost_support::message::tcp::TcpMessage
Type alias for Tcp message.
Definition at line 41 of file tls_socket.h.
TcpMessageConstPtr
using boost_support::socket::tls::TlsSocket::TcpMessageConstPtr = boost_support::message::tcp::TcpMessageConstPtr
Type alias for Tcp message const pointer.
Definition at line 51 of file tls_socket.h.
TcpMessagePtr
using boost_support::socket::tls::TlsSocket::TcpMessagePtr = boost_support::message::tcp::TcpMessagePtr
Type alias for Tcp message pointer.
Definition at line 46 of file tls_socket.h.
TcpSocket
using boost_support::socket::tls::TlsSocket::TcpSocket = Tcp::socket
Type alias for tcp socket.
Definition at line 61 of file tls_socket.h.
Member Enumeration Documentation
SocketError
enum boost_support::socket::tls::TlsSocket::SocketError : std::uint8_t strong
Socket error code.
Enumerator
kOpenFailed
kBindingFailed
kRemoteDisconnected
kTlsHandshakeFailed
kGenericError
Definition at line 30 of file tls_socket.h.
                          : std::uint8_t {
     kOpenFailed,
     kBindingFailed,
     kRemoteDisconnected,
     kTlsHandshakeFailed,
     kGenericError
   };
Constructor & Destructor Documentation
TlsSocket() [1/4]
boost_support::socket::tls::TlsSocket::TlsSocket (std::string_view local_ip_address, std::uint16_t local_port_num, TlsContext & tls_context, IoContext & io_context) noexcept
Constructs an instance of TcpSocket.
Parameters
[in] local_ip_address The local ip address
[in] local_port_num The local port number
[in] io_context The I/O context required to create socket
Definition at line 19 of file tls_socket.cpp.
     : ssl_stream_{io_context.GetContext(), tls_context.GetContext()},
       local_endpoint_{boost::asio::ip::make_address(local_ip_address), local_port_num} {}
TlsSocket() [2/4]
boost_support::socket::tls::TlsSocket::TlsSocket (TlsSocket::TcpSocket tcp_socket, TlsContext & tls_context) noexcept
Constructs an instance of TcpSocket.
Parameters
[in] socket The socket
Definition at line 24 of file tls_socket.cpp.
     : ssl_stream_{std::move(tcp_socket), tls_context.GetContext()},
       local_endpoint_{} {
   TcpErrorCodeType ec{};
   // Perform TLS handshake
   ssl_stream_.handshake(boost::asio::ssl::stream_base::server, ec);
   if (ec.value() == boost::system::errc::success) {
     printf("Connected with %s encryption\n", SSL_get_cipher(ssl_stream_.native_handle()));
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tls client handshake with host failed with error: " << ec.message();
         });
   }
 }
TlsSocket() [3/4]
boost_support::socket::tls::TlsSocket::TlsSocket (const TlsSocket & other) delete noexcept
Deleted copy assignment and copy constructor.
TlsSocket() [4/4]
boost_support::socket::tls::TlsSocket::TlsSocket (TlsSocket && other) noexcept
Move constructor.
Definition at line 42 of file tls_socket.cpp.
     : ssl_stream_{std::move(other.ssl_stream_)},
       local_endpoint_{std::move(other.local_endpoint_)} {}
~TlsSocket()
boost_support::socket::tls::TlsSocket::~TlsSocket () default noexcept
Destruct an instance of TcpSocket.
Member Function Documentation
Close()
core_type::Result< void, TlsSocket::SocketError > boost_support::socket::tls::TlsSocket::Close () noexcept
Function to destroy the socket.
Returns
Empty result on success otherwise error code
Definition at line 178 of file tls_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   // Shutdown of TCP connection
   GetNativeTcpSocket().shutdown(Tcp::socket ::shutdown_both);
   GetNativeTcpSocket().cancel();
   // Destroy the socket
   GetNativeTcpSocket().close();
   result.EmplaceValue();
   return result;
 }
References GetNativeTcpSocket(), and kGenericError.
Connect()
core_type::Result< void, TlsSocket::SocketError > boost_support::socket::tls::TlsSocket::Connect (std::string_view host_ip_address, std::uint16_t host_port_num) noexcept
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
Empty result on success otherwise error code
Definition at line 95 of file tls_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   // Connect to provided Ip address
   GetNativeTcpSocket().connect(
       Tcp::endpoint{boost::asio::ip::make_address(host_ip_address), host_port_num}, ec);
   if (ec.value() == boost::system::errc::success) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           Tcp::endpoint const endpoint_{GetNativeTcpSocket().remote_endpoint()};
           msg << "Tls socket connected to host "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     // Perform TLS handshake
     ssl_stream_.handshake(boost::asio::ssl::stream_base::client, ec);
     if (ec.value() == boost::system::errc::success) {
       printf("Connected with %s encryption\n", SSL_get_cipher(ssl_stream_.native_handle()));
       result.EmplaceValue();
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
             msg << "Tls client handshake with host failed with error: " << ec.message();
           });
       result.EmplaceError(SocketError::kTlsHandshakeFailed);
     }
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tls client socket connect to host failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, and boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
Disconnect()
core_type::Result< void, TlsSocket::SocketError > boost_support::socket::tls::TlsSocket::Disconnect () noexcept
Function to Disconnect from host.
Returns
Empty result on success otherwise error code
Definition at line 131 of file tls_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   // Shutdown TLS connection
   ssl_stream_.shutdown(ec);
   // ssl_stream_.
   if (ec.value() == boost::system::errc::success) {
     // Socket shutdown success
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tls client socket disconnection from host failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), kGenericError, and ssl_stream_.
GetNativeTcpSocket()
TlsSocket::SslStream::lowest_layer_type & boost_support::socket::tls::TlsSocket::GetNativeTcpSocket () private
Function to get the native tcp socket under tls socket.
Definition at line 256 of file tls_socket.cpp.
{
   return ssl_stream_.lowest_layer();
 }
References ssl_stream_.
Referenced by Close(), and Read().
Open()
core_type::Result< void, TlsSocket::SocketError > boost_support::socket::tls::TlsSocket::Open () noexcept
Function to open and bind the socket to provided ip address & port.
Returns
Empty result on success otherwise error code
Definition at line 54 of file tls_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   // Open the socket
   GetNativeTcpSocket().open(local_endpoint_.protocol(), ec);
   if (ec.value() == boost::system::errc::success) {
     // Reuse address
     GetNativeTcpSocket().set_option(boost::asio::socket_base::reuse_address{true});
     // Set socket to non blocking
     GetNativeTcpSocket().non_blocking(false);
     // Bind to local ip address and random port
     GetNativeTcpSocket().bind(local_endpoint_, ec);
     if (ec.value() == boost::system::errc::success) {
       // Socket binding success
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
             Tcp::endpoint const endpoint_{GetNativeTcpSocket().local_endpoint()};
             msg << "Tls Socket opened and bound to "
                 << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
           });
       result.EmplaceValue();
     } else {
       // Socket binding failed
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
             msg << "Tls Socket binding failed with message: " << ec.message();
           });
       result.EmplaceError(SocketError::kBindingFailed);
     }
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tls Socket opening failed with error: " << ec.message();
         });
     result.EmplaceError(SocketError::kOpenFailed);
   }
   return result;
 }
References FILE_NAME, and boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
operator=() [1/2]
TlsSocket& boost_support::socket::tls::TlsSocket::operator= (const TlsSocket & other) delete noexcept
operator=() [2/2]
TlsSocket & boost_support::socket::tls::TlsSocket::operator= (TlsSocket && other) noexcept
Move assignment.
Definition at line 46 of file tls_socket.cpp.
{
   ssl_stream_ = std::move(std::move(other.ssl_stream_));
   local_endpoint_ = std::move(other.local_endpoint_);
   return *this;
 }
Read()
core_type::Result< TlsSocket::TcpMessagePtr, TlsSocket::SocketError > boost_support::socket::tls::TlsSocket::Read () noexcept
Function to read message from socket.
Returns
Tcp message on success otherwise error code
Definition at line 191 of file tls_socket.cpp.
{
   core_type::Result<TcpMessagePtr, SocketError> result{SocketError::kRemoteDisconnected};
   TcpErrorCodeType ec{};
   // create and reserve the buffer
   TcpMessage::BufferType rx_buffer{};
   rx_buffer.resize(message::tcp::kDoipheadrSize);
   // start blocking read to read Header first
   boost::asio::read(ssl_stream_, boost::asio::buffer(&rx_buffer[0u], message::tcp::kDoipheadrSize),
                     ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     // read the next bytes to read
     std::uint32_t read_next_bytes = [&rx_buffer]() noexcept -> std::uint32_t {
       return static_cast<std::uint32_t>(
           (static_cast<std::uint32_t>(rx_buffer[4u] << 24u) & 0xFF000000) |
           (static_cast<std::uint32_t>(rx_buffer[5u] << 16u) & 0x00FF0000) |
           (static_cast<std::uint32_t>(rx_buffer[6u] << 8u) & 0x0000FF00) |
           (static_cast<std::uint32_t>(rx_buffer[7u] & 0x000000FF)));
     }();
     if (read_next_bytes != 0u) {
       Tcp::endpoint const remote_endpoint{GetNativeTcpSocket().remote_endpoint()};
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [&remote_endpoint, read_next_bytes](std::stringstream &msg) {
             msg << "Tcp Message with length= " << read_next_bytes << " received from "
                 << "<" << remote_endpoint.address().to_string() << "," << remote_endpoint.port()
                 << ">";
           });
       read_next_bytes = 0;
       // reserve the buffer
       rx_buffer.resize(message::tcp::kDoipheadrSize + std::size_t{read_next_bytes});
       boost::asio::read(
           ssl_stream_,
           boost::asio::buffer(&rx_buffer[message::tcp::kDoipheadrSize], read_next_bytes), ec);
       // all message received, transfer to upper layer
       TcpMessagePtr tcp_rx_message{std::make_unique<TcpMessage>(
           remote_endpoint.address().to_string(), remote_endpoint.port(), std::move(rx_buffer))};
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [&remote_endpoint, read_next_bytes](std::stringstream &msg) {
             msg << "Tcp Message with length= " << read_next_bytes << " received from "
                 << "<" << remote_endpoint.address().to_string() << "," << remote_endpoint.port()
                 << ">";
           });
       result.EmplaceValue(std::move(tcp_rx_message));
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [](std::stringstream &msg) { msg << "Tcp Message read ignored as header size is zero"; });
     }
   } else if (ec.value() == boost::asio::error::eof) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__,
         [ec](std::stringstream &msg) { msg << "Remote Disconnected with: " << ec.message(); });
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Remote Disconnected with undefined error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), boost_support::message::tcp::kDoipheadrSize, kRemoteDisconnected, and ssl_stream_.
Transmit()
core_type::Result< void, TlsSocket::SocketError > boost_support::socket::tls::TlsSocket::Transmit (TcpMessageConstPtr tcp_message) noexcept
Function to trigger transmission.
Parameters
[in] tcp_message The tcp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 152 of file tls_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   boost::asio::write(
       ssl_stream_,
       boost::asio::buffer(tcp_message->GetPayload().data(), tcp_message->GetPayload().size()), ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           Tcp::endpoint const endpoint_{GetNativeTcpSocket().remote_endpoint()};
           msg << "Tcp message sent to "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp message sending failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, and boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
Member Data Documentation
local_endpoint_
Tcp::endpoint boost_support::socket::tls::TlsSocket::local_endpoint_ private
Store the local endpoints.
Definition at line 171 of file tls_socket.h.
ssl_stream_
SslStream boost_support::socket::tls::TlsSocket::ssl_stream_ private
Store the underlying tcp socket.
Definition at line 166 of file tls_socket.h.
Referenced by Disconnect(), GetNativeTcpSocket(), and Read().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tls/tls_socket.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tls/tls_socket.cpp