Diag-Client-Lib: doip_client::sockets::SocketHandler< ClientType > Class Template Reference
doip_client::sockets::SocketHandler< ClientType > Class Template Reference final
Handler class to manage different socket of various client (Udp / Tcp)
#include <socket_handler.h>
Public Types
using Client = ClientType
Type alias for client.
using Message = typename Client::Message
Type alias for message.
using MessagePtr = typename Client::MessagePtr
Type alias for message pointer.
using MessageConstPtr = typename Client::MessageConstPtr
Type alias for message const pointer.
using HandlerRead = std::function< void(MessagePtr)>
Tcp function template used for reception.
Public Member Functions
SocketHandler (Client client) noexcept
Constructs an instance of TcpSocketHandler.
SocketHandler (const SocketHandler &other) noexcept=delete
Deleted copy assignment and copy constructor.
SocketHandler & operator= (const SocketHandler &other) noexcept=delete
SocketHandler (SocketHandler &&other) noexcept=default
Move assignment and Move constructor.
SocketHandler & operator= (SocketHandler &&other) noexcept=default
~SocketHandler ()=default
Destruct an instance of TcpSocketHandler.
void Initialize () noexcept
Function to start the socket handler.
void DeInitialize () noexcept
Function to stop the socket handler.
void SetReadHandler (HandlerRead read_handler)
Function to set the read handler that is invoked when message is received.
core_type::Result< void > ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num)
Function to connect to remote ip address and port number.
core_type::Result< void > DisconnectFromHost ()
Function to disconnect from remote host if already connected.
auto IsConnectedToHost () const noexcept -> bool
Function to get the connection status.
core_type::Result< void > Transmit (MessageConstPtr message)
Function to transmit the provided message.
Private Attributes
Client client_
Store the client object.
Detailed Description
template<typename ClientType>
class doip_client::sockets::SocketHandler< ClientType >
Handler class to manage different socket of various client (Udp / Tcp)
Definition at line 24 of file socket_handler.h.
Member Typedef Documentation
Client
template<typename ClientType > using doip_client::sockets::SocketHandler< ClientType >::Client = ClientType
Type alias for client.
Definition at line 29 of file socket_handler.h.
HandlerRead
template<typename ClientType > using doip_client::sockets::SocketHandler< ClientType >::HandlerRead = std::function<void(MessagePtr)>
Tcp function template used for reception.
Definition at line 49 of file socket_handler.h.
Message
template<typename ClientType > using doip_client::sockets::SocketHandler< ClientType >::Message = typename Client::Message
Type alias for message.
Definition at line 34 of file socket_handler.h.
MessageConstPtr
template<typename ClientType > using doip_client::sockets::SocketHandler< ClientType >::MessageConstPtr = typename Client::MessageConstPtr
Type alias for message const pointer.
Definition at line 44 of file socket_handler.h.
MessagePtr
template<typename ClientType > using doip_client::sockets::SocketHandler< ClientType >::MessagePtr = typename Client::MessagePtr
Type alias for message pointer.
Definition at line 39 of file socket_handler.h.
Constructor & Destructor Documentation
SocketHandler() [1/3]
template<typename ClientType > doip_client::sockets::SocketHandler< ClientType >::SocketHandler (Client client) inline explicit noexcept
Constructs an instance of TcpSocketHandler.
Parameters
[in] socket The socket used
Definition at line 56 of file socket_handler.h.
 : client_{std::move(client)} {}
SocketHandler() [2/3]
template<typename ClientType > doip_client::sockets::SocketHandler< ClientType >::SocketHandler (const SocketHandler< ClientType > & other) delete noexcept
Deleted copy assignment and copy constructor.
SocketHandler() [3/3]
template<typename ClientType > doip_client::sockets::SocketHandler< ClientType >::SocketHandler (SocketHandler< ClientType > && other) default noexcept
Move assignment and Move constructor.
~SocketHandler()
template<typename ClientType > doip_client::sockets::SocketHandler< ClientType >::~SocketHandler () default
Destruct an instance of TcpSocketHandler.
Member Function Documentation
ConnectToHost()
template<typename ClientType > core_type::Result<void> doip_client::sockets::SocketHandler< ClientType >::ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num) inline
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
Empty void on success, otherwise error is returned
Definition at line 101 of file socket_handler.h.
{
     return client_.ConnectToHost(host_ip_address, host_port_num);
   }
References doip_client::sockets::SocketHandler< ClientType >::client_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::ConnectToHost().
DeInitialize()
template<typename ClientType > void doip_client::sockets::SocketHandler< ClientType >::DeInitialize () inline noexcept
Function to stop the socket handler.
Definition at line 83 of file socket_handler.h.
 { client_.DeInitialize(); }
References doip_client::sockets::SocketHandler< ClientType >::client_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Stop(), and doip_client::channel::udp_channel::DoipUdpChannel::Stop().
DisconnectFromHost()
template<typename ClientType > core_type::Result<void> doip_client::sockets::SocketHandler< ClientType >::DisconnectFromHost () inline
Function to disconnect from remote host if already connected.
Returns
Empty void on success, otherwise error is returned
Definition at line 110 of file socket_handler.h.
 { return client_.DisconnectFromHost(); }
References doip_client::sockets::SocketHandler< ClientType >::client_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::DisconnectFromHost().
Initialize()
template<typename ClientType > void doip_client::sockets::SocketHandler< ClientType >::Initialize () inline noexcept
Function to start the socket handler.
Definition at line 78 of file socket_handler.h.
 { client_.Initialize(); }
References doip_client::sockets::SocketHandler< ClientType >::client_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Start(), and doip_client::channel::udp_channel::DoipUdpChannel::Start().
IsConnectedToHost()
template<typename ClientType > auto doip_client::sockets::SocketHandler< ClientType >::IsConnectedToHost () const -> bool inline noexcept
Function to get the connection status.
Returns
True if connected, False otherwise
Definition at line 116 of file socket_handler.h.
 { return client_.IsConnectedToHost(); }
References doip_client::sockets::SocketHandler< ClientType >::client_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::IsConnectedToHost().
operator=() [1/2]
template<typename ClientType > SocketHandler& doip_client::sockets::SocketHandler< ClientType >::operator= (const SocketHandler< ClientType > & other) delete noexcept
operator=() [2/2]
template<typename ClientType > SocketHandler& doip_client::sockets::SocketHandler< ClientType >::operator= (SocketHandler< ClientType > && other) default noexcept
SetReadHandler()
template<typename ClientType > void doip_client::sockets::SocketHandler< ClientType >::SetReadHandler (HandlerRead read_handler) inline
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 91 of file socket_handler.h.
 { client_.SetReadHandler(std::move(read_handler)); }
References doip_client::sockets::SocketHandler< ClientType >::client_.
Referenced by doip_client::channel::tcp_channel::DoipTcpChannel::Start(), and doip_client::channel::udp_channel::DoipUdpChannel::Start().
Transmit()
template<typename ClientType > core_type::Result<void> doip_client::sockets::SocketHandler< ClientType >::Transmit (MessageConstPtr message) inline
Function to transmit the provided message.
Parameters
[in] message The message to be sent
Returns
Empty void on success, otherwise error is returned
Definition at line 124 of file socket_handler.h.
{
     return client_.Transmit(std::move(message));
   }
References doip_client::sockets::SocketHandler< ClientType >::client_.
Member Data Documentation
client_
template<typename ClientType > Client doip_client::sockets::SocketHandler< ClientType >::client_ private
Store the client object.
Definition at line 132 of file socket_handler.h.
Referenced by doip_client::sockets::SocketHandler< ClientType >::ConnectToHost(), doip_client::sockets::SocketHandler< ClientType >::DeInitialize(), doip_client::sockets::SocketHandler< ClientType >::DisconnectFromHost(), doip_client::sockets::SocketHandler< ClientType >::Initialize(), doip_client::sockets::SocketHandler< ClientType >::IsConnectedToHost(), doip_client::sockets::SocketHandler< ClientType >::SetReadHandler(), and doip_client::sockets::SocketHandler< ClientType >::Transmit().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/sockets/socket_handler.h