Diag-Client-Lib: core_type::Result< void, E > Class Template Reference
core_type::Result< void, E > Class Template Reference final
Specialization of class Result for "void" values.
#include <result.h>
Classes
struct empty_value
An empty value for handling void type in value type.
Public Types
using value_type = void
Type alias for the type T of values, always "void" for this specialization.
using error_type = E
Type alias for the type E of errors.
Public Member Functions
constexpr Result () noexcept
Construct a new Result with a "void" value.
constexpr Result (const E &e) noexcept
Construct a new Result from the specified error (given as lvalue)
constexpr Result (E &&e) noexcept
Construct a new Result from the specified error (given as rvalue)
Result (const Result &other)=default
Copy-construct a new Result from another instance.
Result & operator= (const Result &other)=default
Copy-assign another Result to this instance.
Result (Result &&other) noexcept(std::is_nothrow_move_constructible< E >::value)=default
Move-construct a new Result from another instance.
Result & operator= (Result &&other) noexcept(std::is_nothrow_move_constructible< E >::value &&std::is_nothrow_move_assignable< E >::value)=default
Move-assign another Result to this instance.
~Result () noexcept
Destruct an instance of Result.
void EmplaceValue () noexcept
Put a new value into this instance, constructed in-place from the given arguments.
template<typename... Args>
void EmplaceError (Args &&...args) noexcept
Put a new error into this instance, constructed in-place from the given arguments.
bool HasValue () const noexcept
Check whether *this contains a value.
operator bool () const noexcept
Check whether *this contains a value.
const E & Error () const &noexcept
Access the contained error.
E && Error () &&noexcept
Access the contained error.
std::optional< E > Err () const &noexcept
Return the contained error as an Optional.
std::optional< E > Err () &&noexcept
Return the contained error as an Optional.
template<typename F , typename E2 = std::invoke_result_t<F, E>>
Result< void, E2 > MapError (F &&fn)
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
template<typename F , typename E2 = std::invoke_result_t<F, E>>
Result< void, E2 > CheckError (F &&fn)
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
template<typename F >
Result AndThen (F &&fn) &&noexcept
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
template<typename F >
Result OrElse (F &&fn) &&noexcept
Returns the result itself if it contains a value; otherwise, returns the result of the given function on the error value.
template<typename G >
E ErrorOr (G &&defaultError) const &noexcept
Return the contained error or the given default error.
template<typename G >
E ErrorOr (G &&defaultError) &&noexcept
Return the contained error or the given default error.
template<typename F >
void Resolve (F &&f) const
Do nothing or call a function.
Static Public Member Functions
static Result FromValue () noexcept
Build a new Result with "void" as value.
static Result FromError (const E &e) noexcept
Build a new Result from the specified error (given as lvalue)
static Result FromError (E &&e) noexcept
Build a new Result from the specified error (given as rvalue)
template<typename... Args>
static Result FromError (Args &&...args) noexcept
Build a new Result from an error that is constructed in-place from the given arguments.
Private Attributes
Result< empty_value, E > storage_
Storage to contain an empty value or error of type E.
Detailed Description
template<typename E>
class core_type::Result< void, E >
Specialization of class Result for "void" values.
This class is implemented based on API specification of ara::core::Result from Adaptive Platform Core AUTOSAR AP R21-11
Template Parameters
E The type of error
Definition at line 456 of file result.h.
Member Typedef Documentation
error_type
template<typename E > using core_type::Result< void, E >::error_type = E
Type alias for the type E of errors.
Definition at line 466 of file result.h.
value_type
template<typename E > using core_type::Result< void, E >::value_type = void
Type alias for the type T of values, always "void" for this specialization.
Definition at line 461 of file result.h.
Constructor & Destructor Documentation
Result() [1/5]
template<typename E > constexpr core_type::Result< void, E >::Result () inline explicit constexpr noexcept
Construct a new Result with a "void" value.
Definition at line 513 of file result.h.
 : storage_{empty_value{}} {}
Result() [2/5]
template<typename E > constexpr core_type::Result< void, E >::Result (const E & e) inline explicit constexpr noexcept
Construct a new Result from the specified error (given as lvalue)
Parameters
[in] e The error to put into the Result
Definition at line 520 of file result.h.
 : storage_{e} {}
Result() [3/5]
template<typename E > constexpr core_type::Result< void, E >::Result (E && e) inline explicit constexpr noexcept
Construct a new Result from the specified error (given as rvalue)
Parameters
[in] e The error to put into the Result
Definition at line 527 of file result.h.
 : storage_{std::move(e)} {}
Result() [4/5]
template<typename E > core_type::Result< void, E >::Result (const Result< void, E > & other) default
Copy-construct a new Result from another instance.
Parameters
[in] other The other instance
Result() [5/5]
template<typename E > core_type::Result< void, E >::Result (Result< void, E > && other) const default noexcept
Move-construct a new Result from another instance.
Parameters
[in] other The other instance
~Result()
template<typename E > core_type::Result< void, E >::~Result () inline noexcept
Destruct an instance of Result.
Definition at line 566 of file result.h.
 { static_assert(std::is_trivially_destructible<E>::value); }
Member Function Documentation
AndThen()
template<typename E > template<typename F > Result core_type::Result< void, E >::AndThen (F && fn) && inline noexcept
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
Template Parameters
F Functor type
Parameters
[in] fn Callable function
Returns
Result An Result
Definition at line 678 of file result.h.
{
     if (HasValue()) { fn(); }
     return Result{std::move(*this)};
   }
References core_type::Result< T, E >::HasValue().
CheckError()
template<typename E > template<typename F , typename E2 = std::invoke_result_t<F, E>> Result<void, E2> core_type::Result< void, E >::CheckError (F && fn) inline
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
Template Parameters
F Functor type
Parameters
[in] fn Callable function
Returns
Result An Result
Definition at line 663 of file result.h.
{
     return HasValue() ? Result<void, E2>{} : Result<void, E2>{fn(Error())};
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
EmplaceError()
template<typename E > template<typename... Args> void core_type::Result< void, E >::EmplaceError (Args &&... args) inline noexcept
Put a new error into this instance, constructed in-place from the given arguments.
Template Parameters
Args The types of arguments given to this function
Parameters
[in] args The arguments used for constructing the error
Definition at line 581 of file result.h.
{
     storage_.EmplaceError(std::forward<Args>(args)...);
   }
References core_type::Result< T, E >::storage_.
EmplaceValue()
template<typename E > void core_type::Result< void, E >::EmplaceValue () inline noexcept
Put a new value into this instance, constructed in-place from the given arguments.
Definition at line 571 of file result.h.
 { storage_.EmplaceValue(empty_value{}); }
References core_type::Result< T, E >::storage_.
Err() [1/2]
template<typename E > std::optional<E> core_type::Result< void, E >::Err () && inline noexcept
Return the contained error as an Optional.
Returns
std::optional<E> An Optional with the error, if present
Definition at line 631 of file result.h.
{
     std::optional<E> opt_err{};
     if (!HasValue()) { opt_err.emplace(std::move(Error())); }
     return opt_err;
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
Err() [2/2]
template<typename E > std::optional<E> core_type::Result< void, E >::Err () const & inline noexcept
Return the contained error as an Optional.
Returns
std::optional<E> An Optional with the error, if present
Definition at line 620 of file result.h.
{
     std::optional<E> opt_err{};
     if (!HasValue()) { opt_err.emplace(Error()); }
     return opt_err;
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
Error() [1/2]
template<typename E > E&& core_type::Result< void, E >::Error () && inline noexcept
Access the contained error.
This functions behavior is undefined if *this does not contain an error
Returns
E && An rvalue reference to the contained error
Definition at line 613 of file result.h.
 { return std::move(storage_.Error()); }
References core_type::Result< T, E >::storage_.
Error() [2/2]
template<typename E > const E& core_type::Result< void, E >::Error () const & inline noexcept
Access the contained error.
This functions behavior is undefined if *this does not contain an error
Returns
const E & A const reference to the contained error
Definition at line 605 of file result.h.
 { return storage_.Error(); }
References core_type::Result< T, E >::storage_.
ErrorOr() [1/2]
template<typename E > template<typename G > E core_type::Result< void, E >::ErrorOr (G && defaultError) && inline noexcept
Return the contained error or the given default error.
If *this contains an error, it is returned. Otherwise, the specified default error is returned, static_castd to E
Template Parameters
G The type of defaultError
Parameters
[in] defaultError The error to use if *this does not contain an error
Returns
E The error
Definition at line 724 of file result.h.
{
     return !HasValue() ? Result{std::move(*this)} : static_cast<E>(defaultError);
   }
References core_type::Result< T, E >::HasValue().
ErrorOr() [2/2]
template<typename E > template<typename G > E core_type::Result< void, E >::ErrorOr (G && defaultError) const & inline noexcept
Return the contained error or the given default error.
If *this contains an error, it is returned. Otherwise, the specified default error is returned, static_castd to E
Template Parameters
G The type of defaultError
Parameters
[in] defaultError The error to use if *this does not contain an error
Returns
E The error
Definition at line 709 of file result.h.
{
     return !HasValue() ? Result{*this} : static_cast<E>(defaultError);
   }
References core_type::Result< T, E >::HasValue().
FromError() [1/3]
template<typename E > template<typename... Args> static Result core_type::Result< void, E >::FromError (Args &&... args) inline static noexcept
Build a new Result from an error that is constructed in-place from the given arguments.
This function shall not participate in overload resolution unless: std::is_const Args&&...>::value is true, and the first type of the expanded parameter pack first type of the expanded parameter pack is not a specialization of Result
Template Parameters
Args The types of arguments given to this function
Parameters
[in] args The arguments used for constructing the error
Returns
Result A Result that contains an error
Definition at line 506 of file result.h.
{
     return Result{std::forward<Args>(args)...};
   }
FromError() [2/3]
template<typename E > static Result core_type::Result< void, E >::FromError (const E & e) inline static noexcept
Build a new Result from the specified error (given as lvalue)
Parameters
[in] e The error to put into the Result
Returns
Result A Result that contains the error e
Definition at line 482 of file result.h.
 { return Result{e}; }
FromError() [3/3]
template<typename E > static Result core_type::Result< void, E >::FromError (E && e) inline static noexcept
Build a new Result from the specified error (given as rvalue)
Parameters
[in] e The error to put into the Result
Returns
Result A Result that contains the error e
Definition at line 491 of file result.h.
 { return Result{std::move(e)}; }
FromValue()
template<typename E > static Result core_type::Result< void, E >::FromValue () inline static noexcept
Build a new Result with "void" as value.
Parameters
[in] t The value to put into the Result
Definition at line 473 of file result.h.
 { return Result{}; }
HasValue()
template<typename E > bool core_type::Result< void, E >::HasValue () const inline noexcept
Check whether *this contains a value.
Returns
bool True if *this contains a value, false otherwise
Definition at line 590 of file result.h.
 { return storage_.HasValue(); }
References core_type::Result< T, E >::storage_.
MapError()
template<typename E > template<typename F , typename E2 = std::invoke_result_t<F, E>> Result<void, E2> core_type::Result< void, E >::MapError (F && fn) inline
Returns the result of the given function on the contained value if it exists; otherwise, returns the result itself.
Template Parameters
F Functor type
Parameters
[in] fn Callable function
Returns
Result An Result
Definition at line 648 of file result.h.
{
     return HasValue() ? Result<void, E2>{} : Result<void, E2>{fn(Error())};
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
operator bool()
template<typename E > core_type::Result< void, E >::operator bool () const inline explicit noexcept
Check whether *this contains a value.
Returns
bool True if *this contains a value, false otherwise
Definition at line 597 of file result.h.
 { return HasValue(); }
References core_type::Result< T, E >::HasValue().
operator=() [1/2]
template<typename E > Result& core_type::Result< void, E >::operator= (const Result< void, E > & other) default
Copy-assign another Result to this instance.
Parameters
[in] other The other instance
Returns
Result & *this, containing the contents of other
operator=() [2/2]
template<typename E > Result& core_type::Result< void, E >::operator= (Result< void, E > && other) const && default noexcept
Move-assign another Result to this instance.
Parameters
[in] other The other instance
Returns
Result & *this, containing the contents of other
OrElse()
template<typename E > template<typename F > Result core_type::Result< void, E >::OrElse (F && fn) && inline noexcept
Returns the result itself if it contains a value; otherwise, returns the result of the given function on the error value.
Template Parameters
F Functor type
Parameters
[in] fn Callable function
Returns
Result An Result
Definition at line 694 of file result.h.
{
     return HasValue() ? Result{std::move(*this)} : Result{fn(Error())};
   }
References core_type::Result< T, E >::Error(), and core_type::Result< T, E >::HasValue().
Resolve()
template<typename E > template<typename F > void core_type::Result< void, E >::Resolve (F && f) const inline
Do nothing or call a function.
If *this contains a value, this function does nothing. Otherwise, the specified callable is invoked. The Callable is expected to be compatible to this interface: void f(const E&);
Template Parameters
F The type of the Callable f
Parameters
[in] f The Callable
Returns
T The value
Definition at line 740 of file result.h.
{
     f(Error());
   }
References core_type::Result< T, E >::Error().
Member Data Documentation
storage_
template<typename E > Result<empty_value, E> core_type::Result< void, E >::storage_ private
Storage to contain an empty value or error of type E.
Definition at line 753 of file result.h.
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/platform-core/core/include/result.h