Diag-Client-Lib: doip_client::logger::DoipClientLogger Class Reference
doip_client::logger::DoipClientLogger Class Reference
#include <logger.h>
Public Member Functions
auto GetLogger () noexcept -> Logger &
Static Public Member Functions
static auto GetDiagClientLogger () noexcept -> DoipClientLogger &
Private Member Functions
DoipClientLogger ()=default
Private Attributes
Logger logger_ {"doip"}
Detailed Description
Definition at line 18 of file logger.h.
Constructor & Destructor Documentation
DoipClientLogger()
doip_client::logger::DoipClientLogger::DoipClientLogger () private default
Member Function Documentation
GetDiagClientLogger()
static auto doip_client::logger::DoipClientLogger::GetDiagClientLogger () -> DoipClientLogger& inline static noexcept
Definition at line 20 of file logger.h.
{
     static DoipClientLogger diag_client_logger_;
     return diag_client_logger_;
   }
Referenced by doip_client::sockets::TcpSocketHandler::ConnectToHost(), doip_client::channel::tcp_channel::DoipTcpChannel::ConnectToHost(), doip_client::transport_protocol_handler::DoipTransportProtocolHandler::CreateTcpConnection(), doip_client::transport_protocol_handler::DoipTransportProtocolHandler::CreateUdpConnection(), doip_client::sockets::TcpSocketHandler::DisconnectFromHost(), doip_client::channel::tcp_channel::DiagnosticMessageHandler::HandleDiagnosticRequest(), doip_client::channel::tcp_channel::RoutingActivationHandler::HandleRoutingActivationRequest(), doip_client::channel::tcp_channel::DiagnosticMessageHandler::ProcessDoIPDiagnosticAckMessageResponse(), doip_client::channel::tcp_channel::DiagnosticMessageHandler::ProcessDoIPDiagnosticMessageResponse(), doip_client::channel::tcp_channel::RoutingActivationHandler::ProcessDoIPRoutingActivationResponse(), doip_client::channel::udp_channel::VehicleDiscoveryHandler::ProcessVehicleAnnouncementResponse(), doip_client::sockets::TcpSocketHandler::Transmit(), and doip_client::channel::tcp_channel::DoipTcpChannel::Transmit().
GetLogger()
auto doip_client::logger::DoipClientLogger::GetLogger () -> Logger& inline noexcept
Definition at line 25 of file logger.h.
 { return logger_; }
References logger_.
Member Data Documentation
logger_
Logger doip_client::logger::DoipClientLogger::logger_ {"doip"} private
Definition at line 31 of file logger.h.
Referenced by GetLogger().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/common/logger.h