Diag-Client-Lib: utility::logger::Logger Class Reference
utility::logger::Logger Class Reference final
Logger class that is used to log Dlt messages from the component.
#include <logger.h>
Public Member Functions
template<typename Func >
auto LogFatal (const std::string_view file_name, int line_no, const std::string_view func_name, Func &&func) noexcept -> void
Log fatal message.
template<typename Func >
auto LogFatalAndTerminate (const std::string_view file_name, int line_no, const std::string_view func_name, Func &&func) noexcept -> void
Log fatal message and abort.
template<typename Func >
auto LogError (const std::string_view file_name, int line_no, const std::string_view func_name, Func &&func) noexcept -> void
Log error message.
template<typename Func >
auto LogWarn (const std::string_view file_name, int line_no, const std::string_view func_name, Func &&func) noexcept -> void
Log warning message.
template<typename Func >
auto LogInfo (const std::string_view file_name, int line_no, const std::string_view func_name, Func &&func) noexcept -> void
Log info message.
template<typename Func >
auto LogDebug (const std::string_view file_name, int line_no, const std::string_view func_name, Func &&func) noexcept -> void
Log debug message.
template<typename Func >
auto LogVerbose (const std::string_view file_name, int line_no, const std::string_view func_name, Func &&func) noexcept -> void
Log verbose message.
Logger (std::string_view context_id)
Construct an instance of Logger.
Logger (std::string_view app_id, std::string_view context_id)
Construct an instance of Logger.
~Logger ()
Destruct an instance of Logger.
Private Member Functions
template<typename Func >
auto CreateLoggingMessage (const std::string_view file_name, const std::string_view, int line_no, Func &&func) noexcept -> std::stringstream
Function to create the final logging message.
template<typename Func >
void LogMessageToStdOutput (const std::string_view file_name, const std::string_view func_name, int line_no, Func &&func)
Function to send the messages to dlt infrastructure.
Private Attributes
std::string contxt_
std::string app_id_
std::string context_id_
bool registration_with_app_id_
Detailed Description
Logger class that is used to log Dlt messages from the component.
This class uses COVESA DLT infrastructure to send message to DLT. Also the class does not log dlt message if "ENABLE_DLT_LOGGER" cmake flag is set to OFF
Definition at line 33 of file logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
utility::logger::Logger::Logger (std::string_view context_id) explicit
Construct an instance of Logger.
Parameters
[in] context_id The context id of the user
Definition at line 14 of file logger.cpp.
     : contxt_{},
       app_id_{},
       context_id_{context_id},
       registration_with_app_id_{false} {
 #ifdef ENABLE_DLT_LOGGER
   DLT_REGISTER_CONTEXT(contxt_, context_id_.c_str(), "Application Context");
 #else
   UNUSED_PARAM(registration_with_app_id_);
 #endif
 }
References context_id_, contxt_, registration_with_app_id_, and UNUSED_PARAM.
Logger() [2/2]
utility::logger::Logger::Logger (std::string_view app_id, std::string_view context_id)
Construct an instance of Logger.
Parameters
[in] app_id The application id of the user
[in] context_id The context id of the user
Definition at line 26 of file logger.cpp.
     : contxt_{},
       app_id_{app_id},
       context_id_{context_id},
       registration_with_app_id_{true} {
 #ifdef ENABLE_DLT_LOGGER
   DLT_REGISTER_APP(app_id_.c_str(), "Application Id");
   DLT_REGISTER_CONTEXT(contxt_, context_id_.c_str(), "Application Context");
 #else
   UNUSED_PARAM(registration_with_app_id_);
 #endif
 }
References app_id_, context_id_, contxt_, registration_with_app_id_, and UNUSED_PARAM.
~Logger()
utility::logger::Logger::~Logger ()
Destruct an instance of Logger.
Definition at line 39 of file logger.cpp.
                 {
 #ifdef ENABLE_DLT_LOGGER
   DLT_UNREGISTER_CONTEXT(contxt_);
   if (registration_with_app_id_) { DLT_UNREGISTER_APP(); }
 #endif
 }
References contxt_, and registration_with_app_id_.
Member Function Documentation
CreateLoggingMessage()
template<typename Func > auto utility::logger::Logger::CreateLoggingMessage (const std::string_view file_name, const std::string_view , int line_no, Func && func) -> std::stringstream inline private noexcept
Function to create the final logging message.
Template Parameters
Func The functor type
Parameters
[in] file_name The file name
[in] func_name The function name
[in] line_no The line number
[in] func The functor which gets invoked
Definition at line 234 of file logger.h.
{
     std::stringstream msg{};
     func(msg);
     msg << " [" << file_name << ":" << line_no << "]";
     return msg;
   }
LogDebug()
template<typename Func > auto utility::logger::Logger::LogDebug (const std::string_view file_name, int line_no, const std::string_view func_name, Func && func) -> void inline noexcept
Log debug message.
Template Parameters
Func The functor type invoked on log level set to debug
Parameters
[in] file_name The file name
[in] line_no The line number
[in] func_name The function name
[in] func The functor which gets invoked on log level set to debug
Definition at line 165 of file logger.h.
{
 #ifdef ENABLE_DLT_LOGGER
     LogDltMessage(DLT_LOG_DEBUG, file_name, func_name, line_no, std::forward<Func>(func));
 #else
     LogMessageToStdOutput(file_name, func_name, line_no, std::forward<Func>(func));
 #endif
   }
References LogMessageToStdOutput().
LogError()
template<typename Func > auto utility::logger::Logger::LogError (const std::string_view file_name, int line_no, const std::string_view func_name, Func && func) -> void inline noexcept
Log error message.
Template Parameters
Func The functor type invoked on log level set to error
Parameters
[in] file_name The file name
[in] line_no The line number
[in] func_name The function name
[in] func The functor which gets invoked on log level set to error
Definition at line 96 of file logger.h.
{
 #ifdef ENABLE_DLT_LOGGER
     LogDltMessage(DLT_LOG_ERROR, file_name, func_name, line_no, std::forward<Func>(func));
 #else
     LogMessageToStdOutput(file_name, func_name, line_no, std::forward<Func>(func));
 #endif
   }
References LogMessageToStdOutput().
LogFatal()
template<typename Func > auto utility::logger::Logger::LogFatal (const std::string_view file_name, int line_no, const std::string_view func_name, Func && func) -> void inline noexcept
Log fatal message.
Template Parameters
Func The functor type invoked on log level set to fatal
Parameters
[in] file_name The file name
[in] line_no The line number
[in] func_name The function name
[in] func The functor which gets invoked on log level set to fatal
Definition at line 49 of file logger.h.
{
 #ifdef ENABLE_DLT_LOGGER
     LogDltMessage(DLT_LOG_FATAL, file_name, func_name, line_no, std::forward<Func>(func));
 #else
     LogMessageToStdOutput(file_name, func_name, line_no, std::forward<Func>(func));
 #endif
   }
References LogMessageToStdOutput().
LogFatalAndTerminate()
template<typename Func > auto utility::logger::Logger::LogFatalAndTerminate (const std::string_view file_name, int line_no, const std::string_view func_name, Func && func) -> void inline noexcept
Log fatal message and abort.
Template Parameters
Func The functor type invoked on log level set to fatal
Parameters
[in] file_name The file name
[in] line_no The line number
[in] func_name The function name
[in] func The functor which gets invoked on log level set to fatal
Definition at line 72 of file logger.h.
{
 #ifdef ENABLE_DLT_LOGGER
     LogDltMessage(DLT_LOG_FATAL, file_name, func_name, line_no, std::forward<Func>(func));
 #else
     LogMessageToStdOutput(file_name, func_name, line_no, std::forward<Func>(func));
 #endif
     std::abort();  // abort in case of fatal issue
   }
References LogMessageToStdOutput().
LogInfo()
template<typename Func > auto utility::logger::Logger::LogInfo (const std::string_view file_name, int line_no, const std::string_view func_name, Func && func) -> void inline noexcept
Log info message.
Template Parameters
Func The functor type invoked on log level set to info
Parameters
[in] file_name The file name
[in] line_no The line number
[in] func_name The function name
[in] func The functor which gets invoked on log level set to info
Definition at line 142 of file logger.h.
{
 #ifdef ENABLE_DLT_LOGGER
     LogDltMessage(DLT_LOG_INFO, file_name, func_name, line_no, std::forward<Func>(func));
 #else
     LogMessageToStdOutput(file_name, func_name, line_no, std::forward<Func>(func));
 #endif
   }
References LogMessageToStdOutput().
LogMessageToStdOutput()
template<typename Func > void utility::logger::Logger::LogMessageToStdOutput (const std::string_view file_name, const std::string_view func_name, int line_no, Func && func) inline private
Function to send the messages to dlt infrastructure.
Template Parameters
log_level The log level
Parameters
[in] file_name The file name
[in] func_name The function name
[in] line_no The line number
[in] func The functor which gets invoked
Function to send the messages to standard output
Template Parameters
Func The logging functor to be executed
Parameters
[in] file_name The file name
[in] func_name The function name
[in] line_no The line number
[in] func The functor which gets invoked
Definition at line 282 of file logger.h.
{
     std::cout << CreateLoggingMessage(file_name, func_name, line_no, std::forward<Func>(func)).str()
               << std::endl;
   }
Referenced by LogDebug(), LogError(), LogFatal(), LogFatalAndTerminate(), LogInfo(), LogVerbose(), and LogWarn().
LogVerbose()
template<typename Func > auto utility::logger::Logger::LogVerbose (const std::string_view file_name, int line_no, const std::string_view func_name, Func && func) -> void inline noexcept
Log verbose message.
Template Parameters
Func The functor type invoked on log level set to verbose
Parameters
[in] file_name The file name
[in] line_no The line number
[in] func_name The function name
[in] func The functor which gets invoked on log level set to verbose
Definition at line 188 of file logger.h.
{
 #ifdef ENABLE_DLT_LOGGER
     LogDltMessage(DLT_LOG_VERBOSE, file_name, func_name, line_no, std::forward<Func>(func));
 #else
     LogMessageToStdOutput(file_name, func_name, line_no, std::forward<Func>(func));
 #endif
   }
References LogMessageToStdOutput().
LogWarn()
template<typename Func > auto utility::logger::Logger::LogWarn (const std::string_view file_name, int line_no, const std::string_view func_name, Func && func) -> void inline noexcept
Log warning message.
Template Parameters
Func The functor type invoked on log level set to warning
Parameters
[in] file_name The file name
[in] line_no The line number
[in] func_name The function name
[in] func The functor which gets invoked on log level set to warning
Definition at line 119 of file logger.h.
{
 #ifdef ENABLE_DLT_LOGGER
     LogDltMessage(DLT_LOG_WARN, file_name, func_name, line_no, std::forward<Func>(func));
 #else
     LogMessageToStdOutput(file_name, func_name, line_no, std::forward<Func>(func));
 #endif
   }
References LogMessageToStdOutput().
Member Data Documentation
app_id_
std::string utility::logger::Logger::app_id_ private
Definition at line 295 of file logger.h.
Referenced by Logger().
context_id_
std::string utility::logger::Logger::context_id_ private
Definition at line 298 of file logger.h.
Referenced by Logger().
contxt_
std::string utility::logger::Logger::contxt_ private
Definition at line 292 of file logger.h.
Referenced by Logger(), and ~Logger().
registration_with_app_id_
bool utility::logger::Logger::registration_with_app_id_ private
Definition at line 301 of file logger.h.
Referenced by Logger(), and ~Logger().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/utility-support/utility/logger.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/utility-support/utility/logger.cpp