Diag-Client-Lib: boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket > Class Template Reference
boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket > Class Template Reference final
Client connection class used to handle transmission and reception of tcp message from socket.
#include <tcp_connection.h>
Public Types
using TcpMessage = typename Socket::TcpMessage
Type alias for Tcp message.
using TcpMessagePtr = typename Socket::TcpMessagePtr
Type alias for Tcp message pointer.
using TcpMessageConstPtr = typename Socket::TcpMessageConstPtr
Type alias for Tcp message const pointer.
using HandlerRead = std::function< void(TcpMessagePtr)>
Tcp function template used for reception.
Public Member Functions
TcpConnection (std::string_view connection_name, Socket socket) noexcept
Constructs an instance of TcpConnection.
TcpConnection (const TcpConnection &other) noexcept=delete
Deleted copy assignment and copy constructor.
TcpConnection & operator= (const TcpConnection &other) &noexcept=delete
TcpConnection (TcpConnection &&other) noexcept=default
Move assignment and move constructor.
TcpConnection & operator= (TcpConnection &&other) &noexcept=default
~TcpConnection () noexcept=default
Destruct an instance of TcpConnection.
void SetReadHandler (HandlerRead read_handler)
Function to set the read handler that is invoked when message is received.
void Initialize () noexcept
Initialize the client.
void DeInitialize () noexcept
De-initialize the client.
auto ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num) noexcept -> bool
Function to connect to remote ip address and port number.
void DisconnectFromHost () noexcept
Function to Disconnect from host.
core_type::Result< void > Transmit (TcpMessageConstPtr message) noexcept
Function to trigger transmission.
Private Member Functions
auto ReadMessage () -> bool
Function to send the received message to stored handler.
Private Attributes
Socket socket_
Store socket used for reading and writing tcp message.
HandlerRead handler_read_
Store the handler.
std::atomic_bool exit_request_
Flag to terminate the thread.
std::atomic_bool running_
Flag to start the thread.
std::condition_variable cond_var_
Conditional variable to block the thread.
std::string connection_name_
Store the connection name.
utility::thread::Thread thread_
Store the thread.
std::mutex mutex_
mutex to lock critical section
Detailed Description
template<typename Socket>
class boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >
Client connection class used to handle transmission and reception of tcp message from socket.
Template Parameters
Socket The type of socket to read and write from/to
Definition at line 49 of file tcp_connection.h.
Member Typedef Documentation
HandlerRead
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::HandlerRead = std::function<void(TcpMessagePtr)>
Tcp function template used for reception.
Definition at line 69 of file tcp_connection.h.
TcpMessage
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::TcpMessage = typename Socket::TcpMessage
Type alias for Tcp message.
Definition at line 54 of file tcp_connection.h.
TcpMessageConstPtr
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::TcpMessageConstPtr = typename Socket::TcpMessageConstPtr
Type alias for Tcp message const pointer.
Definition at line 64 of file tcp_connection.h.
TcpMessagePtr
template<typename Socket > using boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::TcpMessagePtr = typename Socket::TcpMessagePtr
Type alias for Tcp message pointer.
Definition at line 59 of file tcp_connection.h.
Constructor & Destructor Documentation
TcpConnection() [1/3]
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::TcpConnection (std::string_view connection_name, Socket socket) inline explicit noexcept
Constructs an instance of TcpConnection.
Parameters
[in] socket The socket used for read and writing messages
Definition at line 77 of file tcp_connection.h.
       : socket_{std::move(socket)},
         handler_read_{},
         exit_request_{false},
         running_{false},
         cond_var_{},
         connection_name_{connection_name},
         thread_{},
         mutex_{} {}
TcpConnection() [2/3]
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::TcpConnection (const TcpConnection< ConnectionType::kClient, Socket > & other) delete noexcept
Deleted copy assignment and copy constructor.
TcpConnection() [3/3]
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::TcpConnection (TcpConnection< ConnectionType::kClient, Socket > && other) default noexcept
Move assignment and move constructor.
~TcpConnection()
template<typename Socket > boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::~TcpConnection () default noexcept
Destruct an instance of TcpConnection.
Member Function Documentation
ConnectToHost()
template<typename Socket > auto boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num) -> bool inline noexcept
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
Empty result on success otherwise error code
Definition at line 157 of file tcp_connection.h.
               {
     return socket_.Connect(host_ip_address, host_port_num)
         .AndThen([this]() noexcept {
           {  // start reading
             std::lock_guard<std::mutex> lock{mutex_};
             running_ = true;
             cond_var_.notify_all();
           }
         })
         .HasValue();
   }
DeInitialize()
template<typename Socket > void boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::DeInitialize () inline noexcept
De-initialize the client.
Definition at line 138 of file tcp_connection.h.
{
     socket_.Close();
     {
       std::unique_lock<std::mutex> lck(mutex_);
       exit_request_ = true;
       running_ = false;
     }
     cond_var_.notify_all();
     thread_.Join();
   }
DisconnectFromHost()
template<typename Socket > void boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::DisconnectFromHost () inline noexcept
Function to Disconnect from host.
Returns
Empty result on success otherwise error code
Definition at line 174 of file tcp_connection.h.
{
     {  // stop reading
       std::lock_guard<std::mutex> lock{mutex_};
       running_ = false;
     }
     socket_.Disconnect();
   }
Initialize()
template<typename Socket > void boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::Initialize () inline noexcept
Initialize the client.
Definition at line 115 of file tcp_connection.h.
{
     // Open socket
     socket_.Open();
     // Start thread to receive messages
     thread_ = utility::thread::Thread{
         connection_name_, [this]() {
           std::unique_lock<std::mutex> lck(mutex_);
           while (!exit_request_) {
             if (!running_) {
               cond_var_.wait(lck, [this]() { return exit_request_ || running_; });
             }
             if (!exit_request_.load() && running_) {
               lck.unlock();
               running_ = ReadMessage();
               lck.lock();
             }
           }
         }};
   }
operator=() [1/2]
template<typename Socket > TcpConnection& boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::operator= (const TcpConnection< ConnectionType::kClient, Socket > & other) & delete noexcept
operator=() [2/2]
template<typename Socket > TcpConnection& boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::operator= (TcpConnection< ConnectionType::kClient, Socket > && other) & default noexcept
ReadMessage()
template<typename Socket > auto boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::ReadMessage () -> bool inline private
Function to send the received message to stored handler.
Returns
True if message is read successfully, otherwise False
Definition at line 242 of file tcp_connection.h.
{
     // Try reading from socket
     return socket_.Read()
         .AndThen([this](TcpMessagePtr tcp_message) {
           if (handler_read_) { handler_read_(std::move(tcp_message)); }
           return core_type::Result<void, typename Socket::SocketError>::FromValue();
         })
         .HasValue();
   }
References core_type::Result< T, E >::FromValue().
SetReadHandler()
template<typename Socket > void boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::SetReadHandler (HandlerRead read_handler) inline
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 110 of file tcp_connection.h.
 { handler_read_ = std::move(read_handler); }
Transmit()
template<typename Socket > core_type::Result<void> boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::Transmit (TcpMessageConstPtr message) inline noexcept
Function to trigger transmission.
Parameters
[in] message The tcp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 188 of file tcp_connection.h.
{
     return socket_.Transmit(std::move(message))
         .AndThen([]() { return core_type::Result<void>::FromValue(); })
         .MapError([](typename Socket::SocketError const &) {
           return error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kSocketError);
         });
   }
References core_type::Result< T, E >::FromValue(), boost_support::error_domain::kSocketError, and boost_support::error_domain::MakeErrorCode().
Member Data Documentation
cond_var_
template<typename Socket > std::condition_variable boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::cond_var_ private
Conditional variable to block the thread.
Definition at line 220 of file tcp_connection.h.
connection_name_
template<typename Socket > std::string boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::connection_name_ private
Store the connection name.
Definition at line 225 of file tcp_connection.h.
exit_request_
template<typename Socket > std::atomic_bool boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::exit_request_ private
Flag to terminate the thread.
Definition at line 210 of file tcp_connection.h.
handler_read_
template<typename Socket > HandlerRead boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::handler_read_ private
Store the handler.
Definition at line 205 of file tcp_connection.h.
mutex_
template<typename Socket > std::mutex boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::mutex_ private
mutex to lock critical section
Definition at line 235 of file tcp_connection.h.
running_
template<typename Socket > std::atomic_bool boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::running_ private
Flag to start the thread.
Definition at line 215 of file tcp_connection.h.
socket_
template<typename Socket > Socket boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::socket_ private
Store socket used for reading and writing tcp message.
Definition at line 200 of file tcp_connection.h.
thread_
template<typename Socket > utility::thread::Thread boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::thread_ private
Store the thread.
Definition at line 230 of file tcp_connection.h.
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/connection/tcp/tcp_connection.h