Diag-Client-Lib: doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl Class Reference
doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl Class Reference
Class implements routing activation handler.
Public Types
using DiagnosticMessageStateContext = utility::state::StateContext< DiagnosticMessageState >
Type alias for state context.
using SyncTimer = utility::sync_timer::SyncTimer< std::chrono::steady_clock >
Type alias for Sync timer.
Public Member Functions
DiagnosticMessageHandlerImpl (sockets::TcpSocketHandler &tcp_socket_handler, DoipTcpChannel &channel)
Constructs an instance of DiagnosticMessageHandlerImpl.
void Start ()
Function to start the handler.
void Stop ()
Function to stop the handler.
void Reset ()
Function to reset the handler.
auto GetStateContext () noexcept -> DiagnosticMessageStateContext &
Function to get the Diagnostic Message State context.
auto GetSocketHandler () noexcept -> sockets::TcpSocketHandler &
Function to get the socket handler.
auto GetDoipChannel () noexcept -> DoipTcpChannel &
Function to get the doip channel.
auto GetSyncTimer () noexcept -> SyncTimer &
Function to get the sync timer.
Private Attributes
sockets::TcpSocketHandler & tcp_socket_handler_
The reference to socket handler.
DoipTcpChannel & channel_
The reference to doip channel.
DiagnosticMessageStateContext state_context_
Stores the diagnostic message states.
SyncTimer sync_timer_
Store the synchronous timer.
Detailed Description
Class implements routing activation handler.
Definition at line 261 of file doip_diagnostic_message_handler.cpp.
Member Typedef Documentation
DiagnosticMessageStateContext
using doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::DiagnosticMessageStateContext = utility::state::StateContext<DiagnosticMessageState>
Type alias for state context.
Definition at line 266 of file doip_diagnostic_message_handler.cpp.
SyncTimer
using doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::SyncTimer = utility::sync_timer::SyncTimer<std::chrono::steady_clock>
Type alias for Sync timer.
Definition at line 271 of file doip_diagnostic_message_handler.cpp.
Constructor & Destructor Documentation
DiagnosticMessageHandlerImpl()
doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::DiagnosticMessageHandlerImpl (sockets::TcpSocketHandler & tcp_socket_handler, DoipTcpChannel & channel) inline
Constructs an instance of DiagnosticMessageHandlerImpl.
Parameters
[in] tcp_socket_handler The reference to socket handler
[in] channel The reference to doip channel
Definition at line 280 of file doip_diagnostic_message_handler.cpp.
       : tcp_socket_handler_{tcp_socket_handler},
         channel_{channel},
         state_context_{},
         sync_timer_{} {
     // create and add state for Diagnostic State
     // kIdle
     state_context_.AddState(DiagnosticMessageState::kIdle, std::make_unique<kIdle>(DiagnosticMessageState::kIdle));
     // kSendDiagnosticReqFailed
     state_context_.AddState(
         DiagnosticMessageState::kSendDiagnosticReqFailed,
         std::make_unique<kSendDiagnosticReqFailed>(DiagnosticMessageState::kSendDiagnosticReqFailed));
     // kWaitForDiagnosticAck
     state_context_.AddState(DiagnosticMessageState::kWaitForDiagnosticAck,
                             std::make_unique<kWaitForDiagnosticAck>(DiagnosticMessageState::kWaitForDiagnosticAck));
     // kDiagnosticPositiveAckRecvd
     state_context_.AddState(
         DiagnosticMessageState::kDiagnosticPositiveAckRecvd,
         std::make_unique<kDiagnosticPositiveAckRecvd>(DiagnosticMessageState::kDiagnosticPositiveAckRecvd));
     // kDiagnosticNegativeAckRecvd
     state_context_.AddState(
         DiagnosticMessageState::kDiagnosticNegativeAckRecvd,
         std::make_unique<kDiagnosticNegativeAckRecvd>(DiagnosticMessageState::kDiagnosticNegativeAckRecvd));
     // kWaitForDiagnosticResponse
     state_context_.AddState(
         DiagnosticMessageState::kWaitForDiagnosticResponse,
         std::make_unique<kWaitForDiagnosticResponse>(DiagnosticMessageState::kWaitForDiagnosticResponse));
     // Transit to idle state
     state_context_.TransitionTo(DiagnosticMessageState::kIdle);
   }
References utility::state::StateContext< EnumState >::AddState(), state_context_, and utility::state::StateContext< EnumState >::TransitionTo().
Member Function Documentation
GetDoipChannel()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::GetDoipChannel () -> DoipTcpChannel & inline noexcept
Function to get the doip channel.
Returns
The reference to channel
Definition at line 347 of file doip_diagnostic_message_handler.cpp.
 { return channel_; }
References channel_.
GetSocketHandler()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::GetSocketHandler () -> sockets::TcpSocketHandler & inline noexcept
Function to get the socket handler.
Returns
The reference to socket handler
Definition at line 341 of file doip_diagnostic_message_handler.cpp.
 { return tcp_socket_handler_; }
References tcp_socket_handler_.
GetStateContext()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::GetStateContext () -> DiagnosticMessageStateContext & inline noexcept
Function to get the Diagnostic Message State context.
Returns
The reference to state context
Definition at line 335 of file doip_diagnostic_message_handler.cpp.
 { return state_context_; }
References state_context_.
GetSyncTimer()
auto doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::GetSyncTimer () -> SyncTimer & inline noexcept
Function to get the sync timer.
Returns
The reference to sync timer
Definition at line 353 of file doip_diagnostic_message_handler.cpp.
 { return sync_timer_; }
References sync_timer_.
Reset()
void doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::Reset () inline
Function to reset the handler.
This will reset all the internal handler back to default state
Definition at line 329 of file doip_diagnostic_message_handler.cpp.
 { Stop(); }
References Stop().
Start()
void doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::Start () inline
Function to start the handler.
Definition at line 314 of file doip_diagnostic_message_handler.cpp.
 {}
Stop()
void doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::Stop () inline
Function to stop the handler.
This will reset all the internal handler back to default state
Definition at line 320 of file doip_diagnostic_message_handler.cpp.
               {
     if (sync_timer_.IsTimerActive()) { sync_timer_.CancelWait(); }
     state_context_.TransitionTo(DiagnosticMessageState::kIdle);
   }
References utility::sync_timer::SyncTimer< ClockType >::CancelWait(), utility::sync_timer::SyncTimer< ClockType >::IsTimerActive(), state_context_, sync_timer_, and utility::state::StateContext< EnumState >::TransitionTo().
Referenced by Reset().
Member Data Documentation
channel_
DoipTcpChannel& doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::channel_ private
The reference to doip channel.
Definition at line 364 of file doip_diagnostic_message_handler.cpp.
Referenced by GetDoipChannel().
state_context_
DiagnosticMessageStateContext doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::state_context_ private
Stores the diagnostic message states.
Definition at line 369 of file doip_diagnostic_message_handler.cpp.
Referenced by DiagnosticMessageHandlerImpl(), GetStateContext(), and Stop().
sync_timer_
SyncTimer doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::sync_timer_ private
Store the synchronous timer.
Definition at line 374 of file doip_diagnostic_message_handler.cpp.
Referenced by GetSyncTimer(), and Stop().
tcp_socket_handler_
sockets::TcpSocketHandler& doip_client::channel::tcp_channel::DiagnosticMessageHandler::DiagnosticMessageHandlerImpl::tcp_socket_handler_ private
The reference to socket handler.
Definition at line 359 of file doip_diagnostic_message_handler.cpp.
Referenced by GetSocketHandler().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/tcp_channel/doip_diagnostic_message_handler.cpp