Diag-Client-Lib: diag::client::logger::DiagClientLogger Class Reference
diag::client::logger::DiagClientLogger Class Reference final
Class to create a singleton logger for diag-client.
#include <logger.h>
Public Types
using Logger = utility::logger::Logger
Type alias of logger.
Public Member Functions
auto GetLogger () noexcept -> Logger &
Get the logger instance.
Static Public Member Functions
static auto GetDiagClientLogger () noexcept -> DiagClientLogger &
Get the diag client logger instance.
Private Member Functions
DiagClientLogger ()=default
Construct an instance of DiagClientLogger.
Private Attributes
Logger logger_ {"dcap"}
Store the logger instance with context id.
Detailed Description
Class to create a singleton logger for diag-client.
Definition at line 20 of file logger.h.
Member Typedef Documentation
Logger
using diag::client::logger::DiagClientLogger::Logger = utility::logger::Logger
Type alias of logger.
Definition at line 25 of file logger.h.
Constructor & Destructor Documentation
DiagClientLogger()
diag::client::logger::DiagClientLogger::DiagClientLogger () private default
Construct an instance of DiagClientLogger.
Member Function Documentation
GetDiagClientLogger()
static auto diag::client::logger::DiagClientLogger::GetDiagClientLogger () -> DiagClientLogger& inline static noexcept
Get the diag client logger instance.
Returns
DiagClientLogger The singleton instance
Definition at line 32 of file logger.h.
{
     static DiagClientLogger diag_client_logger_;
     return diag_client_logger_;
   }
Referenced by diag::client::conversation::DmConversation::ConnectToDiagServer(), diag::client::DiagClient::DiagClientImpl::DeInitialize(), diag::client::conversation::DmConversation::DisconnectFromDiagServer(), diag::client::dcm::GetConversationManager(), diag::client::conversation_manager::ConversationManager::GetDiagnosticClientConversation(), diag::client::DiagClient::DiagClientImpl::GetDiagnosticClientConversation(), diag::client::conversation::DmConversation::IndicateMessage(), diag::client::DiagClient::DiagClientImpl::Initialize(), diag::client::dcm::DCMClient::Initialize(), diag::client::dcm::DCMClient::Run(), diag::client::conversation::DmConversation::SendDiagnosticRequest(), diag::client::DiagClient::DiagClientImpl::SendVehicleIdentificationRequest(), diag::client::conversation::VdConversation::SendVehicleIdentificationRequest(), diag::client::conversation_manager::ConversationManager::Shutdown(), diag::client::conversation::DmConversation::Shutdown(), diag::client::conversation::VdConversation::Shutdown(), diag::client::dcm::DCMClient::Shutdown(), diag::client::conversation::DmConversation::Startup(), and diag::client::conversation::VdConversation::Startup().
GetLogger()
auto diag::client::logger::DiagClientLogger::GetLogger () -> Logger& inline noexcept
Get the logger instance.
Returns
Logger The logger instance
Definition at line 42 of file logger.h.
 { return logger_; }
References logger_.
Member Data Documentation
logger_
Logger diag::client::logger::DiagClientLogger::logger_ {"dcap"} private
Store the logger instance with context id.
Definition at line 53 of file logger.h.
Referenced by GetLogger().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/common/logger.h