Diag-Client-Lib: boost_support::socket::tcp::TlsClientSocket Class Reference
boost_support::socket::tcp::TlsClientSocket Class Reference final
Class used to create a tls socket for handling transmission and reception of tcp message from driver.
#include <tls_client_.h>
Public Types
enum class TlsErrorCode : std::uint8_t {
kOpenFailed , kBindingFailed , kConnectFailed , kTlsHandshakeFailed ,
kGenericError
}
TLS error code.
using TcpHandlerRead = std::function< void(message::tcp::TcpMessagePtr)>
Tcp function template used for reception.
Public Member Functions
TlsClientSocket (std::string_view local_ip_address, std::uint16_t local_port_num, TcpHandlerRead tcp_handler_read, std::string_view ca_certification_path)
Constructs an instance of TlsClientSocket.
~TlsClientSocket ()
Destruct an instance of TcpClientSocket.
core_type::Result< void, TlsErrorCode > Open ()
Function to Open the socket.
core_type::Result< void, TlsErrorCode > ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num)
Function to connect to remote ip address and port number.
core_type::Result< void, TlsErrorCode > DisconnectFromHost ()
Function to Disconnect from host.
core_type::Result< void, TlsErrorCode > Transmit (message::tcp::TcpMessageConstPtr tcp_message)
Function to trigger transmission.
core_type::Result< void, TlsErrorCode > Destroy ()
Function to destroy the socket.
Private Types
using Tcp = boost::asio::ip::tcp
Type alias for tcp protocol.
using TcpSocket = Tcp::socket
Type alias for tcp socket.
using TlsStream = boost::asio::ssl::stream< TcpSocket >
Type alias for tls stream wrapping tcp socket.
using TcpIpAddress = boost::asio::ip::address
Type alias for tcp ip address.
using TcpErrorCodeType = boost::system::error_code
Type alias for tcp error codes.
Private Member Functions
TlsStream::lowest_layer_type & GetNativeTcpSocket ()
Function to get the native tcp socket under tls socket.
void HandleMessage ()
Function to handle the reception of tcp message.
Private Attributes
std::string local_ip_address_
Store local ip address.
std::uint16_t local_port_num_
Store local port number.
boost::asio::io_context io_context_
boost io context
boost::asio::ssl::context io_ssl_context_
boost io ssl context
TlsStream tls_socket_
Store ssl socket.
std::atomic_bool exit_request_
Flag to terminate the thread.
std::atomic_bool running_
Flag to start the thread.
std::condition_variable cond_var_
Conditional variable to block the thread.
std::mutex mutex_
mutex to lock critical section
std::thread thread_
The thread itself.
TcpHandlerRead tcp_handler_read_
Store the handler.
Detailed Description
Class used to create a tls socket for handling transmission and reception of tcp message from driver.
Definition at line 27 of file tls_client_.h.
Member Typedef Documentation
Tcp
using boost_support::socket::tcp::TlsClientSocket::Tcp = boost::asio::ip::tcp private
Type alias for tcp protocol.
Definition at line 106 of file tls_client_.h.
TcpErrorCodeType
using boost_support::socket::tcp::TlsClientSocket::TcpErrorCodeType = boost::system::error_code private
Type alias for tcp error codes.
Definition at line 126 of file tls_client_.h.
TcpHandlerRead
using boost_support::socket::tcp::TlsClientSocket::TcpHandlerRead = std::function<void(message::tcp::TcpMessagePtr)>
Tcp function template used for reception.
Definition at line 43 of file tls_client_.h.
TcpIpAddress
using boost_support::socket::tcp::TlsClientSocket::TcpIpAddress = boost::asio::ip::address private
Type alias for tcp ip address.
Definition at line 121 of file tls_client_.h.
TcpSocket
using boost_support::socket::tcp::TlsClientSocket::TcpSocket = Tcp::socket private
Type alias for tcp socket.
Definition at line 111 of file tls_client_.h.
TlsStream
using boost_support::socket::tcp::TlsClientSocket::TlsStream = boost::asio::ssl::stream<TcpSocket> private
Type alias for tls stream wrapping tcp socket.
Definition at line 116 of file tls_client_.h.
Member Enumeration Documentation
TlsErrorCode
enum boost_support::socket::tcp::TlsClientSocket::TlsErrorCode : std::uint8_t strong
TLS error code.
Enumerator
kOpenFailed
kBindingFailed
kConnectFailed
kTlsHandshakeFailed
kGenericError
Definition at line 32 of file tls_client_.h.
                           : std::uint8_t {
     kOpenFailed,
     kBindingFailed,
     kConnectFailed,
     kTlsHandshakeFailed,
     kGenericError
   };
Constructor & Destructor Documentation
TlsClientSocket()
boost_support::socket::tcp::TlsClientSocket::TlsClientSocket (std::string_view local_ip_address, std::uint16_t local_port_num, TcpHandlerRead tcp_handler_read, std::string_view ca_certification_path)
Constructs an instance of TlsClientSocket.
Parameters
[in] local_ip_address The local ip address
[in] local_port_num The local port number
[in] tcp_handler_read The handler to send received data to user
[in] ca_certification_path The path to root ca certificate
Definition at line 51 of file tls_client_.cpp.
     : local_ip_address_{local_ip_address},
       local_port_num_{local_port_num},
       io_context_{},
       io_ssl_context_{boost::asio::ssl::context::tlsv13_client},
       tls_socket_{io_context_, io_ssl_context_},
       exit_request_{false},
       running_{false},
       cond_var_{},
       mutex_{},
       thread_{},
       tcp_handler_read_{std::move(tcp_handler_read)} {
   // Set verification mode
   tls_socket_.set_verify_mode(boost::asio::ssl::verify_peer);
   // Set the verification callback
   tls_socket_.set_verify_callback(
       [](bool pre_verified, boost::asio::ssl::verify_context &ctx) noexcept -> bool {
         X509 *cert = X509_STORE_CTX_get_current_cert(ctx.native_handle());
         int depth = X509_STORE_CTX_get_error_depth(ctx.native_handle());
         fprintf(stdout, "verify_callback (depth=%d)(preverify=%d)\n", depth, pre_verified);
         X509_NAME *iname = cert ? X509_get_issuer_name(cert) : nullptr;
         X509_NAME *sname = cert ? X509_get_subject_name(cert) : nullptr;
         /* Issuer is the authority we trust that warrants nothing useful */
         print_cn_name("Issuer (cn)", iname);
         /* Subject is who the certificate is issued to by the authority  */
         print_cn_name("Subject (cn)", sname);
         return true;
       });
   // Load the root CA certificates
   io_ssl_context_.load_verify_file(std::string{ca_certification_path});
   SSL_set_ciphersuites(tls_socket_.native_handle(),
                        "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_"
                        "CHACHA20_POLY1305_SHA256");
   // Start thread to receive messages
   thread_ = std::thread([this]() {
     std::unique_lock<std::mutex> lck(mutex_);
     while (!exit_request_) {
       if (!running_) {
         cond_var_.wait(lck, [this]() { return exit_request_ || running_; });
       }
       if (!exit_request_.load()) {
         if (running_) {
           lck.unlock();
           HandleMessage();
           lck.lock();
         }
       }
     }
   });
 }
References cond_var_, exit_request_, HandleMessage(), io_ssl_context_, mutex_, boost_support::socket::tcp::anonymous_namespace{tls_client_.cpp}::print_cn_name(), running_, thread_, and tls_socket_.
~TlsClientSocket()
boost_support::socket::tcp::TlsClientSocket::~TlsClientSocket ()
Destruct an instance of TcpClientSocket.
Definition at line 109 of file tls_client_.cpp.
{
   {
     std::unique_lock<std::mutex> lck(mutex_);
     exit_request_ = true;
     running_ = false;
   }
   cond_var_.notify_all();
   thread_.join();
 }
References cond_var_, exit_request_, mutex_, running_, and thread_.
Member Function Documentation
ConnectToHost()
core_type::Result< void, TlsClientSocket::TlsErrorCode > boost_support::socket::tcp::TlsClientSocket::ConnectToHost (std::string_view host_ip_address, std::uint16_t host_port_num)
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
Empty result on success otherwise error code
Definition at line 161 of file tls_client_.cpp.
{
   core_type::Result<void, TlsErrorCode> result{TlsErrorCode::kGenericError};
   TcpErrorCodeType ec{};
   // Connect to provided Ip address
   GetNativeTcpSocket().connect(
       Tcp::endpoint(TcpIpAddress::from_string(std::string{host_ip_address}), host_port_num), ec);
   if (ec.value() == boost::system::errc::success) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           Tcp::endpoint const endpoint_{GetNativeTcpSocket().remote_endpoint()};
           msg << "Tcp Socket connected to host "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     // Perform TLS handshake
     tls_socket_.handshake(boost::asio::ssl::stream_base::client, ec);
     if (ec.value() == boost::system::errc::success) {
       {  // start reading
         std::lock_guard<std::mutex> lock{mutex_};
         running_ = true;
       }
       cond_var_.notify_all();
       printf("Connected with %s encryption\n", SSL_get_cipher(tls_socket_.native_handle()));
       result.EmplaceValue();
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
             msg << "Tls client handshake with host failed with error: " << ec.message();
           });
       result.EmplaceError(TlsErrorCode::kTlsHandshakeFailed);
     }
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp Socket connect to host failed with error: " << ec.message();
         });
     result.EmplaceError(TlsErrorCode::kConnectFailed);
   }
   return result;
 }
References cond_var_, FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), kConnectFailed, kGenericError, kTlsHandshakeFailed, mutex_, running_, and tls_socket_.
Destroy()
core_type::Result< void, TlsClientSocket::TlsErrorCode > boost_support::socket::tcp::TlsClientSocket::Destroy ()
Function to destroy the socket.
Returns
Empty result on success otherwise error code
Definition at line 254 of file tls_client_.cpp.
{
   core_type::Result<void, TlsErrorCode> result{TlsErrorCode::kGenericError};
   // destroy the socket
   GetNativeTcpSocket().close();
   result.EmplaceValue();
   return result;
 }
References GetNativeTcpSocket(), and kGenericError.
DisconnectFromHost()
core_type::Result< void, TlsClientSocket::TlsErrorCode > boost_support::socket::tcp::TlsClientSocket::DisconnectFromHost ()
Function to Disconnect from host.
Returns
Empty result on success otherwise error code
Definition at line 203 of file tls_client_.cpp.
{
   core_type::Result<void, TlsErrorCode> result{TlsErrorCode::kGenericError};
   TcpErrorCodeType ec{};
   // Shutdown TLS connection
   tls_socket_.shutdown(ec);
   // Shutdown of TCP connection
   GetNativeTcpSocket().shutdown(TcpSocket::shutdown_both, ec);
   if (ec.value() == boost::system::errc::success) {
     {
       std::lock_guard<std::mutex> lock{mutex_};
       // stop reading
       running_ = false;
     }
     // Socket shutdown success
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp Socket disconnection from host failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), kGenericError, mutex_, running_, and tls_socket_.
GetNativeTcpSocket()
TlsClientSocket::TlsStream::lowest_layer_type & boost_support::socket::tcp::TlsClientSocket::GetNativeTcpSocket () private
Function to get the native tcp socket under tls socket.
Definition at line 318 of file tls_client_.cpp.
{
   return tls_socket_.lowest_layer();
 }
References tls_socket_.
Referenced by ConnectToHost(), Destroy(), DisconnectFromHost(), HandleMessage(), Open(), and Transmit().
HandleMessage()
void boost_support::socket::tcp::TlsClientSocket::HandleMessage () private
Function to handle the reception of tcp message.
Definition at line 262 of file tls_client_.cpp.
{
   TcpErrorCodeType ec{};
   // create and reserve the buffer
   message::tcp::TcpMessage::BufferType rx_buffer{};
   rx_buffer.resize(message::tcp::kDoipheadrSize);
   // start blocking read to read Header first
   boost::asio::read(tls_socket_, boost::asio::buffer(&rx_buffer[0u], message::tcp::kDoipheadrSize),
                     ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     // read the next bytes to read
     std::uint32_t const read_next_bytes = [&rx_buffer]() noexcept -> std::uint32_t {
       return static_cast<std::uint32_t>(
           (static_cast<std::uint32_t>(rx_buffer[4u] << 24u) & 0xFF000000) |
           (static_cast<std::uint32_t>(rx_buffer[5u] << 16u) & 0x00FF0000) |
           (static_cast<std::uint32_t>(rx_buffer[6u] << 8u) & 0x0000FF00) |
           (static_cast<std::uint32_t>(rx_buffer[7u] & 0x000000FF)));
     }();
     if (read_next_bytes != 0u) {
       // reserve the buffer
       rx_buffer.resize(message::tcp::kDoipheadrSize + std::size_t(read_next_bytes));
       boost::asio::read(
           tls_socket_,
           boost::asio::buffer(&rx_buffer[message::tcp::kDoipheadrSize], read_next_bytes), ec);
       // all message received, transfer to upper layer
       Tcp::endpoint const endpoint_{GetNativeTcpSocket().remote_endpoint()};
       message::tcp::TcpMessagePtr tcp_rx_message{std::make_unique<message::tcp::TcpMessage>(
           endpoint_.address().to_string(), endpoint_.port(), std::move(rx_buffer))};
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__, [endpoint_](std::stringstream &msg) {
             msg << "Tcp Message received from "
                 << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
           });
       // notify upper layer about received message
       tcp_handler_read_(std::move(tcp_rx_message));
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [](std::stringstream &msg) { msg << "Tcp Message read ignored as header size is zero"; });
     }
   } else if (ec.value() == boost::asio::error::eof) {
     running_ = false;
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__,
         [ec](std::stringstream &msg) { msg << "Remote Disconnected with: " << ec.message(); });
   } else {
     running_ = false;
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Remote Disconnected with undefined error: " << ec.message();
         });
   }
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), boost_support::message::tcp::kDoipheadrSize, running_, tcp_handler_read_, and tls_socket_.
Referenced by TlsClientSocket().
Open()
core_type::Result< void, TlsClientSocket::TlsErrorCode > boost_support::socket::tcp::TlsClientSocket::Open ()
Function to Open the socket.
Returns
Empty result on success otherwise error code
Definition at line 119 of file tls_client_.cpp.
{
   core_type::Result<void, TlsErrorCode> result{TlsErrorCode::kGenericError};
   TcpErrorCodeType ec{};
   // Open the socket
   GetNativeTcpSocket().open(Tcp::v4(), ec);
   if (ec.value() == boost::system::errc::success) {
     // Re-use address
     GetNativeTcpSocket().set_option(boost::asio::socket_base::reuse_address{true});
     // Set socket to non blocking
     GetNativeTcpSocket().non_blocking(false);
     // Bind to local ip address and random port
     GetNativeTcpSocket().bind(
         Tcp::endpoint(TcpIpAddress::from_string(local_ip_address_), local_port_num_), ec);
     if (ec.value() == boost::system::errc::success) {
       // Socket binding success
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
             Tcp::endpoint const endpoint_{GetNativeTcpSocket().local_endpoint()};
             msg << "Tcp Socket opened and bound to "
                 << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
           });
       result.EmplaceValue();
     } else {
       // Socket binding failed
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
             msg << "Tcp Socket binding failed with message: " << ec.message();
           });
       result.EmplaceError(TlsErrorCode::kBindingFailed);
     }
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp Socket opening failed with error: " << ec.message();
         });
     result.EmplaceError(TlsErrorCode::kOpenFailed);
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), kBindingFailed, kGenericError, kOpenFailed, local_ip_address_, and local_port_num_.
Transmit()
core_type::Result< void, TlsClientSocket::TlsErrorCode > boost_support::socket::tcp::TlsClientSocket::Transmit (message::tcp::TcpMessageConstPtr tcp_message)
Function to trigger transmission.
Parameters
[in] tcp_message The tcp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 228 of file tls_client_.cpp.
{
   core_type::Result<void, TlsErrorCode> result{TlsErrorCode::kGenericError};
   TcpErrorCodeType ec{};
   boost::asio::write(
       tls_socket_,
       boost::asio::buffer(tcp_message->GetPayload().data(), tcp_message->GetPayload().size()), ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           Tcp::endpoint const endpoint_{GetNativeTcpSocket().remote_endpoint()};
           msg << "Tcp message sent to "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp message sending failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), GetNativeTcpSocket(), kGenericError, and tls_socket_.
Member Data Documentation
cond_var_
std::condition_variable boost_support::socket::tcp::TlsClientSocket::cond_var_ private
Conditional variable to block the thread.
Definition at line 166 of file tls_client_.h.
Referenced by ConnectToHost(), TlsClientSocket(), and ~TlsClientSocket().
exit_request_
std::atomic_bool boost_support::socket::tcp::TlsClientSocket::exit_request_ private
Flag to terminate the thread.
Definition at line 156 of file tls_client_.h.
Referenced by TlsClientSocket(), and ~TlsClientSocket().
io_context_
boost::asio::io_context boost_support::socket::tcp::TlsClientSocket::io_context_ private
boost io context
Definition at line 141 of file tls_client_.h.
io_ssl_context_
boost::asio::ssl::context boost_support::socket::tcp::TlsClientSocket::io_ssl_context_ private
boost io ssl context
Definition at line 146 of file tls_client_.h.
Referenced by TlsClientSocket().
local_ip_address_
std::string boost_support::socket::tcp::TlsClientSocket::local_ip_address_ private
Store local ip address.
Definition at line 131 of file tls_client_.h.
Referenced by Open().
local_port_num_
std::uint16_t boost_support::socket::tcp::TlsClientSocket::local_port_num_ private
Store local port number.
Definition at line 136 of file tls_client_.h.
Referenced by Open().
mutex_
std::mutex boost_support::socket::tcp::TlsClientSocket::mutex_ private
mutex to lock critical section
Definition at line 171 of file tls_client_.h.
Referenced by ConnectToHost(), DisconnectFromHost(), TlsClientSocket(), and ~TlsClientSocket().
running_
std::atomic_bool boost_support::socket::tcp::TlsClientSocket::running_ private
Flag to start the thread.
Definition at line 161 of file tls_client_.h.
Referenced by ConnectToHost(), DisconnectFromHost(), HandleMessage(), TlsClientSocket(), and ~TlsClientSocket().
tcp_handler_read_
TcpHandlerRead boost_support::socket::tcp::TlsClientSocket::tcp_handler_read_ private
Store the handler.
Definition at line 181 of file tls_client_.h.
Referenced by HandleMessage().
thread_
std::thread boost_support::socket::tcp::TlsClientSocket::thread_ private
The thread itself.
Definition at line 176 of file tls_client_.h.
Referenced by TlsClientSocket(), and ~TlsClientSocket().
tls_socket_
TlsStream boost_support::socket::tcp::TlsClientSocket::tls_socket_ private
Store ssl socket.
Definition at line 151 of file tls_client_.h.
Referenced by ConnectToHost(), DisconnectFromHost(), GetNativeTcpSocket(), HandleMessage(), TlsClientSocket(), and Transmit().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tcp/tls_client_.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tcp/tls_client_.cpp