Diag-Client-Lib: uds_transport::ConversionHandler Class Reference
uds_transport::ConversionHandler Class Reference abstract
Class to manage reception from transport protocol handler to connection handler.
#include <conversation_handler.h>
Public Member Functions
ConversionHandler (conversion_manager::ConversionHandlerID handler_id)
Constructs an instance of ConversionHandler.
ConversionHandler (const ConversionHandler &other) noexcept=default
Default copy assignment and copy constructor.
ConversionHandler & operator= (const ConversionHandler &other) noexcept=default
ConversionHandler (ConversionHandler &&other) noexcept=default
Default move assignment and move constructor.
ConversionHandler & operator= (ConversionHandler &&other) noexcept=default
virtual ~ConversionHandler () noexcept=default
Destructs an instance of ConversionHandler.
virtual std::pair< UdsTransportProtocolMgr::IndicationResult, UdsMessagePtr > IndicateMessage (UdsMessage::Address source_addr, UdsMessage::Address target_addr, UdsMessage::TargetAddressType type, ChannelID channel_id, std::size_t size, Priority priority, ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) const noexcept=0
Function to indicate a start of reception of message.
virtual void HandleMessage (UdsMessagePtr message) const noexcept=0
Function to Hands over a valid received Uds message.
Protected Attributes
conversion_manager::ConversionHandlerID handler_id_
Store the conversation handle id.
Detailed Description
Class to manage reception from transport protocol handler to connection handler.
Definition at line 19 of file conversation_handler.h.
Constructor & Destructor Documentation
ConversionHandler() [1/3]
uds_transport::ConversionHandler::ConversionHandler (conversion_manager::ConversionHandlerID handler_id) inline explicit
Constructs an instance of ConversionHandler.
Parameters
[in] handler_id The handle id of conversation
Definition at line 26 of file conversation_handler.h.
       : handler_id_{handler_id} {}
ConversionHandler() [2/3]
uds_transport::ConversionHandler::ConversionHandler (const ConversionHandler & other) default noexcept
Default copy assignment and copy constructor.
ConversionHandler() [3/3]
uds_transport::ConversionHandler::ConversionHandler (ConversionHandler && other) default noexcept
Default move assignment and move constructor.
~ConversionHandler()
virtual uds_transport::ConversionHandler::~ConversionHandler () virtual default noexcept
Destructs an instance of ConversionHandler.
Member Function Documentation
HandleMessage()
virtual void uds_transport::ConversionHandler::HandleMessage (UdsMessagePtr message) const pure virtual noexcept
Function to Hands over a valid received Uds message.
Parameters
[in] message The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Referenced by doip_client::connection::DoipTcpConnection::HandleMessage(), and doip_client::connection::DoipUdpConnection::HandleMessage().
IndicateMessage()
virtual std::pair<UdsTransportProtocolMgr::IndicationResult, UdsMessagePtr> uds_transport::ConversionHandler::IndicateMessage (UdsMessage::Address source_addr, UdsMessage::Address target_addr, UdsMessage::TargetAddressType type, ChannelID channel_id, std::size_t size, Priority priority, ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) const pure virtual noexcept
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The view onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Referenced by doip_client::connection::DoipTcpConnection::IndicateMessage(), and doip_client::connection::DoipUdpConnection::IndicateMessage().
operator=() [1/2]
ConversionHandler& uds_transport::ConversionHandler::operator= (const ConversionHandler & other) default noexcept
operator=() [2/2]
ConversionHandler& uds_transport::ConversionHandler::operator= (ConversionHandler && other) default noexcept
Member Data Documentation
handler_id_
conversion_manager::ConversionHandlerID uds_transport::ConversionHandler::handler_id_ protected
Store the conversation handle id.
Definition at line 89 of file conversation_handler.h.
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/uds-transport-layer-api/uds_transport/conversation_handler.h