Diag-Client-Lib: doip_client::channel::udp_channel::VehicleIdentificationHandler Class Reference
doip_client::channel::udp_channel::VehicleIdentificationHandler Class Reference final
Class used as a handler to process vehicle identification req/ res messages.
#include <doip_vehicle_identification_handler.h>
Classes
class VehicleIdentificationHandlerImpl
Class implements vehicle identification handler.
Public Types
using UdpMessagePtr = sockets::UdpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
using UdpMessage = sockets::UdpSocketHandler::Message
Type alias for Udp message.
Public Member Functions
VehicleIdentificationHandler (sockets::UdpSocketHandler &udp_socket_handler, DoipUdpChannel &channel)
Constructs an instance of VehicleIdentificationHandler.
~VehicleIdentificationHandler ()
Destruct an instance of VehicleIdentificationHandler.
auto HandleVehicleIdentificationRequest (uds_transport::UdsMessageConstPtr vehicle_identification_request) noexcept -> uds_transport::UdsTransportProtocolMgr::TransmissionResult
Function to handle sending of vehicle identification request.
void ProcessVehicleIdentificationResponse (DoipMessage &doip_payload) noexcept
Function to process received vehicle identification response.
Private Member Functions
auto SendVehicleIdentificationRequest (uds_transport::UdsMessageConstPtr vehicle_identification_request) noexcept -> uds_transport::UdsTransportProtocolMgr::TransmissionResult
Function to send vehicle identification request.
Private Attributes
std::unique_ptr< VehicleIdentificationHandlerImpl > handler_impl_
Stores the Handler implementation.
Detailed Description
Class used as a handler to process vehicle identification req/ res messages.
Definition at line 26 of file doip_vehicle_identification_handler.h.
Member Typedef Documentation
UdpMessage
using doip_client::channel::udp_channel::VehicleIdentificationHandler::UdpMessage = sockets::UdpSocketHandler::Message
Type alias for Udp message.
Definition at line 36 of file doip_vehicle_identification_handler.h.
UdpMessagePtr
using doip_client::channel::udp_channel::VehicleIdentificationHandler::UdpMessagePtr = sockets::UdpSocketHandler::MessagePtr
Type alias for Tcp message pointer.
Definition at line 31 of file doip_vehicle_identification_handler.h.
Constructor & Destructor Documentation
VehicleIdentificationHandler()
doip_client::channel::udp_channel::VehicleIdentificationHandler::VehicleIdentificationHandler (sockets::UdpSocketHandler & udp_socket_handler, DoipUdpChannel & channel)
Constructs an instance of VehicleIdentificationHandler.
Parameters
[in] udp_socket_handler The reference to socket handler
[in] channel The reference to doip udp channel
Definition at line 278 of file doip_vehicle_identification_handler.cpp.
     : handler_impl_{
           std::make_unique<VehicleIdentificationHandlerImpl>(udp_socket_handler, channel)} {}
~VehicleIdentificationHandler()
doip_client::channel::udp_channel::VehicleIdentificationHandler::~VehicleIdentificationHandler () default
Destruct an instance of VehicleIdentificationHandler.
Member Function Documentation
HandleVehicleIdentificationRequest()
auto doip_client::channel::udp_channel::VehicleIdentificationHandler::HandleVehicleIdentificationRequest (uds_transport::UdsMessageConstPtr vehicle_identification_request) -> uds_transport::UdsTransportProtocolMgr::TransmissionResult noexcept
Function to handle sending of vehicle identification request.
Parameters
[in] vehicle_identification_request The vehicle identification request
Returns
Transmission result
Definition at line 285 of file doip_vehicle_identification_handler.cpp.
{
   uds_transport::UdsTransportProtocolMgr::TransmissionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed};
   if (handler_impl_->GetStateContext().GetActiveState().GetState() ==
       VehicleIdentificationState::kIdle) {
     // change state before sending if SendVehicleIdentificationRequest call takes more time to return and in the
     // same time async reception starts
     handler_impl_->GetStateContext().TransitionTo(
         VehicleIdentificationState::kWaitForVehicleIdentificationRes);
     if (SendVehicleIdentificationRequest(std::move(vehicle_identification_request)) ==
         uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk) {
       ret_val = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk;
       // Wait for 2 sec to collect all the vehicle identification response
       handler_impl_->GetSyncTimer().WaitForTimeout(
           [&]() {
             handler_impl_->GetStateContext().TransitionTo(
                 VehicleIdentificationState::kDoIPCtrlTimeout);
             // Todo: Send data to upper layer here
           },
           [&]() {
             // no cancellation
           },
           std::chrono::milliseconds{kDoIPCtrl});
       handler_impl_->GetStateContext().TransitionTo(VehicleIdentificationState::kIdle);
     } else {
       // failed, do nothing
       handler_impl_->GetStateContext().TransitionTo(VehicleIdentificationState::kIdle);
       logger::DoipClientLogger::GetDiagClientLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, "", [](std::stringstream &msg) {
             msg << "Vehicle Identification request transmission Failed";
           });
     }
   } else {
     // not free, state already in idle state
   }
   return ret_val;
 }
References FILE_NAME, doip_client::logger::DoipClientLogger::GetDiagClientLogger(), doip_client::kDoIPCtrl, uds_transport::UdsTransportProtocolMgr::kTransmitFailed, and uds_transport::UdsTransportProtocolMgr::kTransmitOk.
ProcessVehicleIdentificationResponse()
void doip_client::channel::udp_channel::VehicleIdentificationHandler::ProcessVehicleIdentificationResponse (DoipMessage & doip_payload) noexcept
Function to process received vehicle identification response.
Parameters
[in] doip_payload The doip message received
Definition at line 325 of file doip_vehicle_identification_handler.cpp.
{
   if (handler_impl_->GetStateContext().GetActiveState().GetState() ==
       VehicleIdentificationState::kWaitForVehicleIdentificationRes) {
     // Deserialize data to indicate to upper layer
     std::pair<uds_transport::UdsTransportProtocolMgr::IndicationResult,
               uds_transport::UdsMessagePtr>
         ret_val{handler_impl_->GetDoipChannel().IndicateMessage(
             static_cast<uds_transport::UdsMessage::Address>(0U),
             static_cast<uds_transport::UdsMessage::Address>(0U),
             uds_transport::UdsMessage::TargetAddressType::kPhysical, 0U,
             doip_payload.GetPayload().size(), 0U, "DoIPUdp", doip_payload.GetPayload())};
     if ((ret_val.first ==
          uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationOk) &&
         (ret_val.second != nullptr)) {
       // Add meta info about ip address
       uds_transport::UdsMessage::MetaInfoMap meta_info_map{
           {"kRemoteIpAddress", std::string{doip_payload.GetHostIpAddress()}}};
       ret_val.second->AddMetaInfo(
           std::make_shared<uds_transport::UdsMessage::MetaInfoMap>(meta_info_map));
       // copy to application buffer
       (void) std::copy(doip_payload.GetPayload().begin(), doip_payload.GetPayload().end(),
                        ret_val.second->GetPayload().begin());
       handler_impl_->GetDoipChannel().HandleMessage(std::move(ret_val.second));
     }
   } else {
     // ignore
   }
 }
References uds_transport::UdsTransportProtocolMgr::kIndicationOk, and uds_transport::UdsMessage::kPhysical.
Referenced by doip_client::channel::udp_channel::DoipUdpChannelHandler::ProcessDoIPPayload().
SendVehicleIdentificationRequest()
auto doip_client::channel::udp_channel::VehicleIdentificationHandler::SendVehicleIdentificationRequest (uds_transport::UdsMessageConstPtr vehicle_identification_request) -> uds_transport::UdsTransportProtocolMgr::TransmissionResult private noexcept
Function to send vehicle identification request.
Parameters
[in] vehicle_identification_request The vehicle identification request
Returns
Transmission result
Definition at line 355 of file doip_vehicle_identification_handler.cpp.
{
   uds_transport::UdsTransportProtocolMgr::TransmissionResult ret_val{
       uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed};
   // Get preselection mode
   std::uint8_t const preselection_mode{vehicle_identification_request->GetPayload()[1u]};
   // Get the payload type & length from preselection mode
   VehiclePayloadType const doip_vehicle_payload_type{
       GetVehicleIdentificationPayloadType(preselection_mode)};
   // create header
   UdpMessage::BufferType compose_vehicle_identification_req{
       CreateDoipGenericHeader(doip_vehicle_payload_type.first, doip_vehicle_payload_type.second)};
   // Copy only if containing VIN / EID
   if (doip_vehicle_payload_type.first != kDoip_VehicleIdentification_ReqType) {
     compose_vehicle_identification_req.insert(
         compose_vehicle_identification_req.begin() + kDoipheadrSize,
         vehicle_identification_request->GetPayload().begin() + 2U,
         vehicle_identification_request->GetPayload().end());
   }
   UdpMessagePtr doip_vehicle_identification_req{
       std::make_unique<UdpMessage>(vehicle_identification_request->GetHostIpAddress(),
                                    vehicle_identification_request->GetHostPortNumber(),
                                    std::move(compose_vehicle_identification_req))};
   if (handler_impl_->GetSocketHandler().Transmit(std::move(doip_vehicle_identification_req))) {
     ret_val = uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk;
   }
   return ret_val;
 }
References doip_client::channel::udp_channel::anonymous_namespace{doip_vehicle_identification_handler.cpp}::CreateDoipGenericHeader(), doip_client::channel::udp_channel::anonymous_namespace{doip_vehicle_identification_handler.cpp}::GetVehicleIdentificationPayloadType(), doip_client::kDoip_VehicleIdentification_ReqType, doip_client::kDoipheadrSize, uds_transport::UdsTransportProtocolMgr::kTransmitFailed, and uds_transport::UdsTransportProtocolMgr::kTransmitOk.
Member Data Documentation
handler_impl_
std::unique_ptr<VehicleIdentificationHandlerImpl> doip_client::channel::udp_channel::VehicleIdentificationHandler::handler_impl_ private
Stores the Handler implementation.
Definition at line 91 of file doip_vehicle_identification_handler.h.
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/udp_channel/doip_vehicle_identification_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/channel/udp_channel/doip_vehicle_identification_handler.cpp