Diag-Client-Lib: diag::client::DiagClient::DiagClientImpl Class Reference
diag::client::DiagClient::DiagClientImpl Class Reference final
Class to provide implementation of diag client.
Public Member Functions
DiagClientImpl (std::string_view diag_client_config_path) noexcept
Constructs an instance of DiagClient.
DiagClientImpl (const DiagClientImpl &other) noexcept=delete
Deleted copy assignment and copy constructor.
DiagClientImpl & operator= (const DiagClientImpl &other) noexcept=delete
DiagClientImpl (DiagClientImpl &&other) noexcept=delete
Deleted move assignment and move constructor.
DiagClientImpl & operator= (DiagClientImpl &&other) noexcept=delete
~DiagClientImpl () noexcept=default
Destruct an instance of DiagClient -Destruction.
Result< void > Initialize () noexcept
Function to initialize the already created instance of DiagClient.
Result< void > DeInitialize () noexcept
Function to de-initialize the already initialized instance of DiagClient.
conversation::DiagClientConversation GetDiagnosticClientConversation (std::string_view conversation_name) noexcept
Function to get required diag client conversation object based on conversation name.
Result< vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > SendVehicleIdentificationRequest (diag::client::vehicle_info::VehicleInfoListRequestType vehicle_info_request) noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
Private Attributes
std::unique_ptr< diag::client::common::DiagnosticManager > dcm_instance_
Unique pointer to dcm client instance.
utility::thread::Thread dcm_thread_
Thread to handle dcm client lifecycle.
std::string diag_client_config_path_
Store the diag client config path.
Detailed Description
Class to provide implementation of diag client.
Definition at line 29 of file diagnostic_client.cpp.
Constructor & Destructor Documentation
DiagClientImpl() [1/3]
diag::client::DiagClient::DiagClientImpl::DiagClientImpl (std::string_view diag_client_config_path) inline explicit noexcept
Constructs an instance of DiagClient.
Parameters
[in] diag_client_config_path The path to diag client config file -Construction
Definition at line 37 of file diagnostic_client.cpp.
       : dcm_instance_{},
         dcm_thread_{},
         diag_client_config_path_{diag_client_config_path} {}
DiagClientImpl() [2/3]
diag::client::DiagClient::DiagClientImpl::DiagClientImpl (const DiagClientImpl & other) delete noexcept
Deleted copy assignment and copy constructor.
DiagClientImpl() [3/3]
diag::client::DiagClient::DiagClientImpl::DiagClientImpl (DiagClientImpl && other) delete noexcept
Deleted move assignment and move constructor.
~DiagClientImpl()
diag::client::DiagClient::DiagClientImpl::~DiagClientImpl () default noexcept
Destruct an instance of DiagClient -Destruction.
Member Function Documentation
DeInitialize()
Result<void> diag::client::DiagClient::DiagClientImpl::DeInitialize () inline noexcept
Function to de-initialize the already initialized instance of DiagClient.
Must be called during shutdown phase, no further processing of any function will be allowed after this call
Returns
Result with void in case of success, otherwise error is returned -DeInitialization
Definition at line 100 of file diagnostic_client.cpp.
{
     logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
         FILE_NAME, __LINE__, __func__,
         [](std::stringstream &msg) { msg << "DiagClient De-Initialization started"; });
     // shutdown DCM module here
     return dcm_instance_->SignalShutdown()
         .AndThen([this]() {
           dcm_thread_.Join();
           logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
               FILE_NAME, __LINE__, "",
               [](std::stringstream &msg) { msg << "DiagClient De-Initialization completed"; });
         })
         .OrElse([](core_type::ErrorCode const &) {
           return error_domain::MakeErrorCode(error_domain::DmErrorErrc::kDeInitializationFailed);
         });
   }
References dcm_instance_, dcm_thread_, FILE_NAME, diag::client::logger::DiagClientLogger::GetDiagClientLogger(), utility::thread::Thread::Join(), diag::client::error_domain::kDeInitializationFailed, and diag::client::error_domain::MakeErrorCode().
GetDiagnosticClientConversation()
conversation::DiagClientConversation diag::client::DiagClient::DiagClientImpl::GetDiagnosticClientConversation (std::string_view conversation_name) inline noexcept
Function to get required diag client conversation object based on conversation name.
Parameters
[in] conversation_name Name of conversation configured as json parameter "ConversationName"
Returns
Diag client conversation object as per passed conversation name -MultipleTester-Connection, DiagClientLib-Conversation-Construction
Definition at line 124 of file diagnostic_client.cpp.
{
     if (!dcm_instance_) {
       logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogFatalAndTerminate(
           FILE_NAME, __LINE__, "",
           [](std::stringstream &msg) { msg << "DiagClient is not Initialized"; });
     }
     return dcm_instance_->GetDiagnosticClientConversation(conversation_name);
   }
References dcm_instance_, FILE_NAME, and diag::client::logger::DiagClientLogger::GetDiagClientLogger().
Initialize()
Result<void> diag::client::DiagClient::DiagClientImpl::Initialize () inline noexcept
Function to initialize the already created instance of DiagClient.
Must be called once and before using any other functions of DiagClient
Returns
Result with void in case of success, otherwise error is returned -Initialization
Definition at line 66 of file diagnostic_client.cpp.
{
     logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
         FILE_NAME, __LINE__, __func__,
         [](std::stringstream &msg) { msg << "DiagClient Initialization started"; });
     // read configuration
     return boost_support::parser::Read(diag_client_config_path_)
         .AndThen([this](boost_support::parser::boost_tree config) {
           // Create single dcm instance and pass the configuration
           dcm_instance_ = std::make_unique<diag::client::dcm::DCMClient>(
               config_parser::ReadDcmClientConfig(config));
           // Start dcm client main thread
           dcm_thread_ = utility::thread::Thread{"DcmClientMain",
                                                 [this]() noexcept { dcm_instance_->Main(); }};
           logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
               FILE_NAME, __LINE__, "",
               [](std::stringstream &msg) { msg << "DiagClient Initialization completed"; });
           return Result<void, boost_support::parser::ParsingErrorCode>::FromValue();
         })
         .MapError([](boost_support::parser::ParsingErrorCode const &) noexcept {
           logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogError(
               FILE_NAME, __LINE__, "",
               [](std::stringstream &msg) { msg << "DiagClient Initialization failed"; });
           return error_domain::MakeErrorCode(error_domain::DmErrorErrc::kInitializationFailed);
         });
   }
References dcm_instance_, dcm_thread_, diag_client_config_path_, FILE_NAME, core_type::Result< T, E >::FromValue(), diag::client::logger::DiagClientLogger::GetDiagClientLogger(), diag::client::error_domain::kInitializationFailed, diag::client::error_domain::MakeErrorCode(), boost_support::parser::Read(), and diag::client::config_parser::ReadDcmClientConfig().
operator=() [1/2]
DiagClientImpl& diag::client::DiagClient::DiagClientImpl::operator= (const DiagClientImpl & other) delete noexcept
operator=() [2/2]
DiagClientImpl& diag::client::DiagClient::DiagClientImpl::operator= (DiagClientImpl && other) delete noexcept
SendVehicleIdentificationRequest()
Result<vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError> diag::client::DiagClient::DiagClientImpl::SendVehicleIdentificationRequest (diag::client::vehicle_info::VehicleInfoListRequestType vehicle_info_request) inline noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
Parameters
[in] vehicle_info_request Vehicle information sent along with request
Returns
Result containing available vehicle information response on success, VehicleResponseErrorCode on error -VehicleDiscovery
Definition at line 142 of file diagnostic_client.cpp.
{
     if (!dcm_instance_) {
       logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogFatalAndTerminate(
           FILE_NAME, __LINE__, "",
           [](std::stringstream &msg) { msg << "DiagClient is not Initialized"; });
     }
     return dcm_instance_->SendVehicleIdentificationRequest(std::move(vehicle_info_request));
   }
References dcm_instance_, FILE_NAME, and diag::client::logger::DiagClientLogger::GetDiagClientLogger().
Member Data Documentation
dcm_instance_
std::unique_ptr<diag::client::common::DiagnosticManager> diag::client::DiagClient::DiagClientImpl::dcm_instance_ private
Unique pointer to dcm client instance.
Definition at line 156 of file diagnostic_client.cpp.
Referenced by DeInitialize(), GetDiagnosticClientConversation(), Initialize(), and SendVehicleIdentificationRequest().
dcm_thread_
utility::thread::Thread diag::client::DiagClient::DiagClientImpl::dcm_thread_ private
Thread to handle dcm client lifecycle.
Definition at line 161 of file diagnostic_client.cpp.
Referenced by DeInitialize(), and Initialize().
diag_client_config_path_
std::string diag::client::DiagClient::DiagClientImpl::diag_client_config_path_ private
Store the diag client config path.
Definition at line 166 of file diagnostic_client.cpp.
Referenced by Initialize().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/diagnostic_client.cpp