Diag-Client-Lib: boost_support::client::udp::UdpClient::UdpClientImpl Class Reference
boost_support::client::udp::UdpClient::UdpClientImpl Class Reference final
Class to provide implementation of udp client.
Public Member Functions
UdpClientImpl (std::string_view local_ip_address, std::uint16_t local_port_num) noexcept
Constructs an instance of UdpClientImpl.
UdpClientImpl (const UdpClientImpl &other) noexcept=delete
Deleted copy assignment and copy constructor.
UdpClientImpl & operator= (const UdpClientImpl &other) noexcept=delete
UdpClientImpl (UdpClientImpl &&other) noexcept=delete
Deleted move assignment and move constructor.
UdpClientImpl & operator= (UdpClientImpl &&other) noexcept=delete
~UdpClientImpl () noexcept=default
Destruct an instance of UdpClientImpl.
void Initialize () noexcept
Initialize the client.
void DeInitialize () noexcept
De-initialize the client.
void SetReadHandler (HandlerRead read_handler) noexcept
Function to set the read handler that is invoked when message is received.
core_type::Result< void > Transmit (MessageConstPtr udp_message)
Function to transmit the provided udp message.
Private Types
using UdpConnection = connection::udp::UdpConnection< socket::udp::UdpSocket >
Type alias for Udp connection.
using IoContext = boost_support::socket::IoContext
Type alias for boost context.
Private Attributes
IoContext io_context_
Stores the io context.
UdpConnection udp_connection_
Store the udp connection.
Detailed Description
Class to provide implementation of udp client.
Definition at line 22 of file udp_client.cpp.
Member Typedef Documentation
IoContext
using boost_support::client::udp::UdpClient::UdpClientImpl::IoContext = boost_support::socket::IoContext private
Type alias for boost context.
Definition at line 98 of file udp_client.cpp.
UdpConnection
using boost_support::client::udp::UdpClient::UdpClientImpl::UdpConnection = connection::udp::UdpConnection<socket::udp::UdpSocket> private
Type alias for Udp connection.
Definition at line 93 of file udp_client.cpp.
Constructor & Destructor Documentation
UdpClientImpl() [1/3]
boost_support::client::udp::UdpClient::UdpClientImpl::UdpClientImpl (std::string_view local_ip_address, std::uint16_t local_port_num) inline noexcept
Constructs an instance of UdpClientImpl.
Parameters
[in] local_ip_address The local ip address of client
[in] local_port_num The local port number of client
Definition at line 31 of file udp_client.cpp.
       : io_context_{"UdpClient"},
         udp_connection_{
             socket::udp::UdpSocket{local_ip_address, local_port_num, io_context_.GetContext()}} {}
UdpClientImpl() [2/3]
boost_support::client::udp::UdpClient::UdpClientImpl::UdpClientImpl (const UdpClientImpl & other) delete noexcept
Deleted copy assignment and copy constructor.
UdpClientImpl() [3/3]
boost_support::client::udp::UdpClient::UdpClientImpl::UdpClientImpl (UdpClientImpl && other) delete noexcept
Deleted move assignment and move constructor.
~UdpClientImpl()
boost_support::client::udp::UdpClient::UdpClientImpl::~UdpClientImpl () default noexcept
Destruct an instance of UdpClientImpl.
Member Function Documentation
DeInitialize()
void boost_support::client::udp::UdpClient::UdpClientImpl::DeInitialize () inline noexcept
De-initialize the client.
Definition at line 64 of file udp_client.cpp.
{
     udp_connection_.DeInitialize();
     io_context_.DeInitialize();
   }
References boost_support::connection::udp::UdpConnection< Socket >::DeInitialize(), boost_support::socket::IoContext::DeInitialize(), io_context_, and udp_connection_.
Initialize()
void boost_support::client::udp::UdpClient::UdpClientImpl::Initialize () inline noexcept
Initialize the client.
Definition at line 56 of file udp_client.cpp.
{
     io_context_.Initialize();
     udp_connection_.Initialize();
   }
References boost_support::connection::udp::UdpConnection< Socket >::Initialize(), boost_support::socket::IoContext::Initialize(), io_context_, and udp_connection_.
operator=() [1/2]
UdpClientImpl& boost_support::client::udp::UdpClient::UdpClientImpl::operator= (const UdpClientImpl & other) delete noexcept
operator=() [2/2]
UdpClientImpl& boost_support::client::udp::UdpClient::UdpClientImpl::operator= (UdpClientImpl && other) delete noexcept
SetReadHandler()
void boost_support::client::udp::UdpClient::UdpClientImpl::SetReadHandler (HandlerRead read_handler) inline noexcept
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 75 of file udp_client.cpp.
{
     udp_connection_.SetReadHandler(std::move(read_handler));
   }
References boost_support::connection::udp::UdpConnection< Socket >::SetReadHandler(), and udp_connection_.
Transmit()
core_type::Result<void> boost_support::client::udp::UdpClient::UdpClientImpl::Transmit (MessageConstPtr udp_message) inline
Function to transmit the provided udp message.
Parameters
[in] udp_message The udp message
Returns
Empty void on success, otherwise error is returned
Definition at line 85 of file udp_client.cpp.
{
     return udp_connection_.Transmit(std::move(udp_message));
   }
References boost_support::connection::udp::UdpConnection< Socket >::Transmit(), and udp_connection_.
Member Data Documentation
io_context_
IoContext boost_support::client::udp::UdpClient::UdpClientImpl::io_context_ private
Stores the io context.
Definition at line 103 of file udp_client.cpp.
Referenced by DeInitialize(), and Initialize().
udp_connection_
UdpConnection boost_support::client::udp::UdpClient::UdpClientImpl::udp_connection_ private
Store the udp connection.
Definition at line 108 of file udp_client.cpp.
Referenced by DeInitialize(), Initialize(), SetReadHandler(), and Transmit().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/client/udp/udp_client.cpp