Diag-Client-Lib: doip_client::sockets::UdpSocketHandler Class Reference
doip_client::sockets::UdpSocketHandler Class Reference final
Class used to create a udp socket for handling transmission and reception of udp message from driver.
#include <udp_socket_handler.h>
Public Types
using PortType = boost_support::socket::udp::UdpClientSocket::PortType
Type alias for port type.
using UdpMessage = boost_support::socket::udp::UdpMessage
Type alias for Udp message.
using UdpMessagePtr = boost_support::socket::udp::UdpMessagePtr
Type alias for Udp message pointer.
using UdpMessageConstPtr = boost_support::socket::udp::UdpMessageConstPtr
Type alias for Udp message const pointer.
using DoipUdpChannel = channel::udp_channel::DoipUdpChannel
Type alias for Udp message.
Public Member Functions
UdpSocketHandler (std::string_view local_ip_address, std::uint16_t port_num, PortType port_type, DoipUdpChannel &channel)
Constructs an instance of UdpSocketHandler.
~UdpSocketHandler ()=default
Destruct an instance of UdpSocketHandler.
void Start ()
Function to start the socket handler.
void Stop ()
Function to stop the socket handler.
core_type::Result< void > Transmit (UdpMessageConstPtr udp_message)
Function to transmit the provided udp message.
Private Types
using UdpSocket = boost_support::socket::udp::UdpClientSocket
Type alias for tcp client socket.
Private Attributes
std::string local_ip_address_
Store the local ip address.
std::uint16_t local_port_num_
Store the local port number.
UdpSocket::PortType port_type_
Store the port type.
std::unique_ptr< UdpSocket > udp_socket_
Store the socket object.
DoipUdpChannel & channel_
Store the reference to tcp channel.
Detailed Description
Class used to create a udp socket for handling transmission and reception of udp message from driver.
Definition at line 30 of file udp_socket_handler.h.
Member Typedef Documentation
DoipUdpChannel
using doip_client::sockets::UdpSocketHandler::DoipUdpChannel = channel::udp_channel::DoipUdpChannel
Type alias for Udp message.
Definition at line 55 of file udp_socket_handler.h.
PortType
using doip_client::sockets::UdpSocketHandler::PortType = boost_support::socket::udp::UdpClientSocket::PortType
Type alias for port type.
Definition at line 35 of file udp_socket_handler.h.
UdpMessage
using doip_client::sockets::UdpSocketHandler::UdpMessage = boost_support::socket::udp::UdpMessage
Type alias for Udp message.
Definition at line 40 of file udp_socket_handler.h.
UdpMessageConstPtr
using doip_client::sockets::UdpSocketHandler::UdpMessageConstPtr = boost_support::socket::udp::UdpMessageConstPtr
Type alias for Udp message const pointer.
Definition at line 50 of file udp_socket_handler.h.
UdpMessagePtr
using doip_client::sockets::UdpSocketHandler::UdpMessagePtr = boost_support::socket::udp::UdpMessagePtr
Type alias for Udp message pointer.
Definition at line 45 of file udp_socket_handler.h.
UdpSocket
using doip_client::sockets::UdpSocketHandler::UdpSocket = boost_support::socket::udp::UdpClientSocket private
Type alias for tcp client socket.
Definition at line 95 of file udp_socket_handler.h.
Constructor & Destructor Documentation
UdpSocketHandler()
doip_client::sockets::UdpSocketHandler::UdpSocketHandler (std::string_view local_ip_address, std::uint16_t port_num, PortType port_type, DoipUdpChannel & channel)
Constructs an instance of UdpSocketHandler.
Parameters
[in] local_ip_address The local ip address
[in] channel The reference to tcp transport handler
Definition at line 15 of file udp_socket_handler.cpp.
     : local_ip_address_{local_ip_address},
       local_port_num_{port_num},
       port_type_{port_type},
       channel_{channel} {
   // create sockets and start receiving
   if (port_type == UdpSocket::PortType::kUdp_Broadcast) {
     udp_socket_ = std::make_unique<UdpSocket>(
         local_ip_address_, local_port_num_, port_type_,
         [this](UdpMessagePtr udp_rx_message) { channel_.ProcessReceivedUdpBroadcast(std::move(udp_rx_message)); });
   } else {
     udp_socket_ = std::make_unique<UdpSocket>(
         local_ip_address_, local_port_num_, port_type_,
         [this](UdpMessagePtr udp_rx_message) { channel_.ProcessReceivedUdpUnicast(std::move(udp_rx_message)); });
   }
 }
References channel_, boost_support::socket::udp::UdpClientSocket::kUdp_Broadcast, local_ip_address_, local_port_num_, port_type_, doip_client::channel::udp_channel::DoipUdpChannel::ProcessReceivedUdpBroadcast(), doip_client::channel::udp_channel::DoipUdpChannel::ProcessReceivedUdpUnicast(), and udp_socket_.
~UdpSocketHandler()
doip_client::sockets::UdpSocketHandler::~UdpSocketHandler () default
Destruct an instance of UdpSocketHandler.
Member Function Documentation
Start()
void doip_client::sockets::UdpSocketHandler::Start ()
Function to start the socket handler.
Definition at line 33 of file udp_socket_handler.cpp.
 { udp_socket_->Open(); }
References udp_socket_.
Referenced by doip_client::channel::udp_channel::DoipUdpChannel::Start().
Stop()
void doip_client::sockets::UdpSocketHandler::Stop ()
Function to stop the socket handler.
Definition at line 35 of file udp_socket_handler.cpp.
 { udp_socket_->Destroy(); }
References udp_socket_.
Referenced by doip_client::channel::udp_channel::DoipUdpChannel::Stop().
Transmit()
core_type::Result< void > doip_client::sockets::UdpSocketHandler::Transmit (UdpMessageConstPtr udp_message)
Function to transmit the provided udp message.
Parameters
[in] udp_message The udp message
Returns
The
Definition at line 37 of file udp_socket_handler.cpp.
{
   core_type::Result<void> result{error_domain::MakeErrorCode(error_domain::DoipErrorErrc::kGenericError)};
   if (udp_socket_->Transmit(std::move(udp_message)).HasValue()) { result.EmplaceValue(); }
   return result;
 }
References doip_client::error_domain::kGenericError, doip_client::error_domain::MakeErrorCode(), and udp_socket_.
Member Data Documentation
channel_
DoipUdpChannel& doip_client::sockets::UdpSocketHandler::channel_ private
Store the reference to tcp channel.
Definition at line 120 of file udp_socket_handler.h.
Referenced by UdpSocketHandler().
local_ip_address_
std::string doip_client::sockets::UdpSocketHandler::local_ip_address_ private
Store the local ip address.
Definition at line 100 of file udp_socket_handler.h.
Referenced by UdpSocketHandler().
local_port_num_
std::uint16_t doip_client::sockets::UdpSocketHandler::local_port_num_ private
Store the local port number.
Definition at line 105 of file udp_socket_handler.h.
Referenced by UdpSocketHandler().
port_type_
UdpSocket::PortType doip_client::sockets::UdpSocketHandler::port_type_ private
Store the port type.
Definition at line 110 of file udp_socket_handler.h.
Referenced by UdpSocketHandler().
udp_socket_
std::unique_ptr<UdpSocket> doip_client::sockets::UdpSocketHandler::udp_socket_ private
Store the socket object.
Definition at line 115 of file udp_socket_handler.h.
Referenced by Start(), Stop(), Transmit(), and UdpSocketHandler().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/sockets/udp_socket_handler.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/doip-client/sockets/udp_socket_handler.cpp