Diag-Client-Lib: diag::client::conversation::VdConversation Class Reference
diag::client::conversation::VdConversation Class Reference final
Class to search for available diagnostic server over a network.
#include <vd_conversation.h>
Public Member Functions
VdConversation (std::string_view conversion_name, VDConversationType &conversion_identifier)
Constructs an instance of VdConversation.
VdConversation (const VdConversation &other) noexcept=delete
Deleted copy assignment and copy constructor.
VdConversation & operator= (const VdConversation &other) noexcept=delete
VdConversation (VdConversation &&other) noexcept=delete
Deleted move assignment and move constructor.
VdConversation & operator= (VdConversation &&other) noexcept=delete
~VdConversation () override
Destructs an instance of DmConversation.
void Startup () noexcept override
Function to start the DmConversation.
void Shutdown () noexcept override
Function to shutdown the DmConversation.
void RegisterConnection (std::unique_ptr<::uds_transport::Connection > connection) noexcept override
Function to register the conversation to underlying transport protocol handler.
::uds_transport::ConversionHandler & GetConversationHandler () noexcept override
Function to get the conversation handler from conversation object.
std::pair<::uds_transport::UdsTransportProtocolMgr::IndicationResult, ::uds_transport::UdsMessagePtr > IndicateMessage (::uds_transport::UdsMessage::Address source_addr, ::uds_transport::UdsMessage::Address target_addr, ::uds_transport::UdsMessage::TargetAddressType type, ::uds_transport::ChannelID channel_id, std::size_t size, ::uds_transport::Priority priority, ::uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t > payloadInfo) noexcept override
Function to indicate a start of reception of message.
void HandleMessage (::uds_transport::UdsMessagePtr message) noexcept override
Function to Hands over a valid received Uds message.
core_type::Result< diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > SendVehicleIdentificationRequest (vehicle_info::VehicleInfoListRequestType vehicle_info_request) noexcept override
Function to send vehicle identification request and get the Diagnostic Server list.
vehicle_info::VehicleInfoMessageResponseUniquePtr GetDiagnosticServerList ()
Function to get the list of available diagnostic server.
Public Member Functions inherited from diag::client::conversation::Conversation
Conversation () noexcept=default
Constructs an instance of Conversation.
Conversation (const Conversation &other) noexcept=delete
Deleted copy assignment and copy constructor.
Conversation & operator= (const Conversation &other) noexcept=delete
Conversation (Conversation &&other) noexcept=delete
Deleted move assignment and move constructor.
Conversation & operator= (Conversation &&other) noexcept=delete
virtual ~Conversation () noexcept=default
Destructs an instance of Conversation.
virtual ConnectResult ConnectToDiagServer (std::uint16_t, IpAddress) noexcept
Function to connect to Diagnostic Server.
virtual DisconnectResult DisconnectFromDiagServer () noexcept
Function to disconnect from Diagnostic Server.
virtual Result< uds_message::UdsResponseMessagePtr, DiagError > SendDiagnosticRequest (uds_message::UdsRequestMessageConstPtr) noexcept
Function to send Diagnostic Request and get Diagnostic Response.
Private Types
using PreselectionMode = std::uint8_t
Type alias of pre-selection mode.
using PreselectionValue = std::vector< std::uint8_t >
Type alias of pre-selection value in terms of vector.
using VehicleAddrInfoResponseStruct = diag::client::vehicle_info::VehicleAddrInfoResponse
Type alias of vehicle address info response.
using LogicalAddress = std::uint16_t
Type alias of logical address.
Private Member Functions
bool VerifyVehicleInfoRequest (PreselectionMode preselection_mode, std::uint8_t preselection_value_length)
Function to verify the received vehicle info request.
Static Private Member Functions
static std::pair< LogicalAddress, VehicleAddrInfoResponseStruct > DeserializeVehicleInfoResponse (::uds_transport::UdsMessagePtr message)
Function to deserialize the received Vehicle Identification Response/ Announcement.
static std::pair< PreselectionMode, PreselectionValue > DeserializeVehicleInfoRequest (vehicle_info::VehicleInfoListRequestType &vehicle_info_request)
Function to deserialize the Vehicle Information request from user.
Private Attributes
std::unique_ptr<::uds_transport::ConversionHandler > vd_conversion_handler_
Store the vd conversation handler.
std::string conversation_name_
Store the conversation name.
std::string broadcast_address_
Store the broadcast Ip address of the conversation.
std::unique_ptr<::uds_transport::Connection > connection_ptr_
Store the underlying transport protocol connection object.
std::map< std::uint16_t, VehicleAddrInfoResponseStruct > vehicle_info_collection_
Store the vehicle info collection received till now.
std::mutex vehicle_info_container_mutex_
Mutex to lock the vehicle info collection container.
Additional Inherited Members
Public Types inherited from diag::client::conversation::Conversation
using IpAddress = DiagClientConversation::IpAddress
Type alias for Ip address.
using ConnectResult = DiagClientConversation::ConnectResult
Type alias for Connection results.
using DisconnectResult = DiagClientConversation::DisconnectResult
Type alias for Disconnection results.
using DiagError = DiagClientConversation::DiagError
Type alias for Diagnostic results.
Detailed Description
Class to search for available diagnostic server over a network.
Definition at line 33 of file vd_conversation.h.
Member Typedef Documentation
LogicalAddress
using diag::client::conversation::VdConversation::LogicalAddress = std::uint16_t private
Type alias of logical address.
Definition at line 53 of file vd_conversation.h.
PreselectionMode
using diag::client::conversation::VdConversation::PreselectionMode = std::uint8_t private
Type alias of pre-selection mode.
Definition at line 38 of file vd_conversation.h.
PreselectionValue
using diag::client::conversation::VdConversation::PreselectionValue = std::vector<std::uint8_t> private
Type alias of pre-selection value in terms of vector.
Definition at line 43 of file vd_conversation.h.
VehicleAddrInfoResponseStruct
using diag::client::conversation::VdConversation::VehicleAddrInfoResponseStruct = diag::client::vehicle_info::VehicleAddrInfoResponse private
Type alias of vehicle address info response.
Definition at line 48 of file vd_conversation.h.
Constructor & Destructor Documentation
VdConversation() [1/3]
diag::client::conversation::VdConversation::VdConversation (std::string_view conversion_name, VDConversationType & conversion_identifier)
Constructs an instance of VdConversation.
Parameters
[in] conversion_name The name of conversation
[in] conversion_identifier The identifier consisting of conversation settings
Definition at line 188 of file vd_conversation.cpp.
     : vd_conversion_handler_{std::make_unique<VdConversationHandler>(conversion_identifier.handler_id, *this)},
       conversation_name_{conversion_name},
       broadcast_address_{conversion_identifier.udp_broadcast_address},
       connection_ptr_{},
       vehicle_info_collection_{},
       vehicle_info_container_mutex_{} {}
VdConversation() [2/3]
diag::client::conversation::VdConversation::VdConversation (const VdConversation & other) delete noexcept
Deleted copy assignment and copy constructor.
VdConversation() [3/3]
diag::client::conversation::VdConversation::VdConversation (VdConversation && other) delete noexcept
Deleted move assignment and move constructor.
~VdConversation()
diag::client::conversation::VdConversation::~VdConversation () override default
Destructs an instance of DmConversation.
Member Function Documentation
DeserializeVehicleInfoRequest()
std::pair< VdConversation::PreselectionMode, VdConversation::PreselectionValue > diag::client::conversation::VdConversation::DeserializeVehicleInfoRequest (vehicle_info::VehicleInfoListRequestType & vehicle_info_request) static private
Function to deserialize the Vehicle Information request from user.
Parameters
[in] vehicle_info_request The vehicle info request
Returns
The pair with preselection mode along with its preselection value
Definition at line 332 of file vd_conversation.cpp.
{
   std::pair<VdConversation::PreselectionMode, VdConversation::PreselectionValue> ret_val{};
   ret_val.first = vehicle_info_request.preselection_mode;
   if (ret_val.first == 1U) {
     // 1U : DoIP Entities with given VIN
     SerializeVINFromString(vehicle_info_request.preselection_value, ret_val.second,
                            static_cast<uint8_t>(vehicle_info_request.preselection_value.length()), 1U);
   } else if (ret_val.first == 2U) {
     // 2U : DoIP Entities with given EID
     vehicle_info_request.preselection_value.erase(
         remove(vehicle_info_request.preselection_value.begin(), vehicle_info_request.preselection_value.end(), ':'),
         vehicle_info_request.preselection_value.end());
     SerializeEIDGIDFromString(vehicle_info_request.preselection_value, ret_val.second,
                               static_cast<uint8_t>(vehicle_info_request.preselection_value.length()), 2U);
   } else {
     // log failure
   }
   return ret_val;
 }
References diag::client::vehicle_info::VehicleAddrInfoRequest::preselection_mode, diag::client::vehicle_info::VehicleAddrInfoRequest::preselection_value, diag::client::conversation::SerializeEIDGIDFromString(), and diag::client::conversation::SerializeVINFromString().
DeserializeVehicleInfoResponse()
std::pair< VdConversation::LogicalAddress, VdConversation::VehicleAddrInfoResponseStruct > diag::client::conversation::VdConversation::DeserializeVehicleInfoResponse (::uds_transport::UdsMessagePtr message) static private
Function to deserialize the received Vehicle Identification Response/ Announcement.
Parameters
[in] message The message to deserialize
Returns
The pair with logical address of server and Vehicle address information
Definition at line 300 of file vd_conversation.cpp.
{
   constexpr std::uint8_t start_index_vin{0U};
   constexpr std::uint8_t total_vin_length{17U};
   constexpr std::uint8_t start_index_eid{19U};
   constexpr std::uint8_t start_index_gid{25U};
   constexpr std::uint8_t total_eid_gid_length{6U};
   std::string const vehicle_info_data_vin{
       ConvertToAsciiString(start_index_vin, total_vin_length, message->GetPayload())};
   std::string const vehicle_info_data_eid{
       ConvertToHexString(start_index_eid, total_eid_gid_length, message->GetPayload())};
   std::string const vehicle_info_data_gid{
       ConvertToHexString(start_index_gid, total_eid_gid_length, message->GetPayload())};
   LogicalAddress const logical_address{
       (static_cast<std::uint16_t>(((message->GetPayload()[17U] & 0xFF) << 8) | (message->GetPayload()[18U] & 0xFF)))};
   // Create the structure out of the extracted string
   VehicleAddrInfoResponseStruct const vehicle_addr_info{std::string{message->GetHostIpAddress()},  // remote ip address
                                                         logical_address,                           // logical address
                                                         vehicle_info_data_vin,                     // vin
                                                         vehicle_info_data_eid,                     // eid
                                                         vehicle_info_data_gid};                    // gid
   return std::pair<std::uint16_t, VdConversation::VehicleAddrInfoResponseStruct>{logical_address, vehicle_addr_info};
 }
References diag::client::conversation::ConvertToAsciiString(), and diag::client::conversation::ConvertToHexString().
GetConversationHandler()
uds_transport::ConversionHandler & diag::client::conversation::VdConversation::GetConversationHandler () override virtual noexcept
Function to get the conversation handler from conversation object.
Returns
ConversionHandler & The reference to conversation handler
Implements diag::client::conversation::Conversation.
Definition at line 327 of file vd_conversation.cpp.
{
   return *vd_conversion_handler_;
 }
References vd_conversion_handler_.
GetDiagnosticServerList()
vehicle_info::VehicleInfoMessageResponseUniquePtr diag::client::conversation::VdConversation::GetDiagnosticServerList ()
Function to get the list of available diagnostic server.
Returns
The Vehicle info message containing available diagnostic server information
Definition at line 249 of file vd_conversation.cpp.
 { return nullptr; }
HandleMessage()
void diag::client::conversation::VdConversation::HandleMessage (::uds_transport::UdsMessagePtr message) override virtual noexcept
Function to Hands over a valid received Uds message.
Parameters
[in] message The The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Implements diag::client::conversation::Conversation.
Definition at line 268 of file vd_conversation.cpp.
{
   if (message != nullptr) {
     std::lock_guard<std::mutex> const lock{vehicle_info_container_mutex_};
     std::pair<std::uint16_t, VehicleAddrInfoResponseStruct> vehicle_info_request{
         DeserializeVehicleInfoResponse(std::move(message))};
     vehicle_info_collection_.emplace(vehicle_info_request.first, vehicle_info_request.second);
   }
 }
Referenced by diag::client::conversation::VdConversationHandler::HandleMessage().
IndicateMessage()
std::pair<::uds_transport::UdsTransportProtocolMgr::IndicationResult,::uds_transport::UdsMessagePtr > diag::client::conversation::VdConversation::IndicateMessage (::uds_transport::UdsMessage::Address source_addr, ::uds_transport::UdsMessage::Address target_addr, ::uds_transport::UdsMessage::TargetAddressType type, ::uds_transport::ChannelID channel_id, std::size_t size, ::uds_transport::Priority priority, ::uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t > payloadInfo) override virtual noexcept
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The View onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Implements diag::client::conversation::Conversation.
Definition at line 252 of file vd_conversation.cpp.
{
   using IndicationResult =
       std::pair<::uds_transport::UdsTransportProtocolMgr::IndicationResult, ::uds_transport::UdsMessagePtr>;
   IndicationResult ret_val{::uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationNOk, nullptr};
   if (!payload_info.empty()) {
     ret_val.first = ::uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationOk;
     ret_val.second = std::make_unique<diag::client::vd_message::VdMessage>();
     ret_val.second->GetPayload().resize(size);
   }
   return ret_val;
 }
References uds_transport::UdsTransportProtocolMgr::kIndicationNOk, and uds_transport::UdsTransportProtocolMgr::kIndicationOk.
Referenced by diag::client::conversation::VdConversationHandler::IndicateMessage().
operator=() [1/2]
VdConversation& diag::client::conversation::VdConversation::operator= (const VdConversation & other) delete noexcept
operator=() [2/2]
VdConversation& diag::client::conversation::VdConversation::operator= (VdConversation && other) delete noexcept
RegisterConnection()
void diag::client::conversation::VdConversation::RegisterConnection (std::unique_ptr<::uds_transport::Connection > connection) override virtual noexcept
Function to register the conversation to underlying transport protocol handler.
Parameters
[in] connection The conversation connection object
Implements diag::client::conversation::Conversation.
Definition at line 210 of file vd_conversation.cpp.
{
   connection_ptr_ = std::move(connection);
 }
SendVehicleIdentificationRequest()
core_type::Result< diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > diag::client::conversation::VdConversation::SendVehicleIdentificationRequest (vehicle_info::VehicleInfoListRequestType vehicle_info_request) override virtual noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
Parameters
[in] vehicle_info_request Vehicle information sent along with request
Returns
Result containing available vehicle information response on success, VehicleResponseErrorCode on error
Reimplemented from diag::client::conversation::Conversation.
Definition at line 215 of file vd_conversation.cpp.
{
   using VehicleIdentificationResponseResult =
       core_type::Result<diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr,
                         DiagClient::VehicleInfoResponseError>;
   VehicleIdentificationResponseResult result{
       VehicleIdentificationResponseResult::FromError(DiagClient::VehicleInfoResponseError::kTransmitFailed)};
   // Deserialize first , Todo: Add optional when deserialize fails
   std::pair<PreselectionMode, PreselectionValue> vehicle_info_request_deserialized_value{
       DeserializeVehicleInfoRequest(vehicle_info_request)};
   if (VerifyVehicleInfoRequest(vehicle_info_request_deserialized_value.first,
                                static_cast<uint8_t>(vehicle_info_request_deserialized_value.second.size()))) {
     if (connection_ptr_->Transmit(std::make_unique<diag::client::vd_message::VdMessage>(
             vehicle_info_request_deserialized_value.first, vehicle_info_request_deserialized_value.second,
             broadcast_address_)) != uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed) {
       // Check if any response received
       if (vehicle_info_collection_.empty()) {
         // no response received
         result.EmplaceError(DiagClient::VehicleInfoResponseError::kNoResponseReceived);
       } else {
         result.EmplaceValue(std::make_unique<VehicleInfoMessageImpl>(vehicle_info_collection_));
         // all the responses are copied, now clear the map
         vehicle_info_collection_.clear();
       }
     }
   } else {
     result.EmplaceError(DiagClient::VehicleInfoResponseError::kInvalidParameters);
   }
   return result;
 }
References diag::client::DiagClient::kInvalidParameters, diag::client::DiagClient::kNoResponseReceived, diag::client::DiagClient::kTransmitFailed, and uds_transport::UdsTransportProtocolMgr::kTransmitFailed.
Shutdown()
void diag::client::conversation::VdConversation::Shutdown () override virtual noexcept
Function to shutdown the DmConversation.
Implements diag::client::conversation::Conversation.
Definition at line 205 of file vd_conversation.cpp.
{
   // shutdown connection
   connection_ptr_->Stop();
 }
References connection_ptr_.
Startup()
void diag::client::conversation::VdConversation::Startup () override virtual noexcept
Function to start the DmConversation.
Implements diag::client::conversation::Conversation.
Definition at line 198 of file vd_conversation.cpp.
{
   // initialize the connection
   static_cast<void>(connection_ptr_->Initialize());
   // start the connection
   connection_ptr_->Start();
 }
References connection_ptr_.
VerifyVehicleInfoRequest()
bool diag::client::conversation::VdConversation::VerifyVehicleInfoRequest (PreselectionMode preselection_mode, std::uint8_t preselection_value_length) private
Function to verify the received vehicle info request.
Parameters
[in] preselection_mode The preselection mode
[in] preselection_value_length The length of preselection value
Returns
True on success, else false
Definition at line 278 of file vd_conversation.cpp.
{
   bool is_veh_info_valid{false};
   // 0U : No preselection
   if (preselection_mode == 0U && (preselection_value_length == 0U)) {
     is_veh_info_valid = true;
   }
   // 1U : DoIP Entities with given VIN
   else if (preselection_mode == 1U && (preselection_value_length == 17U)) {
     is_veh_info_valid = true;
   }
   // 2U : DoIP Entities with given EID
   else if (preselection_mode == 2U && (preselection_value_length == 6U)) {
     is_veh_info_valid = true;
   } else {
     // do nothing
   }
   return is_veh_info_valid;
 }
Member Data Documentation
broadcast_address_
std::string diag::client::conversation::VdConversation::broadcast_address_ private
Store the broadcast Ip address of the conversation.
Definition at line 203 of file vd_conversation.h.
connection_ptr_
std::unique_ptr<::uds_transport::Connection> diag::client::conversation::VdConversation::connection_ptr_ private
Store the underlying transport protocol connection object.
Definition at line 208 of file vd_conversation.h.
Referenced by Shutdown(), and Startup().
conversation_name_
std::string diag::client::conversation::VdConversation::conversation_name_ private
Store the conversation name.
Definition at line 198 of file vd_conversation.h.
vd_conversion_handler_
std::unique_ptr<::uds_transport::ConversionHandler> diag::client::conversation::VdConversation::vd_conversion_handler_ private
Store the vd conversation handler.
Definition at line 193 of file vd_conversation.h.
Referenced by GetConversationHandler().
vehicle_info_collection_
std::map<std::uint16_t, VehicleAddrInfoResponseStruct> diag::client::conversation::VdConversation::vehicle_info_collection_ private
Store the vehicle info collection received till now.
Definition at line 213 of file vd_conversation.h.
vehicle_info_container_mutex_
std::mutex diag::client::conversation::VdConversation::vehicle_info_container_mutex_ private
Mutex to lock the vehicle info collection container.
Definition at line 218 of file vd_conversation.h.
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/dcm/conversation/vd_conversation.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/dcm/conversation/vd_conversation.cpp