Diag-Client-Lib: utility::thread::Thread Class Reference
utility::thread::Thread Class Reference final
#include <thread.h>
Public Member Functions
Thread () noexcept=default
Default constructor.
template<typename Callable , typename... Args>
Thread (std::string const &thread_name, Callable &&callable, Args &&...args) noexcept
Constructor to start the thread with passed callable and arguments.
Thread (const Thread &other) noexcept=delete
Deleted copy assignment and copy constructor.
Thread & operator= (const Thread &other) noexcept=delete
Thread (Thread &&other) noexcept=default
Defaulted move assignment and move constructor.
Thread & operator= (Thread &&other) noexcept=default
~Thread () noexcept
Destructor.
void Join () noexcept
Function to join the running thread.
Private Attributes
std::thread thread_ {}
Detailed Description
Definition at line 20 of file thread.h.
Constructor & Destructor Documentation
Thread() [1/4]
utility::thread::Thread::Thread () default noexcept
Default constructor.
Thread() [2/4]
template<typename Callable , typename... Args> utility::thread::Thread::Thread (std::string const & thread_name, Callable && callable, Args &&... args) inline noexcept
Constructor to start the thread with passed callable and arguments.
Template Parameters
Callable The callable that is invoked by created thread
Args The arguments passed to the callable
Definition at line 36 of file thread.h.
       : thread_{std::forward<Callable>(callable), std::forward<Args>(args)...} {
     // Set thread name
     pthread_setname_np(thread_.native_handle(), thread_name.c_str());
   }
Thread() [3/4]
utility::thread::Thread::Thread (const Thread & other) delete noexcept
Deleted copy assignment and copy constructor.
Thread() [4/4]
utility::thread::Thread::Thread (Thread && other) default noexcept
Defaulted move assignment and move constructor.
~Thread()
utility::thread::Thread::~Thread () inline noexcept
Destructor.
Definition at line 57 of file thread.h.
 { Join(); }
References Join().
Member Function Documentation
Join()
void utility::thread::Thread::Join () inline noexcept
Function to join the running thread.
Definition at line 62 of file thread.h.
{
     if (thread_.joinable()) { thread_.join(); }
   }
References thread_.
Referenced by diag::client::DiagClient::DiagClientImpl::DeInitialize(), boost_support::socket::IoContext::~IoContext(), and ~Thread().
operator=() [1/2]
Thread& utility::thread::Thread::operator= (const Thread & other) delete noexcept
operator=() [2/2]
Thread& utility::thread::Thread::operator= (Thread && other) default noexcept
Member Data Documentation
thread_
std::thread utility::thread::Thread::thread_ {} private
Definition at line 67 of file thread.h.
Referenced by Join().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/utility-support/utility/thread.h