Diag-Client-Lib: boost_support::socket::tcp::TcpSocket Class Reference
boost_support::socket::tcp::TcpSocket Class Reference final
Class used to create a tcp socket for handling transmission and reception of tcp message from driver.
#include <tcp_socket.h>
Public Types
enum class SocketError : std::uint8_t { kOpenFailed , kBindingFailed , kRemoteDisconnected , kGenericError }
Socket error code.
using TcpMessage = boost_support::message::tcp::TcpMessage
Type alias for Tcp message.
using TcpMessagePtr = boost_support::message::tcp::TcpMessagePtr
Type alias for Tcp message pointer.
using TcpMessageConstPtr = boost_support::message::tcp::TcpMessageConstPtr
Type alias for Tcp message const pointer.
using Tcp = boost::asio::ip::tcp
Type alias for tcp protocol.
using Socket = Tcp::socket
Type alias for tcp socket.
Public Member Functions
TcpSocket (std::string_view local_ip_address, std::uint16_t local_port_num, IoContext &io_context) noexcept
Constructs an instance of TcpSocket.
TcpSocket (Socket socket) noexcept
Constructs an instance of TcpSocket.
TcpSocket (const TcpSocket &other) noexcept=delete
Deleted copy assignment and copy constructor.
TcpSocket & operator= (const TcpSocket &other) noexcept=delete
TcpSocket (TcpSocket &&other) noexcept=default
Move assignment and Move constructor.
TcpSocket & operator= (TcpSocket &&other) noexcept=default
~TcpSocket () noexcept
Destruct an instance of TcpSocket.
core_type::Result< void, SocketError > Open () noexcept
Function to open and bind the socket to provided ip address & port.
core_type::Result< void, SocketError > Connect (std::string_view host_ip_address, std::uint16_t host_port_num) noexcept
Function to connect to remote ip address and port number.
core_type::Result< void, SocketError > Disconnect () noexcept
Function to Disconnect from host.
core_type::Result< void, SocketError > Transmit (TcpMessageConstPtr tcp_message) noexcept
Function to trigger transmission.
core_type::Result< TcpMessagePtr, SocketError > Read () noexcept
Function to read message from socket.
core_type::Result< void, SocketError > Close () noexcept
Function to destroy the socket.
Private Types
using TcpIpAddress = boost::asio::ip::address
Type alias for tcp ip address.
using TcpErrorCodeType = boost::system::error_code
Type alias for tcp error codes.
Private Attributes
Socket tcp_socket_
Store the underlying tcp socket.
Tcp::endpoint local_endpoint_
Store the local endpoints.
Detailed Description
Class used to create a tcp socket for handling transmission and reception of tcp message from driver.
Definition at line 24 of file tcp_socket.h.
Member Typedef Documentation
Socket
using boost_support::socket::tcp::TcpSocket::Socket = Tcp::socket
Type alias for tcp socket.
Definition at line 59 of file tcp_socket.h.
Tcp
using boost_support::socket::tcp::TcpSocket::Tcp = boost::asio::ip::tcp
Type alias for tcp protocol.
Definition at line 54 of file tcp_socket.h.
TcpErrorCodeType
using boost_support::socket::tcp::TcpSocket::TcpErrorCodeType = boost::system::error_code private
Type alias for tcp error codes.
Definition at line 150 of file tcp_socket.h.
TcpIpAddress
using boost_support::socket::tcp::TcpSocket::TcpIpAddress = boost::asio::ip::address private
Type alias for tcp ip address.
Definition at line 145 of file tcp_socket.h.
TcpMessage
using boost_support::socket::tcp::TcpSocket::TcpMessage = boost_support::message::tcp::TcpMessage
Type alias for Tcp message.
Definition at line 39 of file tcp_socket.h.
TcpMessageConstPtr
using boost_support::socket::tcp::TcpSocket::TcpMessageConstPtr = boost_support::message::tcp::TcpMessageConstPtr
Type alias for Tcp message const pointer.
Definition at line 49 of file tcp_socket.h.
TcpMessagePtr
using boost_support::socket::tcp::TcpSocket::TcpMessagePtr = boost_support::message::tcp::TcpMessagePtr
Type alias for Tcp message pointer.
Definition at line 44 of file tcp_socket.h.
Member Enumeration Documentation
SocketError
enum boost_support::socket::tcp::TcpSocket::SocketError : std::uint8_t strong
Socket error code.
Enumerator
kOpenFailed
kBindingFailed
kRemoteDisconnected
kGenericError
Definition at line 29 of file tcp_socket.h.
                          : std::uint8_t {
     kOpenFailed,
     kBindingFailed,
     kRemoteDisconnected,
     kGenericError
   };
Constructor & Destructor Documentation
TcpSocket() [1/4]
boost_support::socket::tcp::TcpSocket::TcpSocket (std::string_view local_ip_address, std::uint16_t local_port_num, IoContext & io_context) noexcept
Constructs an instance of TcpSocket.
Parameters
[in] local_ip_address The local ip address
[in] local_port_num The local port number
[in] io_context The I/O context required to create socket
Definition at line 19 of file tcp_socket.cpp.
     : tcp_socket_{io_context.GetContext()},
       local_endpoint_{boost::asio::ip::make_address(local_ip_address), local_port_num} {}
TcpSocket() [2/4]
boost_support::socket::tcp::TcpSocket::TcpSocket (TcpSocket::Socket socket) explicit noexcept
Constructs an instance of TcpSocket.
Parameters
[in] socket The socket
Definition at line 24 of file tcp_socket.cpp.
     : tcp_socket_{std::move(socket)},
       local_endpoint_{tcp_socket_.local_endpoint()} {}
TcpSocket() [3/4]
boost_support::socket::tcp::TcpSocket::TcpSocket (const TcpSocket & other) delete noexcept
Deleted copy assignment and copy constructor.
TcpSocket() [4/4]
boost_support::socket::tcp::TcpSocket::TcpSocket (TcpSocket && other) default noexcept
Move assignment and Move constructor.
~TcpSocket()
boost_support::socket::tcp::TcpSocket::~TcpSocket () default noexcept
Destruct an instance of TcpSocket.
Member Function Documentation
Close()
core_type::Result< void, TcpSocket::SocketError > boost_support::socket::tcp::TcpSocket::Close () noexcept
Function to destroy the socket.
Returns
Empty result on success otherwise error code
Definition at line 141 of file tcp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   // destroy the socket
   tcp_socket_.shutdown(boost::asio::socket_base::shutdown_receive);
   tcp_socket_.close();
   result.EmplaceValue();
   return result;
 }
References kGenericError, and tcp_socket_.
Connect()
core_type::Result< void, TcpSocket::SocketError > boost_support::socket::tcp::TcpSocket::Connect (std::string_view host_ip_address, std::uint16_t host_port_num) noexcept
Function to connect to remote ip address and port number.
Parameters
[in] host_ip_address The host ip address
[in] host_port_num The host port number
Returns
Empty result on success otherwise error code
Definition at line 72 of file tcp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   // Connect to provided Ip address
   tcp_socket_.connect(
       Tcp::endpoint(TcpIpAddress::from_string(std::string{host_ip_address}), host_port_num), ec);
   if (ec.value() == boost::system::errc::success) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           Tcp::endpoint const endpoint_{tcp_socket_.remote_endpoint()};
           msg << "Tcp Socket connected to host "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp Socket connect to host failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, and boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
Disconnect()
core_type::Result< void, TcpSocket::SocketError > boost_support::socket::tcp::TcpSocket::Disconnect () noexcept
Function to Disconnect from host.
Returns
Empty result on success otherwise error code
Definition at line 97 of file tcp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   // Graceful shutdown
   tcp_socket_.shutdown(Socket::shutdown_both, ec);
   if (ec.value() == boost::system::errc::success) {
     // Socket shutdown success
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp Socket disconnection from host failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), kGenericError, and tcp_socket_.
Open()
core_type::Result< void, TcpSocket::SocketError > boost_support::socket::tcp::TcpSocket::Open () noexcept
Function to open and bind the socket to provided ip address & port.
Returns
Empty result on success otherwise error code
Definition at line 30 of file tcp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   // Open the socket
   tcp_socket_.open(local_endpoint_.protocol(), ec);
   if (ec.value() == boost::system::errc::success) {
     // reuse address
     tcp_socket_.set_option(boost::asio::socket_base::reuse_address{true});
     // Set socket to non blocking
     tcp_socket_.non_blocking(false);
     // Bind to local ip address and random port
     tcp_socket_.bind(local_endpoint_, ec);
     if (ec.value() == boost::system::errc::success) {
       local_endpoint_ = tcp_socket_.local_endpoint();
       // Socket binding success
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
             Tcp::endpoint const endpoint_{tcp_socket_.local_endpoint()};
             msg << "Tcp Socket opened and bound to "
                 << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
           });
       result.EmplaceValue();
     } else {
       // Socket binding failed
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
             msg << "Tcp Socket binding failed with message: " << ec.message();
           });
       result.EmplaceError(SocketError::kBindingFailed);
     }
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp Socket opening failed with error: " << ec.message();
         });
     result.EmplaceError(SocketError::kOpenFailed);
   }
   return result;
 }
References FILE_NAME, and boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
operator=() [1/2]
TcpSocket& boost_support::socket::tcp::TcpSocket::operator= (const TcpSocket & other) delete noexcept
operator=() [2/2]
TcpSocket& boost_support::socket::tcp::TcpSocket::operator= (TcpSocket && other) default noexcept
Read()
core_type::Result< TcpSocket::TcpMessagePtr, TcpSocket::SocketError > boost_support::socket::tcp::TcpSocket::Read () noexcept
Function to read message from socket.
Returns
Tcp message on success otherwise error code
Definition at line 150 of file tcp_socket.cpp.
{
   core_type::Result<TcpMessagePtr, SocketError> result{SocketError::kRemoteDisconnected};
   TcpErrorCodeType ec{};
   // create and reserve the buffer
   TcpMessage::BufferType rx_buffer{};
   rx_buffer.resize(message::tcp::kDoipheadrSize);
   // start blocking read to read Header first
   boost::asio::read(tcp_socket_, boost::asio::buffer(&rx_buffer[0u], message::tcp::kDoipheadrSize),
                     ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     // read the next bytes to read
     std::uint32_t const read_next_bytes{[&rx_buffer]() noexcept -> std::uint32_t {
       return static_cast<std::uint32_t>(
           (static_cast<std::uint32_t>(rx_buffer[4u] << 24u) & 0xFF000000) |
           (static_cast<std::uint32_t>(rx_buffer[5u] << 16u) & 0x00FF0000) |
           (static_cast<std::uint32_t>(rx_buffer[6u] << 8u) & 0x0000FF00) |
           (static_cast<std::uint32_t>(rx_buffer[7u] & 0x000000FF)));
     }()};
     if (read_next_bytes != 0u) {
       // reserve the buffer
       rx_buffer.resize(message::tcp::kDoipheadrSize + std::size_t(read_next_bytes));
       boost::asio::read(
           tcp_socket_,
           boost::asio::buffer(&rx_buffer[message::tcp::kDoipheadrSize], read_next_bytes), ec);
       Tcp::endpoint const remote_endpoint{tcp_socket_.remote_endpoint()};
       TcpMessagePtr tcp_rx_message{std::make_unique<TcpMessage>(
           remote_endpoint.address().to_string(), remote_endpoint.port(), std::move(rx_buffer))};
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__, [&remote_endpoint](std::stringstream &msg) {
             msg << "Tcp Message received from "
                 << "<" << remote_endpoint.address().to_string() << "," << remote_endpoint.port()
                 << ">";
           });
       result.EmplaceValue(std::move(tcp_rx_message));
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
           FILE_NAME, __LINE__, __func__,
           [](std::stringstream &msg) { msg << "Tcp Message read ignored as header size is zero"; });
     }
   } else if (ec.value() == boost::asio::error::eof) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__,
         [ec](std::stringstream &msg) { msg << "Remote Disconnected with: " << ec.message(); });
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Remote Disconnected with undefined error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), boost_support::message::tcp::kDoipheadrSize, kRemoteDisconnected, and tcp_socket_.
Transmit()
core_type::Result< void, TcpSocket::SocketError > boost_support::socket::tcp::TcpSocket::Transmit (TcpMessageConstPtr tcp_message) noexcept
Function to trigger transmission.
Parameters
[in] tcp_message The tcp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 115 of file tcp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   TcpErrorCodeType ec{};
   boost::asio::write(
       tcp_socket_,
       boost::asio::buffer(tcp_message->GetPayload().data(), tcp_message->GetPayload().size()), ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           Tcp::endpoint const endpoint_{tcp_socket_.remote_endpoint()};
           msg << "Tcp message sent to "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     result.EmplaceValue();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Tcp message sending failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, and boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
Member Data Documentation
local_endpoint_
Tcp::endpoint boost_support::socket::tcp::TcpSocket::local_endpoint_ private
Store the local endpoints.
Definition at line 160 of file tcp_socket.h.
tcp_socket_
Socket boost_support::socket::tcp::TcpSocket::tcp_socket_ private
Store the underlying tcp socket.
Definition at line 155 of file tcp_socket.h.
Referenced by Close(), Disconnect(), and Read().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tcp/tcp_socket.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/tcp/tcp_socket.cpp