Diag-Client-Lib: boost_support::socket::udp::UdpSocket Class Reference
boost_support::socket::udp::UdpSocket Class Reference final
Class used to create a udp socket for handling transmission and reception of udp message from driver.
#include <udp_socket.h>
Public Types
enum class SocketError : std::uint8_t { kOpenFailed , kBindingFailed , kGenericError }
Socket error code.
using UdpMessage = boost_support::message::udp::UdpMessage
Type alias for Tcp message.
using UdpMessagePtr = boost_support::message::udp::UdpMessagePtr
Type alias for Udp message pointer.
using UdpMessageConstPtr = boost_support::message::udp::UdpMessageConstPtr
Type alias for Udp message const pointer.
using Udp = boost::asio::ip::udp
Type alias for Udp protocol.
using Socket = Udp::socket
Type alias for Udp socket.
using UdpHandlerRead = std::function< void(UdpMessagePtr)>
Udp function template used for reception.
Public Member Functions
UdpSocket (std::string_view local_ip_address, std::uint16_t local_port_num, boost::asio::io_context &io_context) noexcept
Constructs an instance of TcpSocket.
UdpSocket (const UdpSocket &other) noexcept=delete
Deleted copy assignment and copy constructor.
UdpSocket & operator= (const UdpSocket &other) noexcept=delete
UdpSocket (UdpSocket &&other) noexcept=default
Move assignment and Move constructor.
UdpSocket & operator= (UdpSocket &&other) noexcept=default
~UdpSocket () noexcept
Destruct an instance of TcpSocket.
void SetReadHandler (UdpHandlerRead read_handler)
Function to set the read handler that is invoked when message is received.
core_type::Result< void, SocketError > Open () noexcept
Function to open and bind the socket to provided ip address & port.
core_type::Result< void, SocketError > Transmit (UdpMessageConstPtr udp_message) noexcept
Function to trigger transmission.
core_type::Result< void, SocketError > Close () noexcept
Function to destroy the socket.
Private Types
using UdpErrorCodeType = boost::system::error_code
Type alias for udp error codes.
Private Member Functions
core_type::Result< UdpMessagePtr > Read (std::size_t bytes_received)
Function to handle the reception of tcp message.
void StartReceivingMessage ()
Function to start reception of Udp dataframe.
Private Attributes
Socket udp_socket_
Store the underlying udp socket.
Udp::endpoint local_endpoint_
Store the local endpoints.
Udp::endpoint remote_endpoint_
Store the remote endpoints.
std::vector< std::uint8_t > rx_buffer_
Reception buffer needed for async reception of udp data.
UdpHandlerRead udp_handler_read_
Store the handler.
Detailed Description
Class used to create a udp socket for handling transmission and reception of udp message from driver.
Definition at line 24 of file udp_socket.h.
Member Typedef Documentation
Socket
using boost_support::socket::udp::UdpSocket::Socket = Udp::socket
Type alias for Udp socket.
Definition at line 54 of file udp_socket.h.
Udp
using boost_support::socket::udp::UdpSocket::Udp = boost::asio::ip::udp
Type alias for Udp protocol.
Definition at line 49 of file udp_socket.h.
UdpErrorCodeType
using boost_support::socket::udp::UdpSocket::UdpErrorCodeType = boost::system::error_code private
Type alias for udp error codes.
Definition at line 123 of file udp_socket.h.
UdpHandlerRead
using boost_support::socket::udp::UdpSocket::UdpHandlerRead = std::function<void(UdpMessagePtr)>
Udp function template used for reception.
Definition at line 59 of file udp_socket.h.
UdpMessage
using boost_support::socket::udp::UdpSocket::UdpMessage = boost_support::message::udp::UdpMessage
Type alias for Tcp message.
Definition at line 34 of file udp_socket.h.
UdpMessageConstPtr
using boost_support::socket::udp::UdpSocket::UdpMessageConstPtr = boost_support::message::udp::UdpMessageConstPtr
Type alias for Udp message const pointer.
Definition at line 44 of file udp_socket.h.
UdpMessagePtr
using boost_support::socket::udp::UdpSocket::UdpMessagePtr = boost_support::message::udp::UdpMessagePtr
Type alias for Udp message pointer.
Definition at line 39 of file udp_socket.h.
Member Enumeration Documentation
SocketError
enum boost_support::socket::udp::UdpSocket::SocketError : std::uint8_t strong
Socket error code.
Enumerator
kOpenFailed
kBindingFailed
kGenericError
Definition at line 29 of file udp_socket.h.
 : std::uint8_t { kOpenFailed, kBindingFailed, kGenericError };
Constructor & Destructor Documentation
UdpSocket() [1/3]
boost_support::socket::udp::UdpSocket::UdpSocket (std::string_view local_ip_address, std::uint16_t local_port_num, boost::asio::io_context & io_context) noexcept
Constructs an instance of TcpSocket.
Parameters
[in] local_ip_address The local ip address
[in] local_port_num The local port number
[in] io_context The I/O context required to create socket
Definition at line 20 of file udp_socket.cpp.
     : udp_socket_{io_context},
       local_endpoint_{boost::asio::ip::make_address(local_ip_address), local_port_num} {
   rx_buffer_.resize(message::udp::kMaxUdpResSize);
 }
UdpSocket() [2/3]
boost_support::socket::udp::UdpSocket::UdpSocket (const UdpSocket & other) delete noexcept
Deleted copy assignment and copy constructor.
UdpSocket() [3/3]
boost_support::socket::udp::UdpSocket::UdpSocket (UdpSocket && other) default noexcept
Move assignment and Move constructor.
~UdpSocket()
boost_support::socket::udp::UdpSocket::~UdpSocket () default noexcept
Destruct an instance of TcpSocket.
Member Function Documentation
Close()
core_type::Result< void, UdpSocket::SocketError > boost_support::socket::udp::UdpSocket::Close () noexcept
Function to destroy the socket.
Returns
Empty result on success otherwise error code
Definition at line 101 of file udp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   // destroy the socket
   udp_socket_.close();
   result.EmplaceValue();
   return result;
 }
References kGenericError, and udp_socket_.
Open()
core_type::Result< void, UdpSocket::SocketError > boost_support::socket::udp::UdpSocket::Open () noexcept
Function to open and bind the socket to provided ip address & port.
Returns
Empty result on success otherwise error code
Definition at line 33 of file udp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kOpenFailed};
   UdpErrorCodeType ec{};
   udp_socket_.open(local_endpoint_.protocol(), ec);
   if (ec.value() == boost::system::errc::success) {
     // set broadcast option
     udp_socket_.set_option(boost::asio::socket_base::broadcast{true});
     // reuse address
     udp_socket_.set_option(boost::asio::socket_base::reuse_address{true});
     udp_socket_.bind(local_endpoint_, ec);
   }
   if (ec.value() == boost::system::errc::success) {
     local_endpoint_ = udp_socket_.local_endpoint();
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           msg << "Udp Socket opened and bound to "
               << "<" << local_endpoint_.address() << "," << local_endpoint_.port() << ">";
         });
     // start async receive
     StartReceivingMessage();
     result.EmplaceValue();
   } else {
     // Socket binding failed
     result.EmplaceError(SocketError::kBindingFailed);
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [ec](std::stringstream &msg) {
           msg << "Udp Socket Bind failed with message: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), kBindingFailed, kOpenFailed, local_endpoint_, StartReceivingMessage(), and udp_socket_.
operator=() [1/2]
UdpSocket& boost_support::socket::udp::UdpSocket::operator= (const UdpSocket & other) delete noexcept
operator=() [2/2]
UdpSocket& boost_support::socket::udp::UdpSocket::operator= (UdpSocket && other) default noexcept
Read()
core_type::Result< UdpSocket::UdpMessagePtr > boost_support::socket::udp::UdpSocket::Read (std::size_t bytes_received) private
Function to handle the reception of tcp message.
Parameters
[in] bytes_received The number of bytes to be read
Returns
Udp Message created from received data on success, otherwise error
Definition at line 109 of file udp_socket.cpp.
{
   core_type::Result<UdpMessagePtr> result{
       error_domain::MakeErrorCode(error_domain::BoostSupportErrorErrc::kGenericError)};
   // Ignore self reception
   if (local_endpoint_.address().to_string() != remote_endpoint_.address().to_string()) {
     UdpMessage::BufferType received_data{};
     received_data.reserve(total_bytes_received);
     // Received message must be less than max udp message
     assert(total_bytes_received <= message::udp::kMaxUdpResSize);
     // copy the received bytes into local buffer
     received_data.insert(received_data.begin(), rx_buffer_.begin(),
                          rx_buffer_.begin() + static_cast<std::uint8_t>(total_bytes_received));
     UdpMessagePtr udp_rx_message{std::make_unique<UdpMessage>(
         remote_endpoint_.address().to_string(), remote_endpoint_.port(), std::move(received_data))};
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogInfo(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           msg << "Udp Message received from: "
               << "<" << remote_endpoint_.address() << "," << remote_endpoint_.port() << ">";
         });
     result.EmplaceValue(std::move(udp_rx_message));
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogVerbose(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           msg << "Udp Message received from "
               << "<" << remote_endpoint_.address() << "," << remote_endpoint_.port() << ">"
               << " ignored as received by self ip"
               << " <" << local_endpoint_.address() << "," << local_endpoint_.port() << ">";
         });
   }
   // start async receive
   StartReceivingMessage();
   return result;
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), boost_support::error_domain::kGenericError, boost_support::message::udp::kMaxUdpResSize, local_endpoint_, boost_support::error_domain::MakeErrorCode(), remote_endpoint_, rx_buffer_, and StartReceivingMessage().
SetReadHandler()
void boost_support::socket::udp::UdpSocket::SetReadHandler (UdpSocket::UdpHandlerRead read_handler)
Function to set the read handler that is invoked when message is received.
The ownership of provided read handler is moved
Parameters
[in] read_handler The handler to be set
Definition at line 29 of file udp_socket.cpp.
{
   udp_handler_read_ = std::move(read_handler);
 }
StartReceivingMessage()
void boost_support::socket::udp::UdpSocket::StartReceivingMessage () private
Function to start reception of Udp dataframe.
Definition at line 146 of file udp_socket.cpp.
{
   // start async receive
   udp_socket_.async_receive_from(
       boost::asio::buffer(rx_buffer_), remote_endpoint_,
       [this](const UdpErrorCodeType &error, std::size_t bytes_received) {
         if (error.value() == boost::system::errc::success) {
           static_cast<void>(Read(bytes_received).AndThen([this](UdpMessagePtr udp_message) {
             // send data to upper layer
             if (udp_handler_read_) { udp_handler_read_(std::move(udp_message)); }
             return core_type::Result<void>::FromValue();
           }));
         } else {
           if (error.value() != boost::asio::error::operation_aborted) {
             common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
                 FILE_NAME, __LINE__, __func__, [error](std::stringstream &msg) {
                   msg << "Remote Disconnected with undefined error: " << error.message();
                 });
           }
         }
       });
 }
References FILE_NAME, boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), remote_endpoint_, rx_buffer_, and udp_socket_.
Referenced by Open(), and Read().
Transmit()
core_type::Result< void, UdpSocket::SocketError > boost_support::socket::udp::UdpSocket::Transmit (UdpSocket::UdpMessageConstPtr udp_message) noexcept
Function to trigger transmission.
Parameters
[in] udp_message The udp message to be transmitted
Returns
Empty result on success otherwise error code
Definition at line 65 of file udp_socket.cpp.
{
   core_type::Result<void, SocketError> result{SocketError::kGenericError};
   UdpErrorCodeType ec{};
   // Transmit to remote endpoints
   std::size_t const send_size{udp_socket_.send_to(
       boost::asio::buffer(udp_message->GetPayload().data(), udp_message->GetPayload().size()),
       Udp::endpoint{boost::asio::ip::make_address(udp_message->GetHostIpAddress()),
                     udp_message->GetHostPortNumber()},
       {}, ec)};
   // Check for error
   if (ec.value() == boost::system::errc::success && send_size == udp_message->GetPayload().size()) {
     // successful
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         FILE_NAME, __LINE__, __func__, [this, &udp_message](std::stringstream &msg) {
           msg << "Udp message sent : "
               << "<" << local_endpoint_.address() << "," << local_endpoint_.port() << ">"
               << " -> "
               << "<" << udp_message->GetHostIpAddress() << "," << udp_message->GetHostPortNumber()
               << ">";
         });
     result.EmplaceValue();
     // start async receive
     StartReceivingMessage();
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [&ec, &udp_message](std::stringstream &msg) {
           msg << "Udp message sending to "
               << "<" << udp_message->GetHostIpAddress() << "> "
               << "failed with error: " << ec.message();
         });
   }
   return result;
 }
References FILE_NAME, and boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
Member Data Documentation
local_endpoint_
Udp::endpoint boost_support::socket::udp::UdpSocket::local_endpoint_ private
Store the local endpoints.
Definition at line 133 of file udp_socket.h.
Referenced by Open(), and Read().
remote_endpoint_
Udp::endpoint boost_support::socket::udp::UdpSocket::remote_endpoint_ private
Store the remote endpoints.
Definition at line 138 of file udp_socket.h.
Referenced by Read(), and StartReceivingMessage().
rx_buffer_
std::vector<std::uint8_t> boost_support::socket::udp::UdpSocket::rx_buffer_ private
Reception buffer needed for async reception of udp data.
Definition at line 143 of file udp_socket.h.
Referenced by Read(), and StartReceivingMessage().
udp_handler_read_
UdpHandlerRead boost_support::socket::udp::UdpSocket::udp_handler_read_ private
Store the handler.
Definition at line 148 of file udp_socket.h.
udp_socket_
Socket boost_support::socket::udp::UdpSocket::udp_socket_ private
Store the underlying udp socket.
Definition at line 128 of file udp_socket.h.
Referenced by Close(), Open(), and StartReceivingMessage().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/udp/udp_socket.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/socket/udp/udp_socket.cpp