Diag-Client-Lib: boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection Class Reference
boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection Class Reference
#include <tcp_server.h>
Public Member Functions
TcpServerConnection (boost::asio::io_context &io_context, TcpHandlerRead &&tcp_handler_read)
~TcpServerConnection ()=default
TcpServerConnection (TcpServerConnection &&)=default
TcpServerConnection & operator= (TcpServerConnection &&)=default
TcpServerConnection (TcpServerConnection &)=delete
TcpServerConnection & operator= (TcpServerConnection &)=delete
TcpSocket & GetSocket ()
bool Transmit (TcpMessageConstPtr udp_tx_message)
bool ReceivedMessage ()
bool Shutdown ()
Private Attributes
TcpSocket tcp_socket_
TcpHandlerRead tcp_handler_read_
Detailed Description
Definition at line 31 of file tcp_server.h.
Constructor & Destructor Documentation
TcpServerConnection() [1/3]
boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::TcpServerConnection (boost::asio::io_context & io_context, TcpHandlerRead && tcp_handler_read)
Definition at line 53 of file tcp_server.cpp.
     : tcp_socket_{io_context},
       tcp_handler_read_{tcp_handler_read} {}
~TcpServerConnection()
boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::~TcpServerConnection () default
TcpServerConnection() [2/3]
boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::TcpServerConnection (TcpServerConnection &&) default
TcpServerConnection() [3/3]
boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::TcpServerConnection (TcpServerConnection &) delete
Member Function Documentation
GetSocket()
TcpSocket & boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::GetSocket ()
Definition at line 58 of file tcp_server.cpp.
 { return tcp_socket_; }
operator=() [1/2]
TcpServerConnection& boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::operator= (TcpServerConnection &&) default
operator=() [2/2]
TcpServerConnection& boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::operator= (TcpServerConnection &) delete
ReceivedMessage()
bool boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::ReceivedMessage ()
Definition at line 83 of file tcp_server.cpp.
{
   TcpErrorCodeType ec;
   bool connection_closed{false};
   // create and reserve the buffer
   TcpMessage::BufferType rx_buffer{};
   rx_buffer.resize(kDoipheadrSize);
   // start blocking read to read Header first
   boost::asio::read(tcp_socket_, boost::asio::buffer(&rx_buffer[0], kDoipheadrSize), ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     // read the next bytes to read
     std::uint32_t const read_next_bytes = [&rx_buffer]() noexcept -> std::uint32_t {
       return static_cast<std::uint32_t>((static_cast<std::uint32_t>(rx_buffer[4u] << 24u) & 0xFF000000) |
                                         (static_cast<std::uint32_t>(rx_buffer[5u] << 16u) & 0x00FF0000) |
                                         (static_cast<std::uint32_t>(rx_buffer[6u] << 8u) & 0x0000FF00) |
                                         (static_cast<std::uint32_t>(rx_buffer[7u] & 0x000000FF)));
     }();
     // reserve the buffer
     rx_buffer.resize(kDoipheadrSize + std::size_t(read_next_bytes));
     boost::asio::read(tcp_socket_, boost::asio::buffer(&rx_buffer[kDoipheadrSize], read_next_bytes), ec);
     // all message received, transfer to upper layer
     Tcp::endpoint endpoint_{tcp_socket_.remote_endpoint()};
     TcpMessagePtr tcp_rx_message{
         std::make_unique<TcpMessage>(endpoint_.address().to_string(), endpoint_.port(), std::move(rx_buffer))};
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         __FILE__, __LINE__, __func__, [endpoint_](std::stringstream &msg) {
           msg << "Tcp Message received from "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     // send data to upper layer
     tcp_handler_read_(std::move(tcp_rx_message));
   } else if (ec.value() == boost::asio::error::eof) {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         __FILE__, __LINE__, __func__,
         [ec](std::stringstream &msg) { msg << "Remote Disconnected with: " << ec.message(); });
     connection_closed = true;
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         __FILE__, __LINE__, __func__,
         [ec](std::stringstream &msg) { msg << "Remote Disconnected with undefined error: " << ec.message(); });
     connection_closed = true;
   }
   return connection_closed;
 }
References boost_support::common::logger::LibBoostLogger::GetLibBoostLogger(), and boost_support::socket::tcp::kDoipheadrSize.
Shutdown()
bool boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::Shutdown ()
Definition at line 130 of file tcp_server.cpp.
{
   TcpErrorCodeType ec{};
   bool ret_val{false};
   // Graceful shutdown
   if (tcp_socket_.is_open()) {
     tcp_socket_.shutdown(TcpSocket::shutdown_both, ec);
     if (ec.value() == boost::system::errc::success) {
       ret_val = true;
     } else {
       common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
           __FILE__, __LINE__, __func__,
           [ec](std::stringstream &msg) { msg << "Tcp Socket Disconnection failed with error: " << ec.message(); });
     }
     tcp_socket_.close();
   }
   return ret_val;
 }
References boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
Transmit()
bool boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::Transmit (TcpMessageConstPtr udp_tx_message)
Definition at line 60 of file tcp_server.cpp.
{
   TcpErrorCodeType ec{};
   bool ret_val{false};
   boost::asio::write(
       tcp_socket_,
       boost::asio::buffer(tcp_tx_message->GetTxBuffer(), std::size_t(tcp_tx_message->GetTxBuffer().size())), ec);
   // Check for error
   if (ec.value() == boost::system::errc::success) {
     Tcp::endpoint endpoint_{tcp_socket_.remote_endpoint()};
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogDebug(
         __FILE__, __LINE__, __func__, [endpoint_](std::stringstream &msg) {
           msg << "Tcp message sent to "
               << "<" << endpoint_.address().to_string() << "," << endpoint_.port() << ">";
         });
     ret_val = true;
   } else {
     common::logger::LibBoostLogger::GetLibBoostLogger().GetLogger().LogError(
         __FILE__, __LINE__, __func__,
         [ec](std::stringstream &msg) { msg << "Tcp message sending failed with error: " << ec.message(); });
   }
   return ret_val;
 }
References boost_support::common::logger::LibBoostLogger::GetLibBoostLogger().
Member Data Documentation
tcp_handler_read_
TcpHandlerRead boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::tcp_handler_read_ private
Definition at line 66 of file tcp_server.h.
tcp_socket_
TcpSocket boost_support::socket::tcp::CreateTcpServerSocket::TcpServerConnection::tcp_socket_ private
Definition at line 63 of file tcp_server.h.
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/socket/tcp/tcp_server.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/socket/tcp/tcp_server.cpp