Diag-Client-Lib: diag::client::common::DiagnosticManager Class Reference
diag::client::common::DiagnosticManager Class Reference abstract
Parent class to create Diagnostic Manager.
#include <diagnostic_manager.h>
Public Member Functions
DiagnosticManager () noexcept
Constructs an instance of DiagnosticManager.
DiagnosticManager (const DiagnosticManager &other) noexcept=delete
Deleted copy assignment and copy constructor.
DiagnosticManager & operator= (const DiagnosticManager &other) noexcept=delete
DiagnosticManager (DiagnosticManager &&other) noexcept=delete
Deleted move assignment and move constructor.
DiagnosticManager & operator= (DiagnosticManager &&other) noexcept=delete
virtual ~DiagnosticManager () noexcept
Destructs an instance of DiagnosticManager.
virtual void Main () noexcept
Function to manage the whole lifecycle of DiagnosticManager.
virtual Result< void > SignalShutdown () noexcept
Function to initiate shutdown of DiagnosticManager.
virtual void Initialize () noexcept=0
Function to initialize the DiagnosticManager.
virtual void Run () noexcept=0
Function to run DiagnosticManager.
virtual void Shutdown () noexcept=0
Function to shutdown the DiagnosticManager.
virtual conversation::DiagClientConversation GetDiagnosticClientConversation (std::string_view conversation_name) noexcept=0
Function to get required diag client conversation object based on conversation name.
virtual core_type::Result< diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > SendVehicleIdentificationRequest (diag::client::vehicle_info::VehicleInfoListRequestType vehicle_info_request) noexcept=0
Function to send vehicle identification request and get the Diagnostic Server list.
Private Attributes
bool exit_requested_
Flag to terminate the main thread.
std::condition_variable cond_var_
Conditional variable to block the thread.
std::mutex mutex_
For locking critical section of code.
Detailed Description
Parent class to create Diagnostic Manager.
Definition at line 31 of file diagnostic_manager.h.
Constructor & Destructor Documentation
DiagnosticManager() [1/3]
diag::client::common::DiagnosticManager::DiagnosticManager () noexcept
Constructs an instance of DiagnosticManager.
Definition at line 14 of file diagnostic_manager.cpp.
 : exit_requested_{false}, cond_var_{}, mutex_{} {}
DiagnosticManager() [2/3]
diag::client::common::DiagnosticManager::DiagnosticManager (const DiagnosticManager & other) delete noexcept
Deleted copy assignment and copy constructor.
DiagnosticManager() [3/3]
diag::client::common::DiagnosticManager::DiagnosticManager (DiagnosticManager && other) delete noexcept
Deleted move assignment and move constructor.
~DiagnosticManager()
diag::client::common::DiagnosticManager::~DiagnosticManager () virtual noexcept
Destructs an instance of DiagnosticManager.
Definition at line 16 of file diagnostic_manager.cpp.
{
   {
     std::lock_guard<std::mutex> const lock{mutex_};
     exit_requested_ = true;
   }
   cond_var_.notify_all();
 }
References cond_var_, exit_requested_, and mutex_.
Member Function Documentation
GetDiagnosticClientConversation()
virtual conversation::DiagClientConversation diag::client::common::DiagnosticManager::GetDiagnosticClientConversation (std::string_view conversation_name) pure virtual noexcept
Function to get required diag client conversation object based on conversation name.
Parameters
[in] conversation_name Name of conversation configured as json parameter "ConversationName"
Returns
Diag client conversation object as per passed conversation name -MultipleTester-Connection, DiagClientLib-Conversation-Construction
Implemented in diag::client::dcm::DCMClient.
Initialize()
virtual void diag::client::common::DiagnosticManager::Initialize () pure virtual noexcept
Function to initialize the DiagnosticManager.
Implemented in diag::client::dcm::DCMClient.
Referenced by Main().
Main()
void diag::client::common::DiagnosticManager::Main () virtual noexcept
Function to manage the whole lifecycle of DiagnosticManager.
Definition at line 24 of file diagnostic_manager.cpp.
{
   // Initialize the module
   Initialize();
   // Run the module
   Run();
   // Entering infinite loop
   while (!exit_requested_) {
     std::unique_lock<std::mutex> lck(mutex_);
     cond_var_.wait(lck, [this]() { return exit_requested_; });
     // Thread exited
   }
   // Shutdown module
   Shutdown();
 }
References cond_var_, exit_requested_, Initialize(), mutex_, Run(), and Shutdown().
operator=() [1/2]
DiagnosticManager& diag::client::common::DiagnosticManager::operator= (const DiagnosticManager & other) delete noexcept
operator=() [2/2]
DiagnosticManager& diag::client::common::DiagnosticManager::operator= (DiagnosticManager && other) delete noexcept
Run()
virtual void diag::client::common::DiagnosticManager::Run () pure virtual noexcept
Function to run DiagnosticManager.
Implemented in diag::client::dcm::DCMClient.
Referenced by Main().
SendVehicleIdentificationRequest()
virtual core_type::Result<diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError> diag::client::common::DiagnosticManager::SendVehicleIdentificationRequest (diag::client::vehicle_info::VehicleInfoListRequestType vehicle_info_request) pure virtual noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
Parameters
[in] vehicle_info_request Vehicle information sent along with request
Returns
Result containing available vehicle information response on success, VehicleResponseErrorCode on error -VehicleDiscovery
Implemented in diag::client::dcm::DCMClient.
Shutdown()
virtual void diag::client::common::DiagnosticManager::Shutdown () pure virtual noexcept
Function to shutdown the DiagnosticManager.
Implemented in diag::client::dcm::DCMClient.
Referenced by Main().
SignalShutdown()
Result< void > diag::client::common::DiagnosticManager::SignalShutdown () virtual noexcept
Function to initiate shutdown of DiagnosticManager.
Definition at line 39 of file diagnostic_manager.cpp.
{
   Result<void> result{};
   {
     std::lock_guard<std::mutex> lock{mutex_};
     exit_requested_ = true;
   }
   cond_var_.notify_all();
   return result;
 }
References cond_var_, exit_requested_, and mutex_.
Member Data Documentation
cond_var_
std::condition_variable diag::client::common::DiagnosticManager::cond_var_ private
Conditional variable to block the thread.
Definition at line 111 of file diagnostic_manager.h.
Referenced by Main(), SignalShutdown(), and ~DiagnosticManager().
exit_requested_
bool diag::client::common::DiagnosticManager::exit_requested_ private
Flag to terminate the main thread.
Definition at line 106 of file diagnostic_manager.h.
Referenced by Main(), SignalShutdown(), and ~DiagnosticManager().
mutex_
std::mutex diag::client::common::DiagnosticManager::mutex_ private
For locking critical section of code.
Definition at line 116 of file diagnostic_manager.h.
Referenced by Main(), SignalShutdown(), and ~DiagnosticManager().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/common/diagnostic_manager.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/common/diagnostic_manager.cpp