Diag-Client-Lib: boost_support::common::logger::LibBoostLogger Class Reference
boost_support::common::logger::LibBoostLogger Class Reference final
#include <logger.h>
Public Member Functions
auto GetLogger () noexcept -> Logger &
Static Public Member Functions
static auto GetLibBoostLogger () noexcept -> LibBoostLogger &
Private Member Functions
LibBoostLogger ()=default
Private Attributes
Logger logger_ {"dcbs"}
Detailed Description
Definition at line 18 of file logger.h.
Constructor & Destructor Documentation
LibBoostLogger()
boost_support::common::logger::LibBoostLogger::LibBoostLogger () private default
Member Function Documentation
GetLibBoostLogger()
static auto boost_support::common::logger::LibBoostLogger::GetLibBoostLogger () -> LibBoostLogger& inline static noexcept
Definition at line 20 of file logger.h.
{
     static LibBoostLogger boost_logger{};
     return boost_logger;
   }
Referenced by boost_support::socket::tcp::TcpSocket::Connect(), boost_support::socket::tls::TlsSocket::Connect(), boost_support::client::tcp::TcpClient::TcpClientImpl::ConnectToHost(), boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::ConnectToHost(), boost_support::socket::tcp::TlsClientSocket::ConnectToHost(), boost_support::socket::tcp::TcpSocket::Disconnect(), boost_support::socket::tls::TlsSocket::Disconnect(), boost_support::client::tcp::TcpClient::TcpClientImpl::DisconnectFromHost(), boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::DisconnectFromHost(), boost_support::socket::tcp::TlsClientSocket::DisconnectFromHost(), boost_support::server::tcp::TcpAcceptor::TcpAcceptorImpl::GetTcpServer(), boost_support::socket::tcp::TlsServerSocket::GetTcpServerConnection(), boost_support::server::tls::TlsAcceptor< TlsVersion >::TlsAcceptorImpl::GetTlsServer(), boost_support::socket::tcp::TlsClientSocket::HandleMessage(), boost_support::socket::tcp::TlsClientSocket::Open(), boost_support::socket::tcp::TcpSocket::Open(), boost_support::socket::tls::TlsSocket::Open(), boost_support::socket::udp::UdpSocket::Open(), boost_support::socket::tcp::TcpSocket::Read(), boost_support::socket::tls::TlsSocket::Read(), boost_support::socket::udp::UdpSocket::Read(), boost_support::parser::Read(), boost_support::socket::tcp::TcpServerConnection::Shutdown(), boost_support::socket::udp::UdpSocket::StartReceivingMessage(), boost_support::socket::tcp::TlsServerSocket::TlsServerSocket(), boost_support::socket::tcp::TlsClientSocket::Transmit(), boost_support::socket::tcp::TcpServerConnection::Transmit(), boost_support::client::tcp::TcpClient::TcpClientImpl::Transmit(), boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::Transmit(), boost_support::socket::tcp::TcpSocket::Transmit(), boost_support::socket::tls::TlsSocket::Transmit(), boost_support::socket::udp::UdpSocket::Transmit(), and boost_support::socket::tcp::TcpServerConnection::TryReceivingMessage().
GetLogger()
auto boost_support::common::logger::LibBoostLogger::GetLogger () -> Logger& inline noexcept
Definition at line 25 of file logger.h.
 { return logger_; }
References logger_.
Member Data Documentation
logger_
Logger boost_support::common::logger::LibBoostLogger::logger_ {"dcbs"} private
Definition at line 31 of file logger.h.
Referenced by GetLogger().
The documentation for this class was generated from the following file:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/lib/boost-support/src/boost-support/common/logger.h