Diag-Client-Lib: diag::client::conversation::DmConversation Class Reference
diag::client::conversation::DmConversation Class Reference final
Class to establish connection with Diagnostic Server.
#include <dm_conversation.h>
Public Types
using ConversationState = conversation_state_impl::ConversationState
Type alias for conversation internal state.
using SyncTimer = utility::sync_timer::SyncTimer< std::chrono::steady_clock >
Type alias for synchronous timer.
Public Types inherited from diag::client::conversation::Conversation
enum class ActivityStatusType : uint8_t { kActive = 0x00 , kInactive = 0x01 }
Definitions of current activity status.
using IpAddress = DiagClientConversation::IpAddress
Type alias for Ip address.
using ConnectResult = DiagClientConversation::ConnectResult
Type alias for Connection results.
using DisconnectResult = DiagClientConversation::DisconnectResult
Type alias for Disconnection results.
using DiagError = DiagClientConversation::DiagError
Type alias for Diagnostic results.
Public Member Functions
DmConversation (std::string_view conversion_name, DMConversationType &conversion_identifier)
Constructs an instance of DmConversation.
DmConversation (const DmConversation &other) noexcept=delete
Deleted copy assignment and copy constructor.
DmConversation & operator= (const DmConversation &other) noexcept=delete
DmConversation (DmConversation &&other) noexcept=delete
Deleted move assignment and move constructor.
DmConversation & operator= (DmConversation &&other) noexcept=delete
~DmConversation () override
Destructs an instance of DmConversation.
void Startup () noexcept override
Function to start the DmConversation.
void Shutdown () noexcept override
Function to shutdown the DmConversation.
void RegisterConnection (std::unique_ptr<::uds_transport::Connection > connection) noexcept override
Function to register the conversation to underlying transport protocol handler.
::uds_transport::ConversionHandler & GetConversationHandler () noexcept override
Function to get the conversation handler from conversation object.
ConnectResult ConnectToDiagServer (std::uint16_t target_address, IpAddress host_ip_addr) noexcept override
Function to connect to Diagnostic Server.
DisconnectResult DisconnectFromDiagServer () noexcept override
Function to disconnect from Diagnostic Server.
std::pair<::uds_transport::UdsTransportProtocolMgr::IndicationResult, ::uds_transport::UdsMessagePtr > IndicateMessage (::uds_transport::UdsMessage::Address source_addr, ::uds_transport::UdsMessage::Address target_addr, ::uds_transport::UdsMessage::TargetAddressType type, ::uds_transport::ChannelID channel_id, std::size_t size, ::uds_transport::Priority priority, ::uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) noexcept override
Function to indicate a start of reception of message.
void HandleMessage (::uds_transport::UdsMessagePtr message) noexcept override
Function to Hands over a valid received Uds message.
Result< uds_message::UdsResponseMessagePtr, DiagError > SendDiagnosticRequest (uds_message::UdsRequestMessageConstPtr message) noexcept override
Function to send Diagnostic Request and get Diagnostic Response.
Public Member Functions inherited from diag::client::conversation::Conversation
Conversation () noexcept=default
Constructs an instance of Conversation.
Conversation (const Conversation &other) noexcept=delete
Deleted copy assignment and copy constructor.
Conversation & operator= (const Conversation &other) noexcept=delete
Conversation (Conversation &&other) noexcept=delete
Deleted move assignment and move constructor.
Conversation & operator= (Conversation &&other) noexcept=delete
virtual ~Conversation () noexcept=default
Destructs an instance of Conversation.
virtual core_type::Result< diag::client::vehicle_info::VehicleInfoMessageResponseUniquePtr, DiagClient::VehicleInfoResponseError > SendVehicleIdentificationRequest (vehicle_info::VehicleInfoListRequestType) noexcept
Function to send vehicle identification request and get the Diagnostic Server list.
auto GetActivityStatus () const noexcept -> ActivityStatusType
Get the current activity status of this conversation.
Private Types
enum class SessionControlType : std::uint8_t { kDefaultSession = 0x01 , kProgrammingSession = 0x02 , kExtendedSession = 0x03 , kSystemSafetySession = 0x04 }
Definitions of active diagnostic session.
enum class SecurityLevelType : std::uint8_t { kLocked = 0x00 , kUnLocked = 0x01 }
Definitions of active security level.
Static Private Member Functions
static DiagClientConversation::DiagError ConvertResponseType (::uds_transport::UdsTransportProtocolMgr::TransmissionResult result_type)
Helper function to convert response type.
Private Attributes
SessionControlType active_session_
Store the active diagnostic session.
SecurityLevelType active_security_level_
Store the active diagnostic security level.
std::uint32_t rx_buffer_size_
Store the size of reception buffer size setting.
std::uint16_t p2_client_max_
Store the maximum p2 client time.
std::uint16_t p2_star_client_max_
Store the maximum p2 star client time.
std::uint16_t source_address_
Store the logical source address of conversation.
std::uint16_t target_address_
Store the logical target address of remote server.
std::string remote_address_
Store the remote IP address of remote server.
std::string conversation_name_
Store the conversation name.
std::unique_ptr<::uds_transport::ConversionHandler > dm_conversion_handler_
Store the dm conversation handler.
std::unique_ptr<::uds_transport::Connection > connection_
Store the underlying transport protocol connection object.
SyncTimer sync_timer_
Store the synchronous timer.
::uds_transport::ByteVector payload_rx_buffer_
Store the received uds response.
conversation_state_impl::ConversationStateImpl conversation_state_
Store the conversation state.
Additional Inherited Members
Protected Attributes inherited from diag::client::conversation::Conversation
ActivityStatusType activity_status_ {ActivityStatusType::kInactive}
Store the conversation activity status.
Detailed Description
Class to establish connection with Diagnostic Server.
Definition at line 28 of file dm_conversation.h.
Member Typedef Documentation
ConversationState
using diag::client::conversation::DmConversation::ConversationState = conversation_state_impl::ConversationState
Type alias for conversation internal state.
Definition at line 33 of file dm_conversation.h.
SyncTimer
using diag::client::conversation::DmConversation::SyncTimer = utility::sync_timer::SyncTimer<std::chrono::steady_clock>
Type alias for synchronous timer.
Definition at line 37 of file dm_conversation.h.
Member Enumeration Documentation
SecurityLevelType
enum diag::client::conversation::DmConversation::SecurityLevelType : std::uint8_t strong private
Definitions of active security level.
Enumerator
kLocked
kUnLocked
Definition at line 178 of file dm_conversation.h.
                                : std::uint8_t {
     kLocked = 0x00,
     kUnLocked = 0x01,
   };
SessionControlType
enum diag::client::conversation::DmConversation::SessionControlType : std::uint8_t strong private
Definitions of active diagnostic session.
Enumerator
kDefaultSession
kProgrammingSession
kExtendedSession
kSystemSafetySession
Definition at line 168 of file dm_conversation.h.
                                 : std::uint8_t {
     kDefaultSession = 0x01,
     kProgrammingSession = 0x02,
     kExtendedSession = 0x03,
     kSystemSafetySession = 0x04
   };
Constructor & Destructor Documentation
DmConversation() [1/3]
diag::client::conversation::DmConversation::DmConversation (std::string_view conversion_name, DMConversationType & conversion_identifier)
Constructs an instance of DmConversation.
Parameters
[in] conversion_name The name of conversation
[in] conversion_identifier The identifier consisting of conversation settings
Definition at line 107 of file dm_conversation.cpp.
     : Conversation{},
       active_session_{SessionControlType::kDefaultSession},
       active_security_level_{SecurityLevelType::kLocked},
       rx_buffer_size_{conversion_identifier.rx_buffer_size},
       p2_client_max_{conversion_identifier.p2_client_max},
       p2_star_client_max_{conversion_identifier.p2_star_client_max},
       source_address_{conversion_identifier.source_address},
       target_address_{},
       conversation_name_{conversion_name},
       dm_conversion_handler_{
           std::make_unique<DmConversationHandler>(conversion_identifier.handler_id, *this)} {}
DmConversation() [2/3]
diag::client::conversation::DmConversation::DmConversation (const DmConversation & other) delete noexcept
Deleted copy assignment and copy constructor.
DmConversation() [3/3]
diag::client::conversation::DmConversation::DmConversation (DmConversation && other) delete noexcept
Deleted move assignment and move constructor.
~DmConversation()
diag::client::conversation::DmConversation::~DmConversation () override default
Destructs an instance of DmConversation.
Member Function Documentation
ConnectToDiagServer()
DiagClientConversation::ConnectResult diag::client::conversation::DmConversation::ConnectToDiagServer (std::uint16_t target_address, IpAddress host_ip_addr) override virtual noexcept
Function to connect to Diagnostic Server.
Parameters
[in] target_address Logical address of the Remote server
[in] host_ip_addr IP address of the Remote server
Returns
ConnectResult Connection result returned
Reimplemented from diag::client::conversation::Conversation.
Definition at line 153 of file dm_conversation.cpp.
{
   // create an uds message just to get the port number
   // source address required for Routing Activation
   uds_transport::ByteVector payload{};  // empty payload
   // Send Connect request to doip layer
   DiagClientConversation::ConnectResult const connection_result{
       static_cast<DiagClientConversation::ConnectResult>(
           connection_->ConnectToHost(std::make_unique<diag::client::uds_message::DmUdsMessage>(
               source_address_, target_address, host_ip_addr, payload)))};
   remote_address_ = host_ip_addr;
   target_address_ = target_address;
   if (connection_result == DiagClientConversation::ConnectResult::kConnectSuccess) {
     logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           msg << "'" << conversation_name_ << "'"
               << "-> "
               << "Successfully connected to Server with IP <" << remote_address_ << ">"
               << " and LA= 0x" << std::hex << target_address_;
         });
   } else {
     logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
           msg << "'" << conversation_name_ << "'"
               << "-> "
               << "Failed connecting to Server with IP <" << remote_address_ << ">"
               << " and LA= 0x" << std::hex << target_address_;
         });
   }
   return connection_result;
 }
References FILE_NAME, diag::client::logger::DiagClientLogger::GetDiagClientLogger(), and diag::client::conversation::DiagClientConversation::kConnectSuccess.
ConvertResponseType()
DiagClientConversation::DiagError diag::client::conversation::DmConversation::ConvertResponseType (::uds_transport::UdsTransportProtocolMgr::TransmissionResult result_type) static private
Helper function to convert response type.
Parameters
[in] result_type The transmission result type
Returns
DiagResult The diagnostic result type
Definition at line 417 of file dm_conversation.cpp.
{
   DiagClientConversation::DiagError ret_result{
       DiagClientConversation::DiagError::kDiagGenericFailure};
   switch (result_type) {
     case uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitFailed:
       ret_result = DiagClientConversation::DiagError::kDiagRequestSendFailed;
       break;
     case uds_transport::UdsTransportProtocolMgr::TransmissionResult::kNoTransmitAckReceived:
       ret_result = DiagClientConversation::DiagError::kDiagAckTimeout;
       break;
     case uds_transport::UdsTransportProtocolMgr::TransmissionResult::kNegTransmitAckReceived:
       ret_result = DiagClientConversation::DiagError::kDiagNegAckReceived;
       break;
     case uds_transport::UdsTransportProtocolMgr::TransmissionResult::kBusyProcessing:
       ret_result = DiagClientConversation::DiagError::kDiagBusyProcessing;
       break;
     default:
       ret_result = DiagClientConversation::DiagError::kDiagGenericFailure;
       break;
   }
   return ret_result;
 }
References uds_transport::UdsTransportProtocolMgr::kBusyProcessing, diag::client::conversation::DiagClientConversation::kDiagAckTimeout, diag::client::conversation::DiagClientConversation::kDiagBusyProcessing, diag::client::conversation::DiagClientConversation::kDiagGenericFailure, diag::client::conversation::DiagClientConversation::kDiagNegAckReceived, diag::client::conversation::DiagClientConversation::kDiagRequestSendFailed, uds_transport::UdsTransportProtocolMgr::kNegTransmitAckReceived, uds_transport::UdsTransportProtocolMgr::kNoTransmitAckReceived, and uds_transport::UdsTransportProtocolMgr::kTransmitFailed.
DisconnectFromDiagServer()
DiagClientConversation::DisconnectResult diag::client::conversation::DmConversation::DisconnectFromDiagServer () override virtual noexcept
Function to disconnect from Diagnostic Server.
Returns
DisconnectResult Disconnection result returned
Reimplemented from diag::client::conversation::Conversation.
Definition at line 185 of file dm_conversation.cpp.
{
   DiagClientConversation::DisconnectResult ret_val{
       DiagClientConversation::DisconnectResult::kDisconnectFailed};
   // Check if already connected before disconnecting
   if (connection_->IsConnectToHost()) {
     // Send disconnect request to doip layer
     ret_val =
         static_cast<DiagClientConversation::DisconnectResult>(connection_->DisconnectFromHost());
     if (ret_val == DiagClientConversation::DisconnectResult::kDisconnectSuccess) {
       logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
           FILE_NAME, __LINE__, __func__, [this](std::stringstream &msg) {
             msg << "'" << conversation_name_ << "'"
                 << "-> "
                 << "Successfully disconnected from Server with IP <" << remote_address_ << ">"
                 << " and LA= 0x" << std::hex << target_address_;
           });
     } else {
       logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogWarn(
           FILE_NAME, __LINE__, __func__, [&](std::stringstream &msg) {
             msg << "'" << conversation_name_ << "'"
                 << "-> "
                 << "Failed to disconnect from Server with IP <" << remote_address_ << ">";
           });
     }
   } else {
     ret_val = DiagClientConversation::DisconnectResult::kAlreadyDisconnected;
   }
   return ret_val;
 }
References connection_, conversation_name_, FILE_NAME, diag::client::logger::DiagClientLogger::GetDiagClientLogger(), diag::client::conversation::DiagClientConversation::kAlreadyDisconnected, diag::client::conversation::DiagClientConversation::kDisconnectFailed, diag::client::conversation::DiagClientConversation::kDisconnectSuccess, remote_address_, and target_address_.
GetConversationHandler()
uds_transport::ConversionHandler & diag::client::conversation::DmConversation::GetConversationHandler () override virtual noexcept
Function to get the conversation handler from conversation object.
Returns
ConversionHandler & The reference to conversation handler
Implements diag::client::conversation::Conversation.
Definition at line 344 of file dm_conversation.cpp.
{
   return *dm_conversion_handler_;
 }
References dm_conversion_handler_.
HandleMessage()
void diag::client::conversation::DmConversation::HandleMessage (::uds_transport::UdsMessagePtr message) override virtual noexcept
Function to Hands over a valid received Uds message.
Parameters
[in] message The The Uds message ptr (unique_ptr semantics) with the request. Ownership of the UdsMessage is given back to the conversation here
Implements diag::client::conversation::Conversation.
Definition at line 411 of file dm_conversation.cpp.
{
   if (message != nullptr) {
     conversation_state_.GetConversationStateContext().TransitionTo(ConversationState::kDiagSuccess);
   }
 }
Referenced by diag::client::conversation::DmConversationHandler::HandleMessage().
IndicateMessage()
std::pair< uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr > diag::client::conversation::DmConversation::IndicateMessage (::uds_transport::UdsMessage::Address source_addr, ::uds_transport::UdsMessage::Address target_addr, ::uds_transport::UdsMessage::TargetAddressType type, ::uds_transport::ChannelID channel_id, std::size_t size, ::uds_transport::Priority priority, ::uds_transport::ProtocolKind protocol_kind, core_type::Span< std::uint8_t const > payload_info) override virtual noexcept
Function to indicate a start of reception of message.
This is called to indicate the reception of new message by underlying transport protocol handler
Parameters
[in] source_addr The UDS source address of message
[in] target_addr The UDS target address of message
[in] type The indication whether its is phys/func request
[in] channel_id The transport protocol channel on which message start happened
[in] size The size in bytes of the UdsMessage starting from SID
[in] priority The priority of the given message, used for prioritization of conversations
[in] protocol_kind The identifier of protocol kind associated to message
[in] payload_info The View onto the first received payload bytes, if any. This view shall be used only within this function call. It is recommended that the TP provides at least the first two bytes of the request message, so the DM can identify a functional TesterPresent
Returns
std::pair< IndicationResult, UdsMessagePtr > The pair of IndicationResult and a pointer to UdsMessage owned/created by DM core and returned to the handler to get filled
Implements diag::client::conversation::Conversation.
Definition at line 349 of file dm_conversation.cpp.
{
   std::pair<uds_transport::UdsTransportProtocolMgr::IndicationResult, uds_transport::UdsMessagePtr>
       ret_val{uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationNOk, nullptr};
   // Verify the payload received :-
   if (!payload_info.empty()) {
     // Check for size, else kIndicationOverflow
     if (size <= rx_buffer_size_) {
       // Check for pending response
       // payload = 0x7F XX 0x78
       if (payload_info[0U] == 0x7F && payload_info[2U] == 0x78) {
         logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
             FILE_NAME, __LINE__, "", [&](std::stringstream &msg) {
               msg << "'" << conversation_name_ << "'"
                   << "-> "
                   << "Diagnostic pending response received in Conversation";
             });
         ret_val.first =
             uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationPending;
         conversation_state_.GetConversationStateContext().TransitionTo(
             ConversationState::kDiagRecvdPendingRes);
       } else {
         logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogDebug(
             FILE_NAME, __LINE__, "", [this](std::stringstream &msg) {
               msg << "'" << conversation_name_ << "'"
                   << "-> "
                   << "Diagnostic final response received in Conversation";
             });
         // positive or negative response, provide valid buffer
         // resize the global rx buffer
         payload_rx_buffer_.resize(size);
         ret_val.first = uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationOk;
         ret_val.second = std::make_unique<diag::client::uds_message::DmUdsMessage>(
             source_address_, target_address_, "", payload_rx_buffer_);
         conversation_state_.GetConversationStateContext().TransitionTo(
             ConversationState::kDiagRecvdFinalRes);
       }
       sync_timer_.CancelWait();
     } else {
       logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogError(
           FILE_NAME, __LINE__, "", [&](std::stringstream &msg) {
             msg << "'" << conversation_name_ << "'"
                 << "-> "
                 << "Diagnostic Conversation Error Indication Overflow";
           });
       ret_val.first = uds_transport::UdsTransportProtocolMgr::IndicationResult::kIndicationOverflow;
     }
   } else {
     logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogError(
         FILE_NAME, __LINE__, "", [&](std::stringstream &msg) {
           msg << "'" << conversation_name_ << "'"
               << "-> "
               << "Diagnostic Conversation Rx Payload size 0 received";
         });
   }
   return ret_val;
 }
References FILE_NAME, diag::client::logger::DiagClientLogger::GetDiagClientLogger(), uds_transport::UdsTransportProtocolMgr::kIndicationNOk, uds_transport::UdsTransportProtocolMgr::kIndicationOk, uds_transport::UdsTransportProtocolMgr::kIndicationOverflow, and uds_transport::UdsTransportProtocolMgr::kIndicationPending.
Referenced by diag::client::conversation::DmConversationHandler::IndicateMessage().
operator=() [1/2]
DmConversation& diag::client::conversation::DmConversation::operator= (const DmConversation & other) delete noexcept
operator=() [2/2]
DmConversation& diag::client::conversation::DmConversation::operator= (DmConversation && other) delete noexcept
RegisterConnection()
void diag::client::conversation::DmConversation::RegisterConnection (std::unique_ptr<::uds_transport::Connection > connection) override virtual noexcept
Function to register the conversation to underlying transport protocol handler.
Parameters
[in] connection The conversation connection object
Implements diag::client::conversation::Conversation.
Definition at line 339 of file dm_conversation.cpp.
{
   connection_ = std::move(connection);
 }
SendDiagnosticRequest()
Result< uds_message::UdsResponseMessagePtr, DiagClientConversation::DiagError > diag::client::conversation::DmConversation::SendDiagnosticRequest (uds_message::UdsRequestMessageConstPtr message) override virtual noexcept
Function to send Diagnostic Request and get Diagnostic Response.
Parameters
[in] message The diagnostic request message wrapped in a unique pointer
Returns
DiagResult The Result returned
uds_message::UdsResponseMessagePtr Diagnostic Response message received, null_ptr in case of error
Reimplemented from diag::client::conversation::Conversation.
Definition at line 216 of file dm_conversation.cpp.
{
   Result<uds_message::UdsResponseMessagePtr, DiagClientConversation::DiagError> result{
       Result<uds_message::UdsResponseMessagePtr, DiagClientConversation::DiagError>::FromError(
           DiagClientConversation::DiagError::kDiagRequestSendFailed)};
   if (message) {
     // fill the data
     uds_transport::ByteVector payload{message->GetPayload()};
     // Initiate Sending of diagnostic request
     uds_transport::UdsTransportProtocolMgr::TransmissionResult const transmission_result{
         connection_->Transmit(std::make_unique<diag::client::uds_message::DmUdsMessage>(
             source_address_, target_address_, message->GetHostIpAddress(), payload))};
     if (transmission_result ==
         uds_transport::UdsTransportProtocolMgr::TransmissionResult::kTransmitOk) {
       // Diagnostic Request Sent successful
       logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
           FILE_NAME, __LINE__, __func__, [&](std::stringstream &msg) {
             msg << "'" << conversation_name_ << "'"
                 << "-> "
                 << "Diagnostic Request Sent & Positive Ack received";
           });
       conversation_state_.GetConversationStateContext().TransitionTo(
           ConversationState::kDiagWaitForRes);
       // Wait P6Max / P2ClientMax
       sync_timer_.WaitForTimeout(
           [this, &result]() {
             result.EmplaceError(DiagClientConversation::DiagError::kDiagResponseTimeout);
             conversation_state_.GetConversationStateContext().TransitionTo(
                 ConversationState::kIdle);
             logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
                 FILE_NAME, __LINE__, "", [&](std::stringstream &msg) {
                   msg << "'" << conversation_name_ << "'"
                       << "-> "
                       << "Diagnostic Response P2 Timeout happened after " << p2_client_max_
                       << " milliseconds";
                 });
           },
           [this]() {
             // pending or pos/neg response
             if (conversation_state_.GetConversationStateContext().GetActiveState().GetState() ==
                 ConversationState::kDiagRecvdFinalRes) {
               // pos/neg response received
             } else if (conversation_state_.GetConversationStateContext()
                            .GetActiveState()
                            .GetState() == ConversationState::kDiagRecvdPendingRes) {
               // first pending received
               conversation_state_.GetConversationStateContext().TransitionTo(
                   ConversationState::kDiagStartP2StarTimer);
             }
           },
           std::chrono::milliseconds{p2_client_max_});
       // Wait until final response or timeout
       while (conversation_state_.GetConversationStateContext().GetActiveState().GetState() !=
              ConversationState::kIdle) {
         // Check the active state
         switch (conversation_state_.GetConversationStateContext().GetActiveState().GetState()) {
           case ConversationState::kDiagRecvdPendingRes:
             conversation_state_.GetConversationStateContext().TransitionTo(
                 ConversationState::kDiagStartP2StarTimer);
             break;
           case ConversationState::kDiagRecvdFinalRes:
             // do nothing
             break;
           case ConversationState::kDiagStartP2StarTimer:
             // wait P6Star/ P2 star client time
             sync_timer_.WaitForTimeout(
                 [this, &result]() {
                   logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
                       FILE_NAME, __LINE__, "", [&](std::stringstream &msg) {
                         msg << "'" << conversation_name_ << "'"
                             << "-> "
                             << "Diagnostic Response P2 Star Timeout "
                                "happened after "
                             << p2_star_client_max_ << " milliseconds";
                       });
                   result.EmplaceError(DiagClientConversation::DiagError::kDiagResponseTimeout);
                   conversation_state_.GetConversationStateContext().TransitionTo(
                       ConversationState::kIdle);
                 },
                 [this]() {
                   // pending or pos/neg response
                   if (conversation_state_.GetConversationStateContext()
                           .GetActiveState()
                           .GetState() == ConversationState::kDiagRecvdFinalRes) {
                     // pos/neg response received
                   } else if (conversation_state_.GetConversationStateContext()
                                  .GetActiveState()
                                  .GetState() == ConversationState::kDiagRecvdPendingRes) {
                     // pending received again
                     conversation_state_.GetConversationStateContext().TransitionTo(
                         ConversationState::kDiagStartP2StarTimer);
                   }
                 },
                 std::chrono::milliseconds{p2_star_client_max_});
             break;
           case ConversationState::kDiagSuccess:
             // change state to idle, form the uds response and return
             result.EmplaceValue(
                 std::make_unique<diag::client::uds_message::DmUdsResponse>(payload_rx_buffer_));
             conversation_state_.GetConversationStateContext().TransitionTo(
                 ConversationState::kIdle);
             break;
           default:
             // nothing
             break;
         }
       }
     } else {
       // failure
       result.EmplaceError(ConvertResponseType(transmission_result));
     }
   } else {
     result.EmplaceError(DiagClientConversation::DiagError::kDiagInvalidParameter);
     logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogWarn(
         FILE_NAME, __LINE__, "", [&](std::stringstream &msg) {
           msg << "'" << conversation_name_ << "'"
               << "-> "
               << "Diagnostic Request message is empty";
         });
   }
   return result;
 }
References FILE_NAME, core_type::Result< T, E >::FromError(), diag::client::logger::DiagClientLogger::GetDiagClientLogger(), diag::client::conversation::DiagClientConversation::kDiagInvalidParameter, diag::client::conversation::DiagClientConversation::kDiagRequestSendFailed, diag::client::conversation::DiagClientConversation::kDiagResponseTimeout, and uds_transport::UdsTransportProtocolMgr::kTransmitOk.
Shutdown()
void diag::client::conversation::DmConversation::Shutdown () override virtual noexcept
Function to shutdown the DmConversation.
Implements diag::client::conversation::Conversation.
Definition at line 138 of file dm_conversation.cpp.
{
   if (GetActivityStatus() == ActivityStatusType::kActive) {
     // shutdown connection
     connection_->Stop();
     // Change the state to InActive
     activity_status_ = ActivityStatusType::kInactive;
     logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
         FILE_NAME, __LINE__, __func__, [&](std::stringstream &msg) {
           msg << "'" << conversation_name_ << "'"
               << "-> "
               << "Shutdown completed";
         });
   }
 }
References diag::client::conversation::Conversation::activity_status_, connection_, conversation_name_, FILE_NAME, diag::client::conversation::Conversation::GetActivityStatus(), diag::client::logger::DiagClientLogger::GetDiagClientLogger(), diag::client::conversation::Conversation::kActive, and diag::client::conversation::Conversation::kInactive.
Startup()
void diag::client::conversation::DmConversation::Startup () override virtual noexcept
Function to start the DmConversation.
Implements diag::client::conversation::Conversation.
Definition at line 123 of file dm_conversation.cpp.
{
   // initialize the connection
   static_cast<void>(connection_->Initialize());
   // start the connection
   connection_->Start();
   // Change the state to Active
   activity_status_ = ActivityStatusType::kActive;
   logger::DiagClientLogger::GetDiagClientLogger().GetLogger().LogInfo(
       FILE_NAME, __LINE__, __func__, [&](std::stringstream &msg) {
         msg << "'" << conversation_name_ << "'"
             << "-> "
             << "Startup completed";
       });
 }
References diag::client::conversation::Conversation::activity_status_, connection_, conversation_name_, FILE_NAME, diag::client::logger::DiagClientLogger::GetDiagClientLogger(), and diag::client::conversation::Conversation::kActive.
Member Data Documentation
active_security_level_
SecurityLevelType diag::client::conversation::DmConversation::active_security_level_ private
Store the active diagnostic security level.
Definition at line 202 of file dm_conversation.h.
active_session_
SessionControlType diag::client::conversation::DmConversation::active_session_ private
Store the active diagnostic session.
Definition at line 197 of file dm_conversation.h.
connection_
std::unique_ptr<::uds_transport::Connection> diag::client::conversation::DmConversation::connection_ private
Store the underlying transport protocol connection object.
Definition at line 247 of file dm_conversation.h.
Referenced by DisconnectFromDiagServer(), Shutdown(), and Startup().
conversation_name_
std::string diag::client::conversation::DmConversation::conversation_name_ private
Store the conversation name.
Definition at line 237 of file dm_conversation.h.
Referenced by DisconnectFromDiagServer(), Shutdown(), and Startup().
conversation_state_
conversation_state_impl::ConversationStateImpl diag::client::conversation::DmConversation::conversation_state_ private
Store the conversation state.
Definition at line 262 of file dm_conversation.h.
dm_conversion_handler_
std::unique_ptr<::uds_transport::ConversionHandler> diag::client::conversation::DmConversation::dm_conversion_handler_ private
Store the dm conversation handler.
Definition at line 242 of file dm_conversation.h.
Referenced by GetConversationHandler().
p2_client_max_
std::uint16_t diag::client::conversation::DmConversation::p2_client_max_ private
Store the maximum p2 client time.
Definition at line 212 of file dm_conversation.h.
p2_star_client_max_
std::uint16_t diag::client::conversation::DmConversation::p2_star_client_max_ private
Store the maximum p2 star client time.
Definition at line 217 of file dm_conversation.h.
payload_rx_buffer_
::uds_transport::ByteVector diag::client::conversation::DmConversation::payload_rx_buffer_ private
Store the received uds response.
Definition at line 257 of file dm_conversation.h.
remote_address_
std::string diag::client::conversation::DmConversation::remote_address_ private
Store the remote IP address of remote server.
Definition at line 232 of file dm_conversation.h.
Referenced by DisconnectFromDiagServer().
rx_buffer_size_
std::uint32_t diag::client::conversation::DmConversation::rx_buffer_size_ private
Store the size of reception buffer size setting.
Definition at line 207 of file dm_conversation.h.
source_address_
std::uint16_t diag::client::conversation::DmConversation::source_address_ private
Store the logical source address of conversation.
Definition at line 222 of file dm_conversation.h.
sync_timer_
SyncTimer diag::client::conversation::DmConversation::sync_timer_ private
Store the synchronous timer.
Definition at line 252 of file dm_conversation.h.
target_address_
std::uint16_t diag::client::conversation::DmConversation::target_address_ private
Store the logical target address of remote server.
Definition at line 227 of file dm_conversation.h.
Referenced by DisconnectFromDiagServer().
The documentation for this class was generated from the following files:
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/dcm/conversation/dm_conversation.h
/home/runner/work/diag-client-lib/diag-client-lib/diag-client-lib/appl/src/diag-client/dcm/conversation/dm_conversation.cpp