Diag-Client-Lib: doip_client::error_domain Namespace Reference
doip_client::error_domain Namespace Reference
Namespaces
anonymous_namespace{doip_error_domain.cpp}
Classes
class DoipErrorDomain
Definition of Doip Client Error domain.
Enumerations
enum class DoipErrorErrc : core_type::ErrorDomain::CodeType { kInitializationFailed = 0U , kDeInitializationFailed = 1U , kSocketError = 2U , kGenericError = 3U }
Definition of error code in Doip Client.
Functions
core_type::ErrorCode MakeErrorCode (DoipErrorErrc code, core_type::ErrorDomain::SupportDataType data=core_type::ErrorDomain::SupportDataType{}) noexcept
Create a new ErrorCode within DoipErrorDomain.
Enumeration Type Documentation
DoipErrorErrc
enum doip_client::error_domain::DoipErrorErrc : core_type::ErrorDomain::CodeType strong
Definition of error code in Doip Client.
Enumerator
kInitializationFailed
Failure on Initialization
kDeInitializationFailed
Failure on De-Initialization
kSocketError
Failure on Socket Open/Destroy
kGenericError
Generic Error
Definition at line 22 of file doip_error_domain.h.
                          : core_type::ErrorDomain::CodeType {
   kInitializationFailed = 0U,
   kDeInitializationFailed = 1U,
   kSocketError = 2U,
   kGenericError = 3U
 };
Function Documentation
MakeErrorCode()
core_type::ErrorCode doip_client::error_domain::MakeErrorCode (DoipErrorErrc code, core_type::ErrorDomain::SupportDataType data = core_type::ErrorDomain::SupportDataType{}) noexcept
Create a new ErrorCode within DoipErrorDomain.
This function is used internally by constructors of ErrorCode. It is usually not used directly by users
Parameters
[in] code The DoipErrorDomain-specific error code value
[in] data The optional vendor-specific error data
Returns
ErrorCode A new ErrorCode instance
Definition at line 61 of file doip_error_domain.cpp.
{
   return core_type::ErrorCode{data, doip_error_domain};
 }
References doip_client::error_domain::anonymous_namespace{doip_error_domain.cpp}::doip_error_domain.
Referenced by doip_client::sockets::TcpSocketHandler::ConnectToHost(), doip_client::sockets::TcpSocketHandler::DisconnectFromHost(), doip_client::sockets::TcpSocketHandler::Transmit(), and doip_client::sockets::UdpSocketHandler::Transmit().