Diag-Client-Lib: diag::client::conversation Namespace Reference
diag::client::conversation Namespace Reference
Classes
class DiagClientConversation
Conversation class to establish connection with a Diagnostic Server.
class Conversation
Interface for diag client conversation.
class DmConversationHandler
Class to manage reception from transport protocol handler to dm connection handler.
class DmConversation
Class to establish connection with Diagnostic Server.
struct DMConversationType
Structure containing DM conversation type.
class VehicleInfoMessageImpl
class VdConversationHandler
Class to manage reception from transport protocol handler to vd connection handler.
class VdConversation
Class to search for available diagnostic server over a network.
struct VDConversationType
Structure containing VD conversation type.
Functions
std::string ConvertToHexString (std::uint8_t char_start, std::uint8_t char_count, std::vector< std::uint8_t > &input_buffer)
std::string ConvertToAsciiString (std::uint8_t char_start, std::uint8_t char_count, std::vector< std::uint8_t > &input_buffer)
void SerializeEIDGIDFromString (std::string &input_string, std::vector< uint8_t > &output_buffer, std::uint8_t total_size, std::uint8_t substring_range)
void SerializeVINFromString (std::string &input_string, std::vector< uint8_t > &output_buffer, std::uint8_t total_size, std::uint8_t substring_range)
Function Documentation
ConvertToAsciiString()
std::string diag::client::conversation::ConvertToAsciiString (std::uint8_t char_start, std::uint8_t char_count, std::vector< std::uint8_t > & input_buffer)
Definition at line 41 of file vd_conversation.cpp.
{
   std::string ascii_string{};
   std::uint8_t total_char_count{static_cast<uint8_t>(char_start + char_count)};
   for (std::uint8_t char_start_count = char_start; char_start_count < total_char_count; char_start_count++) {
     std::stringstream vehicle_info_data_vin{};
     vehicle_info_data_vin << input_buffer[char_start_count];
     ascii_string.append(vehicle_info_data_vin.str());
   }
   return ascii_string;
 }
Referenced by diag::client::conversation::VdConversation::DeserializeVehicleInfoResponse().
ConvertToHexString()
std::string diag::client::conversation::ConvertToHexString (std::uint8_t char_start, std::uint8_t char_count, std::vector< std::uint8_t > & input_buffer)
Definition at line 22 of file vd_conversation.cpp.
{
   std::string hex_string{};
   std::uint8_t total_char_count{static_cast<uint8_t>(char_start + char_count)};
   for (std::uint8_t char_start_count = char_start; char_start_count < total_char_count; char_start_count++) {
     std::stringstream vehicle_info_data_eid{};
     int payload_byte{input_buffer[char_start_count]};
     if ((payload_byte <= 15)) {
       // "0" appended in case of value upto 15/0xF
       vehicle_info_data_eid << "0";
     }
     vehicle_info_data_eid << std::hex << payload_byte << ":";
     hex_string.append(vehicle_info_data_eid.str());
   }
   hex_string.pop_back();  // remove last ":" appended before
   return hex_string;
 }
Referenced by diag::client::conversation::VdConversation::DeserializeVehicleInfoResponse().
SerializeEIDGIDFromString()
void diag::client::conversation::SerializeEIDGIDFromString (std::string & input_string, std::vector< uint8_t > & output_buffer, std::uint8_t total_size, std::uint8_t substring_range)
Definition at line 54 of file vd_conversation.cpp.
{
   for (auto char_count = 0U; char_count < total_size; char_count += substring_range) {
     std::string input_string_new{input_string.substr(char_count, static_cast<std::uint8_t>(substring_range))};
     std::stringstream input_string_stream{input_string_new};
     int get_byte;
     input_string_stream >> std::hex >> get_byte;
     output_buffer.emplace_back(static_cast<std::uint8_t>(get_byte));
   }
 }
Referenced by diag::client::conversation::VdConversation::DeserializeVehicleInfoRequest().
SerializeVINFromString()
void diag::client::conversation::SerializeVINFromString (std::string & input_string, std::vector< uint8_t > & output_buffer, std::uint8_t total_size, std::uint8_t substring_range)
Definition at line 66 of file vd_conversation.cpp.
{
   for (auto char_count = 0U; char_count < total_size; char_count += substring_range) {
     std::string input_string_new{input_string.substr(char_count, static_cast<std::uint8_t>(substring_range))};
     std::stringstream input_string_stream{input_string_new};
     int get_byte{input_string_stream.get()};
     output_buffer.emplace_back(static_cast<std::uint8_t>(get_byte));
   }
 }
Referenced by diag::client::conversation::VdConversation::DeserializeVehicleInfoRequest().