Diag-Client-Lib: boost_support::error_domain Namespace Reference
boost_support::error_domain Namespace Reference
Namespaces
anonymous_namespace{boost_support_error_domain.cpp}
Classes
class BoostSupportErrorDomain
Definition of Doip Client Error domain.
Enumerations
enum class BoostSupportErrorErrc : core_type::ErrorDomain::CodeType { kInitializationFailed = 0U , kDeInitializationFailed = 1U , kSocketError = 2U , kGenericError = 3U }
Definition of error code in Doip Client.
Functions
auto MakeErrorCode (BoostSupportErrorDomain::Errc code, BoostSupportErrorDomain::SupportDataType data) noexcept -> core_type::ErrorCode
Create a new ErrorCode within DoipErrorDomain.
auto MakeErrorCode (BoostSupportErrorErrc code) noexcept -> core_type::ErrorCode
Create a new ErrorCode within DoipErrorDomain.
Enumeration Type Documentation
BoostSupportErrorErrc
enum boost_support::error_domain::BoostSupportErrorErrc : core_type::ErrorDomain::CodeType strong
Definition of error code in Doip Client.
Enumerator
kInitializationFailed
Failure on Initialization
kDeInitializationFailed
Failure on De-Initialization
kSocketError
Failure on Socket Open/Destroy
kGenericError
Generic Error
Definition at line 22 of file boost_support_error_domain.h.
                                  : core_type::ErrorDomain::CodeType {
   kInitializationFailed = 0U,
   kDeInitializationFailed = 1U,
   kSocketError = 2U,
   kGenericError = 3U
 };
Function Documentation
MakeErrorCode() [1/2]
auto boost_support::error_domain::MakeErrorCode (BoostSupportErrorDomain::Errc code, BoostSupportErrorDomain::SupportDataType data) -> core_type::ErrorCode noexcept
Create a new ErrorCode within DoipErrorDomain.
This function is used internally by constructors of ErrorCode. It is usually not used directly by users
Parameters
[in] code The DoipErrorDomain-specific error code value
[in] data The optional vendor-specific error data
Returns
ErrorCode A new ErrorCode instance
Definition at line 62 of file boost_support_error_domain.cpp.
{
   return {static_cast<core_type::ErrorDomain::CodeType>(code), boost_support_error_domain, data};
 }
References boost_support::error_domain::anonymous_namespace{boost_support_error_domain.cpp}::boost_support_error_domain.
Referenced by boost_support::client::tcp::TcpClient::TcpClientImpl::ConnectToHost(), boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::ConnectToHost(), boost_support::client::tcp::TcpClient::TcpClientImpl::DisconnectFromHost(), boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::DisconnectFromHost(), MakeErrorCode(), boost_support::socket::udp::UdpSocket::Read(), boost_support::client::tcp::TcpClient::TcpClientImpl::Transmit(), boost_support::client::tls::TlsClient< TlsVersion >::TlsClientImpl::Transmit(), boost_support::connection::tcp::TcpConnection< ConnectionType::kClient, Socket >::Transmit(), boost_support::connection::tcp::TcpConnection< ConnectionType::kServer, Socket >::Transmit(), and boost_support::connection::udp::UdpConnection< Socket >::Transmit().
MakeErrorCode() [2/2]
auto boost_support::error_domain::MakeErrorCode (BoostSupportErrorErrc code) -> core_type::ErrorCode inline noexcept
Create a new ErrorCode within DoipErrorDomain.
This function is used internally by constructors of ErrorCode. It is usually not used directly by users
Parameters
[in] code The DoipErrorDomain-specific error code value
Returns
ErrorCode A new ErrorCode instance
Definition at line 98 of file boost_support_error_domain.h.
{
   return MakeErrorCode(code, {});
 }
References MakeErrorCode().